// ===== v1.1.031 — SP2: Calon Peminjam (tahap sebelum Nasabah): catat, ubah status, jadikan nasabah, lalu ajukan pinjaman =====
const CL_S={baru:"Baru",proses:"Diproses",lolos:"Lolos",ditolak:"Ditolak",nasabah:"Jadi nasabah"},CL_C={baru:"wr",proses:"wr",lolos:"ok",ditolak:"bd",nasabah:"ok"},
 CL_T={baru:["proses","ditolak"],proses:["lolos","ditolak"],lolos:["proses","ditolak"],ditolak:["baru"],nasabah:[]};
const clAll=()=>db.prospects||[],clBy=()=>(curUser()||{}).name||null;
const clHist=(c,st,note)=>{(c.history=c.history||[]).push({at:now(),by:clBy(),status:st,note:note||""})};
function saveCalon(){try{const v=i=>$("#"+i).value.trim(),n=v("cl-n"),ph=v("cl-p"),ad=v("cl-a"),pu=v("cl-t"),am=Math.round(+pn(v("cl-m"))||0),nt=v("cl-c"),e=S.ecl?clAll().find(x=>x._id===S.ecl):null;
 if(S.ecl&&!e)throw Error("Calon tidak ditemukan");if(e&&!CL_T[e.status].length&&e.status==="nasabah")throw Error("Calon yang sudah jadi nasabah tidak dapat diubah; ubah di data nasabah");
 if(!n)throw fe("cl-n","Nama calon wajib diisi");if(am<0)throw fe("cl-m","Rencana pinjaman tidak boleh negatif");
 const key=x=>(x.name||"").trim().toLowerCase()+"|"+(x.phone||"").trim();
 if(clAll().some(x=>x._id!==(e&&e._id)&&["baru","proses","lolos"].includes(x.status)&&key(x)===n.toLowerCase()+"|"+ph))throw fe("cl-n","Calon dengan nama dan telepon yang sama masih dalam proses");
 if(db.parties.some(p=>p.type==="nasabah"&&key(p)===n.toLowerCase()+"|"+ph))throw fe("cl-n","Sudah terdaftar sebagai nasabah dengan nama dan telepon yang sama");
 const f={name:n,phone:ph,address:ad,purpose:pu,amount:am,note:nt};
 if(e){const cg=chgOf(e,f);Object.assign(e,f);audit("update","prospect",e._id,e.name,null,cg);S.msg="Data calon diperbarui"}
 else{const c={_id:uid("CLN"),...f,status:"baru",created_at:now(),by:clBy(),history:[]};clHist(c,"baru","dicatat");db.prospects.push(c);audit("create","prospect",c._id,c.name);S.msg="Calon peminjam ditambahkan"}
 save();clrF("#cl-n,#cl-p,#cl-a,#cl-t,#cl-m,#cl-c");S.ecl=null;okM()}catch(e){mErr(e);return}render()}
function ubahCalon(){try{const c=clAll().find(x=>x._id===S.ecd),v=i=>($("#"+i)||{}).value||"";if(!c)throw Error("Calon tidak ditemukan");const to=v("cd-s"),nt=v("cd-n").trim();
 if(!CL_T[c.status].includes(to))throw fe("cd-s","Perubahan status tidak diizinkan dari "+CL_S[c.status]);if(to==="ditolak"&&!nt)throw fe("cd-n","Alasan penolakan wajib diisi");
 const from=c.status;c.status=to;clHist(c,to,nt);audit("calon_status","prospect",c._id,CL_S[from]+" → "+CL_S[to]+(nt?" · "+nt:""));save();clrF("#cd-n");S.msg="Status calon: "+CL_S[to]}catch(e){mErr(e);return}render()}
function jadiNasabah(id){try{const c=clAll().find(x=>x._id===id);if(!c)throw Error("Calon tidak ditemukan");if(c.status!=="lolos")throw Error("Hanya calon berstatus Lolos yang dapat dijadikan nasabah");
 if(dupP("nasabah",c.name,c.phone||"",c.address||"",null))throw Error("Nasabah dengan nama, telepon, dan alamat yang sama sudah ada");
 const p={_id:uid("PTY"),type:"nasabah",name:c.name,phone:c.phone||"",address:c.address||"",status:"aktif",from_prospect:c._id};db.parties.push(p);audit("create","party",p._id,p.name);
 c.status="nasabah";c.party_id=p._id;c.converted_at=now();clHist(c,"nasabah","menjadi nasabah");audit("calon_nasabah","prospect",c._id,c.name+" → nasabah");save();S.msg="Calon dijadikan nasabah. Lanjutkan dengan mengajukan pinjaman"}catch(e){S.msg="⚠ "+e.message}render()}
function vCalon(){const q=(S.cq||"").toLowerCase(),L=clAll(),cnt=s=>L.filter(x=>x.status===s).length,fl=L.filter(x=>(!S.cfs||x.status===S.cfs)&&(!q||((x.name||"")+" "+(x.phone||"")+" "+(x.address||"")+" "+(x.purpose||"")).toLowerCase().includes(q))).slice().sort((a,b)=>(b.created_at||"").localeCompare(a.created_at||""));
 return`<h2>Calon peminjam</h2><p class="k">Catat calon sebelum menjadi nasabah. Alurnya: Baru → Diproses → Lolos → jadikan nasabah, lalu ajukan pinjaman.</p>${addB("Tambah calon","cl")}
<div class="fl"><input type="search" placeholder="Cari nama / telepon / keperluan…" aria-label="Cari calon" value="${esc(S.cq||"")}" onchange="S.cq=this.value;render()"><select aria-label="Filter status calon" onchange="S.cfs=this.value;render()"><option value="">Semua status (${L.length})</option>${Object.keys(CL_S).map(k=>`<option value="${k}"${S.cfs===k?" selected":""}>${CL_S[k]} (${cnt(k)})</option>`).join("")}</select>${S.cq||S.cfs?`<button class="b s" onclick="S.cq='';S.cfs='';render()">Reset</button>`:""}</div>
${fl.length?`<div class="ll"><div class="lh" aria-hidden="true"><span>Nama</span><span>Keperluan</span><span class="n">Rencana pinjaman</span><span class="n">Dicatat</span><span>Status</span><span></span></div>${fl.map(c=>`<button class="li" onclick="mdOpen('cd','${c._id}')"><span class="l1"><b>${esc(c.name)}</b><small>${esc(c.phone||"-")}</small></span><span class="l2">${esc(c.purpose||"-")}</span><span class="n l3">${c.amount?rp(c.amount):"-"}</span><span class="n l4">${esc((c.created_at||"").slice(0,10))}</span><span class="l5"><span class="bdg ${CL_C[c.status]||""}">${CL_S[c.status]||c.status}</span></span><span class="l6">${ic("next")}</span></button>`).join("")}</div>`:`<p class="k">${L.length?"Tidak ada calon yang cocok dengan filter.":"Belum ada calon peminjam."}</p>`}`}
MK.cl="ecl";MK.cd="ecd";
MD.cl=()=>{const e=clAll().find(x=>x._id===S.ecl);return{t:e?"Edit calon peminjam":"Calon peminjam baru",s:"saveCalon()",y:"Simpan",b:fld("cl-n","Nama *",{value:e?e.name:"",req:1})+fld("cl-p","Telepon",{value:e?e.phone||"":"",a:' inputmode="tel" autocomplete="off"'})+fld("cl-a","Alamat",{value:e?e.address||"":""})+fld("cl-t","Keperluan pinjaman",{value:e?e.purpose||"":""})+fld("cl-m","Rencana pinjaman (Rp)",{value:e&&e.amount?fm(e.amount):"",a:' inputmode="numeric" autocomplete="off" oninput="fmtR(this)"'})+fld("cl-c","Catatan",{value:e?e.note||"":""})}};
MD.cd=()=>{const c=clAll().find(x=>x._id===S.ecd);if(!c)return{t:"Calon peminjam",s:"mdClose()",y:"Tutup",b:"<p>Calon tidak ditemukan.</p>",nf:1};const R=(k,v)=>`<div class="kv"><span class="k">${k}</span><b>${v}</b></div>`,nx=CL_T[c.status];
 return{t:c.name,s:"mdClose()",y:"Tutup",nf:1,b:`<p><span class="bdg ${CL_C[c.status]||""}">${CL_S[c.status]}</span></p>${R("Telepon",esc(c.phone||"-"))}${R("Alamat",esc(c.address||"-"))}${R("Keperluan",esc(c.purpose||"-"))}${R("Rencana pinjaman",c.amount?rp(c.amount):"-")}${c.note?R("Catatan",esc(c.note)):""}
${(()=>{const L=db.loans.filter(l=>l.prospect_id===c._id);return L.length?`<h3>Pengajuan dari calon ini</h3>${L.map(l=>R(esc(l.loan_number),rp(l.principal||l.P||0)+" · "+esc((typeof LS!=="undefined"&&LS[l.status])||l.status))).join("")}`:""})()}
${nx.length?`<h3>Ubah status</h3>${fld("cd-s","Status baru",{t:"select",opts:opt(nx,k=>[k,CL_S[k]])})}${fld("cd-n","Catatan (wajib bila ditolak)",{value:""})}<div class="fl"><button class="b" onclick="ubahCalon()">Simpan status</button></div>`:""}
<div class="fl">${c.status==="lolos"?`<button class="b" onclick="askC('jadiNasabah','${c._id}')">Jadikan nasabah</button>`:""}${c.status==="nasabah"&&c.party_id?`<button class="b" onclick="mdClose();ajukanDari('${c.party_id}','${c._id}')">Ajukan pinjaman</button>`:""}${c.status!=="nasabah"?`<button class="b s" onclick="mdOpen('cl','${c._id}')">Edit data</button>`:""}</div>
<details class="sx"><summary>Riwayat <span class="stc">${(c.history||[]).length}</span></summary>${(c.history||[]).slice().reverse().map(h=>`<div class="ph"><span><b>${esc(CL_S[h.status]||h.status)}</b> · ${esc((h.at||"").slice(0,16).replace("T"," "))}${h.by?" · "+esc(h.by):""}${h.note?`<small>${esc(h.note)}</small>`:""}</span></div>`).join("")}</details>`}};
