// ===== SINKRON AWAN SUPABASE (v1.1.042, Tahap 1): login pengurus, simpan/muat snapshot, kunci versi =====
// Server: jalankan supabase_schema.sql di Supabase (tabel bumdes, bumdes_members, bumdes_snapshots + fungsi create_bumdes/save_snapshot).
// Hanya "anon key" yang dipakai. Pengaturan dan token disimpan di localStorage terpisah (CL_KEY), TIDAK masuk db/backup/export.
// Kata sandi tidak pernah disimpan. Data tetap utama di perangkat (localStorage); awan = cadangan dan sinkron bergilir.
const CL_KEY="bumdes_cloud_v1",CL_DELAY=8000;
const cloudRaw=()=>{try{return JSON.parse(localStorage.getItem(CL_KEY)||"{}")||{}}catch(e){return{}}};
// koneksi tetap dari config.js (SB_URL + SB_KEY) menggantikan isian manual bila valid
const cloudFixed=()=>{const u=cloudUrl(typeof SB_URL==="string"?SB_URL:""),k=String(typeof SB_KEY==="string"?SB_KEY:"").trim();return u&&cloudKeyOk(k)&&!cloudSecret(k)&&cloudRole(k)!=="service_role"?{url:u,key:k}:null};
const cloudCfg=()=>{const o=cloudRaw(),f=cloudFixed();if(f){if(o.url&&o.url!==f.url)return Object.assign({},f);return Object.assign(o,f,{fixed:1})}return o};
const cloudSet=o=>{try{const r=cloudRaw();Object.assign(r,o);if(cloudFixed()){delete r.url;delete r.key}localStorage.setItem(CL_KEY,JSON.stringify(r))}catch(e){}};
const cloudDel=ks=>{try{const c=cloudRaw();ks.forEach(k=>delete c[k]);localStorage.setItem(CL_KEY,JSON.stringify(c))}catch(e){}};
const cloudUrl=u=>{u=String(u||"").trim().replace(/\/+$/,"");if(!/^https:\/\/[a-z0-9.-]+\.[a-z]{2,}(:\d+)?$/i.test(u))return"";return u};
const cloudRole=k=>{try{const b=String(k).split(".")[1]||"";return JSON.parse(atob(b.replace(/-/g,"+").replace(/_/g,"/"))).role||""}catch(e){return""}};
const cloudSecret=k=>/^sb_secret_/.test(String(k||"").trim());
const cloudKeyOk=k=>/^[A-Za-z0-9._-]{20,}$/.test(String(k||"").trim());
function cloudMsg(raw,st){raw=String(raw||"");
 if(/^version_conflict/.test(raw))return"Data di awan sudah berubah";
 {const mj=/jurnal_tidak_seimbang: (.*)/.exec(raw);if(mj)return"Server menolak: ada jurnal tidak seimbang ("+mj[1]+"). Perbaiki transaksi itu lalu isi tabel lagi"}
 if(/(migrate_snapshot_to_tables|tabel_status)/.test(raw)&&/(does not exist|Could not find)/i.test(raw))return"Fungsi tabel belum ada. Jalankan supabase_tahap2.sql di Supabase > SQL Editor";
 const M=[[/Invalid login credentials/i,"Email atau kata sandi salah"],[/New password should be different/i,"Kata sandi baru harus berbeda dari yang lama"],[/Password should be at least/i,"Kata sandi terlalu pendek"],[/weak.?password|Password is known to be weak/i,"Kata sandi terlalu lemah; pakai kombinasi huruf, angka, dan simbol"],[/rate limit|too many requests|over_email_send_rate_limit/i,"Terlalu sering mencoba; tunggu beberapa menit lalu ulangi"],[/Email not confirmed/i,"Email belum dikonfirmasi. Buka email konfirmasi dari Supabase, atau konfirmasi pengguna di dashboard Supabase"],[/tidak_berhak/,"Anda tidak punya hak untuk tindakan ini (peran pembaca hanya boleh melihat)"],[/harus_login/,"Sesi berakhir. Masuk lagi"],[/JWT expired|invalid JWT|token is expired/i,"Sesi berakhir. Masuk lagi"],[/Invalid API key|No API key/i,"Anon key salah. Salin ulang dari Supabase > Project Settings > API"],[/relation .* does not exist|Could not find the (table|function)/i,"Tabel belum dibuat. Jalankan supabase_schema.sql di Supabase > SQL Editor"],[/nama_wajib/,"Nama BUMDes wajib diisi"],[/data_terlalu_besar/,"Data terlalu besar untuk disimpan ke awan"],[/rate limit|too many/i,"Terlalu sering mencoba. Tunggu sebentar"],[/User already registered/i,"Email sudah terdaftar"]];
 for(const[r,t]of M)if(r.test(raw))return t;return raw||("Galat server ("+(st||"?")+")")}
async function cloudReq(path,o={}){const c=cloudCfg();if(!c.url||!c.key)throw Error("Isi alamat proyek dan anon key dulu");
 const h={apikey:c.key,"Content-Type":"application/json"};
 if(o.auth===false){if(c.key.split(".").length===3)h.Authorization="Bearer "+c.key}else{if(!c.token)throw Error("Belum masuk. Masuk dengan email pengurus dulu");await cloudFresh();h.Authorization="Bearer "+cloudCfg().token}
 let r;try{r=await fetch(c.url+path,{method:o.method||"GET",headers:h,body:o.body===undefined?undefined:JSON.stringify(o.body)})}catch(e){throw Error("Tidak dapat terhubung ke Supabase. Periksa internet dan alamat proyek")}
 const t=await r.text();let j=null;try{j=t?JSON.parse(t):null}catch(e){}
 if(!r.ok){const raw=(j&&(j.message||j.msg||j.error_description||j.error))||"";const er=Error(cloudMsg(raw,r.status));er.raw=String(raw);er.status=r.status;throw er}
 return j}
async function cloudFresh(){const c=cloudCfg();if(!c.token||!c.exp||c.exp-Date.now()>60000)return;
 if(!c.refresh){cloudDel(["token","refresh","exp"]);throw Error("Sesi berakhir. Masuk lagi")}
 let r;try{r=await fetch(c.url+"/auth/v1/token?grant_type=refresh_token",{method:"POST",headers:{apikey:c.key,"Content-Type":"application/json"},body:JSON.stringify({refresh_token:c.refresh})})}catch(e){throw Error("Tidak dapat terhubung ke Supabase. Periksa internet")}
 const j=await r.json().catch(()=>null);if(!r.ok||!j||!j.access_token){cloudDel(["token","refresh","exp"]);throw Error("Sesi berakhir. Masuk lagi")}
 cloudSet({token:j.access_token,refresh:j.refresh_token||c.refresh,exp:Date.now()+(+j.expires_in||3600)*1000})}
// ----- pengaturan koneksi, akun -----
function cloudSave(){try{if(cloudFixed())throw Error("Koneksi sudah diatur di config.js");const u=cloudUrl($("#cl-url").value),k=String($("#cl-key").value||"").trim();if(!u)throw fe("cl-url","Alamat proyek harus berbentuk https://xxxx.supabase.co");if(!cloudKeyOk(k))throw fe("cl-key","Anon key tidak valid (salin dari Project Settings > API > anon public)");
 if(cloudSecret(k)||cloudRole(k)==="service_role")throw fe("cl-key","Ini service_role key. JANGAN dipakai di aplikasi. Pakai anon key");
 const c=cloudCfg();if(c.url&&c.url!==u)cloudDel(["token","refresh","exp","email","bumdes_id","bumdes_name","role","ver"]);cloudSet({url:u,key:k});S.msg=S.clm="Koneksi disimpan";S.fe=null}catch(e){S.msg=S.clm="⚠ "+e.message;S.fe=e.f?{id:e.f,m:e.message}:null}render()}
async function cloudLogin(p){p=typeof p==="string"?p:"ln";const em=($("#"+p+"-em").value||"").trim(),pw=$("#"+p+"-pw").value||"";S.lgem=em;
 try{if(!em||!/^\S+@\S+\.\S+$/.test(em))throw fe(p+"-em","Isi email yang valid");if(!pw)throw fe(p+"-pw","Kata sandi wajib diisi");S.clb=1;render();
  const j=await cloudReq("/auth/v1/token?grant_type=password",{method:"POST",body:{email:em,password:pw},auth:false});
  cloudSet({token:j.access_token,refresh:j.refresh_token,exp:Date.now()+(+j.expires_in||3600)*1000,email:(j.user&&j.user.email)||em});$("#"+p+"-pw").value="";
  S.cll=await cloudList();const L=S.cll;if(L.length===1)cloudPick(L[0].id);S.msg=S.clm="Masuk sebagai "+((j.user&&j.user.email)||em);if(S.lgn){lgClose();if(L.length!==1){S.tab="set";S.su="aw"}}}
 catch(e){S.msg=S.clm="⚠ "+e.message;S.fe=e.f?{id:e.f,m:e.message}:null}S.clb=0;render()}
async function cloudLogout(){try{await cloudReq("/auth/v1/logout",{method:"POST"})}catch(e){}cloudDel(["token","refresh","exp","email","bumdes_id","bumdes_name","role","ver","last","remote","paused","dirty","err"]);S.cll=null;S.clh=null;S.msg=S.clm="Keluar dari akun awan";render()}
async function cloudList(){const j=await cloudReq("/rest/v1/bumdes_members?select=role,bumdes(id,name)");return(j||[]).filter(x=>x.bumdes).map(x=>({id:x.bumdes.id,name:x.bumdes.name,role:x.role}))}
async function cloudRefreshList(){try{S.clb=1;render();S.cll=await cloudList();S.msg=S.clm=S.cll.length?"Daftar BUMDes diperbarui":"Belum ada BUMDes di akun ini. Buat baru atau minta admin menambahkan email Anda"}catch(e){S.msg=S.clm="⚠ "+e.message}S.clb=0;render()}
function cloudPick(id){const b=(S.cll||[]).find(x=>x.id===id);if(!b){S.msg=S.clm="⚠ Pilih BUMDes dulu";render();return}S.clh=null;cloudSet({bumdes_id:b.id,bumdes_name:b.name,role:b.role,ver:0,last:"",remote:0,paused:0});if(db.bumdes[0]&&db.bumdes[0].name!==b.name){db.bumdes[0].name=b.name;S.clpl=1;try{save()}finally{S.clpl=0}}S.msg=S.clm="BUMDes awan dipilih: "+b.name+". Nama header ikut disamakan. Langkah berikut: Simpan ke awan (bila awan masih kosong) atau Muat dari awan";render()}
function cloudPickSel(){cloudPick($("#cl-b").value)}
async function cloudCreate(){const nm=($("#cl-nb").value||"").trim()||bnm();try{S.clb=1;render();const id=await cloudReq("/rest/v1/rpc/create_bumdes",{method:"POST",body:{p_name:nm}});S.cll=await cloudList();cloudPick(id);S.msg=S.clm="BUMDes awan dibuat: "+nm+". Langkah berikut: Simpan ke awan"}catch(e){S.msg=S.clm="⚠ "+e.message}S.clb=0;render()}
// ----- simpan dan muat -----
function cloudPush(silent,force){return cloudPushI(silent,force)}
async function cloudPushI(silent,force){const c=cloudCfg();
 try{if(!c.bumdes_id)throw Error("Pilih BUMDes awan dulu");if(c.role==="pembaca")throw Error("Peran Anda pembaca: hanya boleh memuat dari awan");if(S.clpb)return;S.clpb=1;if(!silent){S.clb=1;render()}
  const body={p_bumdes:c.bumdes_id,p_expected:force&&c.remote!=null?+c.remote:+c.ver||0,p_data:db,p_app_ver:APP_VER};
  const v=await cloudReq("/rest/v1/rpc/save_snapshot",{method:"POST",body});
  cloudSet({ver:+v,last:now(),remote:0,paused:0,dirty:0,err:""});if(cloudCfg().tbl&&!S.tblskip)S.tblq=1;if(!silent)S.msg=S.clm="Tersimpan ke awan (versi "+v+")"}
 catch(e){const m=/^version_conflict:(\d+)/.exec(e.raw||"");if(m){cloudSet({remote:+m[1],paused:1});S.msg=S.clm="⚠ Data di awan sudah berubah (versi "+m[1]+"; versi Anda "+(+cloudCfg().ver||0)+"). Muat dari awan dulu, atau timpa awan bila data di perangkat ini yang benar"}else if(/terhubung/.test(e.message)){cloudSet({err:"offline"});if(!silent)S.msg=S.clm="⚠ "+e.message+". Perubahan akan dikirim otomatis saat koneksi kembali"}else if(!silent)S.msg=S.clm="⚠ "+e.message;else cloudSet({err:e.message})}
 S.clpb=0;S.clb=0;render();if(S.tblq){S.tblq=0;if(typeof tblSync==="function")tblSync({afterPush:true,silent:true})}}
async function cloudFetchSnap(){const c=cloudCfg();if(!c.bumdes_id)throw Error("Pilih BUMDes awan dulu");const j=await cloudReq("/rest/v1/bumdes_snapshots?bumdes_id=eq."+encodeURIComponent(c.bumdes_id)+"&select=version,data,updated_at,app_ver");if(!j||!j.length)throw Error("Belum ada data di awan. Pakai Simpan ke awan dulu");return j[0]}
async function cloudPullAsk(){try{S.clb=1;render();const s=await cloudFetchSnap();S.clsnap=s;S.clb=0;askC("cloudPull","")}catch(e){S.clb=0;S.msg=S.clm="⚠ "+e.message;render()}}
function cloudApply(s){const j=s&&s.data;if(!j||typeof j!=="object")throw Error("Data awan tidak valid");chk(j);
 try{localStorage.setItem(KEY+"_prev",JSON.stringify(db))}catch(e){}
 S.clpl=1;db=j;migr();save();S.clpl=0;cloudSet({ver:+s.version,last:now(),remote:0,paused:0,dirty:0,err:""});return +s.version}
function cloudPull(){try{const s=S.clsnap;if(!s)throw Error("Ambil data awan dulu");const v=cloudApply(s);S.clsnap=null;S.msg=S.clm=s.hv?"Riwayat versi "+s.hv+" dipulihkan di perangkat ini. Klik Simpan ke awan agar menjadi versi terbaru di awan. Salinan data lama disimpan sebagai cadangan lokal":"Data dimuat dari awan (versi "+v+"). Salinan data lama perangkat disimpan sebagai cadangan lokal"}catch(e){S.clpl=0;S.msg=S.clm="⚠ Muat gagal: "+e.message}render()}
async function cloudHist(){try{const c=cloudCfg();if(!c.bumdes_id)throw Error("Pilih BUMDes awan dulu");if(c.role==="pembaca")throw Error("Riwayat hanya untuk admin dan pengurus");S.clb=1;render();S.clh=await cloudReq("/rest/v1/bumdes_snapshot_history?bumdes_id=eq."+encodeURIComponent(c.bumdes_id)+"&select=version,saved_at,app_ver&order=version.desc&limit=30")||[];S.msg=S.clm=S.clh.length?"Riwayat dimuat ("+S.clh.length+" versi)":"Belum ada riwayat di awan"}catch(e){S.msg=S.clm="⚠ "+e.message}S.clb=0;render()}
async function cloudRestore(v){try{const c=cloudCfg();v=+v;if(!(v>0))throw Error("Versi tidak valid");S.clb=1;render();const q="bumdes_id=eq."+encodeURIComponent(c.bumdes_id),h=await cloudReq("/rest/v1/bumdes_snapshot_history?"+q+"&version=eq."+v+"&select=version,data,saved_at,app_ver"),cur=await cloudReq("/rest/v1/bumdes_snapshots?"+q+"&select=version");if(!h||!h.length)throw Error("Versi "+v+" tidak ditemukan di riwayat");S.clsnap={version:cur&&cur.length?+cur[0].version:+h[0].version,hv:v,data:h[0].data,updated_at:h[0].saved_at};S.clb=0;askC("cloudPull","")}catch(e){S.clb=0;S.msg=S.clm="⚠ "+e.message;render()}}
function cloudForce(){cloudPush(false,true)}
function cloudAuto(){if(S.clpl)return;const c=cloudCfg();if(c.token&&c.bumdes_id&&!c.dirty)cloudSet({dirty:1});if(!c.auto||!c.token||!c.bumdes_id||c.role==="pembaca"||c.paused)return;if(typeof setTimeout!=="function")return;clearTimeout(cloudAuto.t);cloudAuto.t=setTimeout(()=>cloudPushI(true),CL_DELAY)}
function cloudAutoSet(v){cloudSet({auto:v==="1",paused:0});S.msg=S.clm="Simpan otomatis "+(v==="1"?"diaktifkan: perubahan dikirim ke awan beberapa detik setelah disimpan":"dimatikan");if(v==="1")cloudAuto();render()}
function cloudReset(){cloudDel(["url","key","tbl","tbl_at","tbl_bad","tbl_err","dirty","err","checked","token","refresh","exp","email","bumdes_id","bumdes_name","role","ver","last","remote","paused","auto"]);S.cll=null;S.msg=S.clm="Pengaturan awan dihapus dari perangkat ini";render()}
// ----- status, sinkron dua arah, akun (v1.1.071) -----
function cloudStat(){const c=cloudCfg();if(!c.url||!c.key||!c.token||!c.bumdes_id)return null;const ago=c.last?Math.max(0,Math.floor((Date.now()-new Date(c.last).getTime())/864e5)):null;
 if(c.paused)return{k:"jeda",t:"Sinkron dijeda: data di awan berubah",bad:1,ago};if(S.clpb)return{k:"kirim",t:"Menyimpan ke awan…",ago};
 if(c.dirty)return c.err==="offline"?{k:"offline",t:"Offline: perubahan belum terkirim ke awan",bad:1,ago}:{k:"tunda",t:c.auto?"Perubahan menunggu dikirim ke awan":"Ada perubahan yang belum disimpan ke awan",bad:!c.auto,ago};
 return{k:"ok",t:"Tersinkron dengan awan"+(c.ver?" (versi "+c.ver+")":""),ago}}
async function cloudCheck(){const c=cloudCfg();if(!c.auto||!c.token||!c.bumdes_id||c.paused||S.clb||S.clpb||S.clck)return;if(typeof navigator!=="undefined"&&navigator.onLine===false)return;
 S.clck=1;try{const j=await cloudReq("/rest/v1/bumdes_snapshots?bumdes_id=eq."+encodeURIComponent(c.bumdes_id)+"&select=version"),rv=j&&j[0]?+j[0].version:0,lv=+c.ver||0;cloudSet({checked:now(),err:""});
  if(rv>lv){if(c.dirty){cloudSet({remote:rv,paused:1});S.msg=S.clm="⚠ Data di awan lebih baru (versi "+rv+") dan perangkat ini punya perubahan belum terkirim. Pilih Muat dari awan atau Timpa awan";render()}
   else if(S.md||(typeof dirtyFields==="function"&&dirtyFields().length)){/* sedang mengisi form: coba lagi nanti */}
   else{const s=await cloudFetchSnap();cloudApply(s);S.msg=S.clm="Data diperbarui dari awan (versi "+s.version+")";render()}}}
 catch(e){cloudSet({err:/terhubung/.test(e.message)?"offline":e.message})}S.clck=0}
function cloudBoot(){if(typeof window==="undefined"||!window.addEventListener||cloudBoot.d)return;cloudBoot.d=1;
 const go=()=>{const c=cloudCfg();if(!c.token||!c.bumdes_id)return;if(c.dirty)cloudAuto();cloudCheck()};
 window.addEventListener("online",go);if(typeof document!=="undefined"&&document.addEventListener)document.addEventListener("visibilitychange",()=>{if(document.visibilityState==="visible")go()});
 if(typeof setInterval==="function")setInterval(()=>{if(typeof document==="undefined"||document.visibilityState!=="hidden")go()},60000);
 if(typeof setTimeout==="function")setTimeout(go,1500);cloudRecBoot();try{if(location.hash==="#masuk"){if(cloudCfg().token)lgClose();else{S.lgn=1;render()}}}catch(e){}}
async function cloudForgot(p){p=typeof p==="string"?p:"ln";try{const em=($("#"+p+"-em")||{}).value||"";const e=em.trim();S.lgem=e;if(!/^\S+@\S+\.\S+$/.test(e))throw fe(p+"-em","Isi email pengurus dulu");S.clb=1;render();
  const ret=typeof location!=="undefined"?location.origin+location.pathname:"";await cloudReq("/auth/v1/recover"+(ret?"?redirect_to="+encodeURIComponent(ret):""),{method:"POST",body:{email:e},auth:false});
  S.msg=S.clm="Jika email terdaftar, tautan untuk mengatur ulang kata sandi sudah dikirim. Buka tautan itu di perangkat ini"}catch(e){S.msg=S.clm="⚠ "+e.message;S.fe=e.f?{id:e.f,m:e.message}:null}S.clb=0;render()}
function cloudPwChk(a,b,fa,fb){a=String(a||"");b=String(b||"");if(a.length<8)throw fe(fa,"Kata sandi minimal 8 karakter");if(a!==b)throw fe(fb,"Ulangi kata sandi baru dengan sama persis");return a}
async function cloudChangePw(){try{const p=cloudPwChk(($("#cl-p1")||{}).value,($("#cl-p2")||{}).value,"cl-p1","cl-p2");S.clb=1;render();await cloudReq("/auth/v1/user",{method:"PUT",body:{password:p}});$("#cl-p1").value="";$("#cl-p2").value="";S.msg=S.clm="Kata sandi diganti"}catch(e){S.msg=S.clm="⚠ "+e.message;S.fe=e.f?{id:e.f,m:e.message}:null}S.clb=0;render()}
function cloudRecBoot(){try{if(typeof location==="undefined"||!location.hash||!/type=recovery/.test(location.hash))return;const h=new URLSearchParams(location.hash.slice(1)),t=h.get("access_token");if(!t)return;
  S.clrec={token:t,refresh:h.get("refresh_token")||"",exp:Date.now()+(+h.get("expires_in")||3600)*1000};if(history&&history.replaceState)history.replaceState(null,"",location.pathname+location.search);setTimeout(()=>{mdOpen("cr")},0)}catch(e){}}
MK.cr="ecr";
MD.cr=()=>({t:"Atur kata sandi baru",s:"cloudRecSet()",y:"Simpan kata sandi",b:`<p class="k">Tautan dari email sudah dikenali. Buat kata sandi baru untuk akun awan Anda.</p>${fld("cl-n1","Kata sandi baru",{type:"password",a:' autocomplete="new-password"',value:""})}${fld("cl-n2","Ulangi kata sandi baru",{type:"password",a:' autocomplete="new-password"',value:""})}`});
async function cloudRecSet(){try{const r=S.clrec;if(!r||!r.token)throw Error("Tautan tidak berlaku lagi. Minta tautan baru");const c=cloudCfg();if(!c.url||!c.key)throw Error("Alamat proyek belum diisi di perangkat ini. Isi di Setelan > Awan lalu minta tautan baru");const p=cloudPwChk($("#cl-n1").value,$("#cl-n2").value,"cl-n1","cl-n2");
  let x;try{x=await fetch(c.url+"/auth/v1/user",{method:"PUT",headers:{apikey:c.key,"Content-Type":"application/json",Authorization:"Bearer "+r.token},body:JSON.stringify({password:p})})}catch(e){throw Error("Tidak dapat terhubung ke Supabase. Periksa internet")}
  const j=await x.json().catch(()=>null);if(!x.ok)throw Error(cloudMsg((j&&(j.message||j.msg||j.error_description))||"",x.status));
  cloudSet({token:r.token,refresh:r.refresh,exp:r.exp,email:(j&&j.email)||c.email||""});S.clrec=null;okM();S.msg=S.clm="Kata sandi baru disimpan dan Anda sudah masuk";render()}catch(e){mErr(e)}}
// ----- tabel relasional (v1.1.075): isi tabel dari snapshot di server, cocokkan dengan data perangkat -----
const TBL_K=[["business_units","Unit usaha"],["parties","Pihak"],["accounts","Akun"],["transactions","Transaksi"],["journal_lines","Baris jurnal"],["loans","Pinjaman"],["loan_installments","Angsuran"],["loan_payments","Pembayaran pinjaman"],["audit_logs","Catatan audit"]];
function tblLocal(){const o={},m2=x=>Math.round(x*100)/100,L=db.journal_lines||[];TBL_K.forEach(([k])=>o[k]=(db[k]||[]).length);o.debit=m2(L.reduce((s,x)=>s+(+x.debit||0),0));o.credit=m2(L.reduce((s,x)=>s+(+x.credit||0),0));o.principal=m2((db.loans||[]).reduce((s,x)=>s+(+x.principal||0),0));return o}
function tblCmp(l,s){s=s||{};const m2=x=>Math.round((+x||0)*100)/100,rows=TBL_K.map(([k,n])=>({k,n,l:l[k],s:+s[k]||0,ok:k==="audit_logs"?(+s[k]||0)>=l[k]:(+s[k]||0)===l[k]}));
 [["debit","Total debit jurnal"],["credit","Total kredit jurnal"],["principal","Total pokok pinjaman"]].forEach(([k,n])=>rows.push({k,n,l:l[k],s:m2(s[k]),ok:m2(s[k])===l[k],m:1}));return rows}
async function tblSync(o){o=o||{};const c=cloudCfg();if(S.cltb)return;
 try{if(!c.bumdes_id)throw Error("Pilih BUMDes awan dulu");if(c.role==="pembaca")throw Error("Peran pembaca tidak boleh mengisi tabel");S.cltb=1;if(!o.silent){S.clb=1;render()}
  if(!o.afterPush&&(c.dirty||!(+c.ver))){S.cltb=0;S.tblskip=1;try{await cloudPushI(true)}finally{S.tblskip=0}S.cltb=1;const c2=cloudCfg();if(c2.dirty||c2.paused)throw Error("Simpan ke awan dulu: snapshot belum berhasil dikirim")}
  await cloudReq("/rest/v1/rpc/migrate_snapshot_to_tables",{method:"POST",body:{p_bumdes:c.bumdes_id}});
  const st=await cloudReq("/rest/v1/rpc/tabel_status",{method:"POST",body:{p_bumdes:c.bumdes_id}}),cd=cloudCfg().dirty;
  if(!cd){S.tblr=tblCmp(tblLocal(),st)}cloudSet({tbl_at:now(),tbl_bad:cd?null:S.tblr.filter(x=>!x.ok).length,tbl_err:""});
  if(!o.silent)S.msg=S.clm=cd?"Tabel terisi dari snapshot awan. Ada perubahan baru di perangkat, simpan ke awan lalu cek lagi":"Tabel terisi. "+(S.tblr.some(x=>!x.ok)?"Ada selisih, lihat rincian di bagian Tabel relasional":"Semua data cocok dengan perangkat")}
 catch(e){cloudSet({tbl_err:/terhubung/.test(e.message)?"offline":e.message});if(!o.silent)S.msg=S.clm="⚠ "+e.message}
 S.cltb=0;S.clb=0;render()}
async function tblCheck(){const c=cloudCfg();try{if(!c.bumdes_id)throw Error("Pilih BUMDes awan dulu");S.clb=1;render();
  const st=await cloudReq("/rest/v1/rpc/tabel_status",{method:"POST",body:{p_bumdes:c.bumdes_id}});S.tblr=tblCmp(tblLocal(),st);const bad=S.tblr.filter(x=>!x.ok).length;cloudSet({tbl_bad:bad,tbl_err:""});S.msg=S.clm=bad?"Ada "+bad+" selisih antara tabel di server dan data perangkat":"Tabel di server cocok dengan data perangkat"}
 catch(e){S.msg=S.clm="⚠ "+e.message}S.clb=0;render()}
function tblAutoSet(v){cloudSet({tbl:v==="1"?1:0});S.msg=S.clm="Isi tabel otomatis "+(v==="1"?"diaktifkan: setiap simpan ke awan diikuti pengisian tabel":"dimatikan");if(v==="1"&&!cloudCfg().dirty)tblSync({silent:false});else render()}
function tblHtml(c,busy){const rows=S.tblr,ro=c.role==="pembaca",bd=c.tbl_err?`<span class="bdg wr">Gagal</span> ${esc(c.tbl_err==="offline"?"Offline":c.tbl_err)}`:c.tbl_at?(c.tbl_bad===0?`<span class="bdg ok">Cocok</span>`:c.tbl_bad>0?`<span class="bdg wr">${+c.tbl_bad} selisih</span>`:`<span class="bdg">Terisi</span>`)+` terakhir ${esc(String(c.tbl_at).replace("T"," ").slice(0,16))}`:`<span class="bdg">Belum diisi</span>`;
 const f=n=>typeof n==="number"&&n%1?n.toLocaleString("id-ID",{minimumFractionDigits:2,maximumFractionDigits:2}):(+n||0).toLocaleString("id-ID");
 return`<div class="k">Salinan data dalam tabel Supabase (unit, pihak, akun, transaksi, jurnal, pinjaman, audit) untuk laporan dan banyak pengguna. Server menolak jurnal yang tidak seimbang. Snapshot tetap jadi cadangan utama. Jalankan <b>supabase_tahap2.sql</b> sekali di SQL Editor.</div><p role="status">${bd}</p>`+
 (ro?`<div class="k">Peran pembaca hanya bisa mengecek kecocokan.</div>`:fld("tb-auto","Isi tabel otomatis setelah simpan ke awan",{t:"select",a:' onchange="tblAutoSet(this.value)"',opts:opt([["0","Mati"],["1","Aktif"]],x=>x,c.tbl?"1":"0")}))+
 `<div class="fl">${ro?"":`<button class="b"${busy} onclick="tblSync()">Isi tabel sekarang</button>`}<button class="b s"${busy} onclick="tblCheck()">Cek kecocokan</button></div>`+
 (rows?`<div class="k">Perangkat vs server:</div>${rows.map(r=>`<div class="fl" style="justify-content:space-between;border-bottom:1px solid var(--bd,#8883);padding:4px 0"><span>${esc(r.n)}</span><span>${f(r.l)} / ${f(r.s)} <b>${r.ok?"✓":"≠"}</b></span></div>`).join("")}`:"")}
// ----- halaman masuk awan (v1.1.074): cover di desktop, tumpuk di mobile -----
function lgOpen(){S.lgn=1;S.fe=null;try{if(history&&history.replaceState)history.replaceState(null,"","#masuk")}catch(e){}render()}
function lgClose(){S.lgn=0;S.fe=null;try{if(typeof location!=="undefined"&&location.hash==="#masuk"&&history&&history.replaceState)history.replaceState(null,"",location.pathname+location.search)}catch(e){}}
function lgBack(){lgClose();render()}
function lgPw(){const e=$("#ln-pw"),b=$("#ln-sh");if(!e)return;const h=e.type==="password";e.type=h?"text":"password";if(b){b.textContent=h?"Sembunyikan":"Tampilkan";b.setAttribute("aria-pressed",h?"true":"false")}}
const LG_ART='<svg viewBox="0 0 600 260" preserveAspectRatio="xMidYMax slice" aria-hidden="true" focusable="false"><circle cx="470" cy="70" r="34" fill="#fff" opacity=".35"/><path d="M0 190 Q90 120 190 170 T380 160 T600 150 V260 H0Z" fill="#fff" opacity=".22"/><path d="M0 220 Q120 170 240 205 T470 195 T600 205 V260 H0Z" fill="#fff" opacity=".3"/><g fill="#fff" opacity=".55"><path d="M120 200l30-26 30 26v22h-60z"/><path d="M330 205l24-20 24 20v17h-48z"/></g></svg>';
function lgV(){const c=cloudCfg(),ok=!!(c.url&&c.key),busy=S.clb?" disabled":"",nm=esc(bnm());
 const cover=`<section class="mk-cv" aria-label="Tentang"><div class="mk-br"><span class="pt-logo" aria-hidden="true">${ic("user")}</span><div><div class="mk-n">${nm}</div><div class="mk-s">Sistem BUMDes Multi-Unit Usaha</div></div></div><h2 class="mk-h">Data BUMDes aman, tersimpan di awan</h2><ul class="mk-ft"><li>Cadangan otomatis dengan 30 riwayat versi</li><li>Sinkron antar HP dan komputer pengurus</li><li>Data tetap di proyek Supabase milik BUMDes</li></ul>${LG_ART}</section>`;
 const form=ok?`<form onsubmit="cloudLogin('ln');return false" novalidate><h1>Masuk pengurus</h1><p class="k">Gunakan akun yang dibuat admin BUMDes.</p>${fld("ln-em","Email",{type:"email",a:' autocomplete="username" inputmode="email" autocapitalize="off"',value:S.lgem||c.email||"",req:1})}<label for="ln-pw">Kata sandi</label><div class="mk-pw"><input id="ln-pw" type="password" autocomplete="current-password" aria-required="true"><button type="button" id="ln-sh" class="b s sm" aria-pressed="false" onclick="lgPw()">Tampilkan</button></div><div class="fl"><button class="b" id="ln-go" type="submit"${busy}>${S.clb?"Memproses…":"Masuk"}</button></div><div class="fl"><button class="b s" type="button"${busy} onclick="cloudForgot('ln')">Lupa kata sandi</button></div></form>`:`<h1>Masuk pengurus</h1><p>Koneksi Supabase belum diisi. Isi dulu di Setelan > Awan, atau pasang <b>SB_URL</b> dan <b>SB_KEY</b> di config.js.</p>`;
 return`${cover}<main class="mk-fm"><div class="card mk-card">${form}</div><div class="mk-bk"><button class="b s" type="button" onclick="lgBack()">‹ Kembali ke aplikasi</button></div></main>`}
function lgRender(){if(typeof document==="undefined"||!document.getElementById)return false;let el=document.getElementById("masuk");
 if(!S.lgn){if(el){el.className="";el.innerHTML=""}document.body.classList.remove("mk-on");return false}
 if(el){const e0=el.querySelector&&el.querySelector("#ln-em");if(e0&&typeof e0.value==="string")S.lgem=e0.value}
 if(!el){el=document.createElement("div");el.id="masuk";el.setAttribute("aria-label","Masuk awan");document.body.appendChild(el)}
 el.className="on";el.innerHTML=lgV();document.body.classList.add("mk-on");if(typeof a11y==="function")a11y();if(typeof S.msg==="string"&&S.msg&&typeof toast==="function"){toast(S.msg,/^⚠/.test(S.msg));S.msg=""}
 if(S.fe){const f=document.getElementById(S.fe.id);if(f&&f.insertAdjacentHTML){f.classList.add("er");(f._b||f).insertAdjacentHTML("afterend",`<div class="fe" role="alert">${esc(S.fe.m)}</div>`)}S.fe=null}return true}
// ----- tampilan -----
function dxSetD(k,v,d){S.dx=S.dx||{};if(!!v===!!d)delete S.dx[k];else S.dx[k]=v}
function vCloudSet(){const c=cloudCfg(),on=!!c.token,sel=!!c.bumdes_id,L=S.cll||[],busy=S.clb?" disabled":"",ok=!!(c.url&&c.key),t=cloudStat();
 const dx=(k,d)=>(S.dx&&k in S.dx)?S.dx[k]:d,sx=(k,d,ti,b,x)=>`<details class="sx"${dx(k,d)?" open":""} ontoggle="dxSetD('${k}',this.open,${d?1:0})"><summary>${ti}${x?` <span class="stc">${x}</span>`:""}</summary><div style="padding:0 12px 12px">${b}</div></details>`;
 const bd=(k,tx,cl)=>`<span class="bdg ${cl}">${esc(tx)}</span>`;
 const sBd=t?bd(0,t.k==="ok"?"Tersinkron":t.k==="jeda"?"Dijeda":t.k==="offline"?"Offline":t.k==="kirim"?"Menyimpan":"Menunggu",t.bad?"wr":t.k==="ok"?"ok":""):bd(0,"Belum aktif","");
 const next=!ok?"Isi koneksi Supabase di bawah (atau di config.js).":!on?"Masuk dengan akun pengurus.":!sel?"Pilih atau buat BUMDes di awan.":c.paused?"Data di awan berubah (versi "+(+c.remote||"?")+"). Pilih Muat dari awan atau Timpa awan.":!(+c.ver)?"Awan masih kosong atau belum disinkron: tekan Simpan ke awan atau Muat dari awan.":"";
 const sum=`<div class="card"><div class="kvg"><div class="kv"><span class="k">Koneksi</span><b>${ok?bd(0,c.fixed?"Terhubung (config.js)":"Terhubung","ok"):bd(0,"Belum diisi","wr")}</b></div><div class="kv"><span class="k">Akun</span><b>${on?esc(c.email||"Masuk"):"Belum masuk"}</b></div><div class="kv"><span class="k">BUMDes awan</span><b>${sel?esc(c.bumdes_name||"")+" · "+esc(c.role||""):"Belum dipilih"}</b></div><div class="kv"><span class="k">Sinkron</span><b>${sBd}</b></div></div>${t?`<p class="k" role="status">${esc(t.t)}${c.last?" · terakhir "+esc(String(c.last).replace("T"," ").slice(0,16)):""}</p>`:""}${next?`<p><b>Langkah berikut:</b> ${esc(next)}</p>`:""}${ok?`<div class="fl">${on?`<button class="b s" id="aw-out"${busy} onclick="cloudLogout()">Keluar</button>`:`<button class="b" id="aw-in" onclick="lgOpen()">Masuk ke akun awan</button>`}</div>`:""}</div>${S.clm?`<div class="card" role="status" aria-live="polite"><b>${esc(S.clm)}</b></div>`:""}`;
 const sync=on&&sel?`<h3>Sinkron</h3><div class="card"><div class="fl"><button class="b"${busy} onclick="cloudPush()">Simpan ke awan</button><button class="b s"${busy} onclick="cloudPullAsk()">Muat dari awan</button>${c.paused?`<button class="b s"${busy} onclick="askC('cloudForce','')">Timpa awan</button>`:""}</div>${fld("cl-auto","Sinkron otomatis dua arah",{t:"select",a:' onchange="cloudAutoSet(this.value)"',opts:opt([["0","Mati"],["1","Aktif"]],x=>x,c.auto?"1":"0")})}<div class="k">Aktif: perubahan dikirim beberapa detik setelah disimpan, dan data baru dari perangkat lain diambil saat aplikasi dibuka atau kembali online. Bila perangkat ini punya perubahan yang belum terkirim, sinkron dijeda agar tidak menimpa.</div></div>${c.role!=="pembaca"?sx("clh",!!(S.clh&&S.clh.length),"Riwayat cadangan","<div class=\"fl\"><button class=\"b s\""+busy+" onclick=\"cloudHist()\">Muat riwayat</button></div>"+(S.clh&&S.clh.length?`<div class="k">30 versi terakhir:</div>${S.clh.map(h=>`<div class="fl" style="justify-content:space-between;align-items:center;border-bottom:1px solid var(--bd,#8883);padding:6px 0"><span><b>Versi ${+h.version}</b><br><small>${esc(String(h.saved_at||"").replace("T"," ").slice(0,16))}${h.app_ver?" · app "+esc(h.app_ver):""}${+h.version===+c.ver?" · versi perangkat":""}</small></span><button class="b s sm"${busy} onclick="cloudRestore(${+h.version})">Pulihkan</button></div>`).join("")}`:"")):""}`:"";
 const kon=c.fixed?`<p>Proyek diatur di <b>config.js</b>: ${esc(c.url)}</p>`:`${SB_URL&&!SB_KEY?`<div class="k">SB_URL sudah ada di config.js tetapi SB_KEY (anon/publishable key) masih kosong. Isi di config.js agar koneksi otomatis, atau isi manual di bawah.</div>`:""}${fld("cl-url","Alamat proyek",{value:c.url||"",a:' autocomplete="off" inputmode="url" placeholder="https://xxxx.supabase.co"'})}${fld("cl-key","Anon key",{value:c.key||"",a:' autocomplete="off" spellcheck="false"'})}<div class="fl"><button class="b"${busy} onclick="cloudSave()">Simpan koneksi</button>${c.url?`<button class="b s" onclick="askC('cloudReset','')">Hapus pengaturan</button>`:""}</div><div class="k">Pakai anon/publishable key saja, bukan service_role atau secret. Pengaturan ini tidak ikut Export JSON.</div>`;
 const akun=on?`${fld("cl-p1","Kata sandi baru (min. 8)",{type:"password",a:' autocomplete="new-password"',value:""})}${fld("cl-p2","Ulangi kata sandi baru",{type:"password",a:' autocomplete="new-password"',value:""})}<div class="fl"><button class="b s"${busy} onclick="cloudChangePw()">Ganti kata sandi</button></div>`:"";
 const bm=on?(L.length?fld("cl-b","Pilih BUMDes",{t:"select",opts:opt(L,b=>[b.id,b.name+" · "+b.role],c.bumdes_id||"")})+`<div class="fl"><button class="b"${busy} onclick="cloudPickSel()">Pakai BUMDes ini</button><button class="b s"${busy} onclick="cloudRefreshList()">Muat ulang daftar</button></div>`:`<div class="fl"><button class="b s"${busy} onclick="cloudRefreshList()">Muat daftar BUMDes</button></div>`)+fld("cl-nb","Atau buat BUMDes baru di awan",{value:bnm()})+`<div class="fl"><button class="b s"${busy} onclick="cloudCreate()">Buat di awan</button></div>`:"";
 return`<h2>Awan (Supabase)</h2>${sum}${sync}
${sx("clk",!ok,"Koneksi",kon,ok?"":"perlu diisi")}${on?sx("cla",false,"Ganti kata sandi",akun):""}${on?sx("clb",!sel,"BUMDes di awan",bm,sel?"":"perlu dipilih"):""}
${on&&sel?sx("clt",!!(c.tbl_err||c.tbl_bad>0),"Tabel relasional (Tahap 2)",tblHtml(c,busy),c.tbl_bad>0?c.tbl_bad+" selisih":""):""}
${sx("clq",false,"Tentang awan","<div class=\"k\">Data utama tetap di perangkat ini; awan menyimpan salinan terbaru dan 30 riwayat. Siapkan proyek di supabase.com dan jalankan <b>supabase_schema.sql</b> di SQL Editor (lihat SUPABASE.md). Lupa kata sandi butuh Site URL dan Redirect URLs proyek diisi alamat aplikasi ini.</div>")}`}
