// ===== KOLEKTIBILITAS DAN TINDAK LANJUT PENAGIHAN (SP4 tahap 1, v1.1.018) =====
// Kolektibilitas = jenjang menurut hari terlambat terlama angsuran belum lunas. Batas hari dapat diatur (asumsi teknis, bukan standar OJK).
const KOL_N=["Lancar","Dalam Perhatian","Kurang Lancar","Diragukan","Macet"],KOL0={dp:30,kl:90,dr:180},KOL_L={dp:"Dalam Perhatian sampai (hari)",kl:"Kurang Lancar sampai (hari)",dr:"Diragukan sampai (hari); lebih = Macet"};
const TL_T={telepon:"Telepon",whatsapp:"WhatsApp",kunjungan:"Kunjungan",surat:"Surat/peringatan",lainnya:"Lainnya"},TL_R={janji_bayar:"Janji bayar",tidak_bertemu:"Tidak bertemu/tidak diangkat",menolak:"Menolak/menunda",sudah_bayar:"Sudah membayar",lainnya:"Lainnya"};
const kolCfg=()=>Object.assign({},KOL0,(db&&db.settings&&db.settings.sp_kol)||{});
function kolOf(l,d){d=d||today();const od=db.loan_installments.filter(i=>i.loan_id===l._id&&i.status!=="paid"&&i.due_date<d),days=od.length?Math.max(...od.map(i=>dayDiff(d,i.due_date))):0,c=kolCfg(),k=days<=0?0:days<=c.dp?1:days<=c.kl?2:days<=c.dr?3:4;return{k,days,label:KOL_N[k],n:od.length}}
const kolBadge=l=>{const o=kolOf(l);return`<span class="bdg ${o.k>=3?"bd":o.k>=1?"wr":"ok"}">${o.label}${o.days>0?" · "+o.days+" hari":""}</span>`};
function kolSummary(){const R=KOL_N.map(n=>({n,c:0,v:0}));db.loans.filter(l=>l.status==="active"&&(S.unit==="all"||l.unit_id===S.unit)).forEach(l=>{const o=kolOf(l),p=db.loan_installments.filter(i=>i.loan_id===l._id).reduce((s,i)=>s+i.principal_due-i.principal_paid,0);R[o.k].c++;R[o.k].v+=p});return R}
function setKol(k,v){try{if(!(k in KOL0))throw Error("Pengaturan tidak dikenal");const x=Number(pn(v));if(String(v).trim()===""||!Number.isInteger(x)||x<1)throw Error("Isi bilangan bulat 1 atau lebih");const c=Object.assign({},kolCfg(),{[k]:x});if(!(c.dp<c.kl&&c.kl<c.dr))throw Error("Urutan batas harus Perhatian < Kurang Lancar < Diragukan");
 db.settings.sp_kol=c;audit("setting","settings","sp_kol",KOL_L[k]+": "+x);save();S.msg="Batas kolektibilitas disimpan"}catch(e){S.msg="⚠ "+e.message}render()}
const tlOf=id=>(db.collection_notes||[]).filter(x=>x.loan_id===id).sort((a,b)=>a.date<b.date?1:a.date>b.date?-1:(a.created_at<b.created_at?1:-1));
function tlStat(l){const L=tlOf(l._id),x=L[0];if(!x)return{last:null,over:false};const od=x.result==="janji_bayar"&&x.promise_date&&x.promise_date<today()&&kolOf(l).days>0;return{last:x,over:od}}
function saveTL(){try{const id=S.etl,l=db.loans.find(x=>x._id===id),v=i=>$("#"+i).value.trim();if(!l)throw Error("Pinjaman tidak ditemukan");if(l.status!=="active")throw Error("Tindak lanjut hanya untuk pinjaman aktif");
 const d=v("tl-d"),ty=v("tl-t"),rs=v("tl-r"),pd=v("tl-p"),nt=v("tl-n");if(!isD(d))throw fe("tl-d","Tanggal tidak valid");if(d>today())throw fe("tl-d","Tanggal tidak boleh melewati hari ini");if(d<(l.disbursement_date||l.application_date))throw fe("tl-d","Tanggal tidak boleh sebelum pencairan");
 if(!TL_T[ty])throw fe("tl-t","Pilih jenis tindakan");if(!TL_R[rs])throw fe("tl-r","Pilih hasil");if(rs==="janji_bayar"){if(!isD(pd))throw fe("tl-p","Isi tanggal janji bayar");if(pd<d)throw fe("tl-p","Janji bayar tidak boleh sebelum tanggal tindakan")}
 const x={_id:uid("TL"),loan_id:id,date:d,type:ty,result:rs,promise_date:rs==="janji_bayar"?pd:null,note:nt,by:(curUser()||{}).name||null,created_at:now()};db.collection_notes.push(x);
 audit("tagih","loan",id,TL_T[ty]+" · "+TL_R[rs]+(x.promise_date?" · janji "+x.promise_date:""));save();okM();S.eld=id;S.md="ld";S.msg="Tindak lanjut dicatat"}catch(e){mErr(e);return}render()}
function tglTL(id){S.etl=id;mdOpen("tl",id)}
function tlHtml(l){if(l.status!=="active")return"";const L=tlOf(l._id),op=(S.dx||{}).tl2;return`<details class="sx"${op?" open":""} ontoggle="dxSet('tl2',this.open)"><summary>Tindak lanjut penagihan <span class="stc">${L.length}</span></summary>${L.slice(0,8).map(x=>`<div class="ph"><span><b>${esc(TL_T[x.type]||x.type)}</b> · ${x.date}<small>${esc(TL_R[x.result]||x.result)}${x.promise_date?" · janji "+x.promise_date:""}${x.note?" — "+esc(x.note):""}${x.by?" · "+esc(x.by):""}</small></span></div>`).join("")||'<p class="k">Belum ada tindak lanjut.</p>'}<div class="sxa"><button class="b s sm" onclick="tglTL('${l._id}')">Catat tindak lanjut</button></div></details>`}
function tgList(tg){const o=new Map();tg.forEach(({i,l})=>{const e=o.get(l._id)||{l,n:0,tag:0,pen:0,mx:0,i:i};e.n++;e.tag+=i.principal_due-i.principal_paid+i.interest_due-i.interest_paid;e.pen+=penaltyFor(i,today());const d=dayDiff(today(),i.due_date);if(d>e.mx){e.mx=d;e.i=i}o.set(l._id,e)});
 const f=S.tkf===undefined||S.tkf===""?-1:+S.tkf,R=[...o.values()].map(e=>({...e,o:kolOf(e.l),s:tlStat(e.l)})).filter(e=>f<0||e.o.k===f).sort((a,b)=>b.o.k-a.o.k||b.mx-a.mx);
 return`<div class="fl"><select aria-label="Filter kolektibilitas" onchange="S.tkf=this.value;render()"><option value="">Semua kolektibilitas</option>${opt(KOL_N.map((n,k)=>[String(k),n]).slice(1),x=>x,String(S.tkf))}</select></div>`+(R.length?`<div class="ll kol"><div class="lh" aria-hidden="true"><span>Pinjaman</span><span>Tunggakan</span><span class="n">Sisa tagihan</span><span>Tindak lanjut terakhir</span><span>Kolektibilitas</span><span></span></div>${R.map(e=>`<button class="li" onclick="openLoan('${e.l._id}')"><span class="l1"><b>${esc(e.l.loan_number)}</b><small>${esc(party(e.l.party_id).name)}</small></span><span class="l2">${e.n} angsuran · tertua jt ${e.i.due_date}</span><span class="n l3">${rp(e.tag+e.pen)}</span><span class="l4">${e.s.last?esc(TL_R[e.s.last.result])+" · "+e.s.last.date+(e.s.over?" · janji lewat":""):"Belum ditindaklanjuti"}</span><span class="l5"><span class="bdg ${e.o.k>=3?"bd":"wr"}">${e.o.label} · ${e.o.days} hari</span></span><span class="l6">${ic("next")}</span></button>`).join("")}</div>`:`<p class="k">Tidak ada tunggakan yang cocok.</p>`)}
function kolBox(){const R=kolSummary(),T=R.reduce((s,r)=>s+r.v,0);return`<h3>Kolektibilitas pinjaman aktif</h3>`+tbl(["Jenjang","#Pinjaman","#Sisa pokok","#%"],R.map(r=>`<tr><td>${r.n}</td><td class="n">${r.c}</td><td class="n">${rp(r.v)}</td><td class="n">${T?Math.round(r.v/T*100):0}%</td></tr>`))}
MK.tl="etl";
MD.tl=()=>{const l=db.loans.find(x=>x._id===S.etl);if(!l)return{t:"Tindak lanjut",s:"mdClose()",y:"Tutup",b:"<p>Pinjaman tidak ditemukan.</p>",nf:1};const o=kolOf(l);
 return{t:"Tindak lanjut · "+l.loan_number,s:"saveTL()",y:"Simpan",b:`<p class="k">${esc(party(l.party_id).name)} · ${o.label}${o.days>0?" · terlambat "+o.days+" hari":""}</p>`+fld("tl-d","Tanggal",{type:"date",value:today(),req:1})+fld("tl-t","Jenis tindakan",{t:"select",opts:opt(Object.entries(TL_T),x=>x,"telepon")})+fld("tl-r","Hasil",{t:"select",opts:opt(Object.entries(TL_R),x=>x,"janji_bayar")})+fld("tl-p","Janji bayar (bila ada)",{type:"date",value:""})+fld("tl-n","Catatan",{value:""})}};
