// ===== SETELAN MODUL (v0.1.039): unit selain Simpan Pinjam bawaan nonaktif; data tidak dihapus =====
function modInfo(k){if(k==="air"){const pc=db.sales.filter(x=>owedS(x)>.005).length;return db.water_connections.length+" sambungan · "+db.sales.length+" penjualan · "+(pc?pc+" piutang pelanggan belum lunas":"tanpa piutang berjalan")}
 const dr=db.payrolls.filter(x=>x.status!=="paid").length;return db.payrolls.length+" gaji · "+(dr?dr+" gaji belum dibayar (draf/disetujui)":"tidak ada gaji tertunda")}
function setMod(k,on){try{const m=MODS.find(x=>x[0]===k);if(!m)throw Error("Modul tidak dikenal");on=!!on;if(!db.settings.modules||typeof db.settings.modules!=="object")db.settings.modules={};
 if(modOn(k)===on){S.msg=m[1]+" sudah "+(on?"aktif":"nonaktif");render();return}
 db.settings.modules[k]=on;audit("setting","settings","modules",m[1]+(on?" diaktifkan":" dinonaktifkan"));save();
 S.msg=m[1]+(on?" diaktifkan; menu dan laporan terkait muncul":" dinonaktifkan; menu disembunyikan, data tetap tersimpan")}catch(e){S.msg="⚠ "+e.message}render()}
function vMod(){return`<h2>Modul Unit Usaha</h2><div class="card"><div class="k">Fokus saat ini: <b>Simpan Pinjam</b>, Transaksi, dan akuntansi selalu aktif. Unit lain bawaan nonaktif agar tampilan ringkas. Menonaktifkan hanya menyembunyikan menu, laporan, dan jalan pintasnya; data, jurnal, dan saldo di buku besar tidak berubah dan tidak dihapus.</div></div>
${MODS.map(([k,n,d])=>{const on=modOn(k);return`<div class="card"><div class="k"><b>${n}</b> · ${on?"Aktif":"Nonaktif"}</div><p class="k">${d}</p><p class="k">${esc(modInfo(k))}</p><button class="b${on?" s":""}" role="switch" aria-checked="${on}" onclick="setMod('${k}',${!on})">${on?"Nonaktifkan":"Aktifkan"} ${n}</button></div>`}).join("")}`}
function vSet(){if(rbacOn()&&curUser()&&!can("setelan.kelola"))return rnBar()+vUsr();return rnBar()+subT(vSet0()+vMod()+vUsr(),"su",[["pf","Profil",null],["mod","Modul","<h2>Modul Unit Usaha</h2>"],["usr","Pengguna & Peran","<h2>Pengguna & Peran</h2>"]])}
function vSet0(){const b=db.bumdes[0]||{};
 return`<h2>Profil BUMDes</h2><div class="card">${BF.map(([k,n,t])=>`<label>${n}${k==="name"?" *":""}</label><input id="bd-${k}" type="${t||"text"}"${t==="tel"?' inputmode="tel"':t==="email"?' inputmode="email"':""} autocomplete="off" value="${esc(b[k])}">`).join("")}<button class="b" onclick="saveBd()">Simpan</button></div>
${docSet()}<h2>Simpan Pinjam</h2><div class="card"><label>Denda keterlambatan (% per hari dari angsuran; 0 = nonaktif)</label><input type="number" step="any" inputmode="decimal" value="${db.settings.penalty_pct_day||0}" onchange="setPen(this.value)"><label>Jasa saat pelunasan dipercepat</label><select onchange="setPo(this.value)"><option value="current"${(db.settings.payoff_interest||"current")==="current"?" selected":""}>Sampai angsuran berjalan (sisa jasa tidak ditagih)</option><option value="full"${db.settings.payoff_interest==="full"?" selected":""}>Seluruh sisa jasa sesuai jadwal</option></select><label>Biaya pelunasan dipercepat (dari Tarif & Pajak)</label><select onchange="setPoFee(this.value)"><option value="">Tanpa biaya</option>${[...new Set(rateRows().filter(r=>r.fee_type==="pelunasan").map(r=>r.fee_code))].map(c=>`<option value="${esc(c)}"${db.settings.payoff_fee===c?" selected":""}>${esc(c)}</option>`).join("")}</select><div class="k">Pilihan berisi tarif berjenis Pelunasan dipercepat. Pajak (bila tarif dikenai pajak) ditambahkan di atas biaya dan masuk akun 2220.</div><label>Biaya yang dipotong saat pencairan</label>${(()=>{const cs=[...new Set(rateRows().filter(r=>DISB_TYPES.includes(r.fee_type)).map(r=>r.fee_code))];return cs.length?cs.map(c=>`<label class="chk"><input type="checkbox" onchange="setDisb('${esc(c)}',this.checked)"${disbCodes().includes(c)?" checked":""}> ${esc(c)}</label>`).join(""):'<div class="k">Belum ada tarif berjenis Administrasi, Provisi, Materai, Transfer, atau Biaya lain di Tarif & Pajak.</div>'})()}<div class="k">Biaya dan pajak dipotong dari pinjaman: dana bersih yang diterima nasabah = pokok − biaya − pajak. Pokok tetap menjadi piutang penuh.</div></div>
<h3>Perhitungan Jasa dan Denda</h3><div class="card"><div class="k">Nilai bawaan sama dengan perilaku sebelumnya. Disimpan sebagai <b>snapshot di setiap pengajuan</b>: mengubahnya tidak mengubah pinjaman yang sudah diajukan. Persentase denda per hari (di atas) berlaku global.</div>${Object.keys(SPC0).map(k=>SPC_OPT[k]?fld("spc-"+k,SPC_L[k],{t:"select",a:' onchange="setCalc(\''+k+'\',this.value)"',opts:opt(SPC_OPT[k],o=>o,String(calcSet()[k]))}):fld("spc-"+k,SPC_L[k],{type:"text",a:' inputmode="numeric" autocomplete="off" onchange="setCalc(\''+k+'\',this.value)"',value:calcSet()[k]})).join("")}</div>
<h3>Alur Pengajuan Lengkap</h3><div class="card"><div class="k">Opsional, bawaan mati. Bila aktif: pengajuan harus diverifikasi (Lolos) dan dianalisis sebelum disetujui, pokok di atas batas Manajer memerlukan hak Persetujuan besar (bila mode pengguna aktif), dan pencairan memerlukan akad. Pinjaman yang sudah aktif tidak terpengaruh.</div>${fld("fl-on","Alur lengkap",{t:"select",a:' onchange="setFlow(\'on\',this.value)"',opts:opt([["0","Mati"],["1","Aktif"]],x=>x,flowOn()?"1":"0")})}${Object.keys(FLOW0).map(k=>fld("fl-"+k,FLOW_L[k],{type:"text",a:k==="docs"?' autocomplete="off" onchange="setFlow(\'docs\',this.value)"':' inputmode="numeric" autocomplete="off" onchange="setFlow(\''+k+'\',this.value)"',value:flowCfg()[k]})).join("")}</div>
<h3>Kolektibilitas Pinjaman</h3><div class="card"><div class="k">Jenjang menurut hari terlambat terlama: Lancar (tidak terlambat), lalu batas hari di bawah. Angka bawaan adalah asumsi teknis, bukan standar OJK; sesuaikan dengan kebijakan BUMDes.</div>${Object.keys(KOL0).map(k=>fld("kol-"+k,KOL_L[k],{type:"text",a:' inputmode="numeric" autocomplete="off" onchange="setKol(\''+k+'\',this.value)"',value:kolCfg()[k]})).join("")}</div>
<h3>Tabungan: Bunga, Biaya, Pajak</h3><div class="card"><div class="k">Bunga dihitung dari saldo harian (per tahun ÷ 365) lewat tombol Proses di sub-tab Tabungan. Biaya administrasi diambil dari kode di Master > Tarif & Pajak (jenis tarif tetap, per bulan); pajak bunga dari kode pajak di master yang sama. Bawaan: bunga 0 (mati), tanpa biaya dan pajak.</div>${fld("sv-rate","Bunga tabungan (% per tahun)",{a:' inputmode="decimal" autocomplete="off" onchange="setSav(\'rate\',this.value)"',value:String(savCfg().rate).replace(".",",")})}${fld("sv-admin_code","Kode biaya administrasi bulanan",{t:"select",a:' onchange="setSav(\'admin_code\',this.value)"',opts:'<option value="">Tanpa biaya</option>'+opt([...new Set(rateRows().map(r=>r.fee_code))],x=>[x,x],savCfg().admin_code)})}${fld("sv-tax_code","Kode pajak bunga",{t:"select",a:' onchange="setSav(\'tax_code\',this.value)"',opts:'<option value="">Tanpa pajak</option>'+opt([...new Set(taxRows().map(r=>r.tax_code))],x=>[x,x],savCfg().tax_code)})}${fld("sv-tax_min","Pajak hanya bila bunga di atas (Rp)",{a:' inputmode="numeric" autocomplete="off" onchange="setSav(\'tax_min\',this.value)"',value:String(savCfg().tax_min)})}<label>Bunga bertingkat menurut saldo</label>${savTiers().length?savTiers().map((t,i)=>`<div class="ph"><span>Saldo ≥ Rp ${fm(t.min)} → <b>${String(t.rate).replace(".",",")}%</b> per tahun</span><span class="pa">${ib("x","Hapus","delSavTier("+i+")","x")}</span></div>`).join(""):'<div class="k">Belum ada tingkat: semua saldo memakai bunga di atas.</div>'}${fld("sv-tmin","Saldo minimum tingkat baru (Rp)",{a:RPA,value:""})}${fld("sv-trate","Bunga tingkat baru (% per tahun)",{a:' inputmode="decimal" autocomplete="off"',value:""})}<button class="b s" onclick="addSavTier()">Tambah tingkat</button><div class="k">Seluruh saldo harian memakai tarif tingkat tertinggi yang tercapai pada hari itu; di bawah tingkat pertama dipakai bunga dasar.</div></div>
<h3>Portal Nasabah</h3><div class="card"><div class="k">Tampilan khusus nasabah (hanya baca): masuk dengan nomor HP dan PIN, melihat pinjaman, jadwal, tabungan, dan mutasi miliknya. Saat ini <b>mode demo tanpa server</b>: data hanya ada di perangkat ini, jadi dipakai untuk pratinjau dan percobaan. Alamat masuk: tambahkan <b>#portal</b> di akhir alamat aplikasi. PIN nasabah diatur dari rincian nasabah di Master.</div>${fld("sp-portal","Portal nasabah",{t:"select",a:' onchange="setPortal(this.value)"',opts:opt([["0","Mati"],["1","Aktif"]],x=>x,ptOn()?"1":"0")})}<p class="k">${db.parties.filter(p=>p.type==="nasabah"&&p.portal).length} nasabah sudah punya PIN portal.</p><div class="fl"><button class="b s" onclick="ptOpen()">Buka halaman masuk</button></div></div>
<h3>Produk Tabungan dan Deposito</h3><div class="card"><div class="k">Produk punya bunga sendiri (menggantikan bunga dasar dan tingkat) dan, bila jangka diisi, menjadi deposito: tidak bisa ditarik sebelum jatuh tempo dan tidak menerima setoran tambahan. Bunga dan jangka dikunci saat rekening dibuka.</div>${savProds().length?savProds().map(p=>`<div class="ph"><span><b>${esc(p.name)}</b> · ${String(p.rate).replace(".",",")}% per tahun · ${p.term>0?"jangka "+p.term+" bulan":"tanpa jangka"}</span><span class="pa">${ib("x","Hapus","delSavProd('"+p.id+"')","x")}</span></div>`).join(""):'<div class="k">Belum ada produk.</div>'}${fld("sv-pn","Nama produk baru",{value:""})}${fld("sv-pr","Bunga (% per tahun)",{a:' inputmode="decimal" autocomplete="off"',value:""})}${fld("sv-pt","Jangka (bulan, 0 = tanpa jangka)",{a:' inputmode="numeric" autocomplete="off"',value:"0"})}<button class="b s" onclick="addSavProd()">Tambah produk</button></div>
<h3>Klausul Akad</h3><div class="card"><div class="k">Ketentuan tambahan yang dicetak di akad (satu klausul per baris, maksimal 30). Isi klausul perlu ditinjau secara hukum oleh pengurus/pengawas; aplikasi tidak menyediakan klausul bawaan.</div>${fld("ak-kl","Klausul",{t:"textarea",a:' onchange="setKlausul(this.value)"',value:aklList().join("\n")})}</div>
<h3>Pemisahan Tugas Simpan Pinjam</h3><div class="card"><div class="k">Berlaku bila Mode Pengguna aktif; bawaan mati. Satu orang tidak boleh menjalankan dua tahap yang saling mengawasi. Pelanggaran ditolak dan tercatat di audit log. Pinjaman saldo awal tidak terpengaruh.</div>${Object.keys(SOD_L).map(k=>fld("sod-"+k,SOD_L[k],{t:"select",a:' onchange="setSod(\''+k+'\',this.value)"',opts:opt([["0","Mati"],["1","Aktif"]],x=>x,sodCfg()[k]?"1":"0")})).join("")}${fld("sod-rsmin","Batas sisa pokok untuk aturan dua orang restrukturisasi (Rp)",{type:"text",a:' inputmode="numeric" autocomplete="off" onchange="setRsMin(this.value)"',value:rsMin(),hint:"0 = berlaku untuk semua pinjaman. Bila diisi, restrukturisasi di bawah batas ini langsung diproses tanpa usulan."})}</div>
<h3>Pengakuan Fee Pencairan</h3><div class="card"><div class="k">Biaya pencairan (administrasi, provisi, dll.) bisa diakui sebagai pendapatan langsung, atau ditangguhkan (akun 2240) lalu diakui per bulan sepanjang tenor. Berlaku untuk pencairan berikutnya; pinjaman lama tidak berubah. Sisa fee diakui penuh saat pinjaman lunas atau dihapus buku.</div>${fld("sp-feerecog","Pengakuan fee pencairan",{t:"select",a:' onchange="setFeeRecog(this.value)"',opts:opt([["langsung","Langsung"],["amortisasi","Diamortisasi sepanjang tenor"]],x=>x,feeRecog())})}${(()=>{const n=db.loans.filter(l=>l.status==="active"&&l.fee_amort&&l.fee_amort.total>l.fee_amort.done).length;return`<p class="k">Fee ditangguhkan: <b>${rp(net(acc("ACC2240"),bal(()=>true)))}</b> · ${n} pinjaman berjalan</p>`+(n?`<div class="fl"><button class="b s" onclick="amortAll()">Akui fee sampai hari ini</button></div>`:"")})()}</div>
<h3>Batas Pengajuan dan Transaksi</h3><div class="card"><div class="k">Pengajuan di luar batas ditolak; pengajuan identik atau melewati batas per nasabah hanya diberi peringatan.</div>${Object.keys(SPL0).map(k=>fld("spl-"+k,SPL_L[k],{type:"text",a:' inputmode="numeric" autocomplete="off" onchange="setSpl(\''+k+'\',this.value)"',value:spl()[k]})).join("")}</div>
<p class="k">Nama tampil di menu, judul tab browser, dan dokumen cetak; alamat dan kontak tampil di kop kwitansi dan bukti pencairan.</p>`}
function saveBd(){try{const v=k=>$("#bd-"+k).value.trim(),n=v("name");
 if(!n)throw fe("bd-name","Nama BUMDes wajib diisi");
 if(v("email")&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v("email")))throw fe("bd-email","Format email tidak valid");
 if(v("phone")&&!/^[\d\s+()\-]{5,20}$/.test(v("phone")))throw fe("bd-phone","Telepon hanya boleh angka, spasi, +, -, ( )");
 const b=db.bumdes[0]||(db.bumdes[0]={_id:"BUMDES-001"});
 BF.forEach(([k])=>{b[k]=v(k)});b.updated_at=now();audit("update","bumdes",b._id);
 if(S.dr)BF.forEach(([k])=>delete S.dr["set|bd-"+k]);S.nsnap=1;save();S.msg="Profil BUMDes disimpan"}catch(e){S.msg="⚠ "+e.message;S.fe=e.f?{id:e.f,m:e.message}:null}render()}
function tgl(id){const p=db.accounting_periods.find(x=>x._id===id);if(p.status==="closed"&&id.slice(0,4)<=cyr()){S.msg="⚠ Periode tahun buku yang sudah ditutup hanya bisa dibuka lewat Batalkan penutupan tahun";render();return}p.status=p.status==="open"?"closed":"open";audit(p.status,"period",id,"Periode "+id);save();render()}
function exp(){const s=JSON.stringify(db,null,1),t=$("#bk");if(t)t.value=s;try{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([s],{type:"application/json"}));a.download="bumdes-backup-"+today()+".json";a.click();try{localStorage.setItem(LB,now())}catch(e){}S.msg="Backup diunduh — simpan file di tempat aman"}catch(e){S.msg="⚠ Export gagal: "+e.message}render()}
function fl(i){const f=i.files[0];if(f)f.text().then(t=>{$("#bk").value=t})}
function chk(j){
 NEWK.forEach(k=>{if(j[k]===undefined)j[k]=[]});
 KEYS.forEach(k=>{if(!Array.isArray(j[k]))throw Error("Koleksi hilang: "+k)});
 const by={};j.journal_lines.forEach(l=>by[l.journal_entry_id]=(by[l.journal_entry_id]||0)+l.debit-l.credit);
 if(Object.values(by).some(x=>Math.abs(x)>.005))throw Error("Ada jurnal yang tidak balance");chkLoans(j)}
// SP0: konsistensi pinjaman pada backup (status vs jadwal vs pembayaran)
function chkLoans(j){const ins={},pay={};j.loan_installments.forEach(i=>(ins[i.loan_id]=ins[i.loan_id]||[]).push(i));j.loan_payments.forEach(p=>(pay[p.loan_id]=pay[p.loan_id]||[]).push(p));
 const ids=new Set(j.loans.map(l=>l._id));
 Object.keys(ins).forEach(k=>{if(!ids.has(k))throw Error("Angsuran mengacu ke pinjaman yang tidak ada ("+k+")")});Object.keys(pay).forEach(k=>{if(!ids.has(k))throw Error("Pembayaran mengacu ke pinjaman yang tidak ada ("+k+")")});
 j.loans.forEach(l=>{const w=m=>Error("Pinjaman "+(l.loan_number||l._id)+": "+m),is=ins[l._id]||[],ps=(pay[l._id]||[]).filter(p=>p.status!=="voided");
  if(!LS[l.status])throw w("status tidak dikenal ("+l.status+")");
  if(!(Number.isFinite(l.principal)&&l.principal>0))throw w("pokok tidak valid");if(!(Number.isInteger(l.tenor)&&l.tenor>=1))throw w("tenor tidak valid");
  if(!(Number.isFinite(l.interest_rate)&&l.interest_rate>=0))throw w("jasa tidak valid");if(!["flat","menurun","anuitas"].includes(l.interest_method))throw w("metode jasa tidak dikenal");if(l.calc!==undefined&&(typeof l.calc!=="object"||!l.calc||Array.isArray(l.calc)))throw w("parameter hitung (snapshot) rusak");
  if(!(j.parties||[]).some(x=>x._id===l.party_id))throw w("nasabah tidak ditemukan");
  if(["active","paid_off"].includes(l.status)){
   if(is.length!==l.tenor)throw w("jumlah angsuran ("+is.length+") tidak sama dengan tenor ("+l.tenor+")");
   if(is.reduce((a,i)=>a+i.principal_due,0)!==l.principal)throw w("jumlah pokok jadwal tidak sama dengan pokok pinjaman");
   if(is.some(i=>i.principal_paid>i.principal_due||i.principal_paid<0))throw w("pembayaran pokok melebihi jadwal");
   if(is.reduce((a,i)=>a+i.principal_paid,0)!==ps.reduce((a,p)=>a+p.principal_amount,0))throw w("pokok terbayar di jadwal tidak sama dengan jumlah pembayaran");
   const all=is.every(i=>i.status==="paid");if(l.status==="paid_off"&&!all)throw w("berstatus Lunas tetapi masih ada angsuran belum lunas");if(l.status==="active"&&all)throw w("berstatus Aktif tetapi semua angsuran sudah lunas");
   if(!l.disbursement_date)throw w("tanggal pencairan kosong")}
  else{if(is.length)throw w("berstatus "+LS[l.status]+" tetapi memiliki jadwal angsuran");if(ps.length)throw w("berstatus "+LS[l.status]+" tetapi memiliki pembayaran")}})}
function impAsk(){try{dataP();const j=JSON.parse($("#bk").value);chk(j);S.imp=j;askC("imp","")}catch(e){S.imp=null;S.msg="⚠ Import gagal: "+e.message;render()}}
function imp(){try{dataP();const j=S.imp||JSON.parse($("#bk").value);chk(j);db=j;migr();S.imp=null;save();S.msg="Import berhasil"}catch(e){S.msg="⚠ Import gagal: "+e.message}render()}
function rst(){try{dataP();reset();S.msg="Data demo direset"}catch(e){S.msg=ER(e)}render()}
