// ===== PIHAK & PEGAWAI SEBAGAI MASTER DATA (v0.1.014) =====
const PT={nasabah:"Nasabah",pelanggan:"Pelanggan",pemasok:"Pemasok",lainnya:"Lainnya"};
const pRef=id=>db.loans.some(l=>l.party_id===id)||db.sales.some(x=>x.party_id===id);
const dupP=(t,n,ph,ad,x)=>db.parties.some(p=>p._id!==x&&p.type===t&&(p.name||"").trim().toLowerCase()===n.toLowerCase()&&(p.phone||"").trim()===ph&&(p.address||"").trim().toLowerCase()===ad.toLowerCase());
function savePihak(){try{const v=i=>$("#"+i).value.trim(),n=v("py-n"),ep=db.parties.find(x=>x._id===S.ey);
 if(!n)throw fe("py-n","Nama wajib diisi");
 const t=ep&&pRef(ep._id)?ep.type:v("py-t");if(!PT[t])throw fe("py-t","Pilih jenis pihak");
 const f={name:n,phone:v("py-p"),address:v("py-a")};
 if(dupP(t,n,f.phone,f.address,S.ey))throw fe("py-n","Pihak dengan jenis, nama, telepon, dan alamat yang sama sudah ada");
 if(ep){Object.assign(ep,f,{type:t});audit("update","party",ep._id,PT[t]+" · "+n);S.ey=null;S.msg="Data pihak diperbarui"}
 else{const p={_id:uid("PTY"),type:t,...f,status:"aktif"};db.parties.push(p);audit("create","party",p._id,PT[t]+" · "+n);S.msg="Pihak ditambahkan"}
 save();clrF("#py-n,#py-p,#py-a");okM()}catch(e){mErr(e);return}render()}
function togP(id){try{const p=db.parties.find(x=>x._id===id),d=(PT[p.type]||p.type)+" · "+p.name;
 if(!isAct(p)){p.status="aktif";audit("activate","party",id,d);save();S.msg="Pihak diaktifkan";render();return}
 if(p.type==="nasabah"&&db.loans.some(l=>l.party_id===id&&["submitted","approved","active"].includes(l.status)))throw Error("Nasabah masih punya pinjaman yang belum selesai (diajukan / disetujui / aktif)");
 if(p.type==="pelanggan"&&piu(id)>0.005)throw Error("Pelanggan masih punya piutang Rp "+fm(piu(id))+"; selesaikan dulu");
 p.status="nonaktif";if(S.ey===id)S.ey=null;audit("deactivate","party",id,d);save();S.msg="Pihak dinonaktifkan; data lama tetap tersimpan"}catch(e){S.msg="⚠ "+e.message}render()}
// ----- master jabatan (v1.1.081): daftar jabatan dipilih dari database, bukan diketik tiap kali -----
const posList=()=>((db.settings&&db.settings.positions)||[]).map(x=>x.name);
const posCnt=n=>db.employees.filter(e=>String(e.position||"").trim().toLowerCase()===n.toLowerCase()).length;
const POS0=[["Direktur","ROL-DIR"],["Sekretaris",""],["Bendahara","ROL-BEN"],["Kepala Unit Usaha","ROL-PTU"],["Kasir","ROL-KSR"],["Petugas Unit","ROL-PTU"],["Petugas Kredit","ROL-KRD"],["Surveyor/Analis","ROL-SVY"],["Staf Administrasi",""]];
// jabatan umum BUMDes (sekali otomatis untuk data baru/lama; tombol "Isi jabatan umum" untuk mengulang); peran bawaan hanya bila peran ada
function posSeed(){db.settings=db.settings||{};const L=db.settings.positions=Array.isArray(db.settings.positions)?db.settings.positions:[];let n=0;POS0.forEach(([nm,r])=>{if(!L.some(x=>x.name.toLowerCase()===nm.toLowerCase())){const o={name:nm};if(r&&(db.roles||[]).some(q=>q._id===r))o.role_id=r;L.push(o);n++}});db.settings.positions_seed=1;return n}
function posDef(){try{needP("master.kelola","Tidak berhak mengelola master");posSync();const n=posSeed();posSync();audit("setting","settings","positions","Jabatan umum diisi: "+n+" ditambah");save();S.msg=n?n+" jabatan umum ditambahkan":"Semua jabatan umum sudah ada"}catch(e){S.msg="⚠ "+e.message}render()}
function posSync(){db.settings=db.settings||{};if(!db.settings.positions_seed)posSeed();const L=db.settings.positions=Array.isArray(db.settings.positions)?db.settings.positions:[];(db.employees||[]).forEach(e=>{const n=String(e.position||"").trim();if(n&&!L.some(x=>x.name.toLowerCase()===n.toLowerCase()))L.push({name:n})});L.sort((a,b)=>a.name.localeCompare(b.name,"id"))}
function openPs(i){mdOpen("ps",String(i))}
function addPos(){try{const n=($("#ps-n").value||"").trim().replace(/\s+/g," ");if(!n)throw fe("ps-n","Isi nama jabatan");if(n.length>60)throw fe("ps-n","Nama jabatan terlalu panjang (maks 60 huruf)");posSync();if(posList().some(x=>x.toLowerCase()===n.toLowerCase()))throw fe("ps-n","Jabatan itu sudah ada");
 db.settings.positions.push({name:n});posSync();audit("setting","settings","positions","Jabatan ditambah: "+n);save();clrF("#ps-n");S.msg="Jabatan "+n+" ditambahkan"}catch(e){S.msg="⚠ "+e.message;S.fe=e.f?{id:e.f,m:e.message}:null}render()}
function delPos(i){try{posSync();const x=db.settings.positions[+i];if(!x)throw Error("Jabatan tidak ditemukan");if(posCnt(x.name))throw Error("Jabatan "+x.name+" masih dipakai "+posCnt(x.name)+" pegawai; ubah jabatan pegawainya dulu");
 db.settings.positions.splice(+i,1);audit("setting","settings","positions","Jabatan dihapus: "+x.name);save();S.msg="Jabatan "+x.name+" dihapus dari daftar"}catch(e){S.msg="⚠ "+e.message}render()}
const empNo=()=>numNext("emp",today());
function saveEmp(){try{negAny();posSync();const v=i=>$("#"+i).value.trim(),n=v("pg-n"),jn=(($("#pg-jn")||{}).value||"").trim().replace(/\s+/g," "),u=v("pg-u"),d=v("pg-d"),ee=db.employees.find(x=>x._id===S.eg);
 if(!n)throw fe("pg-n","Nama pegawai wajib diisi");let j=jn||v("pg-j");if(!j)throw fe("pg-j","Pilih jabatan dari daftar, atau isi Jabatan baru");if(j.length>60)throw fe("pg-jn","Nama jabatan terlalu panjang (maks 60 huruf)");const hit=posList().find(x=>x.toLowerCase()===j.toLowerCase());if(hit)j=hit;
 if(u){const x=db.business_units.find(q=>q._id===u);if(!x)throw fe("pg-u","Unit tidak ditemukan");if(!isAct(x)&&!(ee&&ee.unit_id===u))throw fe("pg-u","Unit nonaktif; pilih unit lain")}
 if(d&&!/^\d{4}-\d{2}-\d{2}$/.test(d))throw fe("pg-d","Tanggal mulai tidak valid");
 const mo=i=>{const x=pn(v(i)||"0");if(!/^\d+(\.\d+)?$/.test(x))throw fe(i,"Isi angka Rupiah (0 jika tidak ada)");return+x},g=mo("pg-g"),ta=mo("pg-t"),po=mo("pg-o");if(po>g+ta)throw fe("pg-o","Potongan tidak boleh melebihi gaji pokok + tunjangan");
 const comps=kRead("pg");const f={name:n,position:j,unit_id:u,phone:v("pg-p"),address:v("pg-a"),start_date:d,base_salary:g,allowance:ta,deduction:po};
 if(db.employees.some(x=>x._id!==S.eg&&x.name.toLowerCase()===n.toLowerCase()&&(x.position||"").toLowerCase()===j.toLowerCase()&&(x.phone||"")===f.phone))throw fe("pg-n","Pegawai dengan nama, jabatan, dan telepon yang sama sudah ada");
 if(!hit){db.settings.positions.push({name:j});posSync();audit("setting","settings","positions","Jabatan ditambah: "+j)}
 if(ee){Object.assign(ee,f);if($("#pg-ks"))ee.components=comps;audit("update","employee",ee._id,ee.emp_number+" · "+n);S.eg=null;S.msg="Data pegawai diperbarui"}
 else{const e={_id:uid("EMP"),emp_number:empNo(),...f,components:comps,status:"aktif"};db.employees.push(e);audit("create","employee",e._id,e.emp_number+" · "+n+" · "+j);S.msg="Pegawai "+e.emp_number+" ditambahkan"}
 save();clrF("#pg-n,#pg-j,#pg-jn,#pg-p,#pg-a,#pg-d,#pg-g,#pg-t,#pg-o");okM()}catch(e){mErr(e);return}render()}
function togG(id){try{const e=db.employees.find(x=>x._id===id),d=e.emp_number+" · "+e.name;
 if(!isAct(e)){const u=e.unit_id&&db.business_units.find(x=>x._id===e.unit_id);if(u&&!isAct(u))throw Error("Unit "+u.name+" nonaktif; pindahkan pegawai ke unit lain lewat Edit dulu");e.status="aktif";delete e.end_date;audit("activate","employee",id,d);S.msg="Pegawai diaktifkan"}
 else{if(db.payrolls.some(p=>p.employee_id===id&&["draft","approved"].includes(p.status)))throw Error("Pegawai masih punya gaji yang belum dibayar (draf / disetujui); selesaikan atau hapus dulu di menu Gaji");e.status="nonaktif";e.end_date=today();if(S.eg===id)S.eg=null;audit("deactivate","employee",id,d);S.msg="Pegawai dinonaktifkan; data lama tetap tersimpan"}save()}catch(e){S.msg="⚠ "+e.message}render()}
function vPihak(){const f=S.pf||"",q=S.pq||"",L=db.parties.filter(p=>(!f||p.type===f)&&mhit(q,p.name,p.phone,p.address));
 return`<h2>Pihak</h2>${addB("Tambah pihak","py")}${dcard("Daftar Pihak","Nasabah, pelanggan, pemasok, dan pihak lain dalam satu daftar. "+L.length+" pihak"+(f?" ("+PT[f]+")":"")+(q.trim()?" cocok dengan pencarian":"")+".",`<div class="fl">${mq("pq","Cari nama / telepon / alamat…","Cari pihak")}<select aria-label="Jenis pihak" onchange="S.pf=this.value;render()"><option value="">Semua jenis</option>${opt(Object.keys(PT),k=>[k,PT[k]],f)}</select></div>`+(L.length?`<div class="upl">${L.slice(0,pgLim("pih")).map((p,i)=>mrw("py",p._id,avA(p.name,i),esc(p.name),esc(p.phone||"-")+" · "+esc(PT[p.type]||p.type),"","",mbd(p),isAct(p)?"":"vd")).join("")}</div>${pgMore("pih",L.length)}`:'<div class="empty">Belum ada pihak yang cocok.</div>'),"")}
`}
function vPeg(){const na=db.employees.filter(isAct).length,q=S.eq||"",fs=S.efs||"",EL=db.employees.filter(e=>(!fs||(fs==="aktif")===isAct(e))&&mhit(q,e.name,e.emp_number,e.position));
 posSync();const PL=posList();
 return`<h2>Pegawai</h2>${addB("Tambah pegawai","pg")}${dcard("Daftar Pegawai",na+" aktif dari "+db.employees.length+" pegawai. Master ini menjadi dasar modul Payroll."+((q.trim()||fs)?" Menampilkan "+EL.length+".":""),`<div class="fl">${mq("eq","Cari nama / nomor / jabatan…","Cari pegawai")}<select aria-label="Filter status pegawai" onchange="S.efs=this.value;render()"><option value="">Semua status</option><option value="aktif"${fs==="aktif"?" selected":""}>Aktif</option><option value="nonaktif"${fs==="nonaktif"?" selected":""}>Nonaktif</option></select></div>`+(EL.length?`<div class="upl">${EL.slice(0,pgLim("peg")).map((e,i)=>mrw("pg",e._id,avA(e.name,i),esc(e.name),esc(e.emp_number)+" · "+esc(e.position||"-")+" · "+esc(unitName(e.unit_id)),rp(e.base_salary||0),"gaji pokok",mbd(e),isAct(e)?"":"vd")).join("")}</div>${pgMore("peg",EL.length)}`:`<div class="empty">${db.employees.length?"Tidak ada pegawai yang cocok.":"Belum ada pegawai."}</div>`),"")}
${sxG("posl",false,"Daftar jabatan ("+PL.length+")",`<div class="mpj"><p class="k">Jabatan dipilih dari daftar ini saat menambah pegawai. Jabatan baru bisa ditambah di sini atau langsung dari form pegawai.</p>${PL.length?PL.map((n,i)=>`<div class="kv"><span>${esc(n)} <span class="k">· ${posCnt(n)} pegawai${posDefTxt(n)}</span></span><span>${ib("edit","Atur bawaan gaji & komponen","openPs("+i+")","s")}${posCnt(n)?"":`<button class="b s sm" onclick="delPos(${i})" aria-label="Hapus jabatan ${esc(n)}">Hapus</button>`}</span></div>`).join(""):`<p class="k">Belum ada jabatan.</p>`}${fld("ps-n","Jabatan baru",{value:""})}<div class="fl"><button class="b s" id="ps-add" onclick="addPos()">Tambah jabatan</button><button class="b s" id="ps-def" onclick="posDef()">Isi jabatan umum</button></div></div>`)}
`}

// ===== PAYROLL (v0.1.015-016): profil gaji, komponen gaji, penggajian per periode, rincian draf, persetujuan, pembayaran → jurnal, slip =====
const PS={draft:"Draf",approved:"Disetujui",paid:"Dibayar"},payGet=id=>db.payrolls.find(x=>x._id===id),payOf=id=>db.salary_payments.find(s=>s.payroll_id===id&&s.status==="posted"),empName=id=>(db.employees.find(e=>e._id===id)||{}).name||"-";
const PK=id=>db.payroll_components.find(c=>c._id===id),PKT={earning:"Pendapatan",deduction:"Potongan"},ecList=e=>(e.components||[]).filter(x=>PK(x.component_id)),
 payRecalc=p=>{const it=db.payroll_items.filter(i=>i.payroll_id===p._id);p.gross_salary=it.filter(i=>i.type==="earning").reduce((s,i)=>s+i.amount,0);p.total_deduction=it.filter(i=>i.type==="deduction").reduce((s,i)=>s+i.amount,0);p.net_salary=p.gross_salary-p.total_deduction};
function payGen(){try{const m=$("#gj-m").value;if(!/^\d{4}-\d{2}$/.test(m))throw fe("gj-m","Pilih periode gaji (bulan)");if(closed(m+"-01"))throw fe("gj-m","Periode "+m+" sudah ditutup");
 const E=db.employees.filter(e=>isAct(e)&&(e.base_salary||0)>0&&!(e.start_date&&e.start_date.slice(0,7)>m)&&!db.payrolls.some(p=>p.employee_id===e._id&&p.period===m));
 if(!E.length)throw fe("gj-m","Tidak ada pegawai aktif bergaji yang belum diproses untuk periode "+m);
// komponen gaji: tetap (Rp), persen_gaji (% gaji pokok), persen_laba (% laba periode; basis sebelum/sesudah beban gaji)
 const kc=k=>CALC[k.calc]?k.calc:"tetap";
 const cs=e=>ecList(e).reduce((o,x)=>{const k=PK(x.component_id);if(kc(k)!=="persen_laba")o[k.type]+=ecAmt(x,e);return o},{earning:0,deduction:0});
 E.forEach(e=>{const c=cs(e);if((e.deduction||0)+c.deduction>e.base_salary+(e.allowance||0)+c.earning)throw fe("gj-m","Potongan "+e.name+" melebihi pendapatannya; periksa komponen tetap pegawai")});
 const P=[];
 E.forEach(e=>{const p={_id:uid("PAY"),period:m,employee_id:e._id,unit_id:e.unit_id||"",gross_salary:0,total_deduction:0,net_salary:0,status:"draft",created_at:now()};db.payrolls.push(p);P.push([p,e]);
  [["Gaji Pokok",e.base_salary,"earning"],["Tunjangan",e.allowance||0,"earning"],["Potongan",e.deduction||0,"deduction"]].forEach(([n,a,t])=>{if(a>0)db.payroll_items.push({_id:uid("PIT"),payroll_id:p._id,name:n,amount:a,type:t,core:true})});
  ecList(e).forEach(x=>{const k=PK(x.component_id);if(kc(k)==="persen_laba")return;const a=ecAmt(x,e);if(a>0)db.payroll_items.push({_id:uid("PIT"),payroll_id:p._id,component_id:k._id,name:k.name+(kc(k)==="persen_gaji"?" ("+rtp(x.rate)+"% gaji pokok)":""),amount:a,type:k.type})});payRecalc(p)});
 const lc={};P.forEach(([p,e])=>{ecList(e).forEach(x=>{const k=PK(x.component_id);if(kc(k)!=="persen_laba")return;const key=(e.unit_id||"")+"|"+(k.basis==="sebelum"?"s":"e"),L=lc[key]=lc[key]||labaGaji(m,e.unit_id||"",k.basis==="sebelum"),a=Math.round(Math.max(0,L)*(+x.rate||0)/100);
  if(a>0)db.payroll_items.push({_id:uid("PIT"),payroll_id:p._id,component_id:k._id,name:k.name+" ("+rtp(x.rate)+"% laba "+(k.basis==="sebelum"?"sebelum":"sesudah")+" beban gaji)",amount:a,type:k.type})});payRecalc(p)});
 audit("create","payroll",m,E.length+" gaji periode "+m+" dibuat (draf)");save();S.msg=E.length+" gaji periode "+m+" dibuat berstatus Draf"}catch(e){mErr(e);return}render()}
// komponen gaji (master), komponen tetap pegawai, rincian gaji draf
const CALC={tetap:"Nominal tetap (Rp)",persen_gaji:"Persen dari gaji pokok",persen_laba:"Persen dari laba"},BASIS={sesudah:"Laba setelah beban gaji",sebelum:"Laba sebelum beban gaji"},rtp=n=>String(+(+n).toFixed(2)).replace(".",",");
const ecAmt=(x,e)=>{const k=PK(x.component_id);if(!k)return 0;if(k.calc==="persen_gaji")return Math.round((e.base_salary||0)*(+x.rate||0)/100);if(k.calc==="persen_laba")return 0;return +x.amount||0};
// laba periode m (tanpa jurnal penutup), per unit bila unit diisi. sebelum=true: tanpa beban gaji; false: dikurangi beban gaji periode itu (gaji pokok + tunjangan + komponen bukan persen laba, semua pegawai pada lingkup yang sama; termasuk draf yang belum dijurnal)
function labaGaji(m,u,sebelum){const T=trT();let L=pl(l=>l.date.slice(0,7)===m&&(!u||l.business_unit_id===u)&&T.get(l.transaction_id)!=="closing");
 let b=0;db.journal_lines.filter(l=>cur(l)&&l.date.slice(0,7)===m&&(!u||l.business_unit_id===u)&&T.get(l.transaction_id)==="payroll"&&l.account_id==="ACC5100").forEach(l=>{b+=l.debit-l.credit});
 const sb=L.p+b;if(sebelum)return sb;
 let g=0;const ids=new Set(db.payrolls.filter(p=>p.period===m&&(!u||p.unit_id===u)).map(p=>p._id));db.payroll_items.forEach(i=>{if(ids.has(i.payroll_id)&&i.type==="earning"&&!/laba (sebelum|sesudah) beban gaji\)$/.test(i.name))g+=i.amount});
 const bj=Math.max(b,0);return sb-Math.max(g,bj)}
const kDesc=k=>{const c=k.calc||"tetap",v=+k.value||0;return c==="tetap"?"Nominal"+(v?" Rp "+fm(v):""):c==="persen_gaji"?rtp(v)+"% gaji pokok":rtp(v)+"% "+(k.basis==="sebelum"?"laba sebelum beban gaji":"laba sesudah beban gaji")};
// ceklist komponen (pola sama dengan biaya pencairan pinjaman): sel=[{component_id,amount|rate}], px=awalan id
function kChecklist(px,sel){const A=db.payroll_components.filter(k=>isAct(k)||sel.some(x=>x.component_id===k._id));if(!A.length)return`<p class="k">Belum ada komponen gaji. Buat dulu di Gaji &gt; Komponen.</p>`;
 return`<label>Komponen gaji pegawai (dari Master Komponen Gaji)</label><div class="chks" id="${px}-ks">${A.map(k=>{const x=sel.find(q=>q.component_id===k._id),c=k.calc||"tetap",v=x?(c==="tetap"?x.amount:x.rate):k.value,id=esc(k._id);
 return`<div class="fcr" style="display:flex;align-items:center;gap:.5rem;flex-wrap:wrap"><label class="chk" style="flex:1 1 12rem"><input type="checkbox" id="${px}-k-${id}"${x?" checked":""}> ${esc(k.name)} <span class="k">${PKT[k.type]} · ${esc(kDesc(k))}${isAct(k)?"":" · nonaktif"}</span></label><span class="fq k"><label class="sr" for="${px}-v-${id}">Nilai ${esc(k.name)}</label>${c==="tetap"?"Rp":"%"} <input type="text" id="${px}-v-${id}" inputmode="decimal" autocomplete="off" value="${v?(c==="tetap"?fm(v):rtp(v)):""}" style="width:7rem"${c==="tetap"?' oninput="fmtR(this)"':""}></span></div>`}).join("")}</div>`}
function kRead(px){const o=[];db.payroll_components.forEach(k=>{const cb=$("#"+px+"-k-"+k._id);if(!cb||!cb.checked)return;const c=k.calc||"tetap",id=px+"-v-"+k._id,raw=pn((($("#"+id)||{}).value||"").trim().replace(",","."));
  if(!/^\d+(\.\d+)?$/.test(raw)||+raw<=0)throw fe(id,"Isi nilai "+k.name+" lebih dari 0");if(c!=="tetap"&&+raw>100)throw fe(id,"Persentase "+k.name+" tidak boleh lebih dari 100");o.push(c==="tetap"?{component_id:k._id,amount:+raw}:{component_id:k._id,rate:+raw})});return o}
// bawaan jabatan: gaji standar + komponen; dipakai mengisi form pegawai baru
const posDefTxt=n=>{const x=posGet(n);return x&&(x.base_salary||(x.comps||[]).length)?" · gaji standar Rp "+fm(x.base_salary||0)+((x.comps||[]).length?" + "+x.comps.length+" komponen":""):""};
const posGet=n=>((db.settings&&db.settings.positions)||[]).find(x=>x.name.toLowerCase()===String(n||"").trim().toLowerCase());
function posPick(){if(S.eg)return;const x=posGet($("#pg-j").value);if(!x)return;[["g","base_salary"],["t","allowance"],["o","deduction"]].forEach(([k,f])=>{const el=$("#pg-"+k);if(el&&x[f]!=null)el.value=x[f]?fm(x[f]):""});
 db.payroll_components.forEach(k=>{const cb=$("#pg-k-"+k._id);if(cb)cb.checked=false});(x.comps||[]).forEach(q=>{const k=PK(q.component_id),cb=k&&$("#pg-k-"+k._id),vi=k&&$("#pg-v-"+k._id);if(cb&&isAct(k)){cb.checked=true;if(vi){const c=k.calc||"tetap",v=c==="tetap"?q.amount:q.rate;vi.value=v?(c==="tetap"?fm(v):rtp(v)):""}}})}
function savePosDef(){try{negAny();posSync();const x=db.settings.positions[+S.ps];if(!x)throw Error("Jabatan tidak ditemukan");const mo=i=>{const r=pn((($("#"+i)||{}).value||"").trim()||"0");if(!/^\d+(\.\d+)?$/.test(r))throw fe(i,"Isi angka Rupiah (0 jika tidak ada)");return+r},g=mo("ps-g"),ta=mo("ps-t"),po=mo("ps-o");if(po>g+ta)throw fe("ps-o","Potongan tidak boleh melebihi gaji pokok + tunjangan");
 x.base_salary=g;x.allowance=ta;x.deduction=po;x.comps=kRead("ps");const rr=(($("#ps-r")||{}).value)||"";if(rr&&!db.roles.some(q=>q._id===rr&&q._id!=="ROL-SUP"))throw fe("ps-r","Peran tidak ditemukan");if(rr)x.role_id=rr;else delete x.role_id;audit("setting","settings","positions","Bawaan jabatan "+x.name+": gaji Rp "+fm(g)+", "+x.comps.length+" komponen");save();S.msg="Bawaan jabatan "+x.name+" disimpan (dipakai saat menambah pegawai baru)";okM()}catch(e){mErr(e);return}render()}
const kUsed=id=>db.employees.some(e=>(e.components||[]).some(x=>x.component_id===id))||db.payroll_items.some(i=>i.component_id===id);
function saveComp(){try{const n=$("#pk-n").value.trim(),ek=PK(S.ek),t=ek&&kUsed(ek._id)?ek.type:$("#pk-t").value;if(!n)throw fe("pk-n","Nama komponen wajib diisi");if(!PKT[t])throw fe("pk-t","Pilih jenis komponen");
 const calc=ek&&kUsed(ek._id)?(ek.calc||"tetap"):(($("#pk-c")||{}).value||"tetap");if(!CALC[calc])throw fe("pk-c","Pilih cara hitung");const basis=calc==="persen_laba"?((($("#pk-b")||{}).value)==="sebelum"?"sebelum":"sesudah"):"";
 const vr=pn((($("#pk-v")||{}).value||"").trim()||"0");if(!/^\d+(\.\d+)?$/.test(vr))throw fe("pk-v","Isi angka (boleh kosong atau 0)");const val=+vr;if(calc!=="tetap"&&val>100)throw fe("pk-v","Persentase tidak boleh lebih dari 100");
 if(db.payroll_components.some(c=>c._id!==S.ek&&c.name.toLowerCase()===n.toLowerCase()))throw fe("pk-n","Komponen dengan nama itu sudah ada");
 if(ek){ek.name=n;ek.type=t;ek.calc=calc;ek.value=val;ek.basis=basis;audit("update","payroll_component",ek._id,PKT[t]+" · "+n);S.ek=null;S.msg="Komponen gaji diperbarui"}
 else{const c={_id:uid("PC"),name:n,type:t,calc,value:val,basis,status:"aktif"};db.payroll_components.push(c);audit("create","payroll_component",c._id,PKT[t]+" · "+n);S.msg="Komponen gaji ditambahkan"}
 save();clrF("#pk-n,#pk-t,#pk-c,#pk-v,#pk-b");okM()}catch(e){mErr(e);return}render()}
function togK(id){try{const k=PK(id),d=PKT[k.type]+" · "+k.name;if(!isAct(k)){k.status="aktif";audit("activate","payroll_component",id,d);S.msg="Komponen diaktifkan"}
 else{if(db.employees.some(e=>isAct(e)&&(e.components||[]).some(x=>x.component_id===id)))throw Error("Komponen masih dipakai pegawai aktif; hapus dari pegawai dulu");k.status="nonaktif";if(S.ek===id)S.ek=null;audit("deactivate","payroll_component",id,d);S.msg="Komponen dinonaktifkan; gaji lama tidak berubah"}save()}catch(e){S.msg="⚠ "+e.message}render()}
function ecAdd(){try{negAny();const e=db.employees.find(x=>x._id===S.eg),k=PK($("#ec-c").value),raw=pn($("#ec-a").value||"");if(!e)return;if(!k||!isAct(k))throw fe("ec-c","Pilih komponen");
 if(!/^\d+(\.\d+)?$/.test(raw)||+raw<=0)throw fe("ec-a","Jumlah harus lebih dari 0");if((e.components||[]).some(x=>x.component_id===k._id))throw fe("ec-c","Komponen sudah ada pada pegawai ini; hapus dulu untuk mengganti jumlah");
 (e.components=e.components||[]).push({component_id:k._id,amount:+raw});audit("update","employee",e._id,e.emp_number+" · +"+k.name+" Rp "+fm(+raw));save();clrF("#ec-a");S.msg="Komponen tetap ditambahkan (berlaku untuk gaji yang dibuat berikutnya)"}catch(e){mErr(e);return}render()}
function ecDel(cid){const e=db.employees.find(x=>x._id===S.eg),k=PK(cid);if(!e)return;e.components=(e.components||[]).filter(x=>x.component_id!==cid);audit("update","employee",e._id,e.emp_number+" · −"+(k?k.name:cid));save();S.msg="Komponen tetap dihapus dari pegawai";render()}
function vEC(e){const L=ecList(e);return`<h2>Komponen tetap ${esc(e.name)}</h2><p class="k">Tambahan per bulan di luar gaji pokok, tunjangan, dan potongan tetap; otomatis masuk gaji yang dibuat berikutnya.</p>${L.length?tbl(["Komponen","Jenis","#Jumlah",""],L.map(x=>{const k=PK(x.component_id);return`<tr><td>${esc(k.name)}</td><td>${PKT[k.type]}</td><td class="n">${rp(x.amount)}</td><td>${ib("x","Hapus","ecDel('"+k._id+"')","s")}</td></tr>`})):'<p class="k">Belum ada komponen tetap.</p>'}
<div class="card">${fld("ec-c","Komponen",{t:"select",opts:opt(db.payroll_components.filter(isAct),k=>[k._id,k.name+" ("+PKT[k.type]+")"])})}${fld("ec-a","Jumlah per bulan (Rp)",{type:"text",a:' inputmode="numeric" autocomplete="off" oninput="fmtR(this)"'})}<button class="b" onclick="ecAdd()">Tambah komponen</button></div>`}
function payOpen(id){S.pd=S.pd===id?null:id;S.msg="";render();if(S.pd){const e=$("#pd-h");if(e&&e.scrollIntoView)e.scrollIntoView({block:"center"})}}
function piAdd(){try{negAny();const p=payGet(S.pd),k=PK($("#pi-c").value),raw=pn($("#pi-a").value||"");if(!p||p.status!=="draft")throw Error("Hanya gaji berstatus Draf yang bisa diubah");if(!k||!isAct(k))throw fe("pi-c","Pilih komponen");
 if(!/^\d+(\.\d+)?$/.test(raw)||+raw<=0)throw fe("pi-a","Jumlah harus lebih dari 0");
 const it={_id:uid("PIT"),payroll_id:p._id,component_id:k._id,name:k.name,amount:+raw,type:k.type};db.payroll_items.push(it);payRecalc(p);
 if(p.net_salary<0){db.payroll_items.pop();payRecalc(p);throw fe("pi-a","Potongan melebihi pendapatan; gaji bersih tidak boleh negatif")}
 audit("update","payroll",p._id,p.period+" · "+empName(p.employee_id)+" · +"+k.name+" Rp "+fm(+raw));save();clrF("#pi-a");S.msg="Komponen ditambahkan ke gaji draf"}catch(e){mErr(e);return}render()}
function piDel(iid){try{const it=db.payroll_items.find(x=>x._id===iid),p=it&&payGet(it.payroll_id);if(!p||p.status!=="draft")throw Error("Hanya gaji berstatus Draf yang bisa diubah");if(it.core)throw Error("Gaji pokok, tunjangan, dan potongan tetap diubah lewat Master > Pegawai lalu buat ulang draf");
 db.payroll_items=db.payroll_items.filter(x=>x._id!==iid);payRecalc(p);
 if(p.net_salary<0){db.payroll_items.push(it);payRecalc(p);throw Error("Menghapus komponen ini membuat gaji bersih negatif")}
 audit("update","payroll",p._id,p.period+" · "+empName(p.employee_id)+" · −"+it.name);save();S.msg="Komponen dihapus dari gaji draf"}catch(e){S.msg="⚠ "+e.message}render()}
function vSlip(id){const p=payGet(id),bar=`<div class="noprint"><button class="b" onclick="window.print()">Cetak</button><button class="b s" onclick="S.doc=null;render()">Kembali</button></div>`;
 if(!p||p.status==="draft")return`${bar}<p class="k">Slip hanya tersedia untuk gaji yang sudah disetujui atau dibayar.</p>`;
 const e=db.employees.find(x=>x._id===p.employee_id)||{},b=db.bumdes[0]||{},R=(a,v)=>`<tr><td>${a}</td><td class="n">${v}</td></tr>`,it=db.payroll_items.filter(i=>i.payroll_id===id),sp=payOf(id),ci=sp&&db.cash_accounts.find(c=>c._id===sp.cash_account_id),
 grp=t=>it.filter(i=>i.type===t).map(i=>R(esc(i.name),rp(i.amount))).join("")||R("-","-");
 return`${bar}<div class="doc">${kop()}<h3>SLIP GAJI</h3><div class="cn">Periode ${p.period} · ${p.status==="paid"?"Dibayar "+sp.payment_date+(ci?" via "+esc(ci.name):""):"Belum dibayar (disetujui)"}</div>
<table>${R("Nama",esc(e.name||"-"))}${R("No. pegawai",esc(e.emp_number||"-"))}${R("Jabatan",esc(e.position||"-"))}${R("Unit usaha",esc(unitName(p.unit_id)))}</table>
<table><tr><th colspan="2">Pendapatan</th></tr>${grp("earning")}<tr><th>Gaji bruto</th><th class="n">${rp(p.gross_salary)}</th></tr><tr><th colspan="2">Potongan</th></tr>${grp("deduction")}<tr><th>Total potongan</th><th class="n">${rp(p.total_deduction)}</th></tr><tr><th>Gaji bersih</th><th class="n">${rp(p.net_salary)}</th></tr></table>
<div class="tb">Terbilang: ${cap(terbilang(p.net_salary))}</div>${sig([["Penerima",e.name],["Bendahara",b.treasurer]],1,sp?sp.payment_date:today())}</div>`}
function payAppr(id){const p=payGet(id);if(!p||p.status!=="draft")return;p.status="approved";p.approved_at=now();audit("approve","payroll",id,p.period+" · "+empName(p.employee_id));save();S.msg="Gaji disetujui";render()}
function payDel(id){const p=payGet(id);if(!p||p.status!=="draft")return;db.payrolls=db.payrolls.filter(x=>x._id!==id);db.payroll_items=db.payroll_items.filter(x=>x.payroll_id!==id);if(S.pd===id)S.pd=null;audit("delete","payroll",id,p.period+" · "+empName(p.employee_id)+" (draf)");save();S.msg="Draf gaji dihapus";render()}
function payPost(p,d,k){const L=[{acc:"ACC5100",d:p.gross_salary},{acc:k.account_id,c:p.net_salary}];if(p.total_deduction>0)L.push({acc:"ACC2200",c:p.total_deduction});
 const t=post({type:"payroll",date:d,unit:p.unit_id,desc:"Gaji "+p.period+" · "+empName(p.employee_id),lines:L});
 db.salary_payments.push({_id:uid("SLP"),payroll_id:p._id,payment_date:d,cash_account_id:k._id,amount:p.net_salary,transaction_id:t._id,status:"posted"});p.status="paid";
 audit("pay","payroll",p._id,p.period+" · "+empName(p.employee_id)+" · Rp "+fm(p.net_salary))}
function payBayar(id){try{const p=payGet(id),d=$("#gj-d").value,k=db.cash_accounts.find(c=>c._id===$("#gj-k").value);
 if(!p||p.status!=="approved")throw Error("Hanya gaji berstatus Disetujui yang bisa dibayar");if(!d)throw fe("gj-d","Tanggal bayar wajib diisi");if(d.slice(0,7)<p.period)throw fe("gj-d","Tanggal bayar tidak boleh sebelum periode gaji");if(!k)throw fe("gj-k","Pilih kas/bank");
 payPost(p,d,k);save();S.msg="Gaji dibayar dan dijurnal"}catch(e){mErr(e);return}render()}
// v1.1.160 — setujui dan bayar massal per periode (mengikuti filter unit di header)
const gjScope=(st,per)=>db.payrolls.filter(p=>p.status===st&&p.period===per&&(S.unit==="all"||p.unit_id===S.unit));
function gjPending(){return[...new Set(db.payrolls.filter(p=>(p.status==="draft"||p.status==="approved")&&(S.unit==="all"||p.unit_id===S.unit)).map(p=>p.period))].sort().reverse()}
function gjPer(){const L=gjPending();return L.includes(S.gpm)?S.gpm:(L[0]||"")}
function payApprAll(per){try{const L=gjScope("draft",per);if(!L.length)throw Error("Tidak ada gaji draf pada periode "+per);
 L.forEach(p=>{p.status="approved";p.approved_at=now();audit("approve","payroll",p._id,p.period+" · "+empName(p.employee_id)+" (massal)")});save();S.msg=L.length+" gaji periode "+per+" disetujui"}catch(e){S.msg="⚠ "+e.message}render()}
function payBayarAll(per){try{const L=gjScope("approved",per),d=$("#gj-d").value,k=db.cash_accounts.find(c=>c._id===$("#gj-k").value);
 if(!L.length)throw Error("Tidak ada gaji berstatus Disetujui pada periode "+per);if(!d)throw fe("gj-d","Tanggal bayar wajib diisi");if(d.slice(0,7)<per)throw fe("gj-d","Tanggal bayar tidak boleh sebelum periode gaji");if(!k)throw fe("gj-k","Pilih kas/bank");
 let n=0,tot=0;try{L.forEach(p=>{payPost(p,d,k);n++;tot+=p.net_salary})}catch(e){save();throw Error(n+" gaji sudah dibayar, berhenti pada "+empName(L[n].employee_id)+": "+e.message)}
 save();S.msg=n+" gaji periode "+per+" dibayar (Rp "+fm(tot)+") dari "+k.name}catch(e){S.msg="⚠ "+e.message}render()}
function batalGaji(id){try{const s=db.salary_payments.find(x=>x._id===id),p=s&&payGet(s.payroll_id);if(!s||s.status!=="posted"||!p)throw Error("Pembayaran gaji tidak ditemukan");{const k=p.unit_id||"",b=potBal()[k]||{o:0,s:0};if(p.total_deduction>0&&b.o-p.total_deduction<b.s)throw Error("Potongan gaji unit ini sudah disetor; batalkan setoran potongan terlebih dahulu")}rev(s.transaction_id);s.status="voided";p.status="approved";audit("void","salary_payment",id,p.period+" · "+empName(p.employee_id));save();S.msg="Pembayaran gaji dibatalkan dengan jurnal pembalik; gaji kembali Disetujui"}catch(e){S.msg="⚠ "+e.message}render()}
function vPay(){return subT(vPay0()+vKomp()+vRepGaji(),"gt",[["proses","Proses Gaji",null],["komp","Komponen","<h2>Komponen Gaji</h2>"],["rekap","Laporan","<h2>Laporan Gaji</h2>"]])}
function vPay0(){const U=x=>S.unit==="all"||x.unit_id===S.unit,L=db.payrolls.filter(U).sort((a,b)=>b.period.localeCompare(a.period)||empName(a.employee_id).localeCompare(empName(b.employee_id))),ne=db.employees.filter(e=>isAct(e)&&(e.base_salary||0)>0).length,kas=opt(db.cash_accounts.filter(isAct),c=>[c._id,c.name]);
 const act=p=>ib("edit","Rincian","payOpen('"+p._id+"')","s")+(p.status!=="draft"?ib("print","Slip","openDoc('slip','"+p._id+"')","s"):"")+(p.status==="draft"?ib("check","Setujui","payAppr('"+p._id+"')")+ib("x","Hapus","payDel('"+p._id+"')","s"):p.status==="approved"?ib("cash","Bayar","payBayar('"+p._id+"')"):(payOf(p._id)?ib("undo","Batalkan","askC('batalGaji','"+payOf(p._id)._id+"')","x"):""));
 const dp=payGet(S.pd),di=dp?db.payroll_items.filter(i=>i.payroll_id===dp._id):[],
  sb=st=>`<span class="bdg ${st==="draft"?"wr":"ok"}">${PS[st]||st}</span>`,sh=L.slice(0,S.lim||PG),tn=L.reduce((t,p)=>t+p.net_salary,0);
 const det=dp?dcard(`<span id="pd-h">Rincian gaji ${esc(empName(dp.employee_id))} · ${dp.period}</span>`,PS[dp.status]+" · bruto "+rp(dp.gross_salary)+" − potongan "+rp(dp.total_deduction)+" = bersih "+rp(dp.net_salary),`<div class="upl">${di.map(i=>`<div class="upr alr"><span class="tri ${i.type==="earning"?"in":"out"}" aria-hidden="true">${i.type==="earning"?"+":"−"}</span><span class="upm"><b>${esc(i.name)}</b><small>${PKT[i.type]}</small></span><span class="upa"><b>${rp(i.amount)}</b>${dp.status==="draft"&&!i.core?`<span class="alb">${ib("x","Hapus","piDel('"+i._id+"')","s")}</span>`:""}</span></div>`).join("")}<div class="upr lgo"><span class="upm"><b>Bersih</b></span><span class="upa"><b>${rp(dp.net_salary)}</b></span></div></div>`+(dp.status==="draft"?`<div class="gjf"><p class="k">Tambah komponen sekali pakai (lembur, insentif, kasbon, dll.) ke gaji draf ini</p><label>Komponen</label><select id="pi-c">${opt(db.payroll_components.filter(isAct),k=>[k._id,k.name+" ("+PKT[k.type]+")"])}</select><label>Jumlah (Rp)</label><input id="pi-a" type="text" inputmode="numeric" autocomplete="off" oninput="fmtR(this)"><button class="b" onclick="piAdd()">Tambah ke gaji</button></div>`:'<p class="k">Gaji yang sudah disetujui tidak dapat diubah.</p>'),"alf"):"";
 return`<h2>Proses Gaji</h2>${dcard("Buat gaji periode","Draf → Disetujui → Dibayar · "+ne+" pegawai aktif punya gaji pokok",`<label>Periode gaji</label><input id="gj-m" type="month" value="${today().slice(0,7)}"><button class="b" onclick="payGen()">Buat gaji periode ini</button><p class="k">Isi gaji pokok di Master &gt; Pegawai. Beban gaji dicatat ke unit pegawai (Umum bila tanpa unit); potongan dicatat sebagai Kewajiban Lain (2200) sampai disetor.</p>`,"alf")}
${dcard("Pembayaran gaji","Dipakai untuk tombol Bayar dan Bayar semua",`<label>Tanggal bayar</label><input id="gj-d" type="date" value="${today()}"><label>Kas/Bank</label><select id="gj-k">${kas}</select>`,"alf")}${gjMass()}${potCard()}
${dcard("Daftar Gaji",L.length?L.length+" gaji · total bersih "+rp(tn)+(L.length>sh.length?" · tampil "+sh.length:""):"Belum ada gaji",(L.length?`<div class="upl">${sh.map((p,i)=>{const nm=empName(p.employee_id);return`<div class="upr alr gjr">${avA(nm,i)}<span class="upm"><b>${esc(nm)}</b><small>${p.period} · ${esc(unitName(p.unit_id))}</small><small>Bruto ${rp(p.gross_salary)} − potongan ${rp(p.total_deduction)}</small></span><span class="upa"><b>${rp(p.net_salary)}</b>${sb(p.status)}</span><span class="alb gjb">${act(p)}</span></div>`}).join("")}</div>`:'<div class="empty">Belum ada gaji diproses. Isi gaji pokok pegawai di Master &gt; Pegawai, lalu buat gaji periode.</div>')+more(L.length-sh.length),"")}${det}`}
function gjMass(){const per=gjPer();if(!per)return"";const dr=gjScope("draft",per),ap=gjScope("approved",per),tn=ap.reduce((t,p)=>t+p.net_salary,0),pl=gjPending();
 const b=(can("gaji.setuju")&&dr.length?`<button class="b" id="gj-ma" onclick="askC('payApprAll','${per}')">Setujui semua draf (${dr.length})</button>`:"")+(can("gaji.kelola")&&ap.length?`<button class="b" id="gj-mb" onclick="askC('payBayarAll','${per}')">Bayar semua disetujui (${ap.length})</button>`:"");
 return dcard("Proses massal",dr.length+" draf · "+ap.length+" disetujui belum dibayar"+(ap.length?" · bersih "+rp(tn):""),`<label>Periode</label><select id="gj-pm" aria-label="Periode proses massal" onchange="S.gpm=this.value;render()">${opt(pl,x=>[x,x],per)}</select>${b||'<p class="k">Tidak ada tindakan massal yang tersedia untuk Anda pada periode ini.</p>'}<p class="k">Mengikuti pilihan unit di header. Tanggal bayar dan kas/bank diambil dari kartu Pembayaran gaji di atas.</p>`,"alf")}
// v1.1.161 — setor potongan gaji: Kewajiban Lain (2200) → kas/bank; saldo per unit = potongan gaji dibayar − setoran
const REM_T="payroll_rem",remList=()=>db.transactions.filter(t=>t.type===REM_T&&t.status==="posted");
function potBal(){const m={};db.payrolls.filter(p=>p.status==="paid").forEach(p=>{(m[p.unit_id||""]??={o:0,s:0}).o+=p.total_deduction||0});remList().forEach(t=>{(m[t.business_unit_id||""]??={o:0,s:0}).s+=t.amount});return m}
const potRows=()=>Object.entries(potBal()).map(([k,v])=>({k,o:v.o,s:v.s,r:v.o-v.s})).filter(x=>x.o>0&&(S.unit==="all"||x.k===(S.unit==="all"?"":S.unit)));
function potSetor(){try{negAny();const u=$("#ps-u").value,d=$("#ps-d").value,k=db.cash_accounts.find(c=>c._id===$("#ps-k").value),raw=pn($("#ps-a").value||""),n=($("#ps-n").value||"").trim(),b=potBal()[u]||{o:0,s:0},r=b.o-b.s;
 if(!(u in potBal())||r<=0)throw fe("ps-u","Tidak ada potongan gaji yang perlu disetor untuk unit ini");
 if(!/^\d+(\.\d+)?$/.test(raw)||+raw<=0)throw fe("ps-a","Jumlah harus lebih dari 0");if(+raw>r)throw fe("ps-a","Jumlah melebihi saldo potongan (Rp "+fm(r)+")");
 if(!d)throw fe("ps-d","Tanggal setor wajib diisi");if(!k)throw fe("ps-k","Pilih kas/bank");if(!n)throw fe("ps-n","Tujuan setoran wajib diisi (mis. BPJS, koperasi, pajak)");
 post({type:REM_T,date:d,unit:u,desc:"Setor potongan gaji · "+n,lines:[{acc:"ACC2200",d:+raw},{acc:k.account_id,c:+raw}]});
 audit("remit","payroll","*",unitName(u)+" · "+n+" · Rp "+fm(+raw));save();S.msg="Setoran potongan gaji Rp "+fm(+raw)+" dicatat"}catch(e){mErr(e);return}render()}
function batalSetorPot(id){try{const t=db.transactions.find(x=>x._id===id);if(!t||t.type!==REM_T||t.status!=="posted")throw Error("Setoran tidak ditemukan");rev(id);audit("void","payroll",id,t.description+" (setoran potongan)");save();S.msg="Setoran potongan dibatalkan dengan jurnal pembalik"}catch(e){S.msg="⚠ "+e.message}render()}
function potCard(){const R=potRows(),H=remList().filter(t=>S.unit==="all"||t.business_unit_id===S.unit).sort((a,b)=>b.date.localeCompare(a.date)||b._id.localeCompare(a._id)).slice(0,10),kas=opt(db.cash_accounts.filter(isAct),c=>[c._id,c.name]),tr=R.reduce((t,x)=>t+x.r,0),can2=can("gaji.kelola");
 if(!R.length&&!H.length)return"";
 const rows=R.map(x=>`<div class="upr alr"><span class="tri out" aria-hidden="true">−</span><span class="upm"><b>${esc(unitName(x.k||null))}</b><small>Dipotong Rp ${fm(x.o)} · disetor Rp ${fm(x.s)}</small></span><span class="upa"><b>${rp(x.r)}</b><span class="bdg ${x.r>0?"wr":"ok"}">${x.r>0?"Belum disetor":"Lunas"}</span></span></div>`).join("");
 const hist=H.map(t=>`<div class="upr alr"><span class="tri out" aria-hidden="true">↗</span><span class="upm"><b>${esc(t.description.replace("Setor potongan gaji · ",""))}</b><small>${t.date} · ${esc(unitName(t.business_unit_id))}</small></span><span class="upa"><b>${rp(t.amount)}</b>${can2?`<span class="alb">${ib("undo","Batalkan","askC('batalSetorPot','"+t._id+"')","x")}</span>`:""}</span></div>`).join("");
 const form=can2&&tr>0?`<div class="gjf"><p class="k">Catat penyetoran potongan (BPJS, pajak, koperasi, dll.) dari kas/bank. Beban sudah dicatat saat gaji dibayar; setoran hanya melunasi Kewajiban Lain (2200).</p><label>Unit</label><select id="ps-u" onchange="potFill()">${opt(R.filter(x=>x.r>0),x=>[x.k,unitName(x.k||null)+" · sisa Rp "+fm(x.r)])}</select><label>Jumlah (Rp)</label><input id="ps-a" type="text" inputmode="numeric" autocomplete="off" oninput="fmtR(this)" value="${fm(R.find(x=>x.r>0).r)}"><label>Tanggal setor</label><input id="ps-d" type="date" value="${today()}"><label>Kas/Bank</label><select id="ps-k">${kas}</select><label>Tujuan setoran</label><input id="ps-n" type="text" autocomplete="off" placeholder="mis. BPJS Ketenagakerjaan"><button class="b" id="ps-go" onclick="potSetor()">Catat setoran</button></div>`:"";
 return dcard("Potongan gaji belum disetor",tr>0?"Total sisa "+rp(tr)+" · Kewajiban Lain (2200)":"Semua potongan gaji sudah disetor",(R.length?`<div class="upl">${rows}</div>`:"")+form+(H.length?`<h3 class="k">Setoran terakhir</h3><div class="upl">${hist}</div>`:""),"alf")}
function potFill(){const u=$("#ps-u").value,b=potBal()[u]||{o:0,s:0};$("#ps-a").value=fm(Math.max(0,b.o-b.s))}
function vKomp(){const P=db.payroll_components;
 return`<h2>Komponen Gaji</h2>${addB("Tambah komponen","pk")}${dcard("Master Komponen",P.length+" komponen",`<p class="k">Master komponen tambahan (lembur, insentif, tunjangan, potongan). Bisa berupa nominal tetap, persen dari gaji pokok, atau persen dari laba (sebelum/sesudah beban gaji). Dipasang per pegawai lewat ceklist di Master &gt; Pegawai (atau jadi bawaan jabatan), atau ditambahkan sekali pakai ke gaji draf.</p>`+(P.length?`<div class="upl">${P.map(k=>`<div class="upr alr${isAct(k)?"":" vd"}"><span class="tri ${k.type==="earning"?"in":"out"}" aria-hidden="true">${k.type==="earning"?"+":"−"}</span><span class="upm"><b>${esc(k.name)}</b><small>${PKT[k.type]} · ${esc(kDesc(k))}</small><small>Dipakai ${db.employees.filter(e=>(e.components||[]).some(x=>x.component_id===k._id)).length} pegawai</small></span><span class="upa">${isAct(k)?"":'<span class="bdg">Nonaktif</span>'}<span class="alb">${ib("edit","Edit","openK('"+k._id+"')","s")+(isAct(k)?ib("x","Nonaktifkan","togK('"+k._id+"')","s"):ib("check","Aktifkan","togK('"+k._id+"')","s"))}</span></span></div>`).join("")}</div>`:'<div class="empty">Belum ada komponen gaji.</div>'),"")}
`}
// ===== LAPORAN GAJI / SDM (v0.1.017): rekap gaji per periode, unit, pegawai, dan komponen; cetak dan CSV =====
const GG={periode:"Periode",tahun:"Tahun",unit:"Unit usaha",pegawai:"Pegawai",pegtahun:"Tahun · pegawai",komponen:"Komponen"};
function gajiSet(){return db.payrolls.filter(p=>p.status!=="draft"&&(S.unit==="all"||p.unit_id===S.unit)&&(!S.gf||p.period>=S.gf)&&(!S.gto||p.period<=S.gto))}
function gajiTab(){const L=gajiSet(),g=GG[S.gg]?S.gg:"periode";
 if(g==="komponen"){const ids=new Set(L.map(p=>p._id)),m={};db.payroll_items.filter(i=>ids.has(i.payroll_id)).forEach(i=>{const x=m[i.type+"|"+i.name]??={n:i.name,t:i.type,c:0,a:0};x.c++;x.a+=i.amount});
  return{g,ct:2,h:["Komponen","Jenis","#Jumlah item","#Total"],r:Object.values(m).sort((a,b)=>(a.t===b.t?0:a.t==="earning"?-1:1)||a.n.localeCompare(b.n)).map(x=>[x.n,PKT[x.t],x.c,x.a])}}
 const peg=p=>{const e=db.employees.find(x=>x._id===p.employee_id)||{};return(e.emp_number?e.emp_number+" · ":"")+(e.name||"-")},key={periode:p=>p.period,tahun:p=>p.period.slice(0,4),unit:p=>unitName(p.unit_id),pegawai:peg,pegtahun:p=>p.period.slice(0,4)+" · "+peg(p)}[g],m={};
 L.forEach(p=>{const k=key(p),x=m[k]??={k,c:0,g:0,d:0,n:0,pd:0,bp:0};x.c++;x.g+=p.gross_salary;x.d+=p.total_deduction;x.n+=p.net_salary;if(p.status==="paid")x.pd+=p.net_salary;else x.bp+=p.net_salary});
 return{g,ct:1,h:[GG[g],"#Jumlah gaji","#Bruto","#Potongan","#Bersih","#Dibayar","#Belum dibayar"],r:Object.values(m).sort((a,b)=>g==="periode"||g==="tahun"?b.k.localeCompare(a.k):g==="pegtahun"?b.k.slice(0,4).localeCompare(a.k.slice(0,4))||a.k.localeCompare(b.k):a.k.localeCompare(b.k)).map(x=>[x.k,x.c,x.g,x.d,x.n,x.pd,x.bp])}}
function gajiSum(){const L=gajiSet(),s={c:L.length,g:0,d:0,n:0,pd:0,bp:0};L.forEach(p=>{s.g+=p.gross_salary;s.d+=p.total_deduction;s.n+=p.net_salary;if(p.status==="paid")s.pd+=p.net_salary;else s.bp+=p.net_salary});return s}
function gajiCsv(){const T=gajiTab(),q=v=>typeof v==="number"?String(Math.round(v)):'"'+String(v).replace(/"/g,'""')+'"';return[T.h.map(h=>q(h.replace("#",""))),...T.r.map(r=>r.map(q))].map(r=>r.join(",")).join("\r\n")}
function gajiDl(){try{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff"+gajiCsv()],{type:"text/csv"}));a.download="laporan-gaji-"+(S.gg||"periode")+"-"+today()+".csv";a.click();S.msg="Laporan gaji diunduh (CSV)"}catch(e){S.msg="⚠ Unduh gagal: "+e.message}render()}
function vRepGaji(){const T=gajiTab(),s=gajiSum(),bad=S.gf&&S.gto&&S.gf>S.gto,un=S.unit==="all"?"Semua unit":unitName(S.unit),per=(S.gf||S.gto)?(S.gf||"awal")+" s/d "+(S.gto||"sekarang"):"Semua periode";
 const cell=(v,i,h)=>i===T.ct?fm(v):h[0]==="#"?rp(v):esc(v),
 K=(ico,tn,k,v,sub)=>`<div class="card kp"><div class="kh"><span class="kic ${tn}">${ic(ico)}</span><span class="k">${k}</span></div><div class="v">${v}</div><div class="s2">${sub}</div></div>`;
 return`<h2>Laporan Gaji</h2>${dcard("Filter dan cetak","Hanya gaji Disetujui dan Dibayar; draf tidak dihitung. Filter unit memakai pilihan di header.",`<div class="fl"><input type="month" aria-label="Dari periode" value="${esc(S.gf||"")}" onchange="S.gf=this.value;S.lim=0;render()"><input type="month" aria-label="Sampai periode" value="${esc(S.gto||"")}" onchange="S.gto=this.value;S.lim=0;render()"><select aria-label="Kelompokkan" onchange="S.gg=this.value;render()">${opt(Object.keys(GG),k=>[k,"Per "+GG[k].toLowerCase()],T.g)}</select>${S.gf||S.gto?`<button class="b s" onclick="S.gf=S.gto='';render()">Reset filter</button>`:""}</div>${bad?'<div class="fe" role="alert">Periode awal sesudah periode akhir</div>':""}<div class="rbt"><button class="b" onclick="window.print()">Cetak</button><button class="b s" onclick="gajiDl()">Unduh CSV</button></div>`,"noprint rpb")}
<div class="doc po">${kop()}<h3>LAPORAN GAJI</h3><div class="cn">${esc(un)} · ${esc(per)} · per ${esc(GG[T.g].toLowerCase())}</div></div>
<div class="g dk gjk" aria-label="Ringkasan gaji">${K("cash","t1","Bruto",rp(s.g),s.c+" gaji")}${K("tdn","t3","Potongan",rp(s.d),per)}${K("chart","t4","Bersih",rp(s.n),"Dibayar "+rp(s.pd))}${K("cal","t2","Belum dibayar",rp(s.bp),"dari gaji disetujui")}</div>
${dcard("Rekap per "+GG[T.g].toLowerCase(),un+" · "+per,T.r.length?tbl(T.h,T.r.map(r=>"<tr>"+r.map((v,i)=>`<td class="${T.h[i][0]==="#"?"n":""}">${cell(v,i,T.h[i])}</td>`).join("")+"</tr>")):'<div class="empty">Belum ada gaji yang disetujui atau dibayar pada filter ini.</div>',"rpc")}${typeof repEnd==="function"?repEnd():""}`}
function pkCalc(){const c=$("#pk-c"),b=$("#pk-bw");if(c&&b)b.hidden=c.value!=="persen_laba"}
