// ===== PENJAGAAN IZIN PER AKSI (v0.1.029) =====
const PD=Object.fromEntries(PERMS),GUARD={"trx.kelola":"editTrx submitT postJnl voidT awalPiutang batalAwalP awalPinjam batalAwalL","sp.data":"savePortalPin saveCalon ubahCalon jadiNasabah saveNasabah togN addJam saveJam kembalikan saveSavAcc tutupSav bukaSav","sp.ajukan":"ajukan simpanDraf kirimDraf hapusDraf saveAjuan saveBatalAjuan","sp.verifikasi":"saveVerif","sp.analisis":"saveAnalisis","sp.akad":"saveAkad","sp.tagih":"saveTL","sp.restruk":"saveRestruk batalRestruk tolakRestruk","sp.hapusbuku":"saveHapus savePulih batalPulih batalHapus tolakHapus","sp.cairkan":"cairkan batalCair amortAll","sp.bayar":"bayar lunasi batalBayar saveSavTx batalSav prosesSav","air.kelola":"jual terima batalJual batalTerima savePel togPel saveProd togProd terbitTagihan saveConn togConn gantiMeter batalGanti saveTarif","gaji.kelola":"payGen saveComp togK payDel payBayar batalGaji piAdd piDel ecAdd ecDel","gaji.setuju":"payAppr","master.kelola":"addPos delPos posDef savePosDef saveUnit saveCash saveAcc togM savePihak togP saveEmp togG saveRate saveTax togRate","periode.kelola":"tgl closeYear reopenYear","setelan.kelola":"saveBd logoSet logoDel setPen setPo setSd setSp setMod setSpl setCalc setFlow setSod cloudSave cloudLogin cloudLogout cloudRefreshList cloudPick cloudPush cloudPullAsk cloudHist cloudRestore cloudPull cloudForce cloudAutoSet cloudReset cloudChangePw cloudCheck tblSync tblCheck tblAutoSet setPortal setRsMin setFeeRecog setSav setKol setPoFee setDisb addSavTier delSavTier addSavProd delSavProd setKlausul","data.backup":"exp"};
function deny(p,n){const u=curUser();S.msg="⚠ Anda tidak berwenang: "+(PD[p]||p)+(u?" (peran "+((roleOf(u)||{}).name||"-")+")":"");audit("akses_ditolak","aksi",n,PD[p]||p);save();render()}
for(const p in GUARD)GUARD[p].split(" ").forEach(n=>{const f=globalThis[n];if(typeof f!=="function"||f.__g)return;const w=function(...a){if(rbacOn()&&!can(p)){deny(p,n);return}if(p!=="setelan.kelola"&&p!=="data.backup"&&typeof cloudRO==="function"&&cloudRO()){S.msg="⚠ Peran pembaca di awan hanya boleh melihat";render();return}return f.apply(this,a)};w.__g=p;globalThis[n]=w});
// ===== TAMPILAN SESUAI AKUN DAN PERAN (v1.1.150): tombol aksi yang tidak boleh dijalankan akun ini disembunyikan =====
const FN_P={},KPERM={ps:"master.kelola",u:"master.kelola",c:"master.kelola",a:"master.kelola",py:"master.kelola",pg:"master.kelola",rt:"master.kelola",tx:"master.kelola",pl:"air.kelola",pr:"air.kelola",cn:"air.kelola",pk:"gaji.kelola",us:"pengguna.kelola",rp:"pengguna.kelola",tn:"trx.kelola",jm:"trx.kelola",lp:"sp.ajukan",cj:"sp.data",n:"sp.data",sa:"sp.data",cl:"sp.data",pp:"sp.data",ls:"sp.setujui",lr:"sp.setujui",lb:"sp.ajukan",la:"sp.ajukan",lc:"sp.cairkan",lw:"sp.bayar",lz:"sp.bayar",st:"sp.bayar",vf:"sp.verifikasi",an:"sp.analisis",ak:"sp.akad",tl:"sp.tagih",rs:"sp.restruk",hb:"sp.hapusbuku",pm:"sp.hapusbuku"};
for(const p in GUARD)GUARD[p].split(" ").forEach(n=>{FN_P[n]=p});
FN_P.impAsk="data.kelola";FN_P.wipeAsk="data.kelola";FN_P.saveUser="pengguna.kelola";FN_P.resetPin="pengguna.kelola";FN_P.rbacOff="pengguna.kelola";FN_P.saveTolak="sp.setujui";
// true bila akun yang login (peran lokal atau peran pembaca di awan) tidak boleh menjalankan izin p
function noPerm(p){if(!p)return false;if(rbacOn()&&!can(p))return true;return p!=="setelan.kelola"&&p!=="data.backup"&&typeof cloudRO==="function"&&cloudRO()}
function roleFx(){if(!document.querySelectorAll)return;if(!rbacOn()&&!(typeof cloudRO==="function"&&cloudRO()))return;
 const cut=new Set();document.querySelectorAll("#main [onclick],#fm [onclick]").forEach(e=>{const cl=e.classList;if(!cl||!(cl.contains("b")||cl.contains("ib")||cl.contains("ad")))return;
  const oc=e.getAttribute("onclick")||"",m=/^\s*([A-Za-z_$][\w$]*)\(\s*'?([\w-]*)/.exec(oc);if(!m)return;const p=m[1]==="mdOpen"?KPERM[m[2]]:m[1]==="lst"?(/cancelled/.test(oc)?"sp.ajukan":"sp.setujui"):FN_P[m[1]];if(noPerm(p)){const par=e.parentNode;e.remove();if(par)cut.add(par)}});
 cut.forEach(par=>{if(par.classList&&par.classList.contains("fl")&&!par.children.length&&par.parentNode)par.remove()});
 const fm=document.querySelector("#fm");if(fm&&cut.size)[...fm.querySelectorAll("button")].forEach(b=>{if(/^Batal$/.test(b.textContent.trim()))b.textContent="Tutup"})}
