// ===== PORTAL NASABAH (NSB2, v1.1.038): tampilan nasabah — masuk HP + PIN, pinjaman, tabungan, profil (hanya baca) =====
// UI SAJA: tanpa server. Data sama dengan aplikasi pengurus dan hanya ada di perangkat ini (mode demo/pratinjau).
// Portal sungguhan (server, OTP, sinkronisasi, persetujuan data pribadi) tetap butuh keputusan arsitektur dan regulasi (lihat ROADMAP NSB2).
const PT_MAXF=5,PT_LOCK=5*60000,PT_IDLE=3*60000;
const ptOn=()=>!!(db.settings&&db.settings.portal);
const ptKey=s=>{let n=String(s||"").replace(/\D/g,"");if(n.startsWith("62"))n="0"+n.slice(2);else if(n.startsWith("8"))n="0"+n;return n};
const ptFind=hp=>{const k=ptKey(hp);if(k.length<8)return null;const m=db.parties.filter(p=>p.type==="nasabah"&&p.status!=="nonaktif"&&ptKey(p.phone)===k);return m.length===1?m[0]:null};
const ptLocked=p=>!!(p.portal&&p.portal.locked_until&&p.portal.locked_until>new Date().toISOString());
function ptLogin(hp,pin){if(!ptOn())throw Error("Portal nasabah belum diaktifkan oleh pengurus");const p=ptFind(hp);if(!p||!p.portal)throw Error("Nomor HP atau PIN salah");
 if(ptLocked(p)){audit("portal_gagal","party",p._id,"Masuk ditolak: akun portal terkunci",p.name);save();throw Error("Akun terkunci sementara. Coba lagi beberapa menit lagi atau hubungi pengurus")}
 if(pinHash(String(pin||""),p.portal.salt)!==p.portal.hash){p.portal.fails=(p.portal.fails||0)+1;if(p.portal.fails>=PT_MAXF){p.portal.fails=0;p.portal.locked_until=new Date(Date.now()+PT_LOCK).toISOString();audit("portal_gagal","party",p._id,"PIN salah "+PT_MAXF+" kali; akun portal terkunci 5 menit",p.name);save();throw Error("PIN salah "+PT_MAXF+" kali. Akun terkunci 5 menit")}
  audit("portal_gagal","party",p._id,"PIN salah ("+p.portal.fails+"/"+PT_MAXF+")",p.name);save();throw Error("Nomor HP atau PIN salah")}
 p.portal.fails=0;p.portal.locked_until="";p.portal.last_login=now();audit("portal_masuk","party",p._id,"Masuk portal nasabah",p.name);save();return p}
function ptPin(p,pin){const salt=newSalt();p.portal=Object.assign({},p.portal||{},{salt,hash:pinHash(pin,salt),set_at:now(),fails:0,locked_until:""})}
function savePortalPin(){try{const p=db.parties.find(x=>x._id===S.epp),v=i=>$("#"+i).value;if(!p||p.type!=="nasabah")throw Error("Nasabah tidak ditemukan");if(!ptKey(p.phone)||ptKey(p.phone).length<8)throw Error("Isi nomor telepon nasabah dulu (dipakai untuk masuk)");
 if(db.parties.some(x=>x._id!==p._id&&x.type==="nasabah"&&x.status!=="nonaktif"&&ptKey(x.phone)===ptKey(p.phone)))throw Error("Nomor telepon dipakai nasabah lain; ubah salah satunya agar masuk portal tidak tertukar");
 pinChk(v("pp-p"),"pp-p");if(v("pp-p")!==v("pp-r"))throw fe("pp-r","Ulangi PIN tidak sama");ptPin(p,v("pp-p"));audit("portal_pin","party",p._id,"PIN portal nasabah diatur pengurus");save();okM();S.msg="PIN portal "+p.name+" disimpan. Sampaikan langsung ke nasabah.";render()}catch(e){mErr(e)}}
function setPortal(v){try{db.settings.portal=v==="1";audit("setting","settings","portal","Portal nasabah: "+(db.settings.portal?"aktif":"mati"));save();S.msg="Portal nasabah "+(db.settings.portal?"diaktifkan":"dimatikan")}catch(e){S.msg="⚠ "+e.message}render()}
MK.pp="epp";
MD.pp=()=>{const p=db.parties.find(x=>x._id===S.epp);if(!p)return{t:"PIN portal",s:"mdClose()",y:"Tutup",b:"<p>Nasabah tidak ditemukan.</p>",nf:1};
 return{t:"PIN portal · "+p.name,s:"savePortalPin()",y:"Simpan PIN",b:`<p class="k">Nasabah masuk ke portal dengan nomor telepon (${esc(p.phone||"belum diisi")}) dan PIN ini. Sampaikan PIN langsung ke nasabah, jangan lewat grup.${p.portal?" PIN lama akan diganti.":""}</p>`+fld("pp-p","PIN baru (4–8 angka)",{type:"password",a:' inputmode="numeric" maxlength="8" autocomplete="new-password"',value:"",req:1})+fld("pp-r","Ulangi PIN",{type:"password",a:' inputmode="numeric" maxlength="8" autocomplete="new-password"',value:"",req:1})}};
// ----- sesi dan tampilan -----
function ptOpen(){S.ptl=1;S.pt=null;render()}
function ptPreview(id){const p=db.parties.find(x=>x._id===id);if(!p)return;S.md=null;for(const x in MK)S[MK[x]]=null;S.pt={pid:id,tab:"home",sel:null,prev:true,at:Date.now()};S.ptl=0;render()}
function ptDoLogin(){try{const p=ptLogin($("#pt-h").value,$("#pt-p").value);S.pt={pid:p._id,tab:"home",sel:null,prev:false,at:Date.now()};S.ptl=0;S.pte=""}catch(e){S.pte=e.message}render()}
function ptOut(idle){const wasP=S.pt&&S.pt.prev;S.pt=null;S.ptl=0;S.pte=idle?"Sesi berakhir karena tidak ada aktivitas":"";if(!wasP&&typeof location!=="undefined"&&location.hash==="#portal")S.ptl=1;render()}
function ptGo(t,sel){if(S.pt){S.pt.tab=t;S.pt.sel=sel||null;S.pt.at=Date.now()}render();if(typeof window!=="undefined"&&window.scrollTo)try{document.getElementById("portal").scrollTop=0}catch(e){}}
function ptChgPin(){try{const p=db.parties.find(x=>x._id===(S.pt||{}).pid),v=i=>$("#"+i).value;if(!p||!p.portal)throw Error("Sesi tidak valid");if(S.pt.prev)throw Error("Ganti PIN tidak tersedia pada pratinjau pengurus");
 if(pinHash(v("pc-o"),p.portal.salt)!==p.portal.hash)throw fe("pc-o","PIN lama salah");pinChk(v("pc-n"),"pc-n");if(v("pc-n")===v("pc-o"))throw fe("pc-n","PIN baru harus berbeda");if(v("pc-n")!==v("pc-r"))throw fe("pc-r","Ulangi PIN tidak sama");
 ptPin(p,v("pc-n"));audit("portal_pin","party",p._id,"PIN portal diganti oleh nasabah",p.name);save();S.msg="PIN berhasil diganti"}catch(e){S.msg="⚠ "+e.message;S.fe=e.f?{id:e.f,m:e.message}:null}render()}
// ----- data nasabah (hanya milik sendiri) -----
const ptLoans=pid=>db.loans.filter(l=>l.party_id===pid&&["active","paid_off","written_off"].includes(l.status)).sort((a,b)=>(a.status==="active"?0:1)-(b.status==="active"?0:1)||((b.disbursement_date||"")>(a.disbursement_date||"")?1:-1));
const ptIns=l=>db.loan_installments.filter(i=>i.loan_id===l._id).sort((a,b)=>a.installment_number-b.installment_number);
const ptSisa=l=>ptIns(l).reduce((s,i)=>s+i.principal_due-i.principal_paid,0);
const ptSav=pid=>(db.savings_accounts||[]).filter(a=>a.party_id===pid&&a.status==="aktif");
function ptNext(pid){const t=today();let best=null;ptLoans(pid).filter(l=>l.status==="active").forEach(l=>{const o=ptIns(l).find(i=>i.status!=="paid");if(o&&(!best||o.due_date<best.i.due_date))best={l,i:o,tot:owed(o,t).total,late:o.due_date<t}});return best}
function ptRecent(pid,n){const out=[];ptSav(pid).forEach(a=>savLive(a._id).forEach(x=>out.push({a,x})));return out.sort((p,q)=>p.x.date<q.x.date?1:p.x.date>q.x.date?-1:0).slice(0,n)}
// ----- tampilan -----
const ptKv=(k,v)=>`<div class="kv"><span class="k">${k}</span><b>${v}</b></div>`;
function ptLoginV(){const off=!ptOn();return`<div class="pt-w pt-c"><div class="pt-b"><span class="pt-logo" aria-hidden="true">${ic("user")}</span><h1>${esc(bnm())}</h1><p class="k">Portal Nasabah</p></div><div class="card pt-card"><span class="bdg wr">Mode demo · data hanya di perangkat ini</span>${off?`<p>Portal nasabah belum diaktifkan oleh pengurus. Hubungi pengurus ${esc(bnm())}.</p>`:`<form onsubmit="ptDoLogin();return false">${fld("pt-h","Nomor HP",{type:"tel",a:' inputmode="tel" autocomplete="username" placeholder="08xxxxxxxxxx"',value:"",req:1})}<label for="pt-p">PIN</label><input id="pt-p" type="password" inputmode="numeric" maxlength="8" autocomplete="current-password" aria-required="true">${S.pte?`<div class="fe" role="alert">${esc(S.pte)}</div>`:""}<div class="fl"><button class="b" type="submit">Masuk</button></div></form><p class="k">Lupa PIN? Hubungi pengurus untuk mengatur ulang.</p>`}</div></div>`}
function ptHomeV(p){const sv=ptSav(p._id),tot=sv.reduce((s,a)=>s+savBal(a._id),0),ln=ptLoans(p._id).filter(l=>l.status==="active"),sisa=ln.reduce((s,l)=>s+ptSisa(l),0),nx=ptNext(p._id),rc=ptRecent(p._id,5);
 return`<div class="pt-g"><div class="card pt-k"><span class="k">Total tabungan</span><b>${rp(tot)}</b><small>${sv.length} rekening</small></div><div class="card pt-k"><span class="k">Sisa pokok pinjaman</span><b>${rp(sisa)}</b><small>${ln.length} pinjaman aktif</small></div></div>`+
 (nx?`<div class="card pt-n ${nx.late?"pt-late":""}"><span class="bdg ${nx.late?"bd":"ok"}">${nx.late?"Terlambat":"Tagihan berikutnya"}</span><b>${rp(nx.tot)}</b><span class="k">${esc(nx.l.loan_number)} · angsuran ke-${nx.i.installment_number} · jatuh tempo ${tglS(nx.i.due_date)}</span></div>`:`<div class="card"><p class="k">Tidak ada tagihan angsuran saat ini.</p></div>`)+
 `<h3>Mutasi tabungan terakhir</h3>`+(rc.length?`<div class="card">${rc.map(r=>`<div class="pt-r"><span><b>${SAV_T[r.x.type]}</b><small>${tglS(r.x.date)} · ${esc(r.a.number)}</small></span><b class="${SAV_SIGN[r.x.type]<0?"neg":"pos"}">${SAV_SIGN[r.x.type]<0?"−":"+"}${rp(r.x.amount)}</b></div>`).join("")}</div>`:`<p class="k">Belum ada mutasi.</p>`)}
function ptLoanV(p,id){const l=ptLoans(p._id).find(x=>x._id===id);if(!l)return`<p class="k">Pinjaman tidak ditemukan.</p>`;const ins=ptIns(l),t=today(),od=ins.filter(i=>i.status!=="paid"&&i.due_date<t);
 return`<button class="b s" onclick="ptGo('loan')">‹ Kembali</button><h3>${esc(l.loan_number)}</h3><div class="card">${ptKv("Status",lbadge(l))}${ptKv("Pokok",rp(l.principal))}${ptKv("Jasa",l.interest_rate+"% per tahun ("+esc(l.interest_method)+")")}${ptKv("Tenor",l.tenor+" bulan")}${ptKv("Sisa pokok",rp(ptSisa(l)))}${l.disbursement_date?ptKv("Dicairkan",tglS(l.disbursement_date)):""}</div>`+
 (od.length&&l.status==="active"?`<div class="card pt-late"><span class="bdg bd">Tunggakan ${od.length} angsuran</span><b>${rp(od.reduce((s,i)=>s+owed(i,t).total,0))}</b><span class="k">Termasuk denda. Hubungi pengurus untuk pembayaran.</span></div>`:"")+
 `<h3>Jadwal angsuran</h3><div class="card">${ins.map(i=>`<div class="pt-r"><span><b>Ke-${i.installment_number}</b><small>${tglS(i.due_date)}</small></span><span class="n">${i.status==="paid"?`<span class="bdg ok">Lunas</span>`:`<b>${rp(owed(i,t).total)}</b>${i.due_date<t?` <span class="bdg bd">Lewat</span>`:""}`}</span></div>`).join("")||'<p class="k">Belum ada jadwal.</p>'}</div>`}
function ptLoansV(p){const L=ptLoans(p._id);return`<h3>Pinjaman saya</h3>`+(L.length?L.map(l=>`<button class="card pt-it" onclick="ptGo('loan','${l._id}')"><span><b>${esc(l.loan_number)}</b><small>${l.tenor}× · ${l.interest_rate}% · sisa pokok ${rp(ptSisa(l))}</small></span><span>${lbadge(l)} ${ic("next")}</span></button>`).join(""):`<p class="k">Belum ada pinjaman.</p>`)}
function ptSavV(p,id){const A=ptSav(p._id);if(id){const a=A.find(x=>x._id===id);if(!a)return`<p class="k">Rekening tidak ditemukan.</p>`;const m=savLive(a._id).slice().reverse().slice(0,30);
  return`<button class="b s" onclick="ptGo('sav')">‹ Kembali</button><h3>${esc(a.number)}</h3><div class="card">${ptKv("Produk",esc(a.product))}${ptKv("Saldo",rp(savBal(a._id)))}${a.prod?ptKv("Bunga",String(a.prod.rate).replace(".",",")+"% per tahun"):""}${savLock(a)?ptKv("Jatuh tempo",tglS(savLock(a))):""}${ptKv("Dibuka",tglS(a.opened_at))}</div><h3>Mutasi (30 terakhir)</h3><div class="card">${m.length?m.map(x=>`<div class="pt-r"><span><b>${SAV_T[x.type]}</b><small>${tglS(x.date)}</small></span><b class="${SAV_SIGN[x.type]<0?"neg":"pos"}">${SAV_SIGN[x.type]<0?"−":"+"}${rp(x.amount)}</b></div>`).join(""):'<p class="k">Belum ada mutasi.</p>'}</div>`}
 return`<h3>Tabungan saya</h3>`+(A.length?A.map(a=>`<button class="card pt-it" onclick="ptGo('sav','${a._id}')"><span><b>${esc(a.number)}</b><small>${esc(a.product)}${savLock(a)?" · jatuh tempo "+tglS(savLock(a)):""}</small></span><span><b>${rp(savBal(a._id))}</b> ${ic("next")}</span></button>`).join(""):`<p class="k">Belum ada rekening tabungan.</p>`)}
function ptProfV(p){const pv=S.pt&&S.pt.prev;return`<h3>Profil</h3><div class="card">${ptKv("Nama",esc(p.name))}${ptKv("Telepon",esc(p.phone||"-"))}${ptKv("Alamat",esc(p.address||"-"))}</div><h3>Ganti PIN</h3><div class="card">${pv?`<p class="k">Tidak tersedia pada pratinjau pengurus.</p>`:`${fld("pc-o","PIN lama",{type:"password",a:' inputmode="numeric" maxlength="8" autocomplete="current-password"',value:""})}${fld("pc-n","PIN baru (4–8 angka)",{type:"password",a:' inputmode="numeric" maxlength="8" autocomplete="new-password"',value:""})}${fld("pc-r","Ulangi PIN baru",{type:"password",a:' inputmode="numeric" maxlength="8" autocomplete="new-password"',value:""})}<div class="fl"><button class="b" onclick="ptChgPin()">Simpan PIN</button></div>`}</div><p class="k">Data di portal bersifat informasi. Bila ada selisih dengan catatan Anda, hubungi pengurus ${esc(bnm())}.</p>`}
function ptV(){const p=db.parties.find(x=>x._id===S.pt.pid);if(!p)return ptLoginV();const T=S.pt.tab,sel=S.pt.sel,tabs=[["home","Beranda"],["loan","Pinjaman"],["sav","Tabungan"],["prof","Profil"]];
 const body=T==="home"?ptHomeV(p):T==="loan"?(sel?ptLoanV(p,sel):ptLoansV(p)):T==="sav"?ptSavV(p,sel):ptProfV(p);
 return`${S.pt.prev?`<div class="pt-pv" role="status">Pratinjau pengurus — beginilah tampilan nasabah. <button class="b s" onclick="ptOut()">Tutup pratinjau</button></div>`:""}<header class="pt-hd"><div><b>${esc(bnm())}</b><small>Halo, ${esc(p.name)}</small></div>${S.pt.prev?"":`<button class="b s" onclick="ptOut()">Keluar</button>`}</header><main class="pt-w">${body}</main><nav class="pt-nv" aria-label="Menu portal">${tabs.map(([k,n])=>`<button ${T===k?'aria-current="page" class="on"':""} onclick="ptGo('${k}')">${n}</button>`).join("")}</nav>`}
function ptRender(){if(typeof document==="undefined"||!document.getElementById)return false;let el=document.getElementById("portal");const on=!!(S.pt||S.ptl);
 if(!on){if(el){el.className="";el.innerHTML=""}document.body.classList.remove("pt-on");return false}
 if(!el){el=document.createElement("div");el.id="portal";el.setAttribute("aria-label","Portal Nasabah");document.body.appendChild(el)}
 el.className="on";el.innerHTML=S.pt?ptV():ptLoginV();document.body.classList.add("pt-on");if(typeof a11y==="function")a11y();if(typeof S.msg==="string"&&S.msg&&typeof toast==="function"){toast(S.msg,/^⚠/.test(S.msg));S.msg=""}
 if(S.fe){const f=document.getElementById(S.fe.id);if(f&&f.insertAdjacentHTML){f.classList.add("er");(f._b||f).insertAdjacentHTML("afterend",`<div class="fe" role="alert">${esc(S.fe.m)}</div>`)}S.fe=null}return true}
if(typeof window!=="undefined"&&window.addEventListener){if(location.hash==="#portal")S.ptl=1;window.addEventListener("hashchange",()=>{if(location.hash==="#portal"){S.ptl=S.pt?0:1}else if(!(S.pt&&S.pt.prev)){S.ptl=0;S.pt=null}render()});
 setInterval(()=>{if(S.pt&&!S.pt.prev&&Date.now()-S.pt.at>PT_IDLE)ptOut(true)},15000);document.addEventListener("click",()=>{if(S.pt)S.pt.at=Date.now()},true)}
