// ===== LAPORAN KEUANGAN (v0.1.018): Neraca, Laba Rugi (per akun / per unit), Arus Kas; membaca jurnal, cetak dan CSV =====
const trT=()=>memo("trt",()=>new Map(db.transactions.map(t=>[t._id,t.type])));
const unTxt=()=>S.unit==="all"?"Semua unit":unitName(S.unit),perTxt=()=>(S.d1||S.d2)?(S.d1||"awal")+" s/d "+(S.d2||"sekarang"):"Semua tanggal";
function neracaData(){const d=S.d2||"9999-12-31",m=bal(l=>l.date<=d&&inUnit(l)),g=t=>db.accounts.filter(a=>postable(a)&&a.type===t&&m[a._id]).map(a=>({code:a.code,name:a.name,v:net(a,m)})).filter(x=>Math.round(x.v)!==0);
 let r=0,e=0;db.accounts.filter(postable).forEach(a=>{if(a.type==="revenue")r+=net(a,m);else if(a.type==="expense")e+=net(a,m)});
 const A=g("asset"),L=g("liability"),E=g("equity"),sum=x=>x.reduce((s,y)=>s+y.v,0),lb=r-e,ta=sum(A),tl=sum(L),te=sum(E)+lb;
 return{A,L,E,lb,ta,tl,te,ok:Math.round(ta)===Math.round(tl+te)}}
function neracaRows(){const D=neracaData(),sec=(t,x)=>[["h",t,null],...x.map(y=>["i",y.code+" "+y.name,y.v])];
 return{D,R:[...sec("ASET",D.A),["t","Total Aset",D.ta],...sec("KEWAJIBAN",D.L),["t","Total Kewajiban",D.tl],["h","EKUITAS",null],...D.E.map(y=>["i",y.code+" "+y.name,y.v]),["i","Laba (rugi) berjalan yang belum ditutup",D.lb],["t","Total Ekuitas",D.te],["t","Total Kewajiban + Ekuitas",D.tl+D.te]]}}
function lrData(){const T=trT(),m=bal(l=>inD(l.date)&&inUnit(l)&&T.get(l.transaction_id)!=="closing"),g=t=>db.accounts.filter(a=>postable(a)&&a.type===t&&m[a._id]).map(a=>({code:a.code,name:a.name,v:net(a,m)})).filter(x=>Math.round(x.v)!==0),R=g("revenue"),E=g("expense"),r=R.reduce((s,x)=>s+x.v,0),e=E.reduce((s,x)=>s+x.v,0);return{R,E,r,e,p:r-e}}
function lrUnit(){const T=trT(),m={};db.journal_lines.forEach(l=>{if(!inD(l.date)||T.get(l.transaction_id)==="closing")return;const t=acc(l.account_id).type;if(t!=="revenue"&&t!=="expense")return;const x=m[l.business_unit_id||""]??={r:0,e:0};if(t==="revenue")x.r+=l.credit-l.debit;else x.e+=l.debit-l.credit});
 return[...db.business_units.map(u=>[u._id,u.name]),["","Umum"]].map(([id,n])=>{const x=m[id]||{r:0,e:0};return{n,r:x.r,e:x.e,p:x.r-x.e}}).filter(x=>Math.round(x.r)||Math.round(x.e))}
function lrRows(){const D=lrData();return{D,R:[["h","PENDAPATAN",null],...D.R.map(y=>["i",y.code+" "+y.name,y.v]),["t","Total Pendapatan",D.r],["h","BEBAN",null],...D.E.map(y=>["i",y.code+" "+y.name,y.v]),["t","Total Beban",D.e],["t",D.p<0?"Rugi bersih":"Laba bersih",D.p]]}}
function kasData(){const cash=new Set(db.cash_accounts.map(c=>c.account_id)),T=trT(),by={},d1=S.d1||"",d2=S.d2||"9999-12-31";
 db.journal_lines.forEach(l=>{if(inUnit(l))(by[l.transaction_id]??=[]).push(l)});
 let open=0;const X={op:{},inv:{},fin:{}};
 for(const id in by){const L=by[id],d=L[0].date,cd=L.reduce((s,l)=>cash.has(l.account_id)?s+l.debit-l.credit:s,0);
  if(!L.some(l=>cash.has(l.account_id))||d>d2)continue;
  if(T.get(id)==="opening"||d<d1){open+=cd;continue}
  L.forEach(l=>{if(cash.has(l.account_id))return;const a=acc(l.account_id),k=a.code[0]==="3"||a.code==="2300"?"fin":a.code.slice(0,2)==="16"?"inv":"op",o=X[k][a.code]??={n:a.name,v:0};o.v+=l.credit-l.debit})}
 const sec=(t,k)=>{const rows=Object.keys(X[k]).sort().map(c=>[c+" "+X[k][c].n,X[k][c].v]).filter(x=>Math.round(x[1])!==0);return{t,rows,tot:rows.reduce((s,x)=>s+x[1],0)}},S3=[sec("Aktivitas Operasi","op"),sec("Aktivitas Investasi","inv"),sec("Aktivitas Pendanaan","fin")],chg=S3.reduce((s,x)=>s+x.tot,0),
  cb=bal(l=>l.date<=d2&&inUnit(l)),ck=[...cash].reduce((s,id)=>s+net(acc(id),cb),0);
 return{open,S3,chg,end:open+chg,ok:Math.round(open+chg)===Math.round(ck),ck}}
function kasRows(){const D=kasData(),R=[["t","Saldo kas & bank awal",D.open]];D.S3.forEach(s=>{R.push(["h",s.t,null]);s.rows.forEach(x=>R.push(["i",x[0],x[1]]));R.push(["t","Kas bersih dari "+s.t.toLowerCase(),s.tot])});R.push(["t","Kenaikan (penurunan) kas",D.chg],["t","Saldo kas & bank akhir",D.end]);return{D,R}}
const repRows=R=>R.map(([c,l,v])=>c==="h"?`<tr><th colspan="2">${esc(l)}</th></tr>`:`<tr><td${c==="i"?' style="padding-left:20px"':' style="font-weight:600"'}>${esc(l)}</td><td class="n"${c==="t"?' style="font-weight:600"':""}>${rp(v)}</td></tr>`);
const repHead=(t,sub)=>`<div class="doc po">${kop()}<h3>${t}</h3><div class="cn">${esc(sub)}</div></div>`;
const repBar=(k,dates)=>{const bad=S.d1&&S.d2&&S.d1>S.d2;if(dates==="none")return`<div class="card noprint"><div class="k">Posisi saat ini; filter unit memakai pilihan di header.</div><button class="b" onclick="window.print()">Cetak</button><button class="b s" onclick="repDl('${k}')">Unduh CSV</button></div>`;return`<div class="card noprint"><div class="k">${dates==="as"?"Posisi sampai tanggal (kosong = semua transaksi).":"Rentang tanggal (kosong = tanpa batas)."} Filter unit memakai pilihan di header.</div><div class="fl">${dates==="as"?"":`<input type="date" aria-label="Dari tanggal" value="${esc(S.d1||"")}" onchange="S.d1=this.value;render()">`}<input type="date" aria-label="${dates==="as"?"Per tanggal":"Sampai tanggal"}" value="${esc(S.d2||"")}" onchange="S.d2=this.value;render()">${S.d1||S.d2?`<button class="b s" onclick="S.d1=S.d2='';render()">Reset filter</button>`:""}</div>${bad?'<div class="fe" role="alert">Tanggal awal sesudah tanggal akhir</div>':""}<button class="b" onclick="window.print()">Cetak</button><button class="b s" onclick="repDl('${k}')">Unduh CSV</button></div>`};
function tblCsv(h,r){const q=v=>typeof v==="number"?String(Math.round(v)):'"'+String(v).replace(/"/g,'""')+'"';return[h.map(x=>q(x.replace("#",""))),...r.map(x=>x.map(q))].map(x=>x.join(",")).join("\r\n")}
function repCsv(k){if(k==="air")return airCsv();if(k==="piu"){const D=piuData();return tblCsv(["Unit","#Piutang pinjaman","#Piutang pelanggan","#Total"],D.units.map(x=>[x.n,x.p,x.c,x.p+x.c]))}if(k==="sp")return tblCsv(["Pinjaman","Nasabah","Unit","#Pokok","#Sisa pokok","Angsuran berikut","Status"],spData().rows.map(r=>[r.no,r.n,r.u,r.pk,r.sisa,r.nx,r.st]));const R=k==="neraca"?neracaRows().R:k==="kas"?kasRows().R:S.lg==="unit"?[...lrUnit().map(x=>["i",x.n+" | pendapatan",x.r]),...lrUnit().map(x=>["i",x.n+" | beban",x.e]),...lrUnit().map(x=>["i",x.n+" | laba",x.p])]:lrRows().R,q=v=>typeof v==="number"?String(Math.round(v)):'"'+String(v).replace(/"/g,'""')+'"';return[["Keterangan","Jumlah"].map(q),...R.map(([c,l,v])=>[q(l),v===null?"":q(v)])].map(r=>r.join(",")).join("\r\n")}
function repDl(k){try{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff"+repCsv(k)],{type:"text/csv"}));a.download="laporan-"+k+"-"+today()+".csv";a.click();S.msg="Laporan diunduh (CSV)"}catch(e){S.msg="⚠ Unduh gagal: "+e.message}render()}
function vNeraca(){const{D,R}=neracaRows();return`<h2>Neraca</h2>${repBar("neraca","as")}${repHead("NERACA",unTxt()+" · per "+(S.d2||"tanggal terakhir"))}${tbl(["Keterangan","#Jumlah"],repRows(R))}<p class="k">${D.ok?"✓ Aset = Kewajiban + Ekuitas":"⚠ Tidak seimbang: selisih Rp "+fm(D.ta-D.tl-D.te)}</p>`}
function vLR(){const u=S.lg==="unit",sw=`<div class="fl noprint"><select aria-label="Tampilan" onchange="S.lg=this.value;render()">${opt([["akun","Per akun"],["unit","Per unit usaha"]],x=>x,u?"unit":"akun")}</select></div>`;
 if(u){const U=lrUnit(),t=U.reduce((a,x)=>({r:a.r+x.r,e:a.e+x.e,p:a.p+x.p}),{r:0,e:0,p:0});return`<h2>Laba Rugi</h2>${repBar("lr")}${sw}${repHead("LAPORAN LABA RUGI PER UNIT USAHA",perTxt())}${U.length?tbl(["Unit","#Pendapatan","#Beban","#Laba (rugi)"],[...U,{n:"Total",...t}].map(x=>`<tr><td>${esc(x.n)}</td><td class="n">${rp(x.r)}</td><td class="n">${rp(x.e)}</td><td class="n">${rp(x.p)}</td></tr>`)):'<p class="k">Belum ada pendapatan atau beban pada rentang ini.</p>'}<p class="k">Jurnal penutup tahun buku tidak dihitung.</p>`}
 const{D,R}=lrRows();return`<h2>Laba Rugi</h2>${repBar("lr")}${sw}${repHead("LAPORAN LABA RUGI",unTxt()+" · "+perTxt())}${D.R.length||D.E.length?tbl(["Keterangan","#Jumlah"],repRows(R)):'<p class="k">Belum ada pendapatan atau beban pada rentang ini.</p>'}<p class="k">Jurnal penutup tahun buku tidak dihitung.</p>`}
function vKas(){const{D,R}=kasRows();return`<h2>Arus Kas</h2>${repBar("kas")}${repHead("LAPORAN ARUS KAS",unTxt()+" · "+perTxt())}${tbl(["Keterangan","#Jumlah"],repRows(R))}<p class="k">${D.ok?"✓ Saldo akhir sama dengan saldo Kas & Bank":"⚠ Tidak sama dengan saldo Kas & Bank (Rp "+fm(D.ck)+")"}. Metode langsung per akun lawan; klasifikasi aktivitas (asumsi teknis): akun 16xx = Investasi, 3xxx dan 2300 (tabungan nasabah) = Pendanaan, selain itu Operasi (termasuk pinjaman ke nasabah). Saldo awal (jurnal Saldo Awal) masuk saldo kas awal.</p>`}
function vRep(){const A=modOn("air");return subT(vNeraca()+vLR()+vKas()+vPiu()+vSpRep()+(A?vAirRep():""),"rp",[["neraca","Neraca",null],["lr","Laba Rugi","<h2>Laba Rugi</h2>"],["kas","Arus Kas","<h2>Arus Kas</h2>"],["piu","Piutang","<h2>Piutang</h2>"],["sp","Simpan Pinjam","<h2>Laporan Simpan Pinjam</h2>"]].concat(A?[["air","Unit Air","<h2>Laporan Unit Air</h2>"]]:[]))}
// ===== LAPORAN PIUTANG & SIMPAN PINJAM (v0.1.019) =====
const AGP=[["Belum jatuh tempo",-1e9,0],["1–30 hari",1,30],["31–60 hari",31,60],["61–90 hari",61,90],["> 90 hari",91,1e9]],AGC=[["0–30 hari",0,30],["31–60 hari",31,60],["61–90 hari",61,90],["> 90 hari",91,1e9]];
const actLoans=()=>db.loans.filter(l=>l.status==="active"&&(S.unit==="all"||l.unit_id===S.unit));
const insOf=ls=>{const s=new Set(ls.map(l=>l._id));return db.loan_installments.filter(i=>s.has(i.loan_id))};
const sisaPok=i=>i.principal_due-i.principal_paid,sisaTag=i=>sisaPok(i)+i.interest_due-i.interest_paid;
function piuData(){const t=today(),ls=actLoans(),ins=insOf(ls),lu=new Map(ls.map(l=>[l._id,l])),U={},P={};
 const un=id=>U[id||""]??={p:0,c:0},pa=(id,ty)=>P[id]??={ty,v:0};
 ins.forEach(i=>{const l=lu.get(i.loan_id),v=sisaPok(i);if(v>0){un(l.unit_id).p+=v;pa(l.party_id,"nasabah").v+=v}});
 const ss=db.sales.filter(x=>owedS(x)>0&&(S.unit==="all"||x.unit_id===S.unit));
 ss.forEach(x=>{const v=owedS(x);un(x.unit_id).c+=v;pa(x.party_id||"","pelanggan").v+=v});
 const agP=AGP.map(([n,a,b])=>{const x=ins.filter(i=>{if(i.status==="paid"||sisaTag(i)<=0)return false;const h=dayDiff(t,i.due_date);return h>=a&&h<=b});return[n,x.length,x.reduce((s,i)=>s+sisaTag(i),0)]}),
  agC=AGC.map(([n,a,b])=>{const x=ss.filter(q=>{const h=dayDiff(t,q.date);return h>=a&&h<=b});return[n,x.length,x.reduce((s,q)=>s+owedS(q),0)]});
 const sp=ins.reduce((s,i)=>s+sisaPok(i),0),sc=ss.reduce((s,x)=>s+owedS(x),0),b=balU(S.unit),g13=net(acc("ACC1300"),b),g14=net(acc("ACC1400"),b);
 const units=Object.keys(U).map(id=>({n:id?unitName(id):"Umum",p:U[id].p,c:U[id].c})).sort((a,b)=>a.n.localeCompare(b.n)),
  pihak=Object.keys(P).map(id=>({n:id?cust(id).name:"Umum",ty:P[id].ty,v:P[id].v})).sort((a,b)=>b.v-a.v);
 return{units,pihak,agP,agC,sp,sc,g13,g14,d13:Math.round(g13-sp),d14:Math.round(g14-sc)}}
function vPiu(){const D=piuData(),T=D.units.reduce((a,x)=>({p:a.p+x.p,c:a.c+x.c}),{p:0,c:0}),tt=x=>`<tr><td>${esc(x.n)}</td><td class="n">${rp(x.p)}</td><td class="n">${rp(x.c)}</td><td class="n">${rp(x.p+x.c)}</td></tr>`,ag=A=>tbl(["Umur","#Jumlah","#Sisa"],A.map(r=>`<tr><td>${r[0]}</td><td class="n">${r[1]}</td><td class="n">${rp(r[2])}</td></tr>`)),
 rc=(n,a,b,d)=>`<tr><td>${n}</td><td class="n">${rp(a)}</td><td class="n">${rp(b)}</td><td class="n">${d===0?"✓":"⚠ "+rp(d)}</td></tr>`;
 return`<h2>Piutang</h2>${repBar("piu","none")}${repHead("LAPORAN PIUTANG",unTxt()+" · posisi per "+today())}
${D.units.length?tbl(["Unit","#Piutang pinjaman","#Piutang pelanggan","#Total"],[...D.units.map(tt),tt({n:"Total",...T})]):'<p class="k">Tidak ada piutang berjalan.</p>'}
<h2>Aging tagihan pinjaman</h2>${ag(D.agP)}<p class="k">Sisa pokok + jasa angsuran yang belum dibayar, menurut umur sejak jatuh tempo.</p>
<h2>Aging piutang pelanggan</h2>${ag(D.agC)}<p class="k">Menurut umur sejak tanggal penjualan (belum ada tanggal jatuh tempo).</p>
<h2>Piutang terbesar</h2>${D.pihak.length?tbl(["Pihak","Jenis","#Sisa"],D.pihak.slice(0,10).map(x=>`<tr><td>${esc(x.n)}</td><td>${PT[x.ty]}</td><td class="n">${rp(x.v)}</td></tr>`)):'<p class="k">—</p>'}
<h2>Kecocokan dengan Buku Besar</h2>${tbl(["Akun","#Buku besar","#Rincian modul","#Selisih"],[rc("1300 Piutang Pinjaman (pokok)",D.g13,D.sp,D.d13),rc("1400 Piutang Pelanggan",D.g14,D.sc,D.d14)])}<p class="k">Selisih biasanya berasal dari Saldo Awal berupa jurnal yang belum terhubung ke modul (Fase 8: saldo awal terpandu).</p>`}
function spData(){const t=today(),T=trT(),U=l=>S.unit==="all"||l.unit_id===S.unit,ls=db.loans.filter(U),lu=new Map(ls.map(l=>[l._id,l])),a=actLoans(),ins=insOf(a);
 const cair=ls.filter(l=>l.disbursement_date&&!l.opening&&["active","paid_off"].includes(l.status)&&inD(l.disbursement_date)),
  ps=db.loan_payments.filter(p=>p.status!=="voided"&&lu.has(p.loan_id)&&inD(p.payment_date)),sm=k=>ps.reduce((s,p)=>s+(p[k]||0),0),
  gl=bal(l=>T.get(l.transaction_id)==="loan_in"&&inD(l.date)&&inUnit(l)),j4100=net(acc("ACC4100"),gl),j4400=net(acc("ACC4400"),gl);
 const rows=a.map(l=>{const li=ins.filter(i=>i.loan_id===l._id).sort((x,y)=>x.installment_number-y.installment_number),op=li.filter(i=>i.status!=="paid"),nx=op[0],od=op.filter(i=>i.due_date<t),mh=od.length?Math.max(...od.map(i=>dayDiff(t,i.due_date))):0;
  return{no:l.loan_number,n:party(l.party_id).name,u:unitName(l.unit_id),pk:l.principal,sisa:li.reduce((s,i)=>s+sisaPok(i),0),nx:nx?nx.due_date:"-",st:mh>0?"Menunggak "+mh+" hari":"Lancar",od:mh>0,tag:od.reduce((s,i)=>s+sisaTag(i),0)}});
 const dep=ins.filter(i=>i.status!=="paid"&&i.due_date>=t&&dayDiff(i.due_date,t)<=30);
 return{n:{aktif:a.length,lunas:ls.filter(l=>l.status==="paid_off").length,pengajuan:ls.filter(l=>["submitted","approved"].includes(l.status)).length},cair:{c:cair.length,v:cair.reduce((s,l)=>s+l.principal,0)},
  bay:{c:ps.length,p:sm("principal_amount"),n:sm("interest_amount"),d:sm("penalty_amount"),t:sm("total_amount")},j4100,j4400,
  okJ:Math.round(j4100)===Math.round(sm("interest_amount"))&&Math.round(j4400)===Math.round(sm("penalty_amount")),
  sisa:rows.reduce((s,r)=>s+r.sisa,0),menung:rows.filter(r=>r.od).length,tag:rows.reduce((s,r)=>s+r.tag,0),dep:{c:dep.length,v:dep.reduce((s,i)=>s+sisaTag(i),0)},rows}}
function vSpRep(){const D=spData(),B=(k,v)=>`<tr><td>${k}</td><td class="n">${v}</td></tr>`;
 return`<h2>Laporan Simpan Pinjam</h2>${repBar("sp")}${repHead("LAPORAN SIMPAN PINJAM",unTxt()+" · "+perTxt()+" · posisi per "+today())}
${tbl(["Posisi saat ini","#Nilai"],[B("Pinjaman aktif",D.n.aktif),B("Pinjaman lunas",D.n.lunas),B("Menunggu pencairan (diajukan/disetujui)",D.n.pengajuan),B("Sisa pokok pinjaman aktif",rp(D.sisa)),B("Pinjaman menunggak",D.menung+(D.n.aktif?" ("+Math.round(D.menung/D.n.aktif*100)+"%)":"")),B("Tagihan menunggak (pokok + jasa)",rp(D.tag)),B("Jatuh tempo 30 hari ke depan",D.dep.c+" angsuran · "+rp(D.dep.v))])}
${tbl(["Pada rentang tanggal","#Nilai"],[B("Pencairan",D.cair.c+" pinjaman · "+rp(D.cair.v)),B("Pembayaran diterima",D.bay.c+" kali · "+rp(D.bay.t)),B("— pokok",rp(D.bay.p)),B("— pendapatan jasa",rp(D.bay.n)),B("— denda",rp(D.bay.d))])}<p class="k">${D.okJ?"✓ Jasa dan denda sama dengan jurnal (4100, 4400)":"⚠ Jasa/denda berbeda dari jurnal: 4100 Rp "+fm(D.j4100)+", 4400 Rp "+fm(D.j4400)}. Pembayaran yang dibatalkan tidak dihitung.</p>
${spRep2()}<h2>Pinjaman aktif</h2>${D.rows.length?tbl(["Pinjaman","Nasabah","Unit","#Pokok","#Sisa pokok","Angsuran berikut","Status"],D.rows.map(r=>`<tr><td>${r.no}</td><td>${esc(r.n)}</td><td>${esc(r.u)}</td><td class="n">${rp(r.pk)}</td><td class="n">${rp(r.sisa)}</td><td>${r.nx}</td><td>${r.st}</td></tr>`)):'<p class="k">Tidak ada pinjaman aktif.</p>'}`}

// ===== SALDO AWAL TERPANDU (v0.1.024): piutang pelanggan dan pinjaman berjalan yang terhubung ke modul =====
const eqOpts=()=>opt(db.accounts.filter(a=>postable(a)&&isAct(a)&&a.type==="equity"),a=>[a._id,a.code+" "+a.name],"ACC3100");
function awalPiutang(){try{negAny();const v=i=>$("#"+i).value.trim(),d=v("aw-d"),a=Math.round(+pn(v("aw-a"))||0),c=v("aw-c"),u=v("aw-u"),e=v("aw-e");
 if(!d)throw fe("aw-d","Tanggal wajib diisi");if(!isD(d))throw fe("aw-d","Tanggal tidak valid");if(d>today())throw fe("aw-d","Tanggal saldo awal tidak boleh melewati hari ini");if(!u)throw fe("aw-u","Pilih unit usaha");if(!c)throw fe("aw-c","Pilih pelanggan (tambahkan di Unit Air > Pelanggan jika belum ada)");if(!(a>0))throw fe("aw-a","Jumlah harus lebih dari 0");if(!e)throw fe("aw-e","Pilih akun ekuitas lawan");
 const n=db.sales.filter(x=>x.opening).length+1,t=post({type:"opening",date:d,unit:u,desc:"Saldo awal piutang – "+cust(c).name,lines:[{acc:"ACC1400",d:a},{acc:e,c:a}]});
 const x={_id:uid("SAL"),sale_number:"SA-"+d.slice(0,4)+"-"+String(n).padStart(4,"0"),unit_id:u,party_id:c,date:d,payment_type:"credit",total:a,cash_id:null,transaction_id:t._id,status:"posted",opening:true};
 db.sales.push(x);audit("opening","sale",x._id,x.sale_number+" · Rp "+fm(a));save();clrF("#aw-a");S.awo=Object.assign(S.awo||{},{p:false});S.msg="Saldo awal piutang "+x.sale_number+" dicatat; bayar lewat Unit Air > Piutang"}catch(e){ferr(e);return}render()}
function batalAwalP(id){try{const x=db.sales.find(q=>q._id===id);if(!x||!x.opening)throw Error("Bukan saldo awal piutang");if(db.payments.some(p=>p.sale_id===id&&p.status!=="voided"))throw Error("Batalkan pembayaran piutang dulu");
 rev(x.transaction_id);x.status="voided";audit("void","sale",id,"saldo awal");save();S.msg="Saldo awal piutang dibatalkan dengan jurnal pembalik"}catch(e){S.msg="⚠ "+e.message}render()}
function awalPinjam(){try{negAny();const v=i=>$("#"+i).value.trim(),d=v("ap-d"),P=Math.round(+pn(v("ap-p"))||0),r=+v("ap-r"),n=parseInt(v("ap-t")),j=v("ap-j"),u=v("ap-u"),pt=v("ap-n"),e=v("ap-e");
 if(!d)throw fe("ap-d","Tanggal saldo wajib diisi");if(!isD(d))throw fe("ap-d","Tanggal tidak valid");if(d>today())throw fe("ap-d","Tanggal saldo awal tidak boleh melewati hari ini");if(!u)throw fe("ap-u","Pilih unit usaha");if(!spUnits().some(x=>x._id===u))throw fe("ap-u","Pinjaman hanya untuk unit bertipe Simpan Pinjam");if(!pt)throw fe("ap-n","Pilih nasabah (tambahkan di Simpan Pinjam jika belum ada)");if(!(P>0))throw fe("ap-p","Sisa pokok harus lebih dari 0");
 if(!(r>=0))throw fe("ap-r","Jasa tidak boleh negatif");if(r>100)throw fe("ap-r","Jasa maksimal 100% per tahun");if(!(n>0))throw fe("ap-t","Sisa tenor minimal 1 angsuran");if(n>360)throw fe("ap-t","Sisa tenor maksimal 360 angsuran");if(!j)throw fe("ap-j","Tanggal jatuh tempo angsuran berikutnya wajib diisi");if(!isD(j))throw fe("ap-j","Tanggal jatuh tempo tidak valid");if(!e)throw fe("ap-e","Pilih akun ekuitas lawan");
 const t=post({type:"opening",date:d,unit:u,desc:"Saldo awal pinjaman – "+party(pt).name,lines:[{acc:"ACC1300",d:P},{acc:e,c:P}]});
 const l={_id:uid("LOAN"),loan_number:numNext("loan",d),unit_id:u,party_id:pt,application_date:d,approval_date:d,disbursement_date:d,principal:P,interest_rate:r,interest_method:v("ap-m"),tenor:n,installment_amount:0,status:"active",opening:true,disbursement_txn:t._id,disbursement_cash:null};
 db.loans.push(l);schedule(l);db.loan_installments.filter(i=>i.loan_id===l._id).forEach(i=>{i.due_date=addM(j,i.installment_number-1)});
 audit("opening","loan",l._id,l.loan_number+" · sisa pokok Rp "+fm(P)+" · "+n+" angsuran");save();clrF("#ap-p,#ap-t");S.awo=Object.assign(S.awo||{},{l:false});S.msg="Saldo awal pinjaman "+l.loan_number+" dicatat; angsuran dibayar lewat Simpan Pinjam"}catch(e){ferr(e);return}render()}
function batalAwalL(id){try{const l=db.loans.find(x=>x._id===id);if(!l||!l.opening)throw Error("Bukan saldo awal pinjaman");if(db.loan_payments.some(p=>p.loan_id===id&&p.status!=="voided"))throw Error("Batalkan pembayaran angsuran dulu");
 rev(l.disbursement_txn);db.loan_installments=db.loan_installments.filter(i=>i.loan_id!==id);db.loans=db.loans.filter(x=>x._id!==id);if(S.ln===id)S.ln=null;audit("void","loan",id,"saldo awal "+l.loan_number);save();S.msg="Saldo awal pinjaman dibatalkan dengan jurnal pembalik"}catch(e){S.msg="⚠ "+e.message}render()}
// Pratinjau langsung (v1.1.025): jurnal dan jadwal angsuran dihitung dari isian formulir tanpa menyimpan apa pun
function awalPv(k){try{const g=i=>($("#"+i)||{}).value||"",o=$(k==="p"?"#aw-pv":"#ap-pv");if(!o)return;const eq=db.accounts.find(a=>a._id===g(k==="p"?"aw-e":"ap-e")),en=eq?eq.code+" "+eq.name:"akun ekuitas";
 if(k==="p"){const a=Math.round(+pn(g("aw-a"))||0);o.innerHTML=a>0?"Jurnal: <b>Dr 1400 Piutang Usaha</b> / <b>Cr "+esc(en)+"</b> · Rp "+fm(a):"Isi sisa piutang untuk melihat jurnal.";return}
 const P=Math.round(+pn(g("ap-p"))||0),r=+g("ap-r"),n=parseInt(g("ap-t")),j=g("ap-j"),d=g("ap-d")||today();
 if(!(P>0&&n>0&&n<=360&&r>=0&&r<=100&&isD(d))){o.innerHTML="Isi sisa pokok, jasa, dan sisa tenor untuk melihat jadwal.";return}
 const rows=buildSchedule({principal:P,rate:r,tenor:n,method:g("ap-m")||"flat",start:d}),tj=rows.reduce((s,x)=>s+x.interest_due,0),f=rows[0];
 let h="Jurnal: <b>Dr 1300 Piutang Pinjaman</b> / <b>Cr "+esc(en)+"</b> · Rp "+fm(P)+"<br>Angsuran pertama ± Rp "+fm(f.total_due)+" (pokok "+fm(f.principal_due)+" + jasa "+fm(f.interest_due)+") · total jasa sisa Rp "+fm(tj)+" · "+n+" angsuran";
 if(isD(j)){h+=j<d?"<br><b>⚠ Jatuh tempo lebih awal dari tanggal saldo</b>":j<today()?"<br><b>⚠ Angsuran pertama sudah lewat jatuh tempo "+dayDiff(today(),j)+" hari</b>":"<br>Angsuran pertama jatuh tempo "+j+", terakhir "+addM(j,n-1)}
 o.innerHTML=h}catch(e){}}
const awoOp=(k,n)=>(S.awo&&S.awo[k]!==undefined?S.awo[k]:!n)?" open":"";
function vAwal(){const uo=opt(db.business_units.filter(isAct),u=>[u._id,u.name]),pel=db.parties.filter(p=>p.type==="pelanggan"&&isAct(p)),nas=db.parties.filter(p=>p.type==="nasabah"&&isAct(p)),
 sp=db.sales.filter(x=>x.opening&&x.status==="posted"&&(S.unit==="all"||x.unit_id===S.unit)),sl=db.loans.filter(l=>l.opening&&(S.unit==="all"||l.unit_id===S.unit)),
 sisa=l=>db.loan_installments.filter(i=>i.loan_id===l._id).reduce((s,i)=>s+sisaPok(i),0),tp=sp.reduce((s,x)=>s+x.total,0),tps=sp.reduce((s,x)=>s+owedS(x),0),tl=sl.reduce((s,l)=>s+sisa(l),0),
 st=(ok,t)=>`<li>${ok?"✓":"○"} ${t}</li>`,air=modOn("air"),
 emp=(n,t)=>n?"":`<p class="k">${t}</p>`;
 return`<h2>Saldo Awal Terpandu</h2><div class="card"><div class="k">Untuk BUMDes yang sudah punya piutang atau pinjaman berjalan sebelum memakai sistem. Data langsung terhubung ke modul (pembayaran, jadwal angsuran, laporan) sehingga laporan Piutang cocok dengan Buku Besar. Jurnal: Dr Piutang / Cr akun ekuitas lawan (asumsi teknis; kebijakan akuntansi mengikuti ketentuan BUMDes). Saldo kas, aset, dan akun lain tetap lewat Jurnal Multi-baris.</div>
<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:8px;margin-top:8px">${air?`<div><div class="k">Piutang pelanggan awal</div><b>${rp(tp)}</b><div class="k">${sp.length} entri · sisa ${rp(tps)}</div></div>`:""}<div><div class="k">Pinjaman berjalan awal</div><b>${rp(tl)}</b><div class="k">${sl.length} pinjaman · sisa pokok</div></div></div>
<ul class="k" style="margin:8px 0 0;padding-left:18px;list-style:none">${st(air?pel.length>0:true,air?"Pelanggan sudah terdaftar (Unit Air > Pelanggan)":"Modul Air nonaktif: piutang pelanggan tidak dipakai")}${st(nas.length>0,"Nasabah sudah terdaftar (Simpan Pinjam)")}${st(sp.length+sl.length>0,"Saldo awal piutang/pinjaman dicatat")}${st(false,"Periksa Neraca Saldo di Pembukuan lalu cocokkan dengan catatan lama")}</ul></div>
${air?`<h3>Piutang pelanggan awal</h3><details class="card"${awoOp("p",sp.length)} ontoggle="S.awo=Object.assign(S.awo||{},{p:this.open})"><summary><b>＋ Tambah saldo awal piutang</b></summary><div oninput="awalPv('p')" onchange="awalPv('p')"><label>Tanggal saldo</label><input id="aw-d" type="date" value="${today()}" max="${today()}"><label>Unit usaha</label><select id="aw-u">${uo}</select><label>Pelanggan</label><select id="aw-c"><option value="">Pilih pelanggan…</option>${opt(pel,p=>[p._id,p.name])}</select>${emp(pel.length,"Belum ada pelanggan aktif. Tambahkan di Unit Air &gt; Pelanggan.")}
<label>Sisa piutang (Rp)</label><input id="aw-a" type="text" inputmode="numeric" autocomplete="off" oninput="fmtR(this)"><label>Akun ekuitas lawan</label><select id="aw-e">${eqOpts()}</select></div><div id="aw-pv" class="k" aria-live="polite" style="margin:8px 0">Isi sisa piutang untuk melihat jurnal.</div><button class="b" onclick="awalPiutang()">Simpan saldo awal piutang</button></details>
${sp.length?tbl(["No","Tanggal","Pelanggan","Unit","#Jumlah","#Sisa",""],sp.map(x=>`<tr><td>${x.sale_number}</td><td>${x.date}</td><td>${esc(cust(x.party_id).name)}</td><td>${esc(unitName(x.unit_id))}</td><td class="n">${rp(x.total)}</td><td class="n">${rp(owedS(x))}</td><td>${ib("undo","Batalkan","askC('batalAwalP','"+x._id+"')","x")}</td></tr>`).concat(`<tr><td colspan="4"><b>Total</b></td><td class="n"><b>${rp(tp)}</b></td><td class="n"><b>${rp(tps)}</b></td><td></td></tr>`)):'<p class="k">Belum ada saldo awal piutang.</p>'}
`:""}
<h3>Pinjaman berjalan awal</h3><details class="card"${awoOp("l",sl.length)} ontoggle="S.awo=Object.assign(S.awo||{},{l:this.open})"><summary><b>＋ Tambah saldo awal pinjaman</b></summary><div oninput="awalPv('l')" onchange="awalPv('l')"><label>Tanggal saldo</label><input id="ap-d" type="date" value="${today()}" max="${today()}"><label>Unit usaha</label><select id="ap-u">${opt(spUnits(),u=>[u._id,u.name])}</select><label>Nasabah</label><select id="ap-n"><option value="">Pilih nasabah…</option>${opt(nas,p=>[p._id,p.name])}</select>${emp(nas.length,"Belum ada nasabah aktif. Tambahkan di Simpan Pinjam &gt; Nasabah.")}
<label>Sisa pokok (Rp)</label><input id="ap-p" type="text" inputmode="numeric" autocomplete="off" oninput="fmtR(this)"><label>Jasa (% per tahun)</label><input id="ap-r" type="text" inputmode="decimal" autocomplete="off" value="12"><label>Metode jasa</label><select id="ap-m"><option value="flat">Flat (dari sisa pokok ini)</option><option value="menurun">Menurun (dari sisa pokok)</option></select>
<label>Sisa tenor (jumlah angsuran)</label><input id="ap-t" type="text" inputmode="numeric" autocomplete="off"><label>Jatuh tempo angsuran berikutnya</label><input id="ap-j" type="date"><label>Akun ekuitas lawan</label><select id="ap-e">${eqOpts()}</select></div><div id="ap-pv" class="k" aria-live="polite" style="margin:8px 0">Isi sisa pokok, jasa, dan sisa tenor untuk melihat jadwal.</div><button class="b" onclick="awalPinjam()">Simpan saldo awal pinjaman</button></details>
${sl.length?tbl(["No","Nasabah","Unit","#Sisa pokok","Angsuran ke-1",""],sl.map(l=>{const i1=db.loan_installments.filter(i=>i.loan_id===l._id).sort((a,b)=>a.installment_number-b.installment_number)[0];return`<tr><td>${l.loan_number}</td><td>${esc(party(l.party_id).name)}</td><td>${esc(unitName(l.unit_id))}</td><td class="n">${rp(sisa(l))}</td><td>${i1?i1.due_date:"-"}</td><td>${ib("undo","Batalkan","askC('batalAwalL','"+l._id+"')","x")}</td></tr>`}).concat(`<tr><td colspan="3"><b>Total</b></td><td class="n"><b>${rp(tl)}</b></td><td colspan="2"></td></tr>`)):'<p class="k">Belum ada saldo awal pinjaman.</p>'}`}
// ===== LAPORAN UNIT AIR (v0.1.020): penjualan per produk, pelanggan, dan bulan; pembayaran piutang; dicocokkan ke jurnal =====
const airSales=()=>db.sales.filter(x=>x.status==="posted"&&!x.opening&&(S.unit==="all"||x.unit_id===S.unit)&&inD(x.date)),airItem=x=>db.sale_items.find(i=>i.sale_id===x._id)||{},qf=q=>(Math.round(q*100)/100).toLocaleString("id-ID");
function airData(){const T=trT(),ss=airSales(),ids=new Set(ss.map(x=>x._id)),sm=new Map(db.sales.map(x=>[x._id,x])),sum=(a,f)=>a.reduce((s,x)=>s+f(x),0),
 tn=ss.filter(x=>x.payment_type==="cash"),kr=ss.filter(x=>x.payment_type!=="cash"),
 pm=db.payments.filter(p=>{const x=sm.get(p.sale_id);return p.status!=="voided"&&inD(p.date)&&x&&(S.unit==="all"||x.unit_id===S.unit)}),P={},C={},B={},bl=m=>B[m]??={m,c:0,v:0,t:0,k:0,p:0};
 db.sale_items.filter(i=>ids.has(i.sale_id)).forEach(i=>{const pr=db.products.find(q=>q._id===i.product_id)||{},k=i.product_id||i.label,o=P[k]??={n:i.label||pr.name||"-",u:i.unit||pr.unit||"",c:0,q:0,v:0};o.c++;o.q+=i.qty;o.v+=i.subtotal});
 ss.forEach(x=>{const k=x.party_id||"",o=C[k]??={n:k?cust(k).name:"Umum (tanpa pelanggan)",c:0,v:0,s:0},b=bl(x.date.slice(0,7));o.c++;o.v+=x.total;o.s+=owedS(x);b.c++;b.v+=x.total;if(x.payment_type==="cash")b.t+=x.total;else b.k+=x.total});
 pm.forEach(p=>{bl(p.date.slice(0,7)).p+=p.amount});
 const gl=bal(l=>["sale_cash","sale_credit"].includes(T.get(l.transaction_id))&&inD(l.date)&&inUnit(l)),gp=bal(l=>T.get(l.transaction_id)==="sale_pay"&&inD(l.date)&&inUnit(l)),
  jr=db.accounts.filter(a=>postable(a)&&a.type==="revenue").reduce((s,a)=>s+net(a,gl),0),jp=-net(acc("ACC1400"),gp),total=sum(ss,x=>x.total),bayar=sum(pm,p=>p.amount);
 return{n:ss.length,total,tn:{c:tn.length,v:sum(tn,x=>x.total)},kr:{c:kr.length,v:sum(kr,x=>x.total)},bay:{c:pm.length,v:bayar},sisa:sum(db.sales.filter(x=>S.unit==="all"||x.unit_id===S.unit),owedS),
  jr,jp,okR:Math.round(jr)===Math.round(total),okP:Math.round(jp)===Math.round(bayar),
  prod:Object.values(P).sort((a,b)=>b.v-a.v||a.n.localeCompare(b.n)),pel:Object.values(C).sort((a,b)=>b.v-a.v||a.n.localeCompare(b.n)),bln:Object.values(B).sort((a,b)=>b.m.localeCompare(a.m))}}
function airCsv(){return tblCsv(["No","Tanggal","Pelanggan","Unit","Produk","#Jumlah","Cara","#Total","#Dibayar","#Sisa"],airSales().sort((a,b)=>a.date.localeCompare(b.date)||a.sale_number.localeCompare(b.sale_number)).map(x=>{const its=db.sale_items.filter(i=>i.sale_id===x._id),nm=its.map(i=>i.label||(db.products.find(q=>q._id===i.product_id)||{}).name||"-").join("; ");return[x.sale_number,x.date,cust(x.party_id).name,unitName(x.unit_id),x.bill?"Tagihan air "+x.bill.period:nm||"-",x.bill?x.bill.usage:its.reduce((a,i)=>a+i.qty,0),x.payment_type==="cash"?"Tunai":"Kredit",x.total,x.total-owedS(x),owedS(x)]}))}
function vAirRep(){const D=airData(),B=(k,v)=>`<tr><td>${k}</td><td class="n">${v}</td></tr>`,none=!D.n&&!D.bay.c;
 return`<h2>Laporan Unit Air</h2>${repBar("air")}${repHead("LAPORAN PENJUALAN UNIT AIR",unTxt()+" · "+perTxt()+" · piutang per "+today())}
${tbl(["Pada rentang tanggal","#Nilai"],[B("Penjualan",D.n+" transaksi · "+rp(D.total)),B("— tunai",D.tn.c+" · "+rp(D.tn.v)),B("— kredit",D.kr.c+" · "+rp(D.kr.v)),B("Pembayaran piutang diterima",D.bay.c+" kali · "+rp(D.bay.v)),B("Piutang pelanggan saat ini",rp(D.sisa))])}
<p class="k">${D.okR&&D.okP?"✓ Penjualan dan pembayaran piutang sama dengan jurnal (pendapatan dan akun 1400)":"⚠ Tidak sama dengan jurnal: pendapatan "+rp(D.jr)+" vs penjualan "+rp(D.total)+"; penerimaan "+rp(D.jp)+" vs pembayaran "+rp(D.bay.v)}</p>
${none?'<p class="k">Belum ada penjualan atau pembayaran piutang pada rentang ini.</p>':`<h2>Per produk</h2>${D.prod.length?tbl(["Produk","Satuan","#Jumlah","#Penjualan","#Total"],D.prod.map(x=>`<tr><td>${esc(x.n)}</td><td>${esc(x.u||"-")}</td><td class="n">${qf(x.q)}</td><td class="n">${x.c}</td><td class="n">${rp(x.v)}</td></tr>`)):'<p class="k">—</p>'}
<h2>Per pelanggan</h2>${D.pel.length?tbl(["Pelanggan","#Penjualan","#Total","#Dibayar","#Sisa piutang"],D.pel.map(x=>`<tr><td>${esc(x.n)}</td><td class="n">${x.c}</td><td class="n">${rp(x.v)}</td><td class="n">${rp(x.v-x.s)}</td><td class="n">${rp(x.s)}</td></tr>`)):'<p class="k">—</p>'}<p class="k">Sisa piutang adalah posisi saat ini untuk penjualan pada rentang ini.</p>
<h2>Per bulan</h2>${tbl(["Bulan","#Transaksi","#Penjualan","#Tunai","#Kredit","#Piutang diterima"],D.bln.map(x=>`<tr><td>${x.m}</td><td class="n">${x.c}</td><td class="n">${rp(x.v)}</td><td class="n">${rp(x.t)}</td><td class="n">${rp(x.k)}</td><td class="n">${rp(x.p)}</td></tr>`))}`}`}
