// ===== RESTRUKTURISASI, HAPUS BUKU, PEMULIHAN (SP4 tahap 2, v1.1.019) =====
// Restrukturisasi: sisa pokok dijadwalkan ulang; jadwal lama diarsipkan di riwayat pinjaman. Jasa dan denda belum dibayar belum dibukukan (pendapatan diakui saat dibayar), sehingga penghapusannya tidak berjurnal.
// Hapus buku: kredit Macet dikeluarkan dari piutang (Dr 5700, Cr 1300); pemulihan sesudahnya = pendapatan 4600. Izin sp.restruk dan sp.hapusbuku TIDAK ikut dari sp.kelola.
const rsOut=l=>db.loan_installments.filter(i=>i.loan_id===l._id).reduce((s,i)=>s+i.principal_due-i.principal_paid,0);
function rsArrears(l,d){let a=0,p=0;db.loan_installments.filter(i=>i.loan_id===l._id&&i.status!=="paid"&&i.due_date<d).forEach(i=>{a+=i.interest_due-i.interest_paid;p+=owed(i,d).pen});return{int:Math.round(a),pen:Math.round(p)}}
const rsLast=l=>(l.restructures||[]).slice(-1)[0]||null,rsMeth={flat:"Flat",menurun:"Menurun",anuitas:"Anuitas"};
function rsFee(l,d,code,out){if(!code)return 0;const r=rateAt(code,d);if(!r||r.fee_type!=="restruk")throw Error("Kode biaya restrukturisasi tidak valid untuk tanggal ini");const od=db.loan_installments.filter(i=>i.loan_id===l._id&&i.status!=="paid"&&i.due_date<d).reduce((s,i)=>s+i.principal_due-i.principal_paid+i.interest_due-i.interest_paid,0);
 return calcFees({date:d,codes:[code],pokok:l.principal,sisa_pokok:out,tunggakan:od,bulan:1})}
// jurnal biaya + pajak atas biaya (v1.1.020): Dr Kas (biaya+pajak), Cr 4400 biaya, Cr 2220 pajak
const feeLines=(cashAcc,res,extra)=>{const L=[{acc:cashAcc,d:res.fee_total+res.tax_total+(extra||0)}];if(res.fee_total>0)L.push(...feeCr(res.items));if(res.tax_total>0)L.push({acc:"ACC2220",c:res.tax_total});return L};
function saveRestruk(){try{const id=S.ers,l=db.loans.find(x=>x._id===id),v=i=>$("#"+i).value.trim();if(!l)throw Error("Pinjaman tidak ditemukan");if(l.status!=="active")throw Error("Hanya pinjaman aktif yang dapat direstrukturisasi");
 const d=v("rs-d"),r=Number(String(v("rs-r")).replace(",",".")),n=Number(pn(v("rs-t"))),m=v("rs-m"),ar=v("rs-a"),fc=v("rs-f"),why=v("rs-n"),c=db.cash_accounts.find(x=>x._id===v("rs-c"));
 if(!isD(d))throw fe("rs-d","Tanggal tidak valid");if(d>today())throw fe("rs-d","Tanggal tidak boleh melewati hari ini");if(d<(l.disbursement_date||l.application_date))throw fe("rs-d","Tanggal tidak boleh sebelum pencairan");
 const lp=db.loan_payments.filter(p=>p.loan_id===l._id&&p.status!=="voided").map(p=>p.payment_date).sort().pop();if(lp&&d<lp)throw fe("rs-d","Tanggal tidak boleh sebelum pembayaran terakhir ("+lp+")");
 if(!Number.isFinite(r)||r<0||r>spl().max_rate)throw fe("rs-r","Jasa 0–"+spl().max_rate+"% per tahun");if(!Number.isInteger(n)||n<1||n>spl().max_tenor)throw fe("rs-t","Tenor baru 1–"+spl().max_tenor+" bulan");if(!rsMeth[m])throw fe("rs-m","Pilih metode jasa");
 if(!why)throw fe("rs-n","Alasan restrukturisasi wajib diisi");const out=rsOut(l);if(!(out>0))throw Error("Tidak ada sisa pokok untuk direstrukturisasi");
 const A=rsArrears(l,d);if(ar!=="hapus"&&ar!=="bayar")throw fe("rs-a","Pilih perlakuan jasa dan denda tertunggak");if(ar==="bayar"&&(A.int>0||A.pen>0))throw fe("rs-a","Masih ada jasa Rp "+fm(A.int)+" dan denda Rp "+fm(A.pen)+" tertunggak: bayar dulu atau pilih Dihapuskan");
 const fr=rsFee(l,d,fc,out),fee=fr?fr.fee_total:0,ftax=fr?fr.tax_total:0;if(fee>0&&!c)throw fe("rs-c","Pilih kas/bank untuk biaya restrukturisasi");
 const sch=buildSchedule({principal:out,rate:r,tenor:n,method:m,start:d,...calcOf(l)}),all=db.loan_installments.filter(i=>i.loan_id===l._id),un=all.filter(i=>i.status!=="paid"),mx=all.filter(i=>i.status==="paid"||i.principal_paid+i.interest_paid+(i.penalty_paid||0)>0).reduce((s,i)=>Math.max(s,i.installment_number),0);
 if(restrukDua(l)){if(!l.restruk_prop){l.restruk_prop={date:d,rate:r,tenor:n,method:m,ar,fee_code:fc,cash_id:c?c._id:"",reason:why,sisa:out,by:(curUser()||{}).name||null,by_id:actorId(),at:now()};audit("usul_restruk","loan",id,"sisa Rp "+fm(out)+" · "+r+"% "+m+", "+n+" bln · "+why);save();okM();S.eld=id;S.md="ld";S.msg="Usulan restrukturisasi dicatat; menunggu persetujuan pengguna lain";render();return}sodChk(l,"restruk_dua")}
 let txn=null;if(fee>0){const t=post({type:"loan_fee",date:d,unit:l.unit_id,desc:"Biaya restrukturisasi "+l.loan_number+" – "+party(l.party_id).name,lines:feeLines(c.account_id,fr)});txn=t._id}
 const old={rate:l.interest_rate,tenor:l.tenor,method:l.interest_method,amount:l.installment_amount,sisa:out,count:un.length,arrears_int:A.int,arrears_pen:A.pen,installments:un.map(i=>JSON.parse(JSON.stringify(i)))};
 un.forEach(i=>{if(i.principal_paid+i.interest_paid+(i.penalty_paid||0)>0){i.principal_due=i.principal_paid;i.interest_due=i.interest_paid;i.penalty_due=i.penalty_paid||0;i.total_due=i.principal_due+i.interest_due;i.status="paid";i.restructured=true;delete i.pen_from}else db.loan_installments.splice(db.loan_installments.indexOf(i),1)});
 const nid=[];sch.forEach(x=>{const _id=uid("INS");nid.push(_id);db.loan_installments.push({_id,loan_id:l._id,installment_number:mx+x.n,due_date:x.due_date,principal_due:x.principal_due,interest_due:x.interest_due,penalty_due:0,total_due:x.total_due,principal_paid:0,interest_paid:0,penalty_paid:0,status:"unpaid"})});
 l.interest_rate=r;l.interest_method=m;l.tenor=mx+n;l.installment_amount=sch[0].total_due;
 (l.restructures=l.restructures||[]).push({_id:uid("RS"),date:d,reason:why,by:(curUser()||{}).name||null,by_id:actorId(),at:now(),old,new:{rate:r,tenor:n,method:m,sisa:out,first_due:sch[0].due_date,installment:sch[0].total_due,ids:nid},pay_n:db.loan_payments.length,arrears:ar,fee_code:fc||null,fee,fee_tax:ftax,txn_id:txn});if(l.restruk_prop){const x=rsLast(l);x.proposed_by=l.restruk_prop.by;x.proposed_date=l.restruk_prop.date;delete l.restruk_prop}
 audit("restruk","loan",id,"sisa Rp "+fm(out)+" · "+old.rate+"% "+old.method+" → "+r+"% "+m+", "+n+" bln"+(A.int+A.pen?" · tertunggak dihapus Rp "+fm(A.int+A.pen):"")+(fee?" · biaya Rp "+fm(fee)+(ftax?" + pajak Rp "+fm(ftax):""):"")+" · "+why);save();okM();S.eld=id;S.md="ld";S.msg="Restrukturisasi dicatat; jadwal baru "+n+" angsuran"}catch(e){mErr(e);return}render()}
// Batal restrukturisasi (v1.1.020): hanya yang TERAKHIR, pinjaman aktif, dan belum ada pembayaran pada jadwal baru. Jadwal lama dipulihkan dari arsip, biaya dibalik.
function rsNewIns(l,x){const ids=x.new.ids,all=db.loan_installments.filter(i=>i.loan_id===l._id);if(ids)return all.filter(i=>ids.includes(i._id));const oid=x.old.installments.map(i=>i._id),mn=Math.min(...x.old.installments.map(i=>i.installment_number));return all.filter(i=>!oid.includes(i._id)&&i.installment_number>=mn)}
function canUndoRs(l){const x=rsLast(l);if(!x||l.status!=="active"||x.undone)return false;return rsNewIns(l,x).every(i=>i.principal_paid+i.interest_paid+(i.penalty_paid||0)===0)}
function batalRestruk(id){try{const l=db.loans.find(v=>v._id===id),x=l&&rsLast(l);if(!x)throw Error("Tidak ada restrukturisasi");if(l.status!=="active")throw Error("Pinjaman harus berstatus Aktif");
 const ni=rsNewIns(l,x);if(ni.some(i=>i.principal_paid+i.interest_paid+(i.penalty_paid||0)>0))throw Error("Sudah ada pembayaran pada jadwal baru: batalkan pembayaran itu dulu");
 if(x.txn_id)rev(x.txn_id);const nids=ni.map(i=>i._id);db.loan_installments=db.loan_installments.filter(i=>!nids.includes(i._id));
 x.old.installments.forEach(o=>{const k=db.loan_installments.findIndex(i=>i._id===o._id),c=JSON.parse(JSON.stringify(o));if(k>=0)db.loan_installments[k]=c;else db.loan_installments.push(c)});
 l.interest_rate=x.old.rate;l.interest_method=x.old.method;l.tenor=x.old.tenor;l.installment_amount=x.old.amount||x.old.installments[0].total_due;l.restructures.pop();
 audit("batal_restruk","loan",id,x.date+" · "+x.new.rate+"% → "+x.old.rate+"%"+(x.fee?" · biaya Rp "+fm(x.fee+(x.fee_tax||0))+" dibalik":""));save();S.msg="Restrukturisasi dibatalkan; jadwal lama dipulihkan"}catch(e){S.msg="⚠ "+e.message}render()}
// Usul hapus buku (dua orang) bila aturan hapus_dua aktif: pengusul ≠ penyetuju
const hapusDua=()=>rbacOn()&&sodCfg().hapus_dua,rsMin=()=>Math.max(0,Number((db.settings||{}).sp_restruk_min)||0),rsSisa=l=>db.loan_installments.filter(i=>i.loan_id===l._id).reduce((s,i)=>s+i.principal_due-i.principal_paid,0),restrukDua=l=>rbacOn()&&sodCfg().restruk_dua&&(!l||!!l.restruk_prop||rsMin()<=0||rsSisa(l)>=rsMin());
function tolakRestruk(id){try{const l=db.loans.find(x=>x._id===id);if(!l||!l.restruk_prop)throw Error("Tidak ada usulan restrukturisasi");audit("tolak_restruk","loan",id,"usulan "+l.restruk_prop.date+" ditarik/ditolak");delete l.restruk_prop;save();S.msg="Usulan restrukturisasi dibatalkan"}catch(e){S.msg="⚠ "+e.message}render()}
function tolakHapus(id){try{const l=db.loans.find(x=>x._id===id);if(!l||!l.writeoff_prop)throw Error("Tidak ada usulan hapus buku");audit("tolak_hapus_buku","loan",id,"usulan "+l.writeoff_prop.date+" ditarik/ditolak");delete l.writeoff_prop;save();S.msg="Usulan hapus buku dibatalkan"}catch(e){S.msg="⚠ "+e.message}render()}
function saveHapus(){try{const id=S.ehb,l=db.loans.find(x=>x._id===id),v=i=>$("#"+i).value.trim();if(!l)throw Error("Pinjaman tidak ditemukan");if(l.status!=="active")throw Error("Hanya pinjaman aktif yang dapat dihapus buku");
 const d=v("hb-d"),why=v("hb-n");if(!isD(d))throw fe("hb-d","Tanggal tidak valid");if(d>today())throw fe("hb-d","Tanggal tidak boleh melewati hari ini");if(d<(l.disbursement_date||l.application_date))throw fe("hb-d","Tanggal tidak boleh sebelum pencairan");
 if(kolOf(l,d).k<4)throw Error("Hapus buku hanya untuk pinjaman berkolektibilitas Macet (kini: "+kolOf(l,d).label+")");if(!why)throw fe("hb-n","Alasan hapus buku wajib diisi");const out=rsOut(l);if(!(out>0))throw Error("Tidak ada sisa pokok");
 if(hapusDua()){if(!l.writeoff_prop){l.writeoff_prop={date:d,reason:why,amount:out,by:(curUser()||{}).name||null,by_id:actorId(),at:now()};audit("usul_hapus_buku","loan",id,"Rp "+fm(out)+" · "+why);save();okM();S.eld=id;S.md="ld";S.msg="Usulan hapus buku dicatat; menunggu persetujuan pengguna lain";render();return}sodChk(l,"hapus_dua")}
 const t=post({type:"loan_wo",date:d,unit:l.unit_id,desc:"Hapus buku "+l.loan_number+" – "+party(l.party_id).name,lines:[{acc:"ACC5700",d:out},{acc:"ACC1300",c:out}]});
 goLoan(l,"written_off");if(l.fee_amort)amortRun(l,d,true);l.writeoff={date:d,amount:out,reason:why,by:(curUser()||{}).name||null,by_id:actorId(),txn_id:t._id};if(l.writeoff_prop){l.writeoff.proposed_by=l.writeoff_prop.by;l.writeoff.proposed_date=l.writeoff_prop.date;delete l.writeoff_prop}l.recoveries=l.recoveries||[];audit("hapus_buku","loan",id,"Rp "+fm(out)+" · "+why);save();okM();S.eld=id;S.md="ld";S.msg="Pinjaman dihapus buku Rp "+fm(out)+(l.disb&&l.disb.sav>0&&!l.disb.sav_ret?" — tabungan wajib Rp "+fm(l.disb.sav)+" tetap di rekening nasabah dan tidak lagi terkunci":"")}catch(e){mErr(e);return}render()}
function savePulih(){try{const id=S.epm,l=db.loans.find(x=>x._id===id),v=i=>$("#"+i).value.trim();if(!l||l.status!=="written_off")throw Error("Pemulihan hanya untuk pinjaman yang sudah dihapus buku");negAny();
 const d=v("pm-d"),a=Math.round(+pn(v("pm-a"))||0),c=db.cash_accounts.find(x=>x._id===v("pm-c"));if(!isD(d))throw fe("pm-d","Tanggal tidak valid");if(d>today())throw fe("pm-d","Tanggal tidak boleh melewati hari ini");if(d<l.writeoff.date)throw fe("pm-d","Tanggal tidak boleh sebelum hapus buku ("+l.writeoff.date+")");
 if(!(a>0))throw fe("pm-a","Jumlah harus lebih dari nol");if(!c)throw fe("pm-c","Pilih kas/bank");
 const t=post({type:"loan_rec",date:d,unit:l.unit_id,desc:"Pemulihan "+l.loan_number+" – "+party(l.party_id).name,lines:[{acc:c.account_id,d:a},{acc:"ACC4600",c:a}]});
 l.recoveries.push({_id:uid("RC"),date:d,amount:a,cash_id:c._id,txn_id:t._id,note:v("pm-n"),by:(curUser()||{}).name||null,status:"posted"});audit("pemulihan","loan",id,"Rp "+fm(a));save();okM();S.eld=id;S.md="ld";S.msg="Pemulihan Rp "+fm(a)+" dicatat"}catch(e){mErr(e);return}render()}
function batalPulih(id){try{const l=db.loans.find(x=>(x.recoveries||[]).some(r=>r._id===id));if(!l)throw Error("Pemulihan tidak ditemukan");const r=l.recoveries.find(x=>x._id===id);if(r.status!=="posted")throw Error("Pemulihan sudah dibatalkan");rev(r.txn_id);r.status="voided";audit("batal_pemulihan","loan",l._id,"Rp "+fm(r.amount));save();S.msg="Pemulihan dibatalkan dengan jurnal pembalik"}catch(e){S.msg="⚠ "+e.message}render()}
function batalHapus(id){try{const l=db.loans.find(x=>x._id===id);if(!l||l.status!=="written_off")throw Error("Pinjaman tidak dalam status dihapus buku");if((l.recoveries||[]).some(r=>r.status==="posted"))throw Error("Batalkan semua pemulihan lebih dulu");
 rev(l.writeoff.txn_id);goLoan(l,"active");audit("batal_hapus_buku","loan",id,"Rp "+fm(l.writeoff.amount));delete l.writeoff;save();S.msg="Hapus buku dibatalkan; pinjaman kembali aktif"}catch(e){S.msg="⚠ "+e.message}render()}
// ----- tampilan -----
function rsBtns(l){let h="";if(l.status==="active"){h+=l.restruk_prop&&restrukDua(l)?ib("check","Setujui restrukturisasi","mdOpen('rs','"+l._id+"')","s")+ib("undo","Tolak usulan restrukturisasi","askC('tolakRestruk','"+l._id+"')","s"):ib("edit",restrukDua(l)?"Usulkan restrukturisasi":"Restrukturisasi","mdOpen('rs','"+l._id+"')","s");if(kolOf(l).k>=4)h+=l.writeoff_prop&&hapusDua()?ib("check","Setujui hapus buku","mdOpen('hb','"+l._id+"')","x")+ib("undo","Tolak usulan","askC('tolakHapus','"+l._id+"')","s"):ib("x",hapusDua()?"Usulkan hapus buku":"Hapus buku","mdOpen('hb','"+l._id+"')","x")}
 else if(l.status==="written_off"){h+=ib("cash","Catat pemulihan","mdOpen('pm','"+l._id+"')");if(!(l.recoveries||[]).some(r=>r.status==="posted"))h+=ib("undo","Batalkan hapus buku","askC('batalHapus','"+l._id+"')","x")}return h}
function rsHist(l){let h="";if(l.restruk_prop&&restrukDua(l)){const q=l.restruk_prop;h+=`<p class="k">Usulan restrukturisasi dari <b>${esc(q.by||"-")}</b> (${q.date}): jasa ${q.rate}% ${esc(rsMeth[q.method]||q.method)}, ${q.tenor} bln. Menunggu persetujuan pengguna lain.</p>`}const R=l.restructures||[];if(R.length)h+=`<details class="sx"><summary>Riwayat restrukturisasi <span class="stc">${R.length}</span></summary>${R.slice().reverse().map((x,i0)=>`<div class="ph"><span><b>${x.date}</b> · ${x.old.rate}% ${esc(rsMeth[x.old.method]||x.old.method)} → ${x.new.rate}% ${esc(rsMeth[x.new.method]||x.new.method)}, ${x.new.tenor} bln<small>Sisa pokok Rp ${fm(x.new.sisa)} · jadwal lama ${x.old.count} angsuran diarsipkan${x.old.arrears_int+x.old.arrears_pen?" · jasa/denda tertunggak dihapus Rp "+fm(x.old.arrears_int+x.old.arrears_pen):""}${x.fee?" · biaya Rp "+fm(x.fee)+(x.fee_tax?" + pajak Rp "+fm(x.fee_tax):""):""} — ${esc(x.reason)}${x.by?" · "+esc(x.by):""}</small></span>${i0===0&&canUndoRs(l)?`<span class="pa">${ib("undo","Batalkan","askC('batalRestruk','"+l._id+"')","x")}</span>`:""}</div>`).join("")}</details>`;
 if(l.writeoff_prop)h+=`<div class="card ldt"><div class="k">Usulan hapus buku ${l.writeoff_prop.date}: Rp ${fm(l.writeoff_prop.amount)} — menunggu persetujuan</div><small>${esc(l.writeoff_prop.reason)}${l.writeoff_prop.by?" · diusulkan "+esc(l.writeoff_prop.by):""}</small></div>`;
 if(l.writeoff){const rc=(l.recoveries||[]);h+=`<div class="card ldt"><div class="k">Dihapus buku ${l.writeoff.date}: Rp ${fm(l.writeoff.amount)}</div><small>${esc(l.writeoff.reason)}${l.writeoff.proposed_by?" · diusulkan "+esc(l.writeoff.proposed_by):""}${l.writeoff.by?" · disetujui "+esc(l.writeoff.by):""}</small></div>${rc.length?`<details class="sx" open><summary>Pemulihan <span class="stc">${rc.length}</span></summary>${rc.map(r=>`<div class="ph"><span><b>${r.date}</b> · Rp ${fm(r.amount)}<small>${esc(r.note||"")}${r.status==="voided"?" (Dibatalkan)":""}</small></span><span class="pa">${r.status==="posted"?ib("undo","Batalkan","askC('batalPulih','"+r._id+"')","x"):""}</span></div>`).join("")}</details>`:""}`}return h}
const _rsEx=()=>{};
MK.rs="ers";MK.hb="ehb";MK.pm="epm";
MD.rs=()=>{const l=db.loans.find(x=>x._id===S.ers);if(!l||l.status!=="active")return{t:"Restrukturisasi",s:"mdClose()",y:"Tutup",b:"<p>Hanya pinjaman aktif yang dapat direstrukturisasi.</p>",nf:1};const d=today(),out=rsOut(l),A=rsArrears(l,d),o=kolOf(l),codes=[...new Set(rateRows().filter(r=>r.fee_type==="restruk").map(r=>r.fee_code))];
 const pr=restrukDua(l)?l.restruk_prop:null;return{t:(pr?"Setujui restrukturisasi · ":restrukDua(l)?"Usulkan restrukturisasi · ":"Restrukturisasi · ")+l.loan_number,s:"saveRestruk()",y:pr?"Setujui restrukturisasi":restrukDua(l)?"Kirim usulan":"Restrukturisasi",b:(restrukDua(l)?`<p class="k">Aturan dua orang aktif: ${pr?"usulan dari <b>"+esc(pr.by||"-")+"</b> ("+pr.date+") harus disetujui pengguna lain; isian terisi dari usulan dan boleh disesuaikan.":"usulan harus disetujui pengguna lain; jadwal baru dibuat saat disetujui."}</p>`:"")+`<p class="k">${esc(party(l.party_id).name)} · ${o.label}${o.days>0?" · terlambat "+o.days+" hari":""}. Sisa pokok <b>Rp ${fm(out)}</b> dijadwalkan ulang; jadwal lama diarsipkan (tidak dihapus dari riwayat). Jasa tertunggak Rp ${fm(A.int)} dan denda Rp ${fm(A.pen)} belum dibukukan sebagai pendapatan.</p>`
  +fld("rs-d","Tanggal restrukturisasi",{type:"date",value:pr?pr.date:d,req:1})+fld("rs-r","Jasa baru (% per tahun)",{a:' inputmode="decimal" autocomplete="off"',value:String(pr?pr.rate:l.interest_rate).replace(".",","),req:1})+fld("rs-t","Tenor baru (bulan)",{a:' inputmode="numeric" autocomplete="off"',value:pr?String(pr.tenor):"",req:1})
  +fld("rs-m","Metode jasa",{t:"select",opts:opt(Object.entries(rsMeth),x=>x,pr?pr.method:l.interest_method)})+fld("rs-a","Jasa dan denda tertunggak",{t:"select",hint:"Dihapuskan = tidak ditagih lagi (belum dibukukan). Bayar dulu = restrukturisasi ditolak bila masih ada.",opts:opt([["hapus","Dihapuskan"],["bayar","Bayar dulu"]],x=>x,pr?pr.ar:A.int+A.pen>0?"hapus":"bayar")})
  +(codes.length?fld("rs-f","Biaya restrukturisasi",{t:"select",hint:"Dari Master > Tarif & Pajak (jenis Restrukturisasi); masuk akun 4400. Bila tarif dikenai pajak, pajak ditambahkan dan masuk akun 2220.",opts:'<option value="">Tanpa biaya</option>'+opt(codes,x=>[x,x],pr?pr.fee_code||"":"")})+fld("rs-c","Kas/Bank untuk biaya",{t:"select",opts:opt(db.cash_accounts.filter(isAct),c=>[c._id,c.name],pr&&pr.cash_id?pr.cash_id:"CASH-001")}):`<input type="hidden" id="rs-f" value=""><input type="hidden" id="rs-c" value="">`)+fld("rs-n","Alasan *",{value:pr?pr.reason:"",req:1})}};
MD.hb=()=>{const l=db.loans.find(x=>x._id===S.ehb);if(!l)return{t:"Hapus buku",s:"mdClose()",y:"Tutup",b:"<p>Pinjaman tidak ditemukan.</p>",nf:1};const o=kolOf(l);
 const pr=hapusDua()?l.writeoff_prop:null;return{t:(pr?"Setujui hapus buku · ":hapusDua()?"Usulkan hapus buku · ":"Hapus buku · ")+l.loan_number,s:"saveHapus()",y:pr?"Setujui hapus buku":hapusDua()?"Kirim usulan":"Hapus buku",b:(hapusDua()?`<p class="k">Aturan dua orang aktif: ${pr?"usulan dari <b>"+esc(pr.by||"-")+"</b> harus disetujui pengguna lain.":"usulan harus disetujui pengguna lain; jurnal baru dibuat saat disetujui."}</p>`:"")+`<p class="k">${esc(party(l.party_id).name)} · ${o.label} · terlambat ${o.days} hari. Sisa pokok <b>Rp ${fm(rsOut(l))}</b> dikeluarkan dari piutang sebagai beban kerugian (Dr 5700, Cr 1300). Pinjaman berstatus Dihapus buku; pemulihan sesudahnya dicatat sebagai pendapatan. Hanya untuk kolektibilitas Macet.</p>`+fld("hb-d","Tanggal",{type:"date",value:today(),req:1})+fld("hb-n","Alasan *",{value:pr?pr.reason:"",req:1})}};
MD.pm=()=>{const l=db.loans.find(x=>x._id===S.epm);if(!l||l.status!=="written_off")return{t:"Pemulihan",s:"mdClose()",y:"Tutup",b:"<p>Pinjaman tidak dalam status dihapus buku.</p>",nf:1};
 return{t:"Pemulihan · "+l.loan_number,s:"savePulih()",y:"Catat pemulihan",b:`<p class="k">${esc(party(l.party_id).name)}. Uang yang diterima dari pinjaman yang sudah dihapus buku dicatat sebagai pendapatan pemulihan piutang (akun 4600).</p>`+fld("pm-d","Tanggal",{type:"date",value:today(),req:1})+fld("pm-a","Jumlah (Rp)",{a:RPA,req:1,value:""})+fld("pm-c","Kas/Bank",{t:"select",opts:opt(db.cash_accounts.filter(isAct),c=>[c._id,c.name],"CASH-001")})+fld("pm-n","Catatan",{value:""})}};
