// ===== TABUNGAN NASABAH (v1.1.014): rekening, setoran, penarikan, bunga; jurnal ke akun 2300 (liabilitas) =====
// Uang tabungan nasabah adalah utang BUMDes ke nasabah (bukan modal). Saldo = setoran + bunga - penarikan (mutasi berstatus posted).
function ensureSavAcc(d){if(!Array.isArray(d.accounts))return;const add=(c,n,t)=>{if(!d.accounts.some(a=>a.code===c))d.accounts.push({_id:"ACC"+c,code:c,name:n,type:t,parent_id:"ACC"+c[0]+"000",status:"aktif"})};add("2300","Tabungan Nasabah","liability");add("5600","Beban Bunga Tabungan","expense");add("2210","Utang Pajak Bunga Tabungan","liability");add("4500","Pendapatan Administrasi Tabungan","revenue");add("5700","Beban Kerugian Piutang","expense");add("4600","Pendapatan Pemulihan Piutang","revenue");add("2220","Utang Pajak atas Biaya Pinjaman","liability");add("2230","Utang Pajak atas Biaya Tabungan","liability");add("2240","Pendapatan Fee Ditangguhkan","liability")}
const SAV_T={setor:"Setoran",tarik:"Penarikan",bunga:"Bunga tabungan",biaya:"Biaya administrasi"},SAV_SIGN={setor:1,bunga:1,tarik:-1,biaya:-1};
const savAccs=()=>db.savings_accounts||[],savTxOf=id=>(db.savings_tx||[]).filter(x=>x.account_id===id),
 savLive=id=>savTxOf(id).filter(x=>x.status==="posted").sort((a,b)=>a.date<b.date?-1:a.date>b.date?1:0),
 savBal=id=>savLive(id).reduce((s,x)=>s+SAV_SIGN[x.type]*x.amount,0),
 savTotal=()=>savAccs().reduce((s,a)=>s+savBal(a._id),0),
 savLast=id=>savLive(id).reduce((m,x)=>x.date>m?x.date:m,"");
function savRun(id,skip){let b=0;return savLive(id).filter(x=>x._id!==skip).map(x=>{b+=SAV_SIGN[x.type]*x.amount;return{x,b}})}
function savNo(){return numNext("tab",today())}
function savCheck(){const a=acc("ACC2300"),g=a?net(a,bal(()=>true)):0,s=savTotal();return{g,s,ok:Math.round(g)===Math.round(s)}}

// ----- pengaturan bunga, biaya, pajak (v1.1.017) -----
const savCfg=()=>Object.assign({rate:0,admin_code:"",tax_code:"",tax_min:0,tiers:[],prods:[]},(db.settings&&db.settings.sav)||{});
// bunga bertingkat (v1.1.023): seluruh saldo harian memakai tarif tingkat tertinggi yang tercapai; di bawah tingkat pertama = bunga dasar
const savTiers=()=>(savCfg().tiers||[]).slice().sort((a,b)=>a.min-b.min),savRateAt=b=>{let r=savCfg().rate;savTiers().forEach(t=>{if(b>=t.min)r=t.rate});return r};
function savInt(a,ym){const n=+eom(ym).slice(8),tx=savLive(a._id);let s=0;for(let d=1;d<=n;d++){const day=ym+"-"+String(d).padStart(2,"0");let b=0;tx.forEach(x=>{if(x.date<=day)b+=SAV_SIGN[x.type]*x.amount});if(a.opened_at<=day&&b>0)s+=b*savRate(a,b)/100/365}return rd0(s)}
function addSavTier(){try{const mn=Math.round(+pn($("#sv-tmin").value)||0),rt=Number(pn($("#sv-trate").value));if(!(mn>0))throw fe("sv-tmin","Saldo minimum tingkat harus lebih dari nol");if(!Number.isFinite(rt)||String($("#sv-trate").value).trim()===""||rt<0||rt>100)throw fe("sv-trate","Bunga tingkat 0–100% per tahun");
 const T=savTiers();if(T.some(t=>t.min===mn))throw fe("sv-tmin","Sudah ada tingkat dengan saldo minimum itu");db.settings.sav=Object.assign({},savCfg(),{tiers:[...T,{min:mn,rate:rt}].sort((a,b)=>a.min-b.min)});audit("setting","settings","sav","tingkat bunga: saldo ≥ Rp "+fm(mn)+" → "+rt+"%");save();S.msg="Tingkat bunga ditambahkan";S.fe=null}catch(e){S.msg="⚠ "+e.message;S.fe=e.f?{id:e.f,m:e.message}:null}render()}
function delSavTier(i){try{const T=savTiers();if(!T[i])throw Error("Tingkat tidak ditemukan");const t=T[i];db.settings.sav=Object.assign({},savCfg(),{tiers:T.filter((x,k)=>k!==i)});audit("setting","settings","sav","tingkat bunga dihapus: saldo ≥ Rp "+fm(t.min));save();S.msg="Tingkat bunga dihapus"}catch(e){S.msg="⚠ "+e.message}render()}
// produk tabungan / deposito (v1.1.037)
const savProds=()=>(savCfg().prods||[]),savRate=(a,b)=>a.prod&&Number.isFinite(a.prod.rate)?a.prod.rate:savRateAt(b),savLock=a=>a.prod&&a.prod.term>0&&a.maturity?a.maturity:"";
function addSavProd(){try{const nm=$("#sv-pn").value.trim(),rt=Number(pn($("#sv-pr").value)),tm=Number(pn($("#sv-pt").value||"0"));if(!nm)throw fe("sv-pn","Nama produk wajib diisi");if(nm.length>40)throw fe("sv-pn","Nama produk maksimal 40 karakter");
 if(savProds().some(p=>p.name.toLowerCase()===nm.toLowerCase()))throw fe("sv-pn","Sudah ada produk dengan nama itu");if(String($("#sv-pr").value).trim()===""||!Number.isFinite(rt)||rt<0||rt>100)throw fe("sv-pr","Bunga produk 0–100% per tahun");
 if(!Number.isInteger(tm)||tm<0||tm>120)throw fe("sv-pt","Jangka 0–120 bulan (0 = tanpa jangka)");
 db.settings.sav=Object.assign({},savCfg(),{prods:[...savProds(),{id:uid("SPR"),name:nm,rate:rt,term:tm}]});audit("setting","settings","sav","produk tabungan: "+nm+" · "+rt+"%"+(tm>0?" · jangka "+tm+" bln":""));save();S.msg="Produk "+nm+" ditambahkan";S.fe=null}catch(e){S.msg="⚠ "+e.message;S.fe=e.f?{id:e.f,m:e.message}:null}render()}
function delSavProd(id){try{const p=savProds().find(x=>x.id===id);if(!p)throw Error("Produk tidak ditemukan");db.settings.sav=Object.assign({},savCfg(),{prods:savProds().filter(x=>x.id!==id)});audit("setting","settings","sav","produk tabungan dihapus: "+p.name);save();S.msg="Produk dihapus; rekening yang sudah dibuka tidak berubah"}catch(e){S.msg="⚠ "+e.message}render()}
// cetak buku tabungan
function vBuku(id){const bar=`<div class="noprint"><button class="b" onclick="window.print()">Cetak</button><button class="b s" onclick="S.doc=null;render()">Kembali</button></div>`,a=savAccs().find(x=>x._id===id);if(!a)return bar+'<p class="k">Rekening tidak ditemukan.</p>';
 const pt=party(a.party_id),run=savRun(a._id),R=(k,v)=>`<tr><td>${k}</td><td class="n">${v}</td></tr>`;
 return`${bar}<div class="doc">${kop()}<h3>BUKU TABUNGAN</h3><div class="cn">No. ${esc(a.number)} · dicetak ${today()}</div><table>${R("Nasabah",esc(pt.name))}${R("Produk",esc(a.product))}${a.prod?R("Bunga produk",String(a.prod.rate).replace(".",",")+"% per tahun"):""}${savLock(a)?R("Jatuh tempo",savLock(a)+(savLock(a)>today()?" (belum jatuh tempo)":" (sudah jatuh tempo)")):""}${R("Dibuka",a.opened_at)}${R("Status",a.status==="aktif"?"Aktif":"Ditutup")}</table>
${run.length?tbl(["Tanggal","Keterangan","#Kredit","#Debit","#Saldo"],run.map(r=>`<tr><td>${r.x.date}</td><td>${esc(SAV_T[r.x.type]||r.x.type)}${r.x.desc?" · "+esc(r.x.desc):""}</td><td class="n">${SAV_SIGN[r.x.type]>0?rp(r.x.amount):""}</td><td class="n">${SAV_SIGN[r.x.type]<0?rp(r.x.amount):""}</td><td class="n">${rp(r.b)}</td></tr>`)):'<p class="k">Belum ada mutasi.</p>'}
<table><tr><th>Saldo akhir</th><th class="n">${rp(savBal(a._id))}</th></tr></table>${sig([["Nasabah",pt.name],["Petugas",petugas()]],0,today())}</div>`}
function savTax(gross,d){const c=savCfg();if(!c.tax_code||gross<=0||gross<=(+c.tax_min||0))return{tax:0,code:"",rate:0};const t=taxAt(c.tax_code,d);if(!t)return{tax:0,code:"",rate:0};return{tax:rd0(gross*(+t.tax_rate||0)/100),code:c.tax_code,rate:+t.tax_rate||0}}
function setSav(k,v){try{if(!["rate","admin_code","tax_code","tax_min"].includes(k))throw Error("Pengaturan tidak dikenal");let x=v;if(k==="rate"||k==="tax_min"){x=Number(pn(v));if(String(v).trim()===""||!Number.isFinite(x)||x<0)throw Error("Isi angka nol atau lebih");if(k==="rate"&&x>100)throw Error("Bunga per tahun maksimal 100%")}
 db.settings.sav=Object.assign({},savCfg(),{[k]:x});audit("setting","settings","sav",k+": "+x);save();S.msg="Pengaturan tabungan disimpan"}catch(e){S.msg="⚠ "+e.message}render()}
const eom=ym=>{const[y,m]=ym.split("-").map(Number);return new Date(Date.UTC(y,m,0)).toISOString().slice(0,10)},ymList=()=>{const t=today(),o=[];let y=+t.slice(0,4),m=+t.slice(5,7);for(let i=0;i<12;i++){m--;if(m<1){m=12;y--}o.push(y+"-"+String(m).padStart(2,"0"))}return o};
function savDaily(a,ym){const n=+eom(ym).slice(8),tx=savLive(a._id);let s=0;for(let d=1;d<=n;d++){const day=ym+"-"+String(d).padStart(2,"0");let b=0;tx.forEach(x=>{if(x.date<=day)b+=SAV_SIGN[x.type]*x.amount});if(a.opened_at<=day)s+=b}return s}
function savPlan(ym){const c=savCfg(),d=eom(ym),P={ym,date:d,bunga:[],biaya:[],skip:[],ok:true};if(!/^\d{4}-\d{2}$/.test(ym)||d>=today())return{...P,ok:false,why:"Bulan belum berakhir"};
 savAccs().filter(a=>a.status==="aktif"&&a.opened_at<=d&&(S.unit==="all"||a.unit_id===S.unit)).forEach(a=>{const has=t=>savTxOf(a._id).some(x=>x.type===t&&x.period===ym&&x.status==="posted");
  if((c.rate>0||c.tiers.length||(a.prod&&a.prod.rate>0))&&!has("bunga")){const g=savInt(a,ym);if(g>0){const t=savTax(g,d);P.bunga.push({a,gross:g,tax:t.tax,code:t.code,net:g-t.tax})}}
  if(c.admin_code&&!has("biaya")){const bl=savBalAt(a._id,d),fr=calcFees({date:d,codes:[c.admin_code],bulan:1,saldo:bl}),f=fr.fee_total,ft=fr.tax_total||0;if(f>0){if(bl-f-ft>=(a.min_balance||0))P.biaya.push({a,fee:f,tax:ft});else P.skip.push({a,fee:f+ft})}}});return P}
const savBalAt=(id,d)=>savLive(id).filter(x=>x.date<=d).reduce((s,x)=>s+SAV_SIGN[x.type]*x.amount,0);
function prosesSav(){try{const ym=S.svm||ymList()[0],P=savPlan(ym);if(!P.ok)throw Error(P.why||"Bulan tidak valid");if(!P.bunga.length&&!P.biaya.length)throw Error("Tidak ada bunga atau biaya yang perlu diproses untuk "+ym);
 P.bunga.forEach(r=>{const lines=[{acc:"ACC5600",d:r.gross},{acc:"ACC2300",c:r.net}];if(r.tax>0)lines.push({acc:"ACC2210",c:r.tax});
  const t=post({type:"sav_int",date:P.date,unit:r.a.unit_id,desc:"Bunga "+ym+" "+r.a.number+" – "+party(r.a.party_id).name,lines});db.savings_tx.push({...byN(),_id:uid("STX"),account_id:r.a._id,type:"bunga",date:P.date,amount:r.net,gross:r.gross,tax:r.tax,tax_code:r.code,period:ym,txn_id:t._id,cash_id:null,desc:"otomatis "+ym,status:"posted",created_at:now()})});
 P.biaya.forEach(r=>{const t=post({type:"sav_fee",date:P.date,unit:r.a.unit_id,desc:"Biaya administrasi "+ym+" "+r.a.number+" – "+party(r.a.party_id).name,lines:[{acc:"ACC2300",d:r.fee+r.tax},{acc:"ACC4500",c:r.fee},...(r.tax>0?[{acc:"ACC2230",c:r.tax}]:[])]});db.savings_tx.push({_id:uid("STX"),account_id:r.a._id,type:"biaya",date:P.date,amount:r.fee+r.tax,fee:r.fee,tax:r.tax,period:ym,txn_id:t._id,cash_id:null,desc:"otomatis "+ym,status:"posted",created_at:now()})});
 audit("sav_proses","savings_account",ym,P.bunga.length+" bunga, "+P.biaya.length+" biaya, "+P.skip.length+" dilewati");save();S.msg="Proses "+ym+": bunga "+P.bunga.length+" rekening (Rp "+fm(P.bunga.reduce((s,r)=>s+r.net,0))+" bersih), biaya "+P.biaya.length+" rekening"+(P.skip.length?", "+P.skip.length+" dilewati (saldo kurang)":"")}catch(e){S.msg="⚠ "+e.message}render()}
function saveSavAcc(){try{const v=i=>$("#"+i).value.trim(),p=db.parties.find(x=>x._id===v("sa-p")),u=db.business_units.find(x=>x._id===v("sa-u")),d=v("sa-d"),pr=v("sa-n")||"Tabungan",mn=Math.round(+pn(v("sa-m"))||0);
 if(!p||p.type!=="nasabah")throw fe("sa-p","Pilih nasabah (tambahkan nasabah jika belum ada)");if(p.status==="nonaktif")throw fe("sa-p","Nasabah nonaktif");
 if(!u)throw fe("sa-u","Pilih unit Simpan Pinjam");if(!isD(d))throw fe("sa-d","Tanggal buka tidak valid");if(d>today())throw fe("sa-d","Tanggal buka tidak boleh melewati hari ini");
 if(mn<0)throw fe("sa-m","Saldo minimum tidak boleh negatif");
 if(savAccs().some(a=>a.party_id===p._id&&a.product===pr&&a.status==="aktif"))throw fe("sa-n","Nasabah ini sudah punya rekening aktif dengan produk yang sama");
 const sp=savProds().find(x=>x.name===pr),a={_id:uid("SAV"),number:savNo(),party_id:p._id,unit_id:u._id,product:pr,min_balance:mn,opened_at:d,status:"aktif",created_at:now(),...(sp?{prod:{id:sp.id,name:sp.name,rate:sp.rate,term:sp.term},maturity:sp.term>0?addM(d,sp.term):null}:{})};
 db.savings_accounts.push(a);audit("create","savings_account",a._id,a.number+" · "+p.name);save();okM();mdOpen("sv",a._id);S.msg="Rekening "+a.number+" dibuka";render();return}catch(e){mErr(e)}}

function saveSavTx(){try{const[ty,id]=String(S.est||"").split("|"),a=savAccs().find(x=>x._id===id),v=i=>$("#"+i).value.trim();
 if(!a||!SAV_T[ty])throw Error("Rekening tidak ditemukan");if(a.status!=="aktif")throw Error("Rekening sudah ditutup");
 negAny();const d=v("st-d"),m=Math.round(+pn(v("st-a"))||0),c=db.cash_accounts.find(x=>x._id===v("st-c")),ds=v("st-s");
 if(!isD(d))throw fe("st-d","Tanggal tidak valid");if(d>today())throw fe("st-d","Tanggal tidak boleh melewati hari ini");if(d<a.opened_at)throw fe("st-d","Tanggal tidak boleh sebelum tanggal buka rekening ("+a.opened_at+")");
 const lt=savLast(a._id);if(lt&&d<lt)throw fe("st-d","Tanggal tidak boleh mendahului mutasi terakhir ("+lt+")");
 if(!(m>0))throw fe("st-a","Jumlah harus lebih dari nol");
 if(savLock(a)){if(ty==="tarik"&&d<a.maturity)throw fe("st-d","Deposito belum jatuh tempo ("+a.maturity+")");if(ty==="setor"&&savLive(a._id).some(x=>x.type==="setor"))throw fe("st-a","Deposito tidak menerima setoran tambahan")}
 const pt=party(a.party_id).name,sk=savBal(a._id);let lines,bx=null;
 if(ty!=="bunga"&&!c)throw fe("st-c","Pilih kas/bank");
 if(ty==="setor")lines=[{acc:c.account_id,d:m},{acc:"ACC2300",c:m}];
 else if(ty==="tarik"){const tl=twLocked(a._id),av=Math.max(0,sk-(a.min_balance||0)-tl);if(m>av)throw fe("st-a","Penarikan melebihi saldo yang dapat ditarik (Rp "+fm(av)+")"+(tl>0?" — Rp "+fm(tl)+" tabungan wajib terkunci sampai pinjaman lunas":""));
  const ks=net(acc(c.account_id),bal(()=>true));if(ks<m)throw fe("st-c","Saldo kas/bank tidak cukup (tersedia Rp "+fm(ks)+")");lines=[{acc:"ACC2300",d:m},{acc:c.account_id,c:m}]}
 else{const tx=savTax(m,d);lines=[{acc:"ACC5600",d:m},{acc:"ACC2300",c:m-tx.tax}];if(tx.tax>0)lines.push({acc:"ACC2210",c:tx.tax});bx=tx}
 const t=post({type:"sav_"+ty,date:d,unit:a.unit_id,desc:SAV_T[ty]+" "+a.number+" – "+pt+(ds?" ("+ds+")":""),lines});
 db.savings_tx.push({...byN(),_id:uid("STX"),account_id:a._id,type:ty,date:d,amount:bx?m-bx.tax:m,gross:bx?m:undefined,tax:bx?bx.tax:undefined,tax_code:bx?bx.code:undefined,txn_id:t._id,cash_id:c?c._id:null,desc:ds,status:"posted",created_at:now()});
 audit("sav_"+ty,"savings_account",a._id,a.number+" · Rp "+fm(m)+(bx&&bx.tax?" (pajak Rp "+fm(bx.tax)+")":""));save();okM();mdOpen("sv",a._id);S.msg=SAV_T[ty]+" Rp "+fm(m)+" tercatat";render();return}catch(e){mErr(e)}}

function batalSav(id){try{const x=(db.savings_tx||[]).find(q=>q._id===id);if(!x)throw Error("Mutasi tidak ditemukan");if(x.status!=="posted")throw Error("Mutasi sudah dibatalkan");if(x.via==="pencairan")throw Error("Setoran ini dibuat saat pencairan pinjaman; batalkan lewat Batalkan pencairan di pinjamannya");
 const bad=savRun(x.account_id,x._id).find(r=>r.b<0);if(bad)throw Error("Tidak bisa dibatalkan: saldo tabungan menjadi negatif pada "+bad.x.date+". Batalkan mutasi yang lebih baru lebih dulu.");
 rev(x.txn_id);x.status="reversed";x.reversed_at=now();audit("sav_batal","savings_account",x.account_id,SAV_T[x.type]+" Rp "+fm(x.amount));save();S.msg="Mutasi tabungan dibatalkan dengan jurnal pembalik"}catch(e){S.msg="⚠ "+e.message}render()}

function tutupSav(id){try{const a=savAccs().find(x=>x._id===id);if(!a)throw Error("Rekening tidak ditemukan");if(a.status!=="aktif")throw Error("Rekening sudah ditutup");
 if(Math.round(savBal(id))!==0)throw Error("Rekening hanya dapat ditutup bila saldo nol (saldo Rp "+fm(savBal(id))+")");a.status="ditutup";a.closed_at=today();audit("sav_tutup","savings_account",id,a.number);save();S.msg="Rekening "+a.number+" ditutup"}catch(e){S.msg="⚠ "+e.message}render()}
function bukaSav(id){try{const a=savAccs().find(x=>x._id===id);if(!a)throw Error("Rekening tidak ditemukan");if(a.status==="aktif")throw Error("Rekening masih aktif");
 if(savAccs().some(x=>x._id!==id&&x.party_id===a.party_id&&x.product===a.product&&x.status==="aktif"))throw Error("Nasabah sudah punya rekening aktif dengan produk yang sama");
 a.status="aktif";delete a.closed_at;audit("sav_buka","savings_account",id,a.number);save();S.msg="Rekening "+a.number+" dibuka kembali"}catch(e){S.msg="⚠ "+e.message}render()}

// ----- tampilan -----
function vTabungan(){const q=(S.tq||"").toLowerCase(),fs=S.tfs||"",U=a=>S.unit==="all"||a.unit_id===S.unit,all=savAccs().filter(U),
 L=all.filter(a=>(!fs||a.status===fs)&&(!q||(a.number+" "+party(a.party_id).name+" "+a.product).toLowerCase().includes(q))).sort((x,y)=>x.number<y.number?1:-1),
 tot=all.filter(a=>a.status==="aktif").reduce((s,a)=>s+savBal(a._id),0),ck=savCheck();
 return`<h2>Tabungan nasabah</h2>${addB("Buka rekening","sa")}<div class="g dk"><div class="card kp"><div class="kh"><span class="kic t6">${ic("user")}</span><span class="k">Total tabungan nasabah</span></div><div class="v">${rp(tot)}</div><div class="s2">${all.filter(a=>a.status==="aktif").length} rekening aktif · utang BUMDes ke nasabah</div></div></div>
${savProc()}
${dcard("Daftar Rekening",(L.length<all.length?L.length+" dari "+all.length:all.length)+" rekening",`<div class="fl"><input type="search" placeholder="Cari no / nasabah / produk…" aria-label="Cari rekening" value="${esc(S.tq||"")}" onchange="S.tq=this.value;render()"><select aria-label="Filter status rekening" onchange="S.tfs=this.value;render()"><option value="">Semua status</option><option value="aktif"${fs==="aktif"?" selected":""}>Aktif</option><option value="ditutup"${fs==="ditutup"?" selected":""}>Ditutup</option></select>${q||fs?`<button class="b s" onclick="S.tq='';S.tfs='';render()">Reset</button>`:""}</div>
${L.length?`<div class="upl">${L.slice(0,pgLim("tab")).map((a,n)=>{const nm=party(a.party_id).name,ml=savLast(a._id);return`<button class="upr snr" onclick="mdOpen('sv','${a._id}')"><span class="bi" style="background:var(--c${n%6+1})" aria-hidden="true">${esc((nm||"?").trim().charAt(0).toUpperCase())}</span><span class="upm"><b>${esc(nm)}</b><small>${esc(a.number)} · ${esc(a.product)}${savLock(a)?" (s.d. "+savLock(a)+")":""} · ${esc(unitName(a.unit_id))}${ml?" · mutasi "+ml:""}</small></span><span class="upa"><small>saldo</small><b>${rp(savBal(a._id))}</b><span class="bdg ${a.status==="aktif"?"ok":""}">${a.status==="aktif"?"Aktif":"Ditutup"}</span></span></button>`}).join("")}</div>${pgMore("tab",L.length)}`:`<div class="empty"><p>${all.length?"Tidak ada rekening yang cocok.":"Belum ada rekening tabungan. Buka rekening untuk nasabah."}</p></div>`}
<p class="k">${ck.ok?"✓ Total saldo sama dengan akun 2300 Tabungan Nasabah di buku besar":"⚠ Saldo rekening (Rp "+fm(ck.s)+") berbeda dari akun 2300 (Rp "+fm(ck.g)+"); biasanya karena jurnal manual ke akun 2300"}.</p>`,"")}`}
function savProc(){const c=savCfg(),ms=ymList(),m=S.svm||ms[0];if(!(c.rate>0||c.admin_code||c.tiers.length||c.prods.some(p=>p.rate>0)))return dcard("Proses akhir bulan","Bunga dan biaya administrasi bulanan",`<p class="k">Bunga dan biaya administrasi bulanan belum diatur. Atur di Setelan > Tabungan dan di Master > Tarif & Pajak.</p>`);
 return dcard("Proses akhir bulan","Hitung bunga dan biaya administrasi untuk satu bulan",`<div class="fl"><select aria-label="Bulan proses" onchange="S.svm=this.value;render()">${opt(ms,x=>[x,x],m)}</select><button class="b" onclick="askC('prosesSav','')">Proses bunga dan biaya akhir bulan</button></div>`)}
const savOf=pid=>savAccs().filter(a=>a.party_id===pid&&a.status==="aktif").reduce((s,a)=>s+savBal(a._id),0),nasSavTxt=p=>{const v=savOf(p._id);return v>0?" · Tab. Rp "+fm(v):""};
function nasSavHtml(p){const L=savAccs().filter(a=>a.party_id===p._id).sort((a,b)=>a.status===b.status?0:a.status==="aktif"?-1:1);return`<h3>Tabungan</h3>`+(L.length?`<div class="ll">${L.map(a=>`<button class="li" onclick="mdOpen('sv','${a._id}')"><span class="l1"><b>${esc(a.number)}</b><small>${esc(a.product)}</small></span><span class="l2">${esc(unitName(a.unit_id))}</span><span class="n l3">${rp(savBal(a._id))}</span><span class="n l4"></span><span class="l5"><span class="bdg ${a.status==="aktif"?"ok":""}">${a.status==="aktif"?"Aktif":"Ditutup"}</span></span><span class="l6">${ic("next")}</span></button>`).join("")}</div>`:`<p class="k">Belum ada rekening tabungan.</p>`)+(p.status!=="nonaktif"?`<div class="lda">${ib("plus","Buka rekening","mdOpen('sa','"+p._id+"')","s")}</div>`:"")}
function savMonth(){const ym=today().slice(0,7);let i=0,o=0;(db.savings_tx||[]).forEach(x=>{if(x.status==="posted"&&x.date.slice(0,7)===ym){if(x.type==="setor")i+=x.amount;if(x.type==="tarik")o+=x.amount}});return{i,o}}
function savCard(){const n=savAccs().filter(a=>a.status==="aktif").length;const lk=can("sp.data")||can("sp.bayar"),bd=`<div class="kh"><span class="kic t6">${ic("user")}</span><span class="k">Tabungan nasabah</span></div><div class="v">${rp(savTotal())}</div><div class="s2">${n?n+" rekening aktif · bulan ini +"+fm(savMonth().i)+" / −"+fm(savMonth().o):"Belum ada rekening"}</div>`;return lk?`<button class="card kp" onclick="goS('sp',{st:'tabungan'})">${bd}</button>`:`<div class="card kp">${bd}</div>`}

MK.sa="esa";MK.sv="esv";MK.st="est";
MD.sa=()=>{const ns=db.parties.filter(p=>p.type==="nasabah"&&p.status!=="nonaktif"),us=db.business_units.filter(u=>u.type==="simpan_pinjam"&&isAct(u));
 return{t:"Buka rekening tabungan",s:"saveSavAcc()",y:"Buka rekening",b:fld("sa-p","Nasabah *",{t:"select",req:1,opts:`<option value="">— pilih —</option>`+opt(ns,p=>[p._id,p.name],S.esa||"")})+fld("sa-u","Unit *",{t:"select",req:1,opts:opt(us,u=>[u._id,u.name],(us[0]||{})._id)})
  +(savProds().length?fld("sa-n","Produk",{t:"select",opts:opt([["Tabungan","Tabungan (bunga dasar)"],...savProds().map(p=>[p.name,p.name+" · "+String(p.rate).replace(".",",")+"%"+(p.term>0?" · "+p.term+" bln":"")])],x=>x,"Tabungan"),hint:"Produk berjangka (deposito) tidak bisa ditarik sebelum jatuh tempo"}):fld("sa-n","Produk",{value:"Tabungan",hint:"Contoh: Tabungan, Tabungan Pendidikan"}))+fld("sa-m","Saldo minimum (Rp, 0 = tanpa)",{a:RPA,value:"0",hint:"Penarikan tidak boleh membuat saldo di bawah angka ini"})+fld("sa-d","Tanggal buka",{type:"date",value:today(),req:1})}};
MD.st=()=>{const[ty,id]=String(S.est||"").split("|"),a=savAccs().find(x=>x._id===id);if(!a||!SAV_T[ty])return{t:"Tabungan",s:"mdClose()",y:"Tutup",b:"<p>Rekening tidak ditemukan.</p>",nf:1};
 const sk=savBal(a._id),ht={setor:"Kas/bank bertambah dan saldo tabungan nasabah bertambah.",tarik:"Kas/bank berkurang dan saldo tabungan berkurang. Maksimal Rp "+fm(Math.max(0,sk-(a.min_balance||0)))+" (saldo Rp "+fm(sk)+(a.min_balance?", minimum Rp "+fm(a.min_balance):"")+").",bunga:"Dicatat sebagai beban bunga tabungan dan menambah saldo nasabah (tidak melibatkan kas)."};
 return{t:SAV_T[ty]+" · "+a.number,s:"saveSavTx()",y:"Simpan "+SAV_T[ty].toLowerCase(),b:`<p class="k">${esc(party(a.party_id).name)}. ${ht[ty]}</p>`+fld("st-d","Tanggal",{type:"date",value:today(),req:1})+fld("st-a","Jumlah (Rp)",{a:RPA,req:1,value:""})
  +(ty==="bunga"?"":fld("st-c","Kas/Bank",{t:"select",opts:opt(db.cash_accounts.filter(isAct),c=>[c._id,c.name],"CASH-001")}))+fld("st-s","Catatan",{value:""})}};
MD.sv=()=>{const a=savAccs().find(x=>x._id===S.esv);if(!a)return{t:"Rekening",s:"mdClose()",y:"Tutup",b:"<p>Rekening tidak ditemukan.</p>",nf:1};
 const R=(k,v)=>`<div class="kv"><span class="k">${k}</span><b>${v}</b></div>`,on=a.status==="aktif",run=savRun(a._id),rb=new Map(run.map(r=>[r.x._id,r.b])),tx=savTxOf(a._id).slice().reverse();
 return{t:a.number,s:"mdClose()",y:"Tutup",nf:1,b:`<div class="ldw"><div class="lds"><span class="bdg ${on?"ok":""}">${on?"Aktif":"Ditutup"}</span></div><div class="kvg">${R("Nasabah",esc(party(a.party_id).name))}${R("Produk",esc(a.product))}${a.prod?R("Bunga produk",String(a.prod.rate).replace(".",",")+"% per tahun"):""}${savLock(a)?R("Jatuh tempo",savLock(a)+(savLock(a)>today()?" (belum jatuh tempo)":" (sudah jatuh tempo)")):""}${R("Unit",esc(unitName(a.unit_id)))}${R("Saldo",rp(savBal(a._id)))}${R("Saldo minimum",rp(a.min_balance||0))}${R("Dibuka",a.opened_at)}</div>
<div class="lda">${on?ib("plus","Setor","mdOpen('st','setor|"+a._id+"')")+ib("out","Tarik","mdOpen('st','tarik|"+a._id+"')")+ib("plus","Bunga","mdOpen('st','bunga|"+a._id+"')","s")+ib("lock","Tutup rekening","tutupSav('"+a._id+"')","s")+ib("print","Cetak buku","docOpen('bt','"+a._id+"')","s"):ib("check","Buka kembali","bukaSav('"+a._id+"')","s")}</div>
<h3>Buku tabungan</h3>${tx.length?tx.map(x=>{const ok=x.status==="posted",sg=SAV_SIGN[x.type];return`<div class="kv" style="align-items:center;gap:8px${ok?"":";opacity:.55;text-decoration:line-through"}"><span><b>${SAV_T[x.type]}</b> <span class="k">${x.date}</span>${x.gross?` <small class="k">(bruto ${fm(x.gross)}, pajak ${fm(x.tax||0)})</small>`:""}${x.desc?`<br><small class="k">${esc(x.desc)}</small>`:""}${ok?"":" <small>(Dibatalkan)</small>"}</span><span style="text-align:right;margin-left:auto"><b>${sg<0?"−":"+"}${fm(x.amount)}</b>${ok?`<br><small class="k">Saldo ${fm(rb.get(x._id))}</small>`:""}</span>${ok&&(x.type==="setor"||x.type==="tarik")?ib("print","Struk","docOpen('ks','"+x._id+"','"+strukP()+"')","s"):""}${ok?ib("x","Batalkan","askC('batalSav','"+x._id+"')","s"):""}</div>`}).join(""):'<p class="k">Belum ada mutasi.</p>'}</div>`}};

// ===== v1.1.190 — bukti setoran / penarikan tabungan (A4 atau struk 80/58 mm) =====
const stxNo=x=>"BS-"+x.date.slice(0,4)+"-"+String((db.savings_tx||[]).indexOf(x)+1).padStart(4,"0");
function vBuktiSav(id){const bar=docBar(1),x=(db.savings_tx||[]).find(q=>q._id===id),a=x&&savAccs().find(q=>q._id===x.account_id);
 if(!x||!a||x.status!=="posted"||!["setor","tarik"].includes(x.type))return`${bar}<p class="k">Bukti tidak tersedia.</p>`;
 const pt=party(a.party_id),ci=x.cash_id&&db.cash_accounts.find(c=>c._id===x.cash_id),R=(k,v)=>`<tr><td>${k}</td><td class="n">${v}</td></tr>`,r=savRun(a._id).find(q=>q.x._id===x._id),st=x.type==="setor";
 return`${bar}<div class="${dcl(1)}">${kop()}<h3>${st?"BUKTI SETORAN TABUNGAN":"BUKTI PENARIKAN TABUNGAN"}</h3><div class="cn">No. ${stxNo(x)} · ${x.date}</div><table>${R("Nasabah",esc(pt.name))}${R("No. rekening",esc(a.number))}${R("Produk",esc(a.product))}<tr><th>${st?"Jumlah setoran":"Jumlah penarikan"}</th><th class="n">${rp(x.amount)}</th></tr>${ci?R(st?"Diterima di":"Dibayar dari",esc(ci.name)):""}${x.desc?R("Keterangan",esc(x.desc)):""}${r?R("Saldo sesudah",rp(r.b)):""}${ptgR(x)}</table><div class="tb">Terbilang: ${cap(terbilang(x.amount))}</div>${sig([[st?"Penyetor":"Penarik",pt.name],["Petugas",petugas(x)]],0,x.date)}</div>`}

// ===== v1.1.158 — O7: Rekap Tabungan nasabah (semua rekening aktif: saldo + 10 mutasi terakhir per rekening) untuk cetak pengurus dan portal nasabah =====
function rekapHtml(pid,o){o=o||{};const pt=db.parties.find(x=>x._id===pid)||{name:"?"},A=savAccs().filter(a=>a.party_id===pid&&a.status==="aktif"),tot=A.reduce((s,a)=>s+savBal(a._id),0);
 return`<div class="doc">${kop()}<h3>REKAP TABUNGAN</h3><div class="cn">${esc(pt.name)} · per ${tglS(today())}</div>
${A.length?tbl(["No. rekening","Produk","Dibuka","#Saldo"],A.map(a=>`<tr><td>${esc(a.number)}</td><td>${esc(a.product)}</td><td>${tglS(a.opened_at)}</td><td class="n">${rp(savBal(a._id))}</td></tr>`).concat(`<tr><th colspan="3">Total tabungan</th><th class="n">${rp(tot)}</th></tr>`)):'<p class="k">Belum ada rekening tabungan aktif.</p>'}
${A.map(a=>{const run=savRun(a._id).slice(-10).reverse();return`<h3>${esc(a.number)} · ${esc(a.product)}</h3>${run.length?tbl(["Tanggal","Keterangan","#Kredit","#Debit","#Saldo"],run.map(r=>`<tr><td>${tglS(r.x.date)}</td><td>${esc(SAV_T[r.x.type]||r.x.type)}${r.x.desc?" · "+esc(r.x.desc):""}</td><td class="n">${SAV_SIGN[r.x.type]>0?rp(r.x.amount):""}</td><td class="n">${SAV_SIGN[r.x.type]<0?rp(r.x.amount):""}</td><td class="n">${rp(r.b)}</td></tr>`)):'<p class="k">Belum ada mutasi.</p>'}`}).join("")}
${o.portal?"":sig([["Nasabah",pt.name],["Petugas",petugas()]],0,today())}</div>`}
function vRekap(pid){const bar=`<div class="noprint"><button class="b" onclick="window.print()">Cetak</button><button class="b s" onclick="S.doc=null;render()">Kembali</button></div>`;
 return db.parties.find(x=>x._id===pid&&x.type==="nasabah")?bar+rekapHtml(pid):bar+'<p class="k">Nasabah tidak ditemukan.</p>'}
