// ===== RINGKASAN NASABAH YANG DAPAT DIBAGIKAN (v1.1.015): teks posisi pinjaman dan tabungan untuk WhatsApp/salin =====
// Data = posisi saat teks dibuat (snapshot). Berisi data pribadi dan keuangan: kirim hanya ke nasabah yang bersangkutan.
function nsText(pid){const p=db.parties.find(x=>x._id===pid);if(!p)return"";const t=today(),L=[],ln=db.loans.filter(l=>l.party_id===pid&&l.status==="active"),sv=(db.savings_accounts||[]).filter(a=>a.party_id===pid&&a.status==="aktif");
 L.push("*"+bnm()+"*","Ringkasan nasabah — "+p.name,"Posisi per "+t,"");
 L.push("*PINJAMAN*");
 if(!ln.length)L.push("Tidak ada pinjaman aktif.");
 ln.forEach(l=>{const ins=db.loan_installments.filter(i=>i.loan_id===l._id).sort((a,b)=>a.installment_number-b.installment_number),op=ins.filter(i=>i.status!=="paid"),od=op.filter(i=>i.due_date<t),nx=op.find(i=>i.due_date>=t),pk=ins.reduce((s,i)=>s+i.principal_due-i.principal_paid,0);
  L.push(l.loan_number+" · sisa pokok Rp "+fm(pk)+" · "+op.length+" dari "+ins.length+" angsuran belum lunas");
  if(od.length){const tot=od.reduce((s,i)=>s+owed(i,t).total,0);L.push("  ⚠ Tunggakan "+od.length+" angsuran, total Rp "+fm(tot)+" (termasuk denda)")}
  if(nx)L.push("  Angsuran berikut: ke-"+nx.installment_number+", jatuh tempo "+nx.due_date+", tagihan Rp "+fm(owed(nx,t).total))});
 L.push("","*TABUNGAN*");
 if(!sv.length)L.push("Tidak ada rekening tabungan aktif.");
 sv.forEach(a=>{L.push(a.number+" ("+a.product+") · saldo Rp "+fm(savBal(a._id)));const m=savLive(a._id).slice(-3).reverse();m.forEach(x=>L.push("  "+x.date+" "+SAV_T[x.type]+" "+(SAV_SIGN[x.type]<0?"−":"+")+"Rp "+fm(x.amount)))});
 L.push("","Data per tanggal di atas; bila ada selisih dengan catatan Anda, hubungi pengurus "+bnm()+".");return L.join("\n")}
const waNo=s=>{let n=String(s||"").replace(/\D/g,"");if(n.startsWith("0"))n="62"+n.slice(1);else if(n.startsWith("8"))n="62"+n;return n.length>=9?n:""};
MK.ns="ens";
MD.ns=()=>{const p=db.parties.find(x=>x._id===S.ens);if(!p)return{t:"Ringkasan nasabah",s:"mdClose()",y:"Tutup",b:"<p>Nasabah tidak ditemukan.</p>",nf:1};
 return{t:"Ringkasan · "+p.name,s:"mdClose()",y:"Tutup",nf:1,b:`<p class="k">Teks ini berisi data pinjaman dan tabungan nasabah pada saat ini. Kirim hanya ke nasabah yang bersangkutan.</p><pre id="ns-t" class="ns-t">${esc(nsText(p._id))}</pre><div class="lda">${ib("check","Salin","nsCopy('"+p._id+"')")}${waNo(p.phone)?ib("out","WhatsApp","nsWa('"+p._id+"')"):""}${typeof navigator!=="undefined"&&navigator.share?ib("out","Bagikan","nsShare('"+p._id+"')","s"):""}</div>${waNo(p.phone)?"":'<p class="k">Nomor telepon nasabah belum diisi atau tidak valid, sehingga tombol WhatsApp tidak tersedia.</p>'}`}};
function nsLog(id,how){audit("share","party",id,"ringkasan nasabah ("+how+")");save()}
function nsCopy(id){const x=nsText(id);try{if(navigator.clipboard&&navigator.clipboard.writeText)navigator.clipboard.writeText(x).then(()=>{S.msg="Ringkasan disalin";render()},()=>{S.msg="⚠ Gagal menyalin; tekan lama teks untuk menyalin manual";render()});else throw 0}catch(e){S.msg="⚠ Penyalinan tidak didukung; tekan lama teks untuk menyalin manual";render()}nsLog(id,"salin")}
function nsWa(id){const p=db.parties.find(x=>x._id===id),n=p&&waNo(p.phone);if(!n){S.msg="⚠ Nomor telepon nasabah tidak valid";render();return}nsLog(id,"WhatsApp");window.open("https://wa.me/"+n+"?text="+encodeURIComponent(nsText(id)),"_blank","noopener")}
function nsShare(id){nsLog(id,"bagikan");try{navigator.share({title:"Ringkasan nasabah",text:nsText(id)}).catch(()=>{})}catch(e){}}

// ===== PENGINGAT JATUH TEMPO / TUNGGAKAN (v1.1.070): teks dari templat yang dapat diatur =====
const REM_D={due:"Yth. Bapak/Ibu {nama}, kami mengingatkan angsuran ke-{ke} pinjaman {no} sebesar Rp {jumlah} jatuh tempo pada {tgl}. Terima kasih. — {bumdes}",late:"Yth. Bapak/Ibu {nama}, angsuran pinjaman {no} menunggak {hari} hari ({n} angsuran), total Rp {jumlah} termasuk denda Rp {denda}. Mohon segera dibayar atau hubungi pengurus. — {bumdes}"},REM_K=["nama","no","ke","tgl","jumlah","hari","n","denda","bumdes"];
const remTpl=k=>{const t=(db.settings.sp_rem||{})[k];return typeof t==="string"&&t.trim()?t:REM_D[k]};
function remKind(l,d){d=d||today();if(!l||l.status!=="active")return null;const op=db.loan_installments.filter(i=>i.loan_id===l._id&&i.status!=="paid").sort((a,b)=>a.installment_number-b.installment_number);if(op.some(i=>i.due_date<d))return"late";const nx=op[0];return nx&&dayDiff(nx.due_date,d)<=7?"due":null}
function remText(id,d){d=d||today();const l=db.loans.find(x=>x._id===id),k=remKind(l,d);if(!k)return"";const p=party(l.party_id),op=db.loan_installments.filter(i=>i.loan_id===l._id&&i.status!=="paid").sort((a,b)=>a.installment_number-b.installment_number);let v;
 if(k==="late"){const od=op.filter(i=>i.due_date<d),w=od.map(i=>owed(i,d)),mx=Math.max(...od.map(i=>dayDiff(d,i.due_date)));v={hari:mx,n:od.length,jumlah:fm(w.reduce((s,x)=>s+x.total,0)),denda:fm(w.reduce((s,x)=>s+x.pen,0)),ke:od[0].installment_number,tgl:od[0].due_date}}
 else{const i=op[0];v={ke:i.installment_number,tgl:i.due_date,jumlah:fm(owed(i,d).total),hari:0,n:1,denda:"0"}}
 return remTpl(k).replace(/\{(\w+)\}/g,(m,x)=>x==="nama"?p.name:x==="no"?l.loan_number:x==="bumdes"?bnm():(x in v?String(v[x]):m))}
function setRemTpl(k,v){try{if(!REM_D[k])throw Error("Templat tidak dikenal");v=String(v||"").trim();if(v.length>600)throw Error("Maksimal 600 karakter");const bad=[...v.matchAll(/\{(\w+)\}/g)].map(m=>m[1]).filter(x=>!REM_K.includes(x));if(bad.length)throw Error("Kode tidak dikenal: {"+bad[0]+"}. Yang tersedia: "+REM_K.map(x=>"{"+x+"}").join(" "));
 db.settings.sp_rem=Object.assign({},db.settings.sp_rem);if(v&&v!==REM_D[k])db.settings.sp_rem[k]=v;else delete db.settings.sp_rem[k];audit("setting","settings","sp_rem","Templat pengingat "+(k==="due"?"jatuh tempo":"tunggakan")+(v?" diubah":" dikembalikan"));save();S.msg="Templat pengingat disimpan"}catch(e){S.msg="⚠ "+e.message}render()}
MK.rm="erm";
MD.rm=()=>{const l=db.loans.find(x=>x._id===S.erm),t=l?remText(l._id):"",p=l&&party(l.party_id);if(!l||!t)return{t:"Pengingat",s:"mdClose()",y:"Tutup",b:"<p>Tidak ada pengingat untuk pinjaman ini (tidak aktif, atau belum jatuh tempo dalam 7 hari).</p>",nf:1};
 return{t:"Pengingat · "+p.name,s:"mdClose()",y:"Tutup",nf:1,b:`<p class="k">Teks dibuat dari templat di Setelan. Kirim hanya ke nasabah yang bersangkutan.</p><pre id="rm-t" class="ns-t">${esc(t)}</pre><div class="lda">${ib("check","Salin","remCopy('"+l._id+"')")}${waNo(p.phone)?ib("out","WhatsApp","remWa('"+l._id+"')"):""}${typeof navigator!=="undefined"&&navigator.share?ib("out","Bagikan","remShare('"+l._id+"')","s"):""}</div>${waNo(p.phone)?"":'<p class="k">Nomor telepon nasabah belum diisi atau tidak valid, sehingga tombol WhatsApp tidak tersedia.</p>'}`}};
function remLog(id,how){audit("share","loan",id,"pengingat ("+how+")");save()}
function remCopy(id){const x=remText(id);try{if(navigator.clipboard&&navigator.clipboard.writeText)navigator.clipboard.writeText(x).then(()=>{S.msg="Pengingat disalin";render()},()=>{S.msg="⚠ Gagal menyalin; tekan lama teks untuk menyalin manual";render()});else throw 0}catch(e){S.msg="⚠ Penyalinan tidak didukung; tekan lama teks untuk menyalin manual";render()}remLog(id,"salin")}
function remWa(id){const l=db.loans.find(x=>x._id===id),n=l&&waNo(party(l.party_id).phone);if(!n){S.msg="⚠ Nomor telepon nasabah tidak valid";render();return}remLog(id,"WhatsApp");window.open("https://wa.me/"+n+"?text="+encodeURIComponent(remText(id)),"_blank","noopener")}
function remShare(id){remLog(id,"bagikan");try{navigator.share({title:"Pengingat angsuran",text:remText(id)}).catch(()=>{})}catch(e){}}
function remBox(){const L=db.loans.filter(l=>(S.unit==="all"||l.unit_id===S.unit)&&remKind(l)).map(l=>({l,k:remKind(l)})).sort((a,b)=>(a.k==="late"?0:1)-(b.k==="late"?0:1));if(!L.length)return"";
 return`<h3>Pengingat penagihan</h3><div class="ll"><div class="lh" aria-hidden="true"><span>Pinjaman</span><span>Jenis</span><span></span></div>${L.map(({l,k})=>`<div class="li"><span class="l1"><b>${esc(l.loan_number)}</b><small>${esc(party(l.party_id).name)}</small></span><span>${k==="late"?'<span class="bdg bd">Menunggak</span>':'<span class="bdg wr">Jatuh tempo ≤ 7 hari</span>'}</span><span>${ib("out","Pengingat","mdOpen('rm','"+l._id+"')","s")}</span></div>`).join("")}</div><p class="k">Teks mengikuti templat di Setelan. Tombol Salin, WhatsApp, atau Bagikan ada di dalam.</p>`}
