// ===== SP5 (v1.1.021): audit dengan nilai sebelum/sesudah, ekspor CSV, jejak audit per pinjaman, laporan tambahan Simpan Pinjam =====
// Audit setelan memakai snapshot (_ss, diisi snapSet() saat load/import); perubahan data lain memakai chgOf(sebelum, sesudah).
const AUD_L={portal_masuk:"Masuk portal nasabah",portal_gagal:"Gagal masuk portal nasabah",portal_pin:"PIN portal nasabah",amort_fee:"Fee pencairan diakui",create:"Dibuat",update:"Diubah",setting:"Setelan",pay:"Pembayaran",payoff:"Pelunasan dipercepat",void_pay:"Pembayaran dibatalkan",restruk:"Restrukturisasi",batal_restruk:"Restrukturisasi dibatalkan",hapus_buku:"Hapus buku",usul_hapus_buku:"Usul hapus buku",tolak_hapus_buku:"Usul hapus buku ditolak",usul_restruk:"Usul restrukturisasi",kirim_draf:"Draf dikirim",hapus_draf:"Draf dihapus",calon_status:"Status calon berubah",calon_nasabah:"Calon jadi nasabah",tolak_restruk:"Usul restrukturisasi ditolak",batal_hapus_buku:"Hapus buku dibatalkan",pemulihan:"Pemulihan",batal_pemulihan:"Pemulihan dibatalkan",void_disburse:"Pencairan dibatalkan",tagih:"Catatan penagihan",akses_ditolak:"Akses ditolak",share:"Ringkasan dibagikan",opening:"Saldo awal"};
// Nama peristiwa baku (v1.1.027): DOMAIN.PERISTIWA, tetap stabil walau label tampilan berubah; dipakai di Audit Log, CSV, dan pencarian
const AUD_D={loan:"PINJAMAN",payment:"PEMBAYARAN",sale:"PENJUALAN",transaction:"JURNAL",savings_account:"TABUNGAN",user:"PENGGUNA",role:"PENGGUNA",settings:"SETELAN",party:"PIHAK",account:"AKUN",cash_account:"KAS",collateral:"JAMINAN",employee:"PEGAWAI",payroll:"GAJI",salary_payment:"GAJI",payroll_component:"GAJI",product:"PRODUK",rate_master:"TARIF",tax_master:"PAJAK",unit:"UNIT",bumdes:"BUMDES",master:"MASTER",fiscal_year:"TAHUN_BUKU",water_connection:"AIR",water_reading:"AIR",aksi:"KEAMANAN",prospect:"CALON"};
const AUD_V={portal_masuk:"PORTAL_MASUK",portal_gagal:"PORTAL_GAGAL",portal_pin:"PORTAL_PIN",amort_fee:"AMORTISASI_FEE",create:"BUAT",update:"UBAH",edit:"UBAH",activate:"AKTIFKAN",deactivate:"NONAKTIFKAN",void:"BATAL",delete:"HAPUS",post:"POSTING",setting:"ATUR",pay:"BAYAR",void_pay:"BAYAR_BATAL",payoff:"LUNAS_DIPERCEPAT",disburse:"CAIR",void_disburse:"CAIR_BATAL",restruk:"RESTRUK",batal_restruk:"RESTRUK_BATAL",hapus_buku:"HAPUS_BUKU",usul_hapus_buku:"HAPUS_BUKU_USUL",tolak_hapus_buku:"HAPUS_BUKU_TOLAK",usul_restruk:"RESTRUK_USUL",kirim_draf:"KIRIM_DRAF",hapus_draf:"HAPUS_DRAF",calon_status:"UBAH_STATUS",calon_nasabah:"JADI_NASABAH",tolak_restruk:"RESTRUK_TOLAK",batal_hapus_buku:"HAPUS_BUKU_BATAL",pemulihan:"PULIH",batal_pemulihan:"PULIH_BATAL",tagih:"TAGIH",akses_ditolak:"AKSES_DITOLAK",share:"BAGIKAN",opening:"SALDO_AWAL",close_year:"TUTUP",reopen_year:"BUKA_KEMBALI",login:"MASUK",login_gagal:"MASUK_GAGAL",login_ditolak:"MASUK_DITOLAK",logout:"KELUAR",kunci_akun:"KUNCI",pin_ganti:"PIN_GANTI",pin_reset:"PIN_RESET",rbac_on:"MODE_PENGGUNA_AKTIF",rbac_off:"MODE_PENGGUNA_MATI",user_buat:"BUAT",user_ubah:"UBAH",user_aktif:"AKTIFKAN",user_nonaktif:"NONAKTIFKAN",peran_izin:"UBAH_IZIN",sav_buka:"BUKA",sav_tutup:"TUTUP",sav_batal:"BATAL",sav_proses:"PROSES",bill:"TAGIHAN",receive:"TERIMA",sale:"JUAL",return:"KEMBALI",approve:"SETUJUI",akad:"AKAD",analisis:"ANALISIS",verifikasi:"VERIFIKASI",meter_change:"GANTI_METER"};
const audEv=a=>(AUD_D[a.entity]||String(a.entity||"LAIN").toUpperCase())+"."+(AUD_V[a.action]||String(a.action||"").toUpperCase());
const audLbl=a=>AUD_L[a]||a;
function chgOf(b,a,keys){const B={},A={};(keys||Object.keys(a)).forEach(k=>{if(JSON.stringify(b[k])!==JSON.stringify(a[k])){B[k]=b[k]===undefined?null:b[k];A[k]=a[k]===undefined?null:a[k]}});return Object.keys(A).length?{b:B,a:A}:null}
const audV=s=>{if(s==null)return"—";try{const v=JSON.parse(s);if(v===null||v==="")return"—";if(typeof v==="object"){const t=Object.entries(v).map(([k,x])=>k+": "+(typeof x==="object"&&x!==null?JSON.stringify(x):String(x))).join(", ");return t.length>160?t.slice(0,157)+"…":t}return String(v)}catch(e){return String(s)}};
const audX=a=>a.after===undefined&&a.before===undefined?"":audV(a.before)+" → "+audV(a.after);
function audAll(){const q=(S.q||"").toLowerCase();return db.audit_logs.filter(a=>(!S.aa||a.action===S.aa)&&(!S.ae||a.entity===S.ae)&&(!S.au||(a.by||"-")===S.au)&&inD(a.at.slice(0,10))&&(!q||(a.action+" "+audEv(a)+" "+a.entity+" "+(a.entity_id||"")+" "+(a.detail||"")).toLowerCase().includes(q))).slice().reverse()}
function audCsv(){return tblCsv(["Waktu","Oleh","Peristiwa","Aksi","Entitas","ID","Keterangan","Sebelum","Sesudah"],audAll().map(a=>[a.at.slice(0,19).replace("T"," "),a.by||"-",audEv(a),a.action,a.entity,a.entity_id||"",a.detail||"",a.before===undefined?"":audV(a.before),a.after===undefined?"":audV(a.after)]))}
function audDl(){try{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["﻿"+audCsv()],{type:"text/csv"}));a.download="audit-log-"+today()+".csv";a.click();S.msg="Audit log diunduh (CSV), sesuai filter yang aktif"}catch(e){S.msg="⚠ Unduh gagal: "+e.message}render()}
const _ss={},audJ=s=>{const t=JSON.stringify(s);return t===undefined?undefined:t.length>300?'"(data besar)"':t};function snapSet(){try{Object.keys(db.settings||{}).forEach(k=>{_ss[k]=audJ(db.settings[k])})}catch(e){}}
// jejak audit per pinjaman (modal pinjaman)
function ajHtml(l){const R=db.audit_logs.filter(a=>a.entity==="loan"&&a.entity_id===l._id).slice().reverse();if(!R.length)return"";
 return`<details class="sx"><summary>Jejak audit <span class="stc">${R.length}</span></summary>${R.slice(0,50).map(a=>`<div class="ph"><span><b>${esc(audLbl(a.action))}</b> · ${esc(a.at.slice(0,16).replace("T"," "))}${a.by?" · "+esc(a.by):""}${a.detail||audX(a)?`<small>${esc(a.detail||"")}${audX(a)?(a.detail?" · ":"")+esc(audX(a)):""}</small>`:""}</span></div>`).join("")}</details>`}
// laporan tambahan Simpan Pinjam
// Laporan biaya per kode (v1.1.025): pencairan, pelunasan dipercepat, restrukturisasi; hanya yang masih berlaku (tidak dibatalkan)
function feeRep(){const U=l=>S.unit==="all"||l.unit_id===S.unit,M=new Map(),add=(src,code,name,a,t)=>{const k=src+"|"+code,x=M.get(k)||{src,code,name,n:0,a:0,t:0};x.n++;x.a+=a||0;x.t+=t||0;M.set(k,x)};
 db.loans.filter(U).forEach(l=>{if(l.disb&&inD(l.disbursement_date))(l.disb.items||[]).forEach(i=>add("Pencairan",i.code,i.name,i.amount,i.tax));
  db.loan_payments.filter(p=>p.loan_id===l._id&&p.status!=="voided"&&p.fee_amount&&inD(p.payment_date)).forEach(p=>{if(p.fee_items&&p.fee_items.length)p.fee_items.forEach(i=>add("Pelunasan dipercepat",i.code,i.name,i.amount,i.tax));else add("Pelunasan dipercepat","-","Biaya pelunasan (sebelum v1.1.025)",p.fee_amount,p.fee_tax)});
  (l.restructures||[]).filter(r=>r.fee&&inD(r.date)).forEach(r=>{const rt=r.fee_code?rateAt(r.fee_code,r.date):null;add("Restrukturisasi",r.fee_code||"-",rt?rt.fee_name:(r.fee_code||"Biaya restrukturisasi"),r.fee,r.fee_tax)})});
 return[...M.values()].sort((x,y)=>x.src.localeCompare(y.src)||x.code.localeCompare(y.code))}
// Waktu proses per tahap (v1.1.028): selisih hari antara tanggal tahap yang tersedia; tahap opsional (verifikasi, analisis, akad) hanya muncul bila ada datanya
const SP_TH=[["Pengajuan → verifikasi",l=>l.application_date,l=>l.verif&&l.verif.date],["Verifikasi → analisis",l=>l.verif&&l.verif.date,l=>l.analysis&&l.analysis.date],["Analisis → persetujuan",l=>l.analysis&&l.analysis.date,l=>l.approval_date],["Pengajuan → persetujuan",l=>l.application_date,l=>l.approval_date,1],["Persetujuan → akad",l=>l.approval_date,l=>l.contract&&l.contract.date],["Akad → pencairan",l=>l.contract&&l.contract.date,l=>l.disbursement_date],["Persetujuan → pencairan",l=>l.approval_date,l=>l.disbursement_date,1],["Pengajuan → pencairan (total)",l=>l.application_date,l=>l.disbursement_date]];
function spWaktu(ls){return SP_TH.map(([n,f,g,k])=>{const v=ls.filter(l=>!l.opening&&isD(f(l))&&isD(g(l))).map(l=>dayDiff(g(l),f(l)));return{n,k:!!k,c:v.length,avg:v.length?v.reduce((a,b)=>a+b,0)/v.length:null,max:v.length?Math.max(...v):null}}).filter(x=>x.c>0||x.k)}
function spRep2(){const U=l=>S.unit==="all"||l.unit_id===S.unit,ls=db.loans.filter(U),B=(k,v)=>`<tr><td>${k}</td><td class="n">${v}</td></tr>`;
 const pipe=Object.keys(LS).map(s=>{const x=ls.filter(l=>l.status===s);return[LS[s],x.length,x.reduce((t,l)=>t+(l.principal||0),0)]}).filter(r=>r[1]>0);
  const g=bal(l=>inD(l.date)&&inUnit(l)),r=c=>net(acc("ACC"+c),g),all=bal(()=>true);
 const kol=kolSummary(),sod=Object.keys(SOD_L).map(k=>{const n=db.audit_logs.filter(a=>a.action==="akses_ditolak"&&a.entity_id===k&&inD(a.at.slice(0,10))).length;return[SOD_L[k],rbacOn()?(sodCfg()[k]?"Aktif":"Mati"):"Tidak berlaku (Mode Pengguna mati)",n]});
 const fx=feeRep(),tx=db.audit_logs.filter(a=>a.action==="akses_ditolak"&&inD(a.at.slice(0,10))).length;
 return`<h2>Pipeline pengajuan</h2>${pipe.length?tbl(["Tahap","#Jumlah","#Pokok"],pipe.map(x=>`<tr><td>${x[0]}</td><td class="n">${x[1]}</td><td class="n">${rp(x[2])}</td></tr>`)):'<p class="k">Belum ada pinjaman.</p>'}
<h2>Waktu proses per tahap</h2>${tbl(["Tahap","#Rata-rata (hari)","#Terlama (hari)","#Pinjaman"],spWaktu(ls).map(x=>`<tr><td>${x.n}</td><td class="n">${x.avg==null?"—":x.avg.toFixed(1)}</td><td class="n">${x.max==null?"—":x.max}</td><td class="n">${x.c}</td></tr>`))}<p class="k">Selisih tanggal antar tahap; tahap verifikasi, analisis, dan akad muncul bila alur lengkap dipakai. Saldo awal tidak dihitung.</p>
<h2>Calon peminjam</h2>${(db.prospects||[]).length?tbl(["Status","#Calon","#Rencana pinjaman"],Object.keys(CL_S).map(k=>{const x=db.prospects.filter(c=>c.status===k);return[k,x.length,x.reduce((s,c)=>s+(c.amount||0),0)]}).filter(r=>r[1]>0).map(r=>`<tr><td>${CL_S[r[0]]}</td><td class="n">${r[1]}</td><td class="n">${rp(r[2])}</td></tr>`)):'<p class="k">Belum ada calon peminjam.</p>'}${(db.prospects||[]).length?`<p class="k">Konversi menjadi nasabah: ${db.prospects.filter(c=>c.status==="nasabah").length} dari ${db.prospects.length} calon (${Math.round(db.prospects.filter(c=>c.status==="nasabah").length/db.prospects.length*100)}%).</p>`:""}
<h2>Kolektibilitas</h2>${tbl(["Jenjang","#Pinjaman","#Sisa pokok"],kol.map(x=>`<tr><td>${esc(x.n)}</td><td class="n">${x.c}</td><td class="n">${rp(x.v)}</td></tr>`))}
<h2>Pendapatan per jenis dan pajak terutang</h2>${tbl(["Rentang tanggal","#Nilai"],[B("Jasa pinjaman (4100)",rp(r("4100"))),B("Denda dan biaya pinjaman (4400)",rp(r("4400"))),B("Administrasi tabungan (4500)",rp(r("4500"))),B("Pemulihan piutang (4600)",rp(r("4600"))),B("Beban bunga tabungan (5600)",rp(r("5600"))),B("Beban kerugian piutang (5700)",rp(r("5700")))])}
${tbl(["Posisi per "+today(),"#Saldo"],[B("Utang pajak bunga tabungan (2210)",rp(net(acc("ACC2210"),all))),B("Utang pajak atas biaya pinjaman (2220)",rp(net(acc("ACC2220"),all))),B("Utang pajak atas biaya tabungan (2230)",rp(net(acc("ACC2230"),all))),B("Fee pencairan ditangguhkan (2240)",rp(net(acc("ACC2240"),all)))])}<p class="k">Pajak terutang adalah titipan yang belum disetor; penyetoran dicatat lewat transaksi pengeluaran biasa.</p>
<h2>Biaya per kode</h2>${fx.length?tbl(["Sumber","Kode","Nama","#Transaksi","#Biaya","#Pajak"],fx.map(x=>`<tr><td>${esc(x.src)}</td><td>${esc(x.code)}</td><td>${esc(x.name)}</td><td class="n">${x.n}</td><td class="n">${rp(x.a)}</td><td class="n">${rp(x.t)}</td></tr>`).concat(`<tr><td colspan="3"><b>Total</b></td><td class="n"><b>${fx.reduce((s,x)=>s+x.n,0)}</b></td><td class="n"><b>${rp(fx.reduce((s,x)=>s+x.a,0))}</b></td><td class="n"><b>${rp(fx.reduce((s,x)=>s+x.t,0))}</b></td></tr>`)):'<p class="k">Belum ada biaya pencairan, pelunasan, atau restrukturisasi pada rentang ini.</p>'}<p class="k">Hanya transaksi yang masih berlaku; pembatalan tidak dihitung. Denda keterlambatan tidak termasuk.</p>
<h2>Kepatuhan pemisahan tugas</h2>${tbl(["Aturan","Status","#Ditolak"],sod.map(x=>`<tr><td>${esc(x[0])}</td><td>${x[1]}</td><td class="n">${x[2]}</td></tr>`))}<p class="k">${tx} penolakan akses/izin tercatat pada rentang ini (semua jenis). Detail di Setelan > Audit Log.</p>`}
