// ===== PENGGUNA, PERAN, LOGIN PIN (v0.1.028) — opsional, bawaan mati; kontrol prosedur (data di localStorage) =====
const PERMS=[["lihat","Melihat dashboard dan laporan"],["audit.lihat","Melihat audit log"],["trx.kelola","Transaksi, jurnal, dan saldo awal"],["sp.kelola","Simpan Pinjam: semua tahap sekaligus (mencakup izin sp.* di bawah)"],["sp.data","SP: nasabah, jaminan, dan rekening tabungan"],["sp.ajukan","SP: mengajukan dan membatalkan pengajuan"],["sp.verifikasi","SP: verifikasi dan survei"],["sp.analisis","SP: analisis kelayakan"],["sp.setujui","SP: menyetujui atau menolak pengajuan"],["sp.setujui.besar","Menyetujui pinjaman di atas batas Manajer (alur lengkap)"],["sp.akad","SP: membuat akad"],["sp.tagih","SP: catatan tindak lanjut penagihan"],["sp.restruk","SP: restrukturisasi pinjaman (tidak ikut sp.kelola)"],["sp.hapusbuku","SP: hapus buku kredit macet dan pemulihan (tidak ikut sp.kelola)"],["sp.cairkan","SP: mencairkan pinjaman"],["sp.bayar","SP: angsuran, pelunasan, dan transaksi tabungan (kasir)"],["air.kelola","Unit Air (penjualan, tagihan, piutang)"],["gaji.kelola","Gaji (profil, penggajian, pembayaran)"],["gaji.setuju","Menyetujui gaji"],["master.kelola","Master data (unit, rekening, akun, pihak, pegawai)"],["periode.kelola","Tutup/buka periode dan tutup buku"],["setelan.kelola","Setelan BUMDes dan dokumen"],["data.backup","Export backup"],["data.kelola","Import dan reset data"],["pengguna.kelola","Kelola pengguna dan peran"]];
const ROLES0=[["ROL-DIR","Direktur","Menyetujui dan mengawasi",["lihat","audit.lihat","gaji.setuju","sp.setujui","sp.setujui.besar","sp.restruk","sp.hapusbuku","periode.kelola","data.backup"]],["ROL-BEN","Bendahara","Mengelola keuangan sehari-hari",["lihat","audit.lihat","trx.kelola","sp.kelola","air.kelola","gaji.kelola","master.kelola","data.backup"]],["ROL-PTU","Petugas Unit","Kasir, petugas air, petugas simpan pinjam",["lihat","trx.kelola","sp.kelola","air.kelola"]],["ROL-PGW","Pengawas","Hanya melihat",["lihat","audit.lihat"]],["ROL-ADM","Admin Sistem","Mengelola pengguna dan sistem",["lihat","audit.lihat","master.kelola","setelan.kelola","data.backup","data.kelola","pengguna.kelola"]],["ROL-KRD","Petugas Kredit","Menerima pengajuan dan mengelola data nasabah",["lihat","sp.data","sp.ajukan","sp.tagih"]],["ROL-SVY","Surveyor/Analis","Verifikasi dan analisis kelayakan",["lihat","sp.verifikasi","sp.analisis"]],["ROL-APR","Approver/Manajer","Menyetujui pengajuan sesuai wewenang dan membuat akad",["lihat","audit.lihat","sp.setujui","sp.akad","sp.restruk"]],["ROL-KSR","Kasir","Pencairan dan pembayaran angsuran/tabungan",["lihat","sp.cairkan","sp.bayar"]],["ROL-SUP","Superadmin","Pengembang sistem: akses penuh ke semua fitur dan izin (izin selalu lengkap, tidak dapat diubah); tersembunyi bagi peran lain",PERMS.map(p=>p[0])]];
function seedRoles(d){if(!Array.isArray(d.roles))d.roles=[];if(!Array.isArray(d.users))d.users=[];ROLES0.forEach(([id,name,desc,perms])=>{if(!d.roles.some(r=>r._id===id))d.roles.push({_id:id,name,desc,perms:perms.slice(),system:true,status:"aktif"})});const sp=d.roles.find(r=>r._id==="ROL-SUP");if(sp)sp.perms=PERMS.map(p=>p[0])}
const MAXF=5,LOCKMS=5*60000,ER=e=>{S.fe=e&&e.f?{id:e.f,m:e.message}:null;return"⚠ "+(e&&e.message)},jam=iso=>{const d=new Date(iso);return String(d.getHours()).padStart(2,"0")+":"+String(d.getMinutes()).padStart(2,"0")};
const K256=(()=>{const k=[];for(let n=2;k.length<64;n++){let q=1;for(let i=2;i*i<=n;i++)if(n%i===0){q=0;break}if(q)k.push(Math.floor((Math.cbrt(n)%1)*4294967296))}return k})(),H256=[2,3,5,7,11,13,17,19].map(n=>Math.floor((Math.sqrt(n)%1)*4294967296));
function sha256(s){const u=unescape(encodeURIComponent(s)),l=u.length,n=(((l+8)>>6)+1)*16,m=new Array(n).fill(0),w=new Array(64),h=H256.slice();
 for(let i=0;i<l;i++)m[i>>2]|=u.charCodeAt(i)<<(24-(i%4)*8);m[l>>2]|=0x80<<(24-(l%4)*8);m[n-1]=l*8;
 for(let j=0;j<n;j+=16){for(let t=0;t<64;t++){if(t<16)w[t]=m[j+t];else{const a=w[t-15],b=w[t-2];w[t]=(w[t-16]+(((a>>>7)|(a<<25))^((a>>>18)|(a<<14))^(a>>>3))+w[t-7]+(((b>>>17)|(b<<15))^((b>>>19)|(b<<13))^(b>>>10)))|0}}
  let[a,b,c,d,e,f,g,x]=h;
  for(let t=0;t<64;t++){const T1=(x+(((e>>>6)|(e<<26))^((e>>>11)|(e<<21))^((e>>>25)|(e<<7)))+((e&f)^(~e&g))+K256[t]+w[t])|0,T2=((((a>>>2)|(a<<30))^((a>>>13)|(a<<19))^((a>>>22)|(a<<10)))+((a&b)^(a&c)^(b&c)))|0;x=g;g=f;f=e;e=(d+T1)|0;d=c;c=b;b=a;a=(T1+T2)|0}
  [a,b,c,d,e,f,g,x].forEach((v,i)=>{h[i]=(h[i]+v)|0})}
 return h.map(v=>(v>>>0).toString(16).padStart(8,"0")).join("")}
const pinHash=(p,salt)=>{let h=sha256(salt+":"+p);for(let i=0;i<2000;i++)h=sha256(h+salt+p);return h};
function newSalt(){try{const a=new Uint32Array(4);crypto.getRandomValues(a);return[...a].map(x=>x.toString(16)).join("")}catch(e){return Array.from({length:4},()=>Math.random().toString(16).slice(2,10)).join("")}}
function pinChk(p,f){if(!/^\d{4,8}$/.test(p))throw fe(f,"PIN harus 4–8 angka");if(/^(\d)\1+$/.test(p))throw fe(f,"PIN tidak boleh angka yang sama semua")}
function usDr(){Object.keys(S.dr||{}).forEach(k=>{if(k.indexOf("set|us-")===0||k.indexOf("set|rp-")===0)delete S.dr[k]});S.nsnap=1}
function ssG(){try{return sessionStorage.getItem("bumdes_sess")}catch(e){return null}}
function ssS(v){try{v?sessionStorage.setItem("bumdes_sess",v):sessionStorage.removeItem("bumdes_sess")}catch(e){}}
function sess(){S.cu=rbacOn()?(ssG()||null):null}
const SPST=["sp.tagih","sp.data","sp.ajukan","sp.verifikasi","sp.analisis","sp.setujui","sp.akad","sp.cairkan","sp.bayar"];
const rbacOn=()=>!!(db&&db.settings&&db.settings.rbac===true),roleOf=u=>u?(db.roles||[]).find(r=>r._id===u.role_id):null,isAdm=u=>!!(u&&u.status==="aktif"&&(roleOf(u)||{perms:[]}).perms.includes("pengguna.kelola")),lastAdm=u=>isAdm(u)&&!db.users.some(x=>x._id!==u._id&&isAdm(x)),isLocked=u=>!!u.locked_until&&Date.parse(u.locked_until)>Date.now();
const isSup=u=>!!(u&&u.role_id==="ROL-SUP"),cuSup=()=>!rbacOn()||isSup(curUser()),needSup=(u)=>{if(isSup(u)&&!cuSup())throw Error("Akun Superadmin (pengembang sistem) hanya dapat dikelola oleh Superadmin")};
function curUser(){if(!rbacOn())return null;return(db.users||[]).find(x=>x._id===S.cu&&x.status==="aktif")||null}
function can(p){if(!rbacOn())return true;const u=curUser(),r=roleOf(u);return!!(u&&r&&(r.perms.includes(p)||(SPST.includes(p)&&r.perms.includes("sp.kelola"))))}
function needP(p,m){if(!can(p))throw Error(m||"Anda tidak berwenang untuk aksi ini")}
function dataP(){if(rbacOn()&&curUser())needP("data.kelola","Hanya Admin Sistem yang dapat mengimpor atau mereset data")}
const nid=(p,a)=>p+"-"+String(1+a.reduce((m,x)=>Math.max(m,+String(x._id).split("-")[1]||0),0)).padStart(3,"0");
function mkUser(name,role,units,pin,must){const salt=newSalt();return{_id:nid("USR",db.users),name,role_id:role,unit_ids:units||[],status:"aktif",pin_salt:salt,pin_hash:pinHash(pin,salt),pin_set_at:now(),must_change:!!must,fails:0,locked_until:"",created_at:now()}}
function authPin(u,p,fid){
 if(isLocked(u)){audit("login_ditolak","user",u._id,"Akun sedang terkunci",u.name);save();throw fe(fid,"Akun terkunci sampai "+jam(u.locked_until)+". Minta Admin Sistem mereset PIN, atau coba lagi nanti.")}
 if(pinHash(p,u.pin_salt)!==u.pin_hash){u.fails=(u.fails||0)+1;
  if(u.fails>=MAXF){u.fails=0;u.locked_until=new Date(Date.now()+LOCKMS).toISOString();audit("kunci_akun","user",u._id,"PIN salah "+MAXF+" kali; akun terkunci 5 menit",u.name);save();throw fe(fid,"PIN salah "+MAXF+" kali. Akun terkunci 5 menit.")}
  audit("login_gagal","user",u._id,"PIN salah ("+u.fails+"/"+MAXF+")",u.name);save();throw fe(fid,"PIN salah. Sisa percobaan: "+(MAXF-u.fails))}
 u.fails=0;u.locked_until=""}
function doLogin(uid,p){const u=db.users.find(x=>x._id===uid);if(!u||u.status!=="aktif")throw fe("lg-u","Akun tidak ditemukan atau nonaktif");if(!p)throw fe("lg-p","PIN wajib diisi");
 authPin(u,p,"lg-p");S.cu=u._id;ssS(u._id);audit("login","user",u._id,"Masuk");save()}
function loginUI(){const u=$("#lg-u"),p=$("#lg-p");try{S.lgu=u?u.value:"";doLogin(S.lgu,p?p.value:"");S.lge="";S.msg="Selamat datang, "+curUser().name}catch(e){S.lge=e.message;S.fe=null}render()}
function doLogout(){const u=curUser();if(u)audit("logout","user",u._id,"Keluar");S.cu=null;ssS(null);S.dr={};S.doc=null;S.pp=null;if(PGK.includes(S.md))S.md=null;S.cf=null;S.msg="";S.lge="";S.more=0;save();render()}
function chgPin(){try{const u=curUser();if(!u)throw Error("Belum masuk");const o=$("#cp-o").value,n=$("#cp-n").value,r=$("#cp-r").value;
 if(pinHash(o,u.pin_salt)!==u.pin_hash)throw fe("cp-o","PIN lama salah");pinChk(n,"cp-n");if(n===o)throw fe("cp-n","PIN baru harus berbeda dari PIN lama");if(n!==r)throw fe("cp-r","Ulangi PIN baru tidak sama");
 u.pin_salt=newSalt();u.pin_hash=pinHash(n,u.pin_salt);u.pin_set_at=now();u.must_change=false;u.fails=0;audit("pin_ganti","user",u._id,"PIN diganti oleh pemilik akun");save();if(S.dx)delete S.dx.pfp;S.msg="PIN berhasil diganti"}catch(e){S.dx=S.dx||{};S.dx.pfp=true;S.msg=ER(e)}render()}
function saveProf(){try{const u=curUser();if(!u)throw Error("Belum masuk");const v=i=>$("#"+i).value.trim().replace(/\s+/g," "),n=v("pf-n"),p=v("pf-p"),a=v("pf-a");
 if(!n)throw fe("pf-n","Nama wajib diisi");if(n.length>60)throw fe("pf-n","Nama terlalu panjang (maks 60 huruf)");
 if(p&&!/^[0-9+()\-\s]{6,20}$/.test(p))throw fe("pf-p","Nomor telepon tidak valid (6–20 angka)");if(a.length>200)throw fe("pf-a","Alamat terlalu panjang (maks 200 huruf)");
 if(db.users.some(x=>x._id!==u._id&&x.name.toLowerCase()===n.toLowerCase()))throw fe("pf-n","Nama pengguna sudah dipakai");
 const e=db.employees.find(x=>x._id===u.employee_id),d=[];if(u.name!==n)d.push("nama "+u.name+" → "+n);if((u.phone||"")!==p)d.push("telepon diubah");if((u.address||"")!==a)d.push("alamat diubah");
 if(!d.length){S.msg="Tidak ada perubahan";render();return}
 u.name=n;u.phone=p;u.address=a;if(e){e.name=n;e.phone=p;e.address=a}
 audit("user_ubah","user",u._id,d.join("; ")+" (oleh pemilik akun)");save();S.msg="Data profil diperbarui"}catch(e){S.msg=ER(e)}render()}
function enableRbac(){try{if(rbacOn())throw Error("Mode pengguna sudah aktif");seedRoles(db);const p=$("#us-p").value;
 if(db.users.length){const u=db.users.find(x=>x._id===$("#us-a").value);if(!isAdm(u))throw fe("us-a","Pilih Admin Sistem yang aktif");if(!p)throw fe("us-p","PIN wajib diisi");authPin(u,p,"us-p");
  db.settings.rbac=true;S.cu=u._id;ssS(u._id);audit("rbac_on","settings","rbac","Mode pengguna diaktifkan kembali");audit("login","user",u._id,"Masuk");usDr();save();S.msg="Mode pengguna aktif kembali. Anda masuk sebagai "+u.name;render();return}
 const n=$("#us-n").value.trim(),p2=$("#us-p2").value,ar=db.roles.find(r=>r.perms.includes("pengguna.kelola"));
 if(!n)throw fe("us-n","Nama Admin wajib diisi");pinChk(p,"us-p");if(p!==p2)throw fe("us-p2","Ulangi PIN tidak sama");if(!ar)throw Error("Tidak ada peran dengan izin Kelola pengguna");
 const u=mkUser(n,ar._id,[],p,false);db.users.push(u);db.settings.rbac=true;S.cu=u._id;ssS(u._id);
 audit("rbac_on","settings","rbac","Mode pengguna diaktifkan; Admin Sistem: "+n);audit("login","user",u._id,"Masuk setelah mengaktifkan mode pengguna");usDr();save();S.msg="Mode pengguna aktif. Anda masuk sebagai "+n}catch(e){S.msg=ER(e)}render()}
function rbacOff(){try{needP("pengguna.kelola","Hanya Admin Sistem yang dapat mematikan mode pengguna");audit("rbac_off","settings","rbac","Mode pengguna dimatikan");db.settings.rbac=false;S.cu=null;ssS(null);save();S.msg="Mode pengguna dimatikan"}catch(e){S.msg=ER(e)}render()}
function saveUser(){try{needP("pengguna.kelola","Hanya Admin Sistem yang dapat mengelola pengguna");
 const n=$("#us-n").value.trim(),r=$("#us-r").value,eu=db.users.find(x=>x._id===S.eus),role=db.roles.find(x=>x._id===r);
 if(!n)throw fe("us-n","Nama pengguna wajib diisi");if(!role)throw fe("us-r","Pilih peran");if(role._id==="ROL-SUP"&&!cuSup())throw fe("us-r","Peran Superadmin hanya dapat diberikan oleh Superadmin");needSup(eu);
 if(db.users.some(x=>x._id!==(eu&&eu._id)&&x.name.toLowerCase()===n.toLowerCase()))throw fe("us-n","Nama pengguna sudah dipakai");
 const emp=db.employees.find(x=>x._id===(($("#us-e")||{}).value||""));if(emp&&db.users.some(x=>x._id!==(eu&&eu._id)&&x.employee_id===emp._id))throw fe("us-e","Pegawai ini sudah punya akun pengguna");
 const un=db.business_units.filter(x=>{const c=$("#us-u-"+x._id);return c&&c.checked}).map(x=>x._id);
 if(eu){if(lastAdm(eu)&&!role.perms.includes("pengguna.kelola"))throw fe("us-r","Ini satu-satunya Admin Sistem aktif; peran tidak boleh diubah");
  const d=[];if(eu.name!==n)d.push("nama "+eu.name+" → "+n);if(eu.role_id!==r)d.push("peran "+(roleOf(eu)||{}).name+" → "+role.name);if((eu.unit_ids||[]).join()!==un.join())d.push("unit tugas diubah");
  eu.name=n;eu.role_id=r;eu.unit_ids=un;if($("#us-e")){if(emp)eu.employee_id=emp._id;else delete eu.employee_id}audit("user_ubah","user",eu._id,d.join("; ")||"tanpa perubahan");S.eus=null;S.msg="Pengguna diperbarui"}
 else{let p=$("#us-p").value,p2=$("#us-p2").value;if(!p&&!p2){p=p2=PIN0}pinChk(p,"us-p");if(p!==p2)throw fe("us-p2","Ulangi PIN tidak sama");
  const u=mkUser(n,r,un,p,true);if(emp)u.employee_id=emp._id;db.users.push(u);audit("user_buat","user",u._id,n+" · "+role.name);usDr();clrF("#us-n,#us-p,#us-p2");S.msg="Pengguna ditambahkan; PIN awal wajib diganti saat masuk pertama"}
 save();okM()}catch(e){S.msg=ER(e)}render()}
function togUser(id){try{needP("pengguna.kelola","Hanya Admin Sistem yang dapat mengelola pengguna");const u=db.users.find(x=>x._id===id);if(!u)throw Error("Pengguna tidak ditemukan");needSup(u);
 if(u.status==="aktif"){if(u._id===S.cu)throw Error("Tidak dapat menonaktifkan akun yang sedang dipakai");if(lastAdm(u))throw Error("Tidak dapat menonaktifkan satu-satunya Admin Sistem aktif");u.status="nonaktif";audit("user_nonaktif","user",u._id,u.name);S.msg="Pengguna dinonaktifkan"}
 else{u.status="aktif";audit("user_aktif","user",u._id,u.name);S.msg="Pengguna diaktifkan"}save()}catch(e){S.msg=ER(e)}render()}
function resetPin(){try{needP("pengguna.kelola","Hanya Admin Sistem yang dapat mereset PIN");const u=db.users.find(x=>x._id===S.rp);if(!u)throw Error("Pengguna tidak ditemukan");needSup(u);if(u._id===S.cu)throw Error("Untuk akun sendiri gunakan Ganti PIN");
 const p=$("#rp-p").value;pinChk(p,"rp-p");u.pin_salt=newSalt();u.pin_hash=pinHash(p,u.pin_salt);u.pin_set_at=now();u.must_change=true;u.fails=0;u.locked_until="";audit("pin_reset","user",u._id,"PIN direset Admin; wajib diganti saat masuk");S.rp=null;save();okM();S.msg="PIN sementara "+u.name+" diset; wajib diganti saat masuk"}catch(e){S.msg=ER(e)}render()}
IC_P.prof=IC_P.user;
const PROF_ROLE={admin:"Admin",pengurus:"Pengurus",pembaca:"Pembaca"};
function profWho(){const u=curUser(),c=typeof cloudCfg==="function"?cloudCfg():{},aw=!!(c.token&&c.email);
 if(u)return{k:"lokal",u,c:aw?c:null,name:u.name,role:(roleOf(u)||{}).name||"",sub:"Mode pengguna di perangkat ini"};
 if(aw)return{k:"awan",c,name:String(c.email).split("@")[0],email:c.email,role:PROF_ROLE[c.role]||"Pengguna",sub:c.bumdes_name||"Akun awan"};
 return null}
function usrChip(){const e=$("#usr");if(!e)return;const w=profWho();e.innerHTML=w?`<button class="b s usrp${S.tab==="prof"?" on":""}" onclick="go('prof')" title="Profil saya" aria-label="Akun saya: ${esc(w.name)}">${avA(w.name,0)}<span class="usn"><b>${esc(w.name)}</b><small>${esc(w.role)}</small></span></button>`+(w.k==="lokal"?`<button class="b s" onclick="doLogout()" aria-label="Keluar" title="Keluar">${ic("out")}</button>`:""):""}
const pkv=(k,v)=>`<div class="pkv"><span>${k}</span><b>${v}</b></div>`,pjm=t=>{try{return t?new Date(t).toLocaleString("id-ID",{day:"numeric",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"}):"-"}catch(e){return t||"-"}};
function profReset(){const w=profWho();if(!w||!w.c)return;S.lgem=w.c.email;cloudForgotEm(w.c.email)}
async function cloudForgotEm(e){try{S.clb=1;render();const ret=typeof location!=="undefined"?location.origin+(typeof rtBase==="function"?rtBase():location.pathname):"";await cloudReq("/auth/v1/recover"+(ret?"?redirect_to="+encodeURIComponent(ret):""),{method:"POST",body:{email:e},auth:false});S.msg="Tautan untuk mengatur ulang kata sandi sudah dikirim ke "+e+". Buka tautan itu di perangkat ini"}catch(x){S.msg="⚠ "+x.message}S.clb=0;render()}
const PF_ACT={login:"Masuk",logout:"Keluar",pin_ganti:"PIN diganti",pin_reset:"PIN direset",user_ubah:"Data pengguna diubah",user_buat:"Akun dibuat",akses_ditolak:"Akses ditolak"};
const pfAct=a=>{if(a.entity==="user"&&PF_ACT[a.action])return PF_ACT[a.action];const t=audEv(a).split(".").pop().toLowerCase();return t.charAt(0).toUpperCase()+t.slice(1)};
function vProf(){const w=profWho();
 if(!w)return dcard("Profil","Belum ada pengguna yang masuk",`<div class="empty">Tidak ada pengguna yang masuk. Aktifkan mode pengguna di Setelan atau masuk ke akun awan untuk memiliki profil.</div><div class="fl"><button class="b" onclick="S.su='usr';go('set')">Buka Pengguna & Peran</button></div>`,"");
 const u=w.u,c=w.c||(w.k==="awan"?w.c:null),all=TABS.filter(([k])=>k!=="prof"),acc=all.filter(([k])=>tabOk(k)).map(([k,l])=>l),r=u?roleOf(u):null,np=r?r.perms.length:0;
 const lg=u?db.audit_logs.filter(a=>a.action==="login"&&a.by_id===u._id).slice(-1)[0]:null,un=u?(u.unit_ids||[]).map(id=>(db.business_units.find(x=>x._id===id)||{}).name).filter(Boolean):[];
 const tm=t=>{try{return t?new Date(t).toLocaleTimeString("id-ID",{hour:"2-digit",minute:"2-digit"}):"-"}catch(e){return"-"}},dy=t=>{try{return t?new Date(t).toLocaleDateString("id-ID",{day:"numeric",month:"short",year:"numeric"}):""}catch(e){return""}};
 const kt=(k,v,sub,ico,tn)=>`<div class="card kp"><div class="kh"><span class="kic ${tn}">${ic(ico)}</span><span class="k">${k}</span></div><div class="v">${v}</div><div class="s2">${sub}</div></div>`;
 const ct=[u&&u.phone,u&&u.address].filter(Boolean).map(esc).join(" · ");
 let h=`<section class="card dc pfh"><span class="bi pfa" style="background:var(--c1)" aria-hidden="true">${esc((w.name||"?").trim().charAt(0).toUpperCase())}</span><div class="pfn"><h2>${esc(w.name)}</h2><span class="bdg ok">${esc(w.role||"Pengguna")}</span><div class="k">${esc(u?(un.length?un.join(", "):"Semua unit"):w.sub)}${ct?" · "+ct:""}</div></div><button class="b s pfx" onclick="${w.k==="lokal"?"doLogout()":"cloudLogout()"}">${ic("out")} Keluar</button></section>`;
 h+=`<div class="g dk pft">`+(u?kt("Menu dapat dibuka",acc.length,"dari "+all.length+" menu","dash","t1")+kt("Izin peran",np,esc(w.role||"-"),"flag","t3")+kt("Masuk sejak",esc(tm(lg&&lg.at)),esc(dy(lg&&lg.at)||"Belum tercatat"),"cal","t5"):kt("Menu dapat dibuka",acc.length,"dari "+all.length+" menu","dash","t1")+kt("Peran akun awan",esc(PROF_ROLE[c&&c.role]||"Pengguna"),esc(c&&c.bumdes_name||"-"),"flag","t3")+kt("Sinkron terakhir",esc(c&&c.last?tm(+c.last||c.last):"-"),esc(c&&c.last?dy(+c.last||c.last):"Belum pernah"),"cal","t5"))+`</div>`;
 const rows=[];
 if(u)rows.push(pkv("Peran",esc(w.role||"-")),pkv("Unit usaha",un.length?esc(un.join(", ")):"Semua unit"),pkv("Status",u.status==="aktif"?'<span class="bdg ok">Aktif</span>':'<span class="bdg bd">Nonaktif</span>'),pkv("Akun dibuat",esc(tglS(wd(u.created_at))||"-")),pkv("PIN terakhir diganti",esc(pjm(u.pin_set_at))));
 if(c)rows.push(pkv("Email",esc(c.email)),pkv("Peran akun awan",esc(PROF_ROLE[c.role]||"Pengguna")),pkv("BUMDes",esc(c.bumdes_name||"-")));
 let b=dcard("Identitas",u?"Akun yang sedang masuk":"Akun awan yang sedang masuk",rows.join(""),"");
 if(u){const E=(k,l,v,x)=>`<div class="pff${x?" w":""}"><label for="${k}">${l}</label><input id="${k}"${k==="pf-p"?' type="tel"':""} maxlength="${k==="pf-a"?200:k==="pf-p"?20:60}" autocomplete="${k==="pf-n"?"name":k==="pf-p"?"tel":"street-address"}" value="${esc(v||"")}"></div>`;
  b+=dcard("Ubah data saya","Nama, telepon, dan alamat"+(u.employee_id?" · ikut memperbarui data pegawai Anda":""),`<div class="pfg">${E("pf-n","Nama",u.name,1)}${E("pf-p","Telepon",u.phone)}${E("pf-a","Alamat",u.address)}</div><div class="k">Peran, unit tugas, dan status hanya dapat diubah oleh Admin Sistem.</div><div class="fl"><button class="b" onclick="saveProf()">Simpan perubahan</button></div>`,"");
  const po=!!(S.dx&&S.dx.pfp);
  b+=`<section class="card dc"><details class="sx pfs"${po?" open":""} ontoggle="dxSetD('pfp',this.open,0)"><summary>Ganti PIN <span class="stc">4–8 angka</span></summary><div class="pfb"><div class="pfg"><div class="pff w"><label for="cp-o">PIN lama</label>${PW("cp-o","current-password")}</div><div class="pff"><label for="cp-n">PIN baru (4–8 angka)</label>${PW("cp-n","new-password")}</div><div class="pff"><label for="cp-r">Ulangi PIN baru</label>${PW("cp-r","new-password")}</div></div><div class="fl"><button class="b" onclick="chgPin()">Ganti PIN</button></div></div></details></section>`}
 if(c)b+=dcard("Kata sandi akun awan","Tautan pengaturan ulang dikirim ke email Anda",`<div class="fl"><button class="b s" onclick="profReset()"${S.clb?" disabled":""}>Kirim tautan atur ulang kata sandi</button><button class="b s" onclick="awGo()">Pengaturan awan</button></div>`,"");
 b+=dcard("Akses saya",acc.length+" menu dapat dibuka",`<div class="pfm">${acc.map(x=>`<span class="bdg ok">${esc(x)}</span>`).join("")}</div>${u?`<div class="k">${np} izin dari peran ${esc(w.role)}</div>`:`<div class="k">Hak akses mengikuti peran akun awan.</div>`}`,"");
 if(u){const L=db.audit_logs.filter(a=>a.by_id===u._id).slice(-5).reverse();b+=dcard("Aktivitas terakhir",L.length+" aktivitas",L.length?`<div class="upl">${L.map(a=>`<div class="upr adr"><span class="upm"><b>${esc(pfAct(a))}</b><small>${esc(a.detail&&a.detail!==pfAct(a)?a.detail:"")}</small></span><span class="upa"><small>${esc(pjm(a.at))}</small></span></div>`).join("")}</div>`:'<div class="empty">Belum ada aktivitas.</div>',"")}
 return `<div class="pfw2">${h}<div class="pfc2">${b}</div></div>`}
function gate(){const el=$("#lock");if(!el)return false;if(!rbacOn()){el.className="";el.innerHTML="";return false}
 const u=curUser();if(u&&!u.must_change){el.className="";el.innerHTML="";return false}lockRender(el,u);return true}
const PW=(id,ac)=>`<input id="${id}" type="password" inputmode="numeric" maxlength="8" autocomplete="${ac}">`;
function lockRender(el,u){unitHome();["#main","#sb","#bn","#sheet","#usr"].forEach(x=>{const n=$(x);if(n)n.innerHTML=""});const nm=bnm();document.title=nm+" · Masuk";
 let h;
 if(u)h=`<div class="lk"><h1>${esc(nm)}</h1><p class="k">Halo, ${esc(u.name)}. PIN Anda masih sementara — buat PIN baru untuk melanjutkan.</p><div class="card"><label>PIN sementara</label>${PW("cp-o","current-password")}<label>PIN baru (4–8 angka)</label>${PW("cp-n","new-password")}<label>Ulangi PIN baru</label>${PW("cp-r","new-password")}<button class="b" onclick="chgPin()">Simpan PIN baru</button><button class="b s" onclick="doLogout()">Keluar</button></div></div>`;
 else{const us=db.users.filter(x=>x.status==="aktif");
  h=`<div class="lk"><h1>${esc(nm)}</h1><p class="k">Masuk untuk melanjutkan.</p><div class="card"><label>Pengguna</label><select id="lg-u" onchange="S.lgu=this.value">${opt(us,x=>[x._id,x.name+" — "+((roleOf(x)||{}).name||"")],S.lgu||"")}</select><label>PIN</label><input id="lg-p" type="password" inputmode="numeric" maxlength="8" autocomplete="current-password" onkeydown="if(event.key==='Enter')loginUI()">${S.lge?`<div class="fe" role="alert">${esc(S.lge)}</div>`:""}<button class="b" onclick="loginUI()">Masuk</button></div>
<details${S.lrec?" open":""} ontoggle="S.lrec=this.open"><summary>Lupa PIN?</summary><p class="k">Minta Admin Sistem lain mereset PIN Anda (Setelan &gt; Pengguna &amp; Peran). Jika satu-satunya Admin lupa PIN atau akunnya terkunci, pulihkan dari file backup yang PIN-nya masih diketahui.</p><textarea id="bk" rows="4" placeholder="Tempel isi backup JSON di sini"></textarea><input type="file" accept=".json" aria-label="Pilih berkas backup JSON" onchange="fl(this)"><button class="b s" onclick="impAsk()">Pulihkan dari backup</button></details></div>`}
 el.innerHTML=h;el.className="on";cfr();
 if(S.fe){const f=$("#"+S.fe.id);if(f&&f.insertAdjacentHTML){f.classList.add("er");f.insertAdjacentHTML("afterend",`<div class="fe" role="alert">${esc(S.fe.m)}</div>`)}S.fe=null}
 if(S.msg){toast(S.msg,/^⚠/.test(S.msg));if(typeof setTimeout==="function")setTimeout(()=>{S.msg=""},0)}
 const f=$(u?"#cp-o":"#lg-p");if(f&&f.focus)f.focus()}
function rolesCard(){const R=db.roles.filter(r=>r.status!=="nonaktif"&&(r._id!=="ROL-SUP"||cuSup())),ed=!!(rbacOn()&&curUser()&&can("pengguna.kelola"));
 return`<h2>Peran dan Izin</h2>`+dcard("Matriks izin","Izin ditegakkan di fungsi aksi (bukan sekadar menyembunyikan tombol), menu menyesuaikan peran, dan pengguna dengan unit tugas hanya bisa mencatat di unit itu. "+(ed?"Centang untuk memberi atau mencabut izin; setiap perubahan tercatat di audit log.":"Hanya Admin Sistem yang dapat mengubah izin.")+" Ini kontrol prosedur, bukan keamanan sungguhan (data di browser). Geser tabel ke samping bila perlu.",tbl(["Izin",...R.map(r=>r.name)],PERMS.map(([k,d])=>`<tr><td>${esc(d)}</td>${R.map(r=>`<td>${ed&&r._id!=="ROL-SUP"?`<input type="checkbox" aria-label="${esc(r.name+": "+d)}"${r.perms.includes(k)?" checked":""} onchange="togPerm('${r._id}','${k}')">`:r.perms.includes(k)?"✓":"—"}</td>`).join("")}</tr>`).concat(`<tr><th>Jumlah izin</th>${R.map(r=>`<th>${r.perms.length}</th>`).join("")}</tr>`)),"")+(ed?dcard("Kembalikan ke bawaan","Mengembalikan izin peran bawaan (Direktur, Bendahara, Petugas Unit, dan lainnya) ke pengaturan awal. Peran buatan sendiri dan Superadmin tidak berubah.",`<button class="b s" onclick="askC('rolesReset','')">Kembalikan matriks ke bawaan</button>`,""):"")}
function togPerm(rid,p){try{needP("pengguna.kelola","Hanya Admin Sistem yang dapat mengubah izin peran");const r=db.roles.find(x=>x._id===rid);if(!r||!PD[p])throw Error("Peran atau izin tidak ditemukan");if(r._id==="ROL-SUP")throw Error("Izin Superadmin selalu lengkap dan tidak dapat diubah");
 const has=r.perms.includes(p);
 if(has&&p==="pengguna.kelola"){const cu=curUser();if(cu&&cu.role_id===rid)throw Error("Tidak dapat mencabut Kelola pengguna dari peran Anda sendiri");const sisa=db.users.some(u=>u.status==="aktif"&&u.role_id!==rid&&(roleOf(u)||{perms:[]}).perms.includes("pengguna.kelola"));if(!sisa)throw Error("Kelola pengguna tidak boleh dicabut: tidak akan ada Admin Sistem aktif tersisa")}
 r.perms=has?r.perms.filter(x=>x!==p):r.perms.concat(p);audit("peran_izin","role",rid,r.name+": "+(has?"cabut ":"beri ")+PD[p]);save();S.msg="Izin "+r.name+" diperbarui"}catch(e){S.msg=ER(e)}render()}
function vUsr(){const on=rbacOn(),cu=curUser();let h=`<h2>Pengguna & Peran</h2>`;
 if(!on){const ex=db.users.filter(isAdm);
  return h+dcard("Aktifkan mode pengguna","Mode pengguna <b>belum aktif</b>: siapa pun yang membuka aplikasi ini dapat melakukan semua hal. Mengaktifkannya menambah login PIN, peran, dan jejak “oleh siapa” di audit log.",`<p class="k"><b>Catatan penting:</b> data tersimpan di browser ini, jadi mode ini hanya <b>kontrol prosedur</b> (pemisahan tugas dan jejak), bukan keamanan sungguhan — orang yang paham teknis masih bisa melewatinya lewat DevTools atau file backup. Penegakan sebenarnya menunggu backend (Fase 10). Export backup dulu sebelum mengaktifkan.</p>`
   +(ex.length?`<label>Admin Sistem</label><select id="us-a">${opt(ex,u=>[u._id,u.name],"")}</select><label>PIN Admin</label>${PW("us-p","current-password")}`:`<label>Nama Admin Sistem *</label><input id="us-n" autocomplete="off"><label>PIN (4–8 angka) *</label>${PW("us-p","new-password")}<label>Ulangi PIN *</label>${PW("us-p2","new-password")}`)
   +`<button class="b" onclick="enableRbac()">${ex.length?"Aktifkan kembali":"Aktifkan mode pengguna"}</button>`,"")+rolesCard()}
 if(!cu)return h;
 h+=dcard("Akun saya",esc(cu.name)+" · "+esc((roleOf(cu)||{}).name||""),`<div class="k">Ubah data diri, ganti PIN, dan keluar ada di halaman Profil.</div><div class="fl"><button class="b s" onclick="go('prof')">${ic("user")} Buka Profil saya</button></div>`,"");
 if(!can("pengguna.kelola"))return h+`<p class="k">Pengelolaan pengguna dan peran hanya untuk Admin Sistem.</p>`;
 const act=db.users.filter(isAdm).length;
 const UL=db.users.filter(u=>!isSup(u)||cuSup());
 const nAk=UL.filter(u=>u.status==="aktif").length,kt=(k,v,sb,ico,tn)=>`<div class="card kp"><div class="kh"><span class="kic ${tn}">${ic(ico)}</span><span class="k">${k}</span></div><div class="v">${v}</div><div class="s2">${sb}</div></div>`;
 h+=`<h2>Daftar Pengguna</h2><div class="g dk">${kt("Pengguna aktif",nAk,"dari "+UL.length+" pengguna","user","t1")+kt("Nonaktif",UL.length-nAk,"tidak dapat masuk","lock","t3")+kt("Admin Sistem aktif",act,act<2?"disarankan minimal 2":"cukup","key",act<2?"t4":"t5")+kt("Peran",db.roles.filter(r=>r.status!=="nonaktif"&&(r._id!=="ROL-SUP"||cuSup())).length,"lihat matriks izin","flag","t2")}</div><div class="fl"><button class="b ad" onclick="mdOpen('us','')">${ic("plus")}<span>Tambah pengguna</span></button><button class="b s" id="us-dp" onclick="usDariPegawai()">Buat pengguna dari pegawai (PIN awal 1234)</button></div>`
  +dcard("Pengguna aplikasi",UL.length+" pengguna · "+UL.filter(u=>u.status==="aktif").length+" aktif"+(act<2?". ⚠ Hanya ada satu Admin Sistem aktif. Disarankan menambah satu lagi agar PIN yang terlupa bisa direset.":""),UL.length?`<div class="upl">${UL.map((u,i)=>`<div class="upr alr usr${u.status==="aktif"?"":" vd"}">${avA(u.name,i)}<span class="upm"><b>${esc(u.name)}${u._id===S.cu?" (Anda)":""}</b><small>${esc((roleOf(u)||{}).name||"?")} · ${esc((u.unit_ids||[]).map(unitName).join(", ")||"Semua unit")}${u.must_change?" · PIN sementara":""}${isLocked(u)?" · Terkunci":""}</small></span><span class="upa"><span class="bdg ${u.status==="aktif"?"ok":"wr"}">${u.status==="aktif"?"Aktif":"Nonaktif"}</span><span class="alb">${ib("edit","Edit","mdOpen('us','"+u._id+"')","s")}${u._id!==S.cu?ib("key","Reset PIN","mdOpen('rp','"+u._id+"')","s")+ib(u.status==="aktif"?"x":"check",u.status==="aktif"?"Nonaktifkan":"Aktifkan","askC('togUser','"+u._id+"')","s"):""}</span></span></div>`).join("")}</div>`:'<div class="empty">Belum ada pengguna.</div>',"");
 return h+rolesCard()+`<h2>Mode Pengguna</h2>`+dcard("Keluar otomatis","Pengguna otomatis keluar bila tidak ada aktivitas, supaya layar yang ditinggalkan tidak dipakai orang lain.",`<label for="idle-m">Keluar bila tidak aktif selama</label><select id="idle-m" aria-label="Batas waktu tidak aktif" onchange="setIdle(this.value)">${IDLE_OPT.map(x=>`<option value="${x}"${idleMin()===x?" selected":""}>${x?x+" menit":"Jangan keluar otomatis"}</option>`).join("")}</select>`,"")+dcard("Matikan mode pengguna","Mematikan mode membuat aplikasi terbuka tanpa login; data pengguna tetap tersimpan.",`<button class="b x" onclick="askC('rbacOff','')">Matikan mode pengguna</button>`,"dz")}


// pilih pegawai saat membuat pengguna: nama, unit, dan peran (bawaan jabatan) terisi otomatis
function usPick(){const e=db.employees.find(x=>x._id===$("#us-e").value);if(!e)return;$("#us-n").value=e.name;const x=posGet(e.position),r=x&&x.role_id&&db.roles.find(q=>q._id===x.role_id&&q.status!=="nonaktif"&&q._id!=="ROL-SUP");if(r)$("#us-r").value=r._id;
 db.business_units.forEach(b=>{const c=$("#us-u-"+b._id);if(c)c.checked=!!e.unit_id&&e.unit_id===b._id})}

// PIN awal bawaan; wajib diganti saat masuk pertama (must_change). Pengganti PIN tidak boleh sama dengan PIN lama, jadi 1234 tidak bisa dipertahankan.
const PIN0="1234";
// buat akun untuk semua pegawai aktif yang belum punya akun: peran dari bawaan jabatan, unit dari unit pegawai, PIN awal 1234
function usDariPegawai(){try{needP("pengguna.kelola","Hanya Admin Sistem yang dapat mengelola pengguna");posSync();let n=0,s=0;const nm=new Set(db.users.map(x=>x.name.toLowerCase()));
 db.employees.filter(isAct).forEach(e=>{if(db.users.some(x=>x.employee_id===e._id)||nm.has(e.name.toLowerCase()))return;const p=posGet(e.position),r=p&&p.role_id&&db.roles.find(q=>q._id===p.role_id&&q.status!=="nonaktif"&&q._id!=="ROL-SUP");if(!r){s++;return}
  const x=mkUser(e.name,r._id,e.unit_id?[e.unit_id]:[],PIN0,true);x.employee_id=e._id;db.users.push(x);nm.add(e.name.toLowerCase());n++;audit("user_buat","user",x._id,e.name+" · "+r.name+" · dari pegawai "+e.emp_number)});
 if(n){usDr();save()}S.msg=n?n+" pengguna dibuat dari pegawai (PIN awal "+PIN0+", wajib diganti saat masuk pertama)"+(s?"; "+s+" pegawai dilewati karena jabatannya belum punya peran bawaan":""):(s?s+" pegawai dilewati: atur peran bawaan di Daftar jabatan dulu":"Semua pegawai aktif sudah punya akun")}catch(e){S.msg="⚠ "+e.message}render()}


// ===== v1.1.159 — RBAC sisa kecil: kembalikan matriks izin ke bawaan dan keluar otomatis saat tidak aktif =====
function rolesReset(){try{needP("pengguna.kelola","Hanya Admin Sistem yang dapat mengubah izin peran");const def=Object.fromEntries(ROLES0.map(x=>[x[0],x[3]]));
 const after=r=>def[r._id]&&r._id!=="ROL-SUP"?def[r._id]:r.perms;
 if(!db.users.some(u=>u.status==="aktif"&&(db.roles.find(r=>r._id===u.role_id)?after(db.roles.find(r=>r._id===u.role_id)):[]).includes("pengguna.kelola")))throw Error("Tidak dapat dikembalikan: tidak akan ada Admin Sistem aktif tersisa");
 let n=0;db.roles.forEach(r=>{if(def[r._id]&&r._id!=="ROL-SUP"){const d=def[r._id];if(d.length!==r.perms.length||d.some(p=>!r.perms.includes(p))){r.perms=d.slice();n++}}});
 audit("peran_izin","role","*","Matriks izin dikembalikan ke bawaan ("+n+" peran berubah)");save();S.msg=n?"Matriks izin dikembalikan ke bawaan ("+n+" peran berubah)":"Matriks izin sudah sama dengan bawaan"}catch(e){S.msg=ER(e)}render()}
const IDLE_OPT=[0,5,15,30,60];
const idleMin=()=>{const v=db&&db.settings?db.settings.idle_min:0;return IDLE_OPT.includes(v)?v:0};
function setIdle(v){try{needP("pengguna.kelola","Hanya Admin Sistem yang dapat mengatur batas waktu");v=+v;if(!IDLE_OPT.includes(v))throw Error("Pilihan tidak dikenal");db.settings.idle_min=v;S.idleAt=Date.now();audit("setting","settings","idle_min","Keluar otomatis: "+(v?v+" menit tidak aktif":"dimatikan"));save();S.msg=v?"Keluar otomatis setelah "+v+" menit tidak aktif":"Keluar otomatis dimatikan"}catch(e){S.msg=ER(e)}render()}
function idleCheck(t){const m=idleMin();if(!m||!rbacOn()||!S.cu)return false;t=t||Date.now();if(!S.idleAt){S.idleAt=t;return false}if(t-S.idleAt<=m*60000)return false;
 const u=curUser();if(u)audit("logout","user",u._id,"Keluar otomatis: tidak aktif "+m+" menit");S.cu=null;ssS(null);S.dr={};S.doc=null;S.pp=null;S.cf=null;S.md=null;S.msg="";S.lge="Sesi berakhir karena tidak aktif selama "+m+" menit. Masuk lagi untuk melanjutkan.";S.idleAt=0;save();render();return true}
if(typeof window!=="undefined"&&window.addEventListener&&typeof document!=="undefined"&&document.addEventListener){["click","keydown","touchstart"].forEach(e=>document.addEventListener(e,()=>{S.idleAt=Date.now()},true));setInterval(()=>idleCheck(),15000)}
