// ===== UNIT AIR (v0.1.009): pelanggan, produk, penjualan tunai/kredit, piutang =====
const cust=id=>db.parties.find(p=>p._id===id)||{name:"Umum"};
const paidOf=x=>db.payments.filter(p=>p.sale_id===x._id&&p.status!=="voided").reduce((a,p)=>a+p.amount,0);
const owedS=x=>x.status!=="posted"||x.payment_type==="cash"?0:Math.round((x.total-paidOf(x))*100)/100;
const ferr=(e,m)=>{S.msg="⚠ "+e.message;S.fe=e.f?{id:e.f,m:e.message}:null;render()};
const isAct=x=>x.status!=="nonaktif",piu=id=>db.sales.filter(x=>x.party_id===id).reduce((a,x)=>a+owedS(x),0);
function savePel(){try{const n=$("#pl-n").value.trim();if(!n)throw fe("pl-n","Nama pelanggan wajib");const f={name:n,phone:$("#pl-p").value.trim(),address:$("#pl-a").value.trim()};
 if(dupP("pelanggan",n,f.phone,f.address,S.ep))throw fe("pl-n","Pelanggan dengan nama, telepon, dan alamat yang sama sudah ada");
 if(S.ep){Object.assign(db.parties.find(x=>x._id===S.ep),f);audit("update","party",S.ep);S.ep=null;S.msg="Data pelanggan diperbarui"}
 else{const x={_id:uid("PTY"),type:"pelanggan",...f,status:"aktif"};db.parties.push(x);audit("create","party",x._id);S.msg="Pelanggan ditambahkan"}save();clrF("#pl-n,#pl-p,#pl-a");okM()}catch(e){S.msg="⚠ "+e.message;S.fe=e.f?{id:e.f,m:e.message}:null}render()}
function togPel(id){try{const x=db.parties.find(q=>q._id===id);
 if(isAct(x)){if(piu(id)>0.005)throw Error("Pelanggan masih punya piutang Rp "+fm(piu(id))+"; selesaikan dulu");x.status="nonaktif";if(S.ep===id)S.ep=null;audit("deactivate","party",id);S.msg="Pelanggan dinonaktifkan"}
 else{x.status="aktif";audit("activate","party",id);S.msg="Pelanggan diaktifkan"}save()}catch(e){S.msg="⚠ "+e.message}render()}
function saveProd(){try{negAny();const v=i=>$("#"+i).value.trim(),h=+pn(v("pr-h"));if(!v("pr-n"))throw fe("pr-n","Nama produk wajib");if(!(h>0))throw fe("pr-h","Harga harus lebih dari 0");
 const f={unit_id:v("pr-u"),name:v("pr-n"),unit:v("pr-s")||"unit",price:h,revenue_account:v("pr-a")};
 if(S.epr){Object.assign(db.products.find(x=>x._id===S.epr),f);audit("update","product",S.epr);S.epr=null;S.msg="Produk diperbarui; berlaku untuk penjualan berikutnya"}
 else{const x={_id:uid("PRD"),...f,status:"aktif"};db.products.push(x);audit("create","product",x._id);S.msg="Produk ditambahkan"}save();clrF("#pr-n,#pr-s,#pr-h");okM()}catch(e){S.msg="⚠ "+e.message;S.fe=e.f?{id:e.f,m:e.message}:null}render()}
function togProd(id){const x=db.products.find(q=>q._id===id);x.status=isAct(x)?"nonaktif":"aktif";if(S.epr===id&&!isAct(x))S.epr=null;audit(isAct(x)?"activate":"deactivate","product",id);save();S.msg=isAct(x)?"Produk diaktifkan":"Produk dinonaktifkan";render()}
function jLine(){const v=i=>$("#"+i).value.trim(),p=db.products.find(x=>x._id===v("j-p")),q=+pn(v("j-q")),hr=v("j-h"),h=hr?+pn(hr):(p&&p.price);
 if(!p||!isAct(p))throw fe("j-p","Pilih produk aktif dulu (tambahkan di sub-tab Produk)");if(!(q>0))throw fe("j-q","Jumlah harus lebih dari 0");if(!(h>0))throw fe("j-h","Harga satuan harus lebih dari 0");
 const c0=(S.cart||[])[0],cu=c0&&(db.products.find(x=>x._id===c0.p)||{}).unit_id;
 if(cu&&p.unit_id!==cu)throw fe("j-p","Semua barang dalam satu penjualan harus dari unit yang sama ("+unitName(cu)+")");
 return{p:p._id,q,h}}
function jAdd(){try{const z=jLine();S.cart=(S.cart||[]).concat([z]);clrF("#j-q,#j-h");S.msg=""}catch(e){ferr(e);return}render()}
function jDel(i){(S.cart||[]).splice(i,1);render()}
function jual(){try{negAny();const v=i=>$("#"+i).value.trim(),d=v("j-d"),ty=v("j-t"),k=db.cash_accounts.find(c=>c._id===v("j-k"));
 if(!d)throw fe("j-d","Tanggal wajib diisi");
 const its=(S.cart||[]).slice();if(v("j-q")||!its.length)its.push(jLine());
 if(ty==="credit"&&!v("j-c"))throw fe("j-c","Penjualan kredit wajib memilih pelanggan");if(v("j-c")&&!isAct(cust(v("j-c"))))throw fe("j-c","Pelanggan nonaktif; aktifkan dulu atau pilih Umum");if(ty==="cash"&&!k)throw fe("j-k","Pilih kas/bank");
 const P=its.map(z=>({...z,pr:db.products.find(x=>x._id===z.p)})),sub=z=>Math.round(z.q*z.h*100)/100,tot=Math.round(P.reduce((a,z)=>a+sub(z),0)*100)/100,R={};
 P.forEach(z=>{R[z.pr.revenue_account]=(R[z.pr.revenue_account]||0)+sub(z)});
 const dc=discFor(($("#j-ds")||{}).value||"","penjualan",tot);if(dc&&dc.amt>=tot)throw fe("j-ds","Diskon tidak boleh melebihi total penjualan");
 if(dc){let left=dc.amt;const ks=Object.keys(R);ks.forEach((a,i)=>{const cut=i===ks.length-1?left:Math.round(dc.amt*R[a]/tot*100)/100;R[a]=Math.round((R[a]-cut)*100)/100;left=Math.round((left-cut)*100)/100})}
 const net=Math.round((tot-(dc?dc.amt:0))*100)/100;
 const nm=P.map(z=>z.pr.name+" x"+z.q).join(", "),un=P[0].pr.unit_id,
 t=post({type:ty==="cash"?"sale_cash":"sale_credit",date:d,unit:un,desc:"Penjualan "+(nm.length>90?nm.slice(0,87)+"…":nm)+" – "+cust(v("j-c")).name,lines:[{acc:ty==="cash"?k.account_id:"ACC1400",d:net}].concat(Object.entries(R).map(([a,c])=>({acc:a,c:Math.round(c*100)/100})))});
 const x={_id:uid("SAL"),sale_number:numNext("sale",d),unit_id:un,party_id:v("j-c")||null,date:d,payment_type:ty,total:net,cash_id:ty==="cash"?k._id:null,transaction_id:t._id,status:"posted",...(dc?{disc:dc}:{})};
 db.sales.push(x);P.forEach(z=>db.sale_items.push({_id:uid("SIT"),sale_id:x._id,product_id:z.p,qty:z.q,price:z.h,subtotal:sub(z)}));if(dc)db.sale_items.push({_id:uid("SIT"),sale_id:x._id,product_id:null,label:"Diskon "+dc.name,unit:"",qty:1,price:-dc.amt,subtotal:-dc.amt});audit("sale","sale",x._id,(P.length>1?P.length+" barang":"")+(dc?(P.length>1?" · ":"")+"diskon "+fm(dc.amt):"")||undefined);save();S.cart=[];clrF("#j-q,#j-h");S.msg="Penjualan "+x.sale_number+" dicatat"}catch(e){ferr(e);return}render()}
const avA=(n,i)=>`<span class="bi" style="background:var(--c${i%6+1})" aria-hidden="true">${esc((n||"?").trim().charAt(0).toUpperCase())}</span>`;
const notaBtn=x=>x.status==="posted"&&!x.opening?ib("print","Nota","openDoc('"+(x.bill?"tagih":"jual")+"','"+x._id+"')","s"):"";
const itemsNote=x=>{const it=db.sale_items.filter(i=>i.sale_id===x._id);return it.slice(0,2).map(i=>esc(i.label||(db.products.find(p=>p._id===i.product_id)||{}).name||"")+" ×"+qf(i.qty)).join(", ")+(it.length>2?" +"+(it.length-2)+" lainnya":"")};
function cartHtml(){const c=S.cart||[];if(!c.length)return"";let t=0;
 const rows=c.map((z,i)=>{const pr=db.products.find(x=>x._id===z.p)||{},sb=Math.round(z.q*z.h*100)/100;t+=sb;return`<tr><td>${esc(pr.name)}</td><td class="n">${qf(z.q)} ${esc(pr.unit||"")}</td><td class="n">${rp(z.h)}</td><td class="n">${rp(sb)}</td><td>${ib("x","Hapus","jDel("+i+")","x")}</td></tr>`});
 return`<h2>Daftar barang (${c.length})</h2>${tbl(["Barang","#Jumlah","#Harga","#Subtotal",""],rows)}<p><b>Total: ${rp(t)}</b> · Unit ${esc(unitName((db.products.find(x=>x._id===c[0].p)||{}).unit_id))}. Isi barang lain lalu <i>Tambah ke daftar</i>, atau langsung <i>Simpan penjualan</i>.</p>`}
function terima(id,px){px=px||"ar";try{negAny();const x=db.sales.find(q=>q._id===id),d=$("#"+px+"-d").value,k=db.cash_accounts.find(c=>c._id===$("#"+px+"-k").value),o=owedS(x),raw=pn($("#"+px+"-a").value||""),a=raw===""?o:+raw;
 if(!d)throw fe(px+"-d","Tanggal wajib diisi");if(!k)throw fe(px+"-k","Pilih kas/bank");if(d<x.date)throw fe(px+"-d","Tanggal bayar tidak boleh sebelum tanggal penjualan");
 if(!(a>0))throw fe(px+"-a","Jumlah harus lebih dari 0");if(a>o+.005)throw fe(px+"-a","Melebihi sisa piutang (Rp "+fm(o)+")");
 const lf=lateFine(x,d,o),fr=$("#"+px+"-f")?pn($("#"+px+"-f").value.trim()):"";let f=0;if(lf!==null){f=fr===""?lf:+fr;if(!isFinite(f)||f<0)throw fe(px+"-f","Denda tidak valid")}else if(fr!==""&&+fr>0)throw fe(px+"-f","Denda tidak berlaku untuk tagihan ini (belum terlambat, sudah pernah didenda, atau denda nonaktif)");
 f=Math.round(f);const t=post({type:"sale_pay",date:d,unit:x.unit_id,desc:"Pembayaran "+x.sale_number+" – "+cust(x.party_id).name+(f>0?" + denda":""),lines:[{acc:k.account_id,d:a+f},{acc:"ACC1400",c:a}].concat(f>0?[{acc:"ACC4210",c:f}]:[])}),pid=uid("PAY");
 db.payments.push({_id:pid,sale_id:x._id,date:d,amount:a,cash_id:k._id,transaction_id:t._id,status:"posted",...(lf!==null?{fine:f}:{})});if(lf!==null)x.fine_done={amt:f,date:d,pay:pid,auto:lf};audit("receive","sale",id,f>0?"denda Rp "+fm(f):lf!==null?"denda dibebaskan":undefined);save();clrF("#"+px+"-a,#"+px+"-f");S.msg="Pembayaran Rp "+fm(a)+" dicatat"+(f>0?" + denda Rp "+fm(f):"");if(S.md==="wb"){S.md=null;S.ewb=null;S.mv=null}}catch(e){ferr(e);return}render()}
function batalJual(id){try{const x=db.sales.find(q=>q._id===id);if(db.payments.some(p=>p.sale_id===id&&p.status!=="voided"))throw Error("Batalkan pembayaran piutang dulu");
 if(x.bill){const l=wRds(x.bill.conn_id).pop();if(l&&l.sale_id!==id)throw Error("Ada bacaan meter sesudahnya; batalkan tagihan atau ganti meter yang terbaru dulu")}
 rev(x.transaction_id);x.status="voided";if(x.bill)db.water_readings.forEach(r=>{if(r.sale_id===id)r.status="voided"});audit("void","sale",id);save();S.msg="Penjualan dibatalkan dengan jurnal pembalik"}catch(e){S.msg="⚠ "+e.message}render()}
function batalTerima(id){try{const y=db.payments.find(q=>q._id===id);rev(y.transaction_id);y.status="voided";{const sx=db.sales.find(q=>q._id===y.sale_id);if(sx&&sx.fine_done&&sx.fine_done.pay===id)delete sx.fine_done}audit("void","payment",id);save();S.msg="Pembayaran dibatalkan dengan jurnal pembalik"}catch(e){S.msg="⚠ "+e.message}render()}
function vAir(){const st=S.at||"baca",U=x=>S.unit==="all"||x.unit_id===S.unit,ss=db.sales.filter(U).sort((a,b)=>b.date.localeCompare(a.date)||b._id.localeCompare(a._id)),pel=db.parties.filter(p=>p.type==="pelanggan"),pelV=pel.filter(p=>wqHit(p)),pr=db.products.filter(U),ops=ss.filter(x=>owedS(x)>0),eP=db.parties.find(x=>x._id===S.ep),eR=db.products.find(x=>x._id===S.epr),SN=x=>db.sales.find(q=>q._id===x)||{};
 const wcs=db.water_connections.filter(U),ktp=[["baca","Baca Meter",wcs.filter(c=>c.status==="aktif").length],["samb","Sambungan",wcs.length],["piutang","Piutang",ops.length],["jual","Penjualan Lain",ss.length],["set","Pengaturan",null]],isSet=["tarif","pel","prod"].includes(st),rs="S.lim=0;S.wq='';S.wf='';S.wpf='';render()";
 const bar=tabBar(ktp.map(([k,n,c])=>[k,c==null?n:n+" ("+c+")"]),isSet?"set":st,k=>`S.at='${k==="set"?"tarif":k}';${rs}`)+(isSet?`<div class="stsub">${tabBar([["tarif","Tarif"],["pel","Pelanggan ("+pel.length+")"],["prod","Produk ("+pr.length+")"]],st,k=>`S.at='${k}';${rs}`)}</div>`:""),kas=opt(db.cash_accounts.filter(isAct),c=>[c._id,c.name]);
  const stB=x=>x.status==="voided"?'<span class="bdg">Batal</span>':x.payment_type==="credit"?(owedS(x)>0?'<span class="bdg wr">Belum lunas</span>':'<span class="bdg ok">Lunas</span>'):'<span class="bdg ok">Lunas</span>',
  sumO=ops.reduce((t,x)=>t+owedS(x),0),pays=db.payments.filter(y=>U(SN(y.sale_id))).slice().reverse();
 const P={jual:`${cartHtml()}${dcard("Penjualan baru","Tambahkan barang ke daftar, lalu pilih cara bayar",`<label>Tanggal</label><input id="j-d" type="date" value="${today()}"><label>Produk / layanan</label><select id="j-p">${opt(pr.filter(isAct),p=>[p._id,p.name+" – Rp "+fm(p.price)+"/"+p.unit])}</select><label>Jumlah</label><input id="j-q" type="text" inputmode="decimal" autocomplete="off"><label>Harga satuan (Rp) — kosong = harga produk</label><input id="j-h" type="text" inputmode="numeric" autocomplete="off" oninput="fmtR(this)"><button class="b s" onclick="jAdd()">Tambah ke daftar</button>${discOpts("penjualan")?`<label for="j-ds">Diskon</label><select id="j-ds">${discOpts("penjualan")}</select>`:""}<label>Cara bayar</label><select id="j-t"><option value="cash">Tunai</option><option value="credit">Kredit (piutang)</option></select><label>Pelanggan (wajib untuk kredit)</label><select id="j-c"><option value="">Umum</option>${opt(pel.filter(isAct),p=>[p._id,p.name])}</select><label>Kas/Bank (untuk tunai)</label><select id="j-k">${kas}</select><button class="b" onclick="jual()">Simpan penjualan</button>`,"alf")}
${dcard("Daftar Penjualan",ss.length+" penjualan"+(ss.length>(S.lim||PG)?" · tampil "+Math.min(ss.length,S.lim||PG):""),(ss.length?`<div class="upl">${ss.slice(0,S.lim||PG).map((x,i)=>{const nm=x.party_id?cust(x.party_id).name:"Umum",vd=x.status==="voided";return`<div class="upr alr${vd?" vd":""}">${avA(nm,i)}<span class="upm"><b>${esc(nm)}</b><small>${x.sale_number} · ${x.date}</small><small>${x.opening?"Saldo awal piutang":x.bill?billNote(x,1):itemsNote(x)} · ${x.payment_type==="cash"?"Tunai":"Kredit"}</small></span><span class="upa"><b>${rp(x.total)}</b>${stB(x)}<span class="alb">${notaBtn(x)}${x.status==="posted"?ib("undo","Batalkan","askC('batalJual','"+x._id+"')","x"):""}</span></span></div>`}).join("")}</div>`:'<div class="empty">Belum ada penjualan.</div>')+more(ss.length-Math.min(ss.length,S.lim||PG)),"")}`,
 piutang:`${(()=>{const pf=S.wpf||"",q=(S.wq||"").trim().toLowerCase(),late=x=>owedS(x)>0.005&&x.bill&&x.bill.due&&x.bill.due<today(),
  opsF=ops.filter(x=>(!pf||(pf==="air"?!!x.bill:pf==="lain"?!x.bill:late(x)))&&(!q||wqHit(x.party_id?cust(x.party_id):{name:"Umum"},x.bill&&x.bill.meter)||String(x.sale_number||"").toLowerCase().includes(q))),sumF=opsF.reduce((t,x)=>t+owedS(x),0),nLate=ops.filter(late).length,
  flt=`<div class="fl wsr"><input type="search" placeholder="Cari nama / no tagihan / no meter…" aria-label="Cari piutang" value="${esc(S.wq||"")}" onchange="S.wq=this.value;S.lim=0;S.pl=null;render()"><select aria-label="Filter jenis piutang" onchange="S.wpf=this.value;S.pl=null;render()"><option value="">Semua piutang</option><option value="air"${pf==="air"?" selected":""}>Tagihan air</option><option value="lain"${pf==="lain"?" selected":""}>Penjualan lain</option><option value="telat"${pf==="telat"?" selected":""}>Terlambat (${nLate})</option></select>${q||pf?`<button class="b s" onclick="S.wq='';S.wpf='';render()">Reset</button>`:""}</div>`;
  return dcard("Piutang Pelanggan",ops.length?(opsF.length<ops.length?opsF.length+" dari "+ops.length:ops.length)+" belum lunas · sisa "+rp(opsF.length<ops.length?sumF:sumO):"Semua penjualan sudah lunas",ops.length?flt+(opsF.length?`<div class="upl">${opsF.slice(0,pgLim("pcl")).map((x,i)=>{const nm=x.party_id?cust(x.party_id).name:"Umum",lt=late(x),pd=paidOf(x);return`<button class="upr nsr" onclick="mdOpen('wb','${x._id}')">${avA(nm,i)}<span class="upm"><b>${esc(nm)}</b><small>${x.sale_number} · ${x.bill?"Air "+esc(x.bill.period)+" · jatuh tempo "+esc(tglS(x.bill.due)):x.opening?"Saldo awal piutang":"Penjualan kredit · "+esc(tglS(x.date))}</small></span><span class="upa"><b>${rp(owedS(x))}</b>${lt?'<span class="bdg bd">Terlambat</span>':""}${pd>0?'<span class="bdg wr">Dibayar sebagian</span>':""}</span></button>`}).join("")}</div>${pgMore("pcl",opsF.length)}${btt(Math.min(opsF.length,pgLim("pcl")))}`:wNone()):`<div class="empty">Tidak ada piutang.</div>`,"")})()}
${dcard("Riwayat Pembayaran",pays.length+" pembayaran"+(pays.length>(S.lim||PG)?" · tampil "+(S.lim||PG):""),(pays.length?`<div class="upl">${pays.slice(0,S.lim||PG).map(y=>{const q=SN(y.sale_id),nm=q.party_id?cust(q.party_id).name:"Umum",vd=y.status==="voided";return`<div class="upr alr${vd?" vd":""}"><span class="tri in" aria-hidden="true">↓</span><span class="upm"><b>${esc(nm)}</b><small>${y.date} · ${q.sale_number}</small></span><span class="upa"><b>${rp(y.amount)}</b>${y.fine?`<small>+ denda ${rp(y.fine)}</small>`:""}${vd?'<span class="bdg">Batal</span>':'<span class="bdg ok">Diterima</span>'}${y.status==="posted"?`<span class="alb">${ib("print","Kuitansi","openDoc('kuit','"+y._id+"')","s")}${ib("undo","Batalkan","askC('batalTerima','"+y._id+"')","x")}</span>`:""}</span></div>`}).join("")}</div>`:'<div class="empty">Belum ada pembayaran.</div>')+more(pays.length-Math.min(pays.length,S.lim||PG)),"")}`,
 pel:`<h2>Pelanggan</h2>${addB("Tambah pelanggan","pl")}${dcard("Daftar Pelanggan",(pelV.length<pel.length?pelV.length+" dari "+pel.length:pel.length)+" pelanggan",pel.length?wSrch("Cari nama / telepon / alamat…")+(pelV.length?`<div class="upl">${pelV.slice(0,pgLim("pel")).map((p,i)=>`<div class="upr alr${isAct(p)?"":" vd"}">${avA(p.name,i)}<span class="upm"><b>${esc(p.name)}</b><small>${[p.phone,p.address].filter(Boolean).map(esc).join(" · ")||"Tanpa telepon dan alamat"}</small></span><span class="upa"><b>${rp(piu(p._id))}</b><small>piutang</small>${isAct(p)?"":'<span class="bdg">Nonaktif</span>'}<span class="alb">${ib("edit","Edit","openE('ep','"+p._id+"')","s")}${isAct(p)?ib("x","Nonaktifkan","togPel('"+p._id+"')","s"):ib("check","Aktifkan","togPel('"+p._id+"')","s")}</span></span></div>`).join("")}</div>${pgMore("pel",pelV.length)}${btt(Math.min(pelV.length,pgLim("pel")))}`:wNone()):'<div class="empty">Belum ada pelanggan.</div>',"")}
`,
 prod:`<h2>Produk / Layanan</h2>${addB("Tambah produk","pr")}${dcard("Daftar Produk",pr.length+" produk / layanan",pr.length?`<div class="upl">${pr.map((p,i)=>`<div class="upr alr${isAct(p)?"":" vd"}">${avA(p.name,i)}<span class="upm"><b>${esc(p.name)}</b><small>${esc(unitName(p.unit_id))} · per ${esc(p.unit)}</small><small>${esc((acc(p.revenue_account)||{}).name||"")}</small></span><span class="upa"><b>${rp(p.price)}</b><small>/ ${esc(p.unit)}</small>${isAct(p)?"":'<span class="bdg">Nonaktif</span>'}<span class="alb">${ib("edit","Edit","openE('epr','"+p._id+"')","s")}${isAct(p)?ib("x","Nonaktifkan","togProd('"+p._id+"')","s"):ib("check","Aktifkan","togProd('"+p._id+"')","s")}</span></span></div>`).join("")}</div>`:'<div class="empty">Belum ada produk.</div>',"")}
`};
 const W={baca:vBaca,samb:vSamb,tarif:vTarif};return bar+(W[st]?W[st]():(P[st]||P.jual))}
// ===== UNIT AIR – LANGGANAN / PAMSIMAS (v0.1.024): sambungan & meter, tarif bertingkat, baca meter → tagihan bulanan =====
const addDays=(d,n)=>{const t=new Date(d+"T00:00:00Z");t.setUTCDate(t.getUTCDate()+n);return t.toISOString().slice(0,10)};
const airCfg=()=>db.settings.air||AIRDEF();
function hitungAir(u,c){c=c||airCfg();const bl=Math.max(u,+c.min_m3||0),rows=[];let pv=0,w=0;
 for(const t of c.tiers){const hi=t.upto==null?Infinity:+t.upto,q=Math.min(bl,hi)-pv;if(q>0){const v=Math.round(q*t.price);rows.push({q,price:+t.price,v});w+=v}pv=hi;if(bl<=hi)break}
 const ab=Math.round(+c.abon||0);return{usage:u,billed:bl,rows,water:w,abon:ab,total:w+ab}}
const wConn=id=>db.water_connections.find(c=>c._id===id)||{};
const wRds=id=>db.water_readings.filter(r=>r.conn_id===id&&r.status!=="voided");
const wPrev=id=>{const l=wRds(id).pop();return l?l.curr:(+wConn(id).initial||0)};
const wLastB=id=>wRds(id).filter(r=>r.kind==="baca").pop();
const billOf=(cid,per)=>db.sales.find(x=>x.bill&&x.bill.conn_id===cid&&x.bill.period===per&&x.status==="posted");
const arrears=cid=>db.sales.filter(x=>x.bill&&x.bill.conn_id===cid&&owedS(x)>0.005);
const billNote=(x,short)=>{const b=x.bill;if(!b)return"";if(short)return"Tagihan air "+b.period+" · "+qf(b.usage)+" m³";const late=owedS(x)>0.005&&b.due&&b.due<today();return"Air "+b.period+" · "+qf(b.usage)+" m³ · jatuh tempo "+b.due+(late?" ⚠ terlambat":"")};
const clrDr=p=>{if(S.dr)Object.keys(S.dr).forEach(k=>{if(k.startsWith(p))delete S.dr[k]});S.nsnap=1};
// pencarian pelanggan Unit Air (nama, telepon, alamat, nomor meter) dipakai di Baca Meter, Sambungan, dan Pelanggan
const wqHit=(p,m)=>{const q=(S.wq||"").trim().toLowerCase();return!q||[p.name,p.phone,p.address,m].filter(Boolean).join(" ").toLowerCase().includes(q)};
const wSrch=ph=>`<div class="fl wsr"><input type="search" placeholder="${ph}" aria-label="Cari pelanggan" value="${esc(S.wq||"")}" onchange="S.wq=this.value;S.lim=0;render()">${(S.wq||"").trim()?`<button class="b s" onclick="S.wq='';render()">Reset</button>`:""}</div>`;
const wNone=()=>`<div class="empty em"><p>Tidak ada pelanggan yang cocok dengan “${esc((S.wq||"").trim())}”.</p></div>`;
function bpChg(v){S.bp=v;clrDr("air|bm");render()}
function bilTxt(cid,v){const raw=pn(String(v||"").trim());if(raw==="")return"";const cu=+raw,pv=wPrev(cid);
 if(!isFinite(cu)||cu<0)return"⚠ angka tidak valid";if(cu<pv)return"⚠ lebih kecil dari angka awal";const us=Math.round((cu-pv)*100)/100;const cc=wConn(cid),hh=hitungAir(us,airCfgFor(cc)),dd=discFor(cc.disc,"tagihan",hh.total);return qf(us)+" m³ → Rp "+fm(hh.total-(dd?dd.amt:0))+(dd?" (diskon "+fm(dd.amt)+")":"")}
function bmPrev(cid){const e=$("#bm_"+cid),h=$("#bm_"+cid+"-h");if(!e||!h)return;h.textContent=bilTxt(cid,e.value)}
function wdPrev(){const e=$("#wd-a"),h=$("#wd-pv");if(!e||!h)return;h.textContent=bilTxt(S.ewd,e.value)}
// pemeriksaan periode dan validasi satu sambungan dipakai bersama oleh tagihan massal (Baca Meter) dan modal detail
function bilChk(per,d,ip,id){if(!/^\d{4}-\d{2}$/.test(per))throw fe(ip,"Pilih bulan pemakaian");if(!d)throw fe(id,"Tanggal tagihan wajib diisi");
 if(d.slice(0,7)<per)throw fe(id,"Tanggal tagihan tidak boleh sebelum bulan pemakaian");if(closed(d))throw fe(id,"Periode "+d.slice(0,7)+" sudah ditutup");
 if((acc("ACC4200")||{}).status==="nonaktif")throw Error("Akun 4200 Pendapatan Air nonaktif")}
function bilPrep(c,per,raw,id){const cu=+raw,pv=wPrev(c._id),lb=wLastB(c._id);
 if(!isFinite(cu)||cu<0)throw fe(id,c.meter_no+": angka meter tidak valid");
 if(billOf(c._id,per))throw fe(id,c.meter_no+" sudah ditagih untuk "+per);
 if(lb&&lb.period>=per)throw fe(id,c.meter_no+": bacaan terakhir sudah periode "+lb.period);
 if(cu<pv)throw fe(id,c.meter_no+": angka akhir lebih kecil dari angka awal ("+qf(pv)+"). Jika meter diganti, pakai Ganti meter di Sambungan");
 const us=Math.round((cu-pv)*100)/100,h=hitungAir(us,airCfgFor(c));if(h.total<=0)throw fe(id,c.meter_no+": tagihan Rp 0 — atur tarif/abonemen dulu");const dc=discFor(c.disc,"tagihan",h.total);if(dc&&dc.amt>=h.total)throw fe(id,c.meter_no+": diskon menghabiskan seluruh tagihan; periksa diskon sambungan");return{c,cu,pv,us,h,dc}}
function bilPost(todo,per,d){const cfg=airCfg();let sum=0;todo.forEach(({c,cu,pv,us,h,dc})=>{const net=h.total-(dc?dc.amt:0);const nm=cust(c.party_id).name,t=post({type:"sale_credit",date:d,unit:c.unit_id,desc:"Tagihan air "+per+" – "+nm+" ("+c.meter_no+")",lines:[{acc:"ACC1400",d:net},{acc:"ACC4200",c:net}]}),
  x={_id:uid("SAL"),sale_number:numNext("bill",per+"-01"),unit_id:c.unit_id,party_id:c.party_id,date:d,payment_type:"credit",total:net,cash_id:null,transaction_id:t._id,status:"posted",
   bill:{conn_id:c._id,meter:c.meter_no,period:per,prev:pv,curr:cu,usage:us,billed:h.billed,water:h.water,abon:h.abon,rows:h.rows,...(c.cls?{cls:c.cls,cls_name:clsName(c.cls)}:{}),...(dc?{disc:dc}:{}),due:addDays(d,+cfg.due_days||0)}};
  db.sales.push(x);
  if(h.water>0)db.sale_items.push({_id:uid("SIT"),sale_id:x._id,product_id:null,label:"Pemakaian air",unit:"m³",qty:h.billed,price:h.water/h.billed,subtotal:h.water});
  if(h.abon>0)db.sale_items.push({_id:uid("SIT"),sale_id:x._id,product_id:null,label:"Beban tetap",unit:"bulan",qty:1,price:h.abon,subtotal:h.abon});
  if(dc)db.sale_items.push({_id:uid("SIT"),sale_id:x._id,product_id:null,label:"Diskon "+dc.name,unit:"",qty:1,price:-dc.amt,subtotal:-dc.amt});
  db.water_readings.push({_id:uid("WRD"),conn_id:c._id,kind:"baca",period:per,date:d,prev:pv,curr:cu,usage:us,sale_id:x._id,meter_no:c.meter_no,status:"posted"});
  audit("bill","sale",x._id,x.sale_number+" · "+nm+" · "+qf(us)+" m³ · Rp "+fm(net)+(dc?" (diskon "+fm(dc.amt)+")":""));sum+=net});return sum}
// terbitTagihan (massal) tidak lagi punya tombol di UI (angka meter diisi di modal detail); dipertahankan untuk generator data dan uji
// angka akhir sebuah sambungan; baris yang tidak tampil dibaca dari draf isian
const bmVal=id=>{const e=$("#bm_"+id);if(e)return e.value;return String(((S.dr||{})["air|bm_"+id])||"")};
function terbitTagihan(){try{const per=$("#bm-p").value,d=$("#bm-d").value,todo=[];
 bilChk(per,d,"bm-p","bm-d");
 db.water_connections.filter(c=>c.status==="aktif"&&(S.unit==="all"||c.unit_id===S.unit)).forEach(c=>{const id="bm_"+c._id,raw=pn(bmVal(c._id).trim());if(raw==="")return;todo.push(bilPrep(c,per,raw,id))});
 if(!todo.length)throw fe("bm-d","Isi angka meter akhir minimal satu sambungan");
 const sum=bilPost(todo,per,d);
 save();clrF(todo.map(q=>"#bm_"+q.c._id).join(","));if(S.dr)todo.forEach(q=>{delete S.dr["air|bm_"+q.c._id]});S.msg=todo.length+" tagihan air "+per+" diterbitkan · total Rp "+fm(sum)+"; bayar lewat sub-tab Piutang"}catch(e){ferr(e);return}render()}
// tagihan satu pelanggan dari modal detail
function terbitSatu(lanjut){try{const c=wConn(S.ewd);if(!c._id)throw Error("Sambungan tidak ditemukan");if(c.status!=="aktif")throw Error("Sambungan diputus; sambungkan kembali dulu");
 const per=$("#wd-p").value,d=$("#wd-d").value,raw=pn($("#wd-a").value.trim());bilChk(per,d,"wd-p","wd-d");if(raw==="")throw fe("wd-a","Isi angka meter akhir");
 const it=bilPrep(c,per,raw,"wd-a"),nx=lanjut===true?wdNext(c._id):null,sum=bilPost([it],per,d);save();S.bp=per;S.wdd=d;clrF("#bm_"+c._id);if(S.dr)delete S.dr["air|bm_"+c._id];
 S.msg="Tagihan air "+per+" diterbitkan · "+cust(c.party_id).name+" · "+qf(it.us)+" m³ · Rp "+fm(sum)+(lanjut===true?(nx?"":"; semua sambungan periode ini sudah ditagih"):"; bayar di bagian Pembayaran modal ini atau lewat sub-tab Piutang");
 if(nx){S.ewd=nx;S.mv=null;S.wgo=1;S.msg+=" · lanjut: "+cust(wConn(nx).party_id).name}}catch(e){ferr(e);return}render()}
// data daftar Baca Meter: sambungan aktif, status tagihan periode, dan urutan tampil (belum ditagih dulu bila "Semua")
const bmData=()=>{const per=S.bp||today().slice(0,7),cs=db.water_connections.filter(c=>c.status==="aktif"&&(S.unit==="all"||c.unit_id===S.unit)).sort((a,b)=>a.meter_no.localeCompare(b.meter_no,"id",{numeric:true})),bl=cs.map(c=>billOf(c._id,per)),fs=S.wf||"belum",
 ix=cs.map((c,i)=>i).filter(i=>wqHit(cust(cs[i].party_id),cs[i].meter_no)&&(fs==="semua"||(fs==="belum")===!bl[i]));if(fs==="semua")ix.sort((x,y)=>(!!bl[x]-!!bl[y])||x-y);const ad=cs.map(c=>String(cust(c.party_id).address||"").trim()||"Tanpa alamat"),nad=new Set(ad).size,wo=nad>1&&S.wo==="alamat";if(wo)ix.sort((x,y)=>ad[x].localeCompare(ad[y],"id",{numeric:true})||x-y);return{per,cs,bl,fs,ix,ad,nad,wo,done:bl.filter(Boolean).length}};
// tombol kembali ke atas untuk daftar panjang (UA-8)
const btt=n=>n>12?`<button type="button" class="b s btt" onclick="window.scrollTo({top:0,behavior:(typeof matchMedia==='function'&&matchMedia('(prefers-reduced-motion:reduce)').matches)?'auto':'smooth'})">↑ Kembali ke atas</button>`:"";
// pelanggan belum ditagih berikutnya setelah id (sesuai pencarian); kembali ke awal bila id terakhir; null bila tidak ada lagi
function wdNext(cur){const d=bmData(),L=d.cs.map((c,i)=>i).filter(i=>!d.bl[i]&&wqHit(cust(d.cs[i].party_id),d.cs[i].meter_no)).map(i=>d.cs[i]._id),k=L.indexOf(cur),R=L.filter(x=>x!==cur);return R.length?(R[k<0?0:k]||R[0]):null}
function vBaca(){const D=bmData(),{per,cs,bl,fs,ix,done,ad,nad,wo}=D,cfg=airCfg(),tot=cs.length,pc=tot?Math.round(done/tot*100):0,
 gs=wo?(()=>{const m={};cs.forEach((c,i)=>{const k=ad[i];(m[k]=m[k]||[0,0]);m[k][1]++;if(bl[i])m[k][0]++});return m})():null,
 rows=ix.map((i,n)=>{const c=cs[i],b=bl[i],nm=cust(c.party_id).name,gh=wo&&(n===0||ad[ix[n-1]]!==ad[i])?`<div class="wgh" role="presentation"><b>${esc(ad[i])}</b><span>${gs[ad[i]][0]} dari ${gs[ad[i]][1]} ditagih</span></div>`:"";return gh+`<button class="upr nsr" onclick="mdOpen('wd','${c._id}')">${avA(nm,i)}<span class="upm"><b>${esc(nm)}</b><small>Meter ${esc(c.meter_no)} · angka terakhir ${qf(wPrev(c._id))}</small></span><span class="upa">${b?`<b>${rp(b.total)}</b><span class="bdg ok">✓ Sudah ditagih</span>`:`<span class="bdg wr">Belum ditagih</span>`}</span></button>`}).join(""),
 flt=`<div class="fl wsr"><input type="search" placeholder="Cari nama / telepon / alamat / no meter…" aria-label="Cari pelanggan" value="${esc(S.wq||"")}" onchange="S.wq=this.value;S.lim=0;render()"><select aria-label="Filter status tagihan" onchange="S.wf=this.value;render()"><option value="belum"${fs==="belum"?" selected":""}>Belum ditagih</option><option value="sudah"${fs==="sudah"?" selected":""}>Sudah ditagih</option><option value="semua"${fs==="semua"?" selected":""}>Semua status</option></select>${nad>1?`<select aria-label="Urutan daftar" onchange="S.wo=this.value;render()"><option value="">Urut no meter</option><option value="alamat"${wo?" selected":""}>Kelompok per alamat</option></select>`:""}${(S.wq||"").trim()||fs!=="belum"?`<button class="b s" onclick="S.wq='';S.wf='';render()">Reset</button>`:""}</div>`,
 sm=(()=>{const bs=db.sales.filter(x=>x.bill&&x.bill.period===per&&x.status==="posted"&&(S.unit==="all"||x.unit_id===S.unit)),tb=bs.reduce((t,x)=>t+x.total,0),tp=bs.reduce((t,x)=>t+Math.min(paidOf(x),x.total),0);return bs.length?`<div class="wsm" aria-label="Ringkasan periode ${esc(per)}"><div><small>Tertagih</small><b>${rp(tb)}</b></div><div><small>Terbayar</small><b>${rp(tp)}</b><small>${tb>0?Math.round(tp/tb*100):0}%</small></div><div><small>Belum dibayar</small><b>${rp(Math.max(tb-tp,0))}</b></div></div>`:""})(),
 prog=tot?`<div class="wpt"><span><b>${done}</b> dari ${tot} sudah ditagih</span><span>${done===tot?"✓ Selesai":"sisa "+(tot-done)}</span></div><div class="wpg" role="progressbar" aria-label="Progres tagihan ${esc(per)}" aria-valuemin="0" aria-valuemax="${tot}" aria-valuenow="${done}"><i style="width:${pc}%"></i></div>`:"",
 empty=!ix.length?((S.wq||"").trim()?wNone():fs==="belum"&&done===tot?`<div class="empty em"><p>✓ Semua sambungan periode ${esc(per)} sudah ditagih.</p><button class="b s" onclick="S.wf='sudah';render()">Lihat yang sudah ditagih</button></div>`:`<div class="empty em"><p>Tidak ada sambungan pada filter ini.</p></div>`):"";
 return`<h2>Baca Meter &amp; Terbitkan Tagihan</h2>${dcard("Periode tagihan","Jatuh tempo "+cfg.due_days+" hari setelah tanggal tagihan",`<label>Bulan pemakaian</label><input id="bm-p" type="month" value="${per}" onchange="bpChg(this.value)"><p class="k">Pilih pelanggan di daftar untuk mengisi angka meter akhir dan menerbitkan tagihannya. Tagihan langsung menjadi piutang pelanggan (Dr 1400 / Cr 4200); pembayaran dicatat di sub-tab Piutang.</p>`,"alf")}
${dcard("Pelanggan",tot?"Sambungan aktif · periode "+esc(per):"Belum ada sambungan aktif",tot?prog+sm+flt+(ix.length?`<div class="upl">${rows}</div>${btt(ix.length)}`:empty):`<div class="empty">Belum ada sambungan aktif. Tambahkan pelanggan di sub-tab Pelanggan, lalu daftarkan meternya di sub-tab Sambungan.</div>`,"")}`}
function saveConn(){try{negAny();const v=i=>($("#"+i)||{value:""}).value.trim(),e=db.water_connections.find(c=>c._id===S.ecn),m=v("cn-m"),pid=e?e.party_id:v("cn-c"),a=+pn(v("cn-a")||"0"),d=v("cn-d");
 if(!pid)throw fe("cn-c","Pilih pelanggan (tambahkan dulu di sub-tab Pelanggan)");if(!m)throw fe("cn-m","Nomor meter wajib diisi");
 if(db.water_connections.some(c=>c._id!==S.ecn&&c.meter_no.toLowerCase()===m.toLowerCase()))throw fe("cn-m","Nomor meter sudah dipakai sambungan lain");
 if(!isFinite(a)||a<0)throw fe("cn-a","Angka meter awal tidak valid");if(!d)throw fe("cn-d","Tanggal pasang wajib diisi");
 if(e){if(db.water_readings.some(r=>r.conn_id===e._id)&&+e.initial!==a)throw fe("cn-a","Angka awal tidak bisa diubah setelah ada bacaan");e.meter_no=m;e.initial=a;e.installed=d;if($("#cn-g"))e.cls=v("cn-g");if($("#cn-ds"))e.disc=v("cn-ds");audit("update","water_connection",e._id,m);S.ecn=null;S.msg="Sambungan diperbarui"}
 else{const x={_id:uid("WCN"),unit_id:airCfg().unit_id,party_id:pid,meter_no:m,initial:a,installed:d,status:"aktif",...(v("cn-g")?{cls:v("cn-g")}:{}),...(v("cn-ds")?{disc:v("cn-ds")}:{})};let ins=null;if(aInst().on&&v("cn-bp")!=="0")ins=instSale(x,d);db.water_connections.push(x);audit("create","water_connection",x._id,m);S.msg="Sambungan "+m+" ditambahkan"+(ins?"; biaya pasang baru "+ins.sale_number+" Rp "+fm(ins.total)+" masuk Piutang":"")}
 save();clrF("#cn-m,#cn-a");okM()}catch(e){ferr(e);return}render()}
function togConn(id){const c=wConn(id);c.status=c.status==="aktif"?"putus":"aktif";audit(c.status==="putus"?"cut":"reconnect","water_connection",id,c.meter_no);save();S.msg=c.status==="putus"?"Sambungan "+c.meter_no+" diputus; tidak ditagih sampai disambung kembali":"Sambungan "+c.meter_no+" disambung kembali";render()}
function gantiMeter(){try{negAny();const v=i=>$("#"+i).value.trim(),c=wConn(v("gm-c")),m=v("gm-m"),a=+pn(v("gm-a")||""),d=v("gm-d");
 if(!c._id)throw fe("gm-c","Pilih sambungan");if(!m)throw fe("gm-m","Nomor meter baru wajib diisi");
 if(db.water_connections.some(q=>q._id!==c._id&&q.meter_no.toLowerCase()===m.toLowerCase()))throw fe("gm-m","Nomor meter sudah dipakai sambungan lain");
 if(v("gm-a")===""||!isFinite(a)||a<0)throw fe("gm-a","Angka awal meter baru tidak valid");if(!d)throw fe("gm-d","Tanggal ganti wajib diisi");
 db.water_readings.push({_id:uid("WRD"),conn_id:c._id,kind:"ganti",period:d.slice(0,7),date:d,prev:wPrev(c._id),curr:a,usage:0,old_meter:c.meter_no,meter_no:m,status:"posted"});
 audit("meter_change","water_connection",c._id,c.meter_no+" → "+m);c.meter_no=m;save();clrF("#gm-m,#gm-a");S.msg="Meter diganti; bacaan berikutnya dihitung dari angka awal meter baru"}catch(e){ferr(e);return}render()}
function batalGanti(id){try{const r=db.water_readings.find(q=>q._id===id),l=wRds(r.conn_id).pop();if(!l||l._id!==id)throw Error("Hanya ganti meter terbaru yang bisa dibatalkan (batalkan bacaan sesudahnya dulu)");
 if(db.water_connections.some(q=>q._id!==r.conn_id&&q.meter_no.toLowerCase()===String(r.old_meter).toLowerCase()))throw Error("Nomor meter lama sudah dipakai sambungan lain");
 wConn(r.conn_id).meter_no=r.old_meter;r.status="voided";audit("void","water_reading",id);save();S.msg="Ganti meter dibatalkan; nomor meter kembali "+r.old_meter}catch(e){S.msg="⚠ "+e.message}render()}
function vSamb(){const cfg=airCfg(),cs=db.water_connections.filter(c=>S.unit==="all"||c.unit_id===S.unit),pel=db.parties.filter(p=>p.type==="pelanggan"&&isAct(p)),eC=db.water_connections.find(c=>c._id===S.ecn),used=eC&&db.water_readings.some(r=>r.conn_id===eC._id),
 gs=db.water_readings.filter(r=>r.kind==="ganti"&&r.status!=="voided"&&cs.some(c=>c._id===r.conn_id)).slice().reverse();
 const aktif=cs.filter(c=>c.status==="aktif").length,csV=cs.filter(c=>wqHit(cust(c.party_id),c.meter_no));
 return`<h2>Sambungan &amp; Meter</h2>${addB("Tambah sambungan","cn")}${dcard("Daftar Sambungan",cs.length?(csV.length<cs.length?csV.length+" dari "+cs.length:cs.length)+" sambungan · "+aktif+" aktif":"Belum ada sambungan",cs.length?wSrch("Cari nama / telepon / alamat / no meter…")+(csV.length?`<div class="upl">${csV.slice(0,pgLim("sam")).map((c,i)=>{const a=arrears(c._id),o=a.reduce((t,x)=>t+owedS(x),0),nm=cust(c.party_id).name,off=c.status!=="aktif";return`<button class="upr nsr${off?" vd":""}" onclick="mdOpen('wd','${c._id}')">${avA(nm,i)}<span class="upm"><b>${esc(nm)}</b><small>Meter ${esc(c.meter_no)} · angka terakhir ${qf(wPrev(c._id))}${c.cls?" · "+esc(clsName(c.cls)):""}${c.disc&&discByCode(c.disc)?" · diskon "+esc(discByCode(c.disc).name):""}</small>${a.length?`<small class="smw">Menunggak ${a.length} bln · ${rp(o)}${a.length>=cfg.cut_months?" ⚠ layak diputus":""}</small>`:""}</span><span class="upa">${off?'<span class="bdg">Diputus</span>':'<span class="bdg ok">Aktif</span>'}</span></button>`}).join("")}</div>${pgMore("sam",csV.length)}${btt(Math.min(csV.length,pgLim("sam")))}`:wNone()):`<div class="empty">Belum ada sambungan.</div>`,"")}
${dcard("Ganti Meter","Baca dan tagih dulu angka akhir meter lama, baru catat penggantian; pemakaian setelah ini dihitung dari angka awal meter baru.",`<label>Sambungan</label><select id="gm-c"><option value="">Pilih sambungan</option>${opt(cs,c=>[c._id,c.meter_no+" – "+cust(c.party_id).name])}</select><label>Nomor meter baru</label><input id="gm-m"><label>Angka awal meter baru</label><input id="gm-a" type="text" inputmode="decimal" autocomplete="off"><label>Tanggal ganti</label><input id="gm-d" type="date" value="${today()}"><button class="b" onclick="gantiMeter()">Catat ganti meter</button>`,"alf")}
${gs.length?dcard("Riwayat Ganti Meter",gs.length+" penggantian",`<div class="upl">${gs.map(r=>`<div class="upr alr"><span class="tri nt" aria-hidden="true">⇄</span><span class="upm"><b>${esc(cust(wConn(r.conn_id).party_id).name)}</b><small>${r.date} · ${esc(r.old_meter||"")} → ${esc(r.meter_no)}</small></span><span class="upa"><b>${qf(r.curr)}</b><small>angka awal</small><span class="alb">${ib("undo","Batalkan","askC('batalGanti','"+r._id+"')","x")}</span></span></div>`).join("")}</div>`,""):""}`}
function saveTarif(){try{negAny();const n=i=>{const e=$("#"+i);const x=e?pn(e.value.trim()):"";return x===""?NaN:+x},md=$("#tw-md").value==="tier"?"tier":"flat",p1=n("tw-p1"),ab=n("tw-ab"),mn=n("tw-mn"),du=n("tw-du"),cm=n("tw-cm");let tiers;
 if(!(p1>=0))throw fe("tw-p1",md==="flat"?"Harga per m³ tidak valid":"Harga blok 1 tidak valid");
 if(md==="flat")tiers=[{upto:null,price:p1}];else{const u1=n("tw-u1"),u2=n("tw-u2"),p2=n("tw-p2"),p3=n("tw-p3");
  if(!(u1>0))throw fe("tw-u1","Batas blok 1 harus lebih dari 0");if(!(u2>u1))throw fe("tw-u2","Batas blok 2 harus lebih besar dari blok 1");
  [["tw-p2",p2],["tw-p3",p3]].forEach(([i,x])=>{if(!(x>=0))throw fe(i,"Harga per m³ tidak valid")});tiers=[{upto:u1,price:p1},{upto:u2,price:p2},{upto:null,price:p3}]}
 if(!(ab>=0))throw fe("tw-ab","Beban tetap tidak valid");if(!(mn>=0))throw fe("tw-mn","Pemakaian minimum tidak valid");if(!(du>=0&&du<=90))throw fe("tw-du","Jatuh tempo 0–90 hari");if(!(cm>=1))throw fe("tw-cm","Batas tunggakan minimal 1 bulan");
 if(tiers.every(t=>!t.price)&&!ab)throw fe("tw-ab","Semua tarif 0; isi tarif atau beban tetap");
 db.settings.air={...airCfg(),mode:md,unit_id:$("#tw-un").value,abon:ab,min_m3:mn,due_days:du,cut_months:cm,tiers};
 audit("update","settings","air","Tarif air diperbarui");save();S.tm=null;clrDr("air|tw-");S.msg="Tarif disimpan; berlaku untuk tagihan berikutnya (tagihan lama tidak berubah)"}catch(e){ferr(e);return}render()}
function simTarif(){const e=$("#tw-s"),r=$("#tw-sr");if(!e||!r)return;const raw=pn(e.value.trim());if(raw===""||!isFinite(+raw)||+raw<0){r.textContent="";return}const h=hitungAir(+raw);
 r.innerHTML=h.rows.map(x=>qf(x.q)+" m³ × Rp "+fm(x.price)+" = Rp "+fm(x.v)).join("<br>")+(h.abon?"<br>Beban tetap Rp "+fm(h.abon):"")+"<br><b>Total Rp "+fm(h.total)+"</b>"}
function vTarif(){const c=airCfg(),md=S.tm||c.mode||"flat",t=c.tiers.length===3?c.tiers:[{upto:10,price:c.tiers[0].price},{upto:20,price:c.tiers[0].price},{upto:null,price:c.tiers[0].price}],I=(id,val,lb)=>`<div class="tgf"><label for="${id}">${lb}</label><input id="${id}" type="text" inputmode="numeric" autocomplete="off" oninput="fmtR(this)" value="${fm(val)}"></div>`,G=(h,b)=>`<div class="tgp"><h4>${h}</h4>${b}</div>`;
 return`<h2>Tarif Air</h2><div class="twg">${dcard("Tarif standar","Berlaku untuk golongan Umum. Perubahan hanya berlaku untuk tagihan berikutnya; tagihan yang sudah terbit tidak berubah.",
 G("Model tarif",`<label for="tw-md">Model tarif</label><select id="tw-md" onchange="S.tm=this.value;render()"><option value="flat"${md==="flat"?" selected":""}>Sama untuk semua (satu harga per m³)</option><option value="tier"${md==="tier"?" selected":""}>Bertingkat (3 blok)</option></select>`)
 +G(md==="flat"?"Harga":"Blok tarif",md==="flat"?I("tw-p1",t[0].price,"Harga per m³ (Rp)"):`<div class="tgi">${I("tw-u1",t[0].upto,"Blok 1: sampai (m³)")}${I("tw-p1",t[0].price,"Blok 1: harga/m³ (Rp)")}</div><div class="tgi">${I("tw-u2",t[1].upto,"Blok 2: sampai (m³)")}${I("tw-p2",t[1].price,"Blok 2: harga/m³ (Rp)")}</div>${I("tw-p3",t[2].price,"Blok 3 (selebihnya): harga per m³ (Rp)")}`)
 +G("Lainnya",`<div class="tgi">${I("tw-ab",c.abon,"Beban tetap/bulan (Rp)")}${I("tw-mn",c.min_m3,"Pemakaian minimum (m³; 0 = tanpa)")}</div><div class="tgi">${I("tw-du",c.due_days,"Jatuh tempo (hari)")}${I("tw-cm",c.cut_months,"Batas tunggakan (bulan)")}</div><label for="tw-un">Unit usaha</label><select id="tw-un">${opt(db.business_units,u=>[u._id,u.name],c.unit_id)}</select>`)
 +`<button class="b" onclick="saveTarif()">Simpan tarif</button>`,"alf")}
${dcard("Simulasi tagihan","Memakai tarif yang tersimpan",`<label for="tw-s">Pemakaian (m³)</label><input id="tw-s" type="text" inputmode="decimal" autocomplete="off" oninput="simTarif()"><div class="k" id="tw-sr" aria-live="polite"></div>`,"alf tws")}</div>${vTarifAirX()}`}
function vNota(id){const x=db.sales.find(q=>q._id===id),bar=`<div class="noprint"><button class="b" onclick="window.print()">Cetak</button><button class="b s" onclick="S.doc=null;render()">Kembali</button></div>`;
 if(!x||x.bill||x.opening||x.status!=="posted")return`${bar}<p class="k">Nota tidak tersedia.</p>`;
 const p=cust(x.party_id),R=(a,v)=>`<tr><td>${a}</td><td class="n">${v}</td></tr>`,ci=x.cash_id&&db.cash_accounts.find(c=>c._id===x.cash_id),pd=paidOf(x),o=owedS(x),
  rows=db.sale_items.filter(i=>i.sale_id===x._id).map(i=>{const pr=db.products.find(z=>z._id===i.product_id)||{};return`<tr><td>${esc(i.label||pr.name||"-")}</td><td class="n">${qf(i.qty)}${pr.unit?" "+esc(pr.unit):""}</td><td class="n">${rp(i.price)}</td><td class="n">${rp(i.subtotal)}</td></tr>`}).join("");
 return`${bar}<div class="doc">${kop()}<h3>NOTA PENJUALAN</h3><div class="cn">No. ${x.sale_number} · ${x.date}</div><table>${R("Pelanggan",esc(p.name))}${p.address?R("Alamat",esc(p.address)):""}${R("Unit usaha",esc(unitName(x.unit_id)))}</table>
<table class="nt"><tr><th>Barang</th><th class="n">Jumlah</th><th class="n">Harga</th><th class="n">Subtotal</th></tr>${rows}<tr><th colspan="3">Total</th><th class="n">${rp(x.total)}</th></tr></table>
<table>${R("Cara bayar",x.payment_type==="cash"?"Tunai"+(ci?" · "+esc(ci.name):""):"Kredit (piutang)")}${x.payment_type==="credit"?R("Sudah dibayar",rp(pd))+R("<b>Sisa</b>","<b>"+rp(o)+"</b>"):R("Status","Lunas")}</table>
<div class="tb">Terbilang: ${cap(terbilang(x.total))}</div>${sig([["Pembeli",x.party_id?p.name:""],["Bendahara",tres()]],0,x.date)}</div>`}
function vTagih(id){const x=db.sales.find(q=>q._id===id),bar=`<div class="noprint"><button class="b" onclick="window.print()">Cetak</button><button class="b s" onclick="S.doc=null;render()">Kembali</button></div>`;
 if(!x||!x.bill||x.status!=="posted")return`${bar}<p class="k">Nota tidak tersedia.</p>`;
 const b=x.bill,p=cust(x.party_id),R=(a,v)=>`<tr><td>${a}</td><td class="n">${v}</td></tr>`,pd=paidOf(x),o=owedS(x);
 return`${bar}<div class="doc">${kop()}<h3>NOTA TAGIHAN AIR</h3><div class="cn">No. ${x.sale_number} · Periode ${b.period} · Tanggal ${x.date}</div><table>${R("Pelanggan",esc(p.name))}${p.address?R("Alamat",esc(p.address)):""}${R("No. meter",esc(b.meter||wConn(b.conn_id).meter_no||"-"))}${b.cls_name?R("Golongan tarif",esc(b.cls_name)):""}${R("Angka awal → akhir",qf(b.prev)+" → "+qf(b.curr))}${R("Pemakaian",qf(b.usage)+" m³"+(b.billed>b.usage?" (dikenai minimum "+qf(b.billed)+" m³)":""))}${b.rows.map(r=>R("&nbsp;&nbsp;"+qf(r.q)+" m³ × Rp "+fm(r.price),rp(r.v))).join("")}${b.abon?R("Beban tetap",rp(b.abon)):""}${b.disc?R("Jumlah sebelum diskon",rp(b.water+b.abon))+R("Diskon "+esc(b.disc.name),"− "+rp(b.disc.amt)):""}${R("<b>Total tagihan</b>","<b>"+rp(x.total)+"</b>")}${pd?R("Sudah dibayar",rp(pd)):""}${R("<b>Sisa</b>","<b>"+rp(o)+"</b>")}${R("Jatuh tempo",b.due)}</table></div>`}

// kuitansi pembayaran tagihan air (satu kuitansi per pembayaran; sebagian atau pelunasan)
const payOk=x=>db.payments.filter(y=>y.sale_id===x._id&&y.status==="posted"),kwNo=y=>"KA-"+y.date.slice(0,4)+"-"+String(db.payments.indexOf(y)+1).padStart(4,"0"),
 dkb=(t,f,i,c)=>`<button class="dkb${c?" "+c:""}" onclick="${f}">${ic(i||"print")}<span>${t}</span></button>`,
 kwBtn=(y,full)=>dkb(full?"Cetak kuitansi":"Kuitansi "+tglS(y.date)+" · Rp "+fm(y.amount+(y.fine||0)),"mdClose();openDoc('kuit','"+y._id+"')");
function vKuit(id){const y=db.payments.find(q=>q._id===id),bar=`<div class="noprint"><button class="b" onclick="window.print()">Cetak</button><button class="b s" onclick="S.doc=null;render()">Kembali</button></div>`;
 const x=y&&db.sales.find(q=>q._id===y.sale_id);if(!y||y.status==="voided"||!x||x.status!=="posted")return`${bar}<p class="k">Kuitansi tidak tersedia.</p>`;
 const b=x.bill,p=cust(x.party_id),R=(a,v)=>`<tr><td>${a}</td><td class="n">${v}</td></tr>`,ci=db.cash_accounts.find(c=>c._id===y.cash_id),ix=db.payments.indexOf(y),
  tot=y.amount+(y.fine||0),paid=db.payments.filter((q,n)=>q.sale_id===x._id&&q.status!=="voided"&&n<=ix).reduce((t,q)=>t+q.amount,0),sisa=Math.round((x.total-paid)*100)/100;
 return`${bar}<div class="doc">${kop()}<h3>KUITANSI PEMBAYARAN</h3><div class="cn">No. ${kwNo(y)} · ${y.date}</div><table>${R("Diterima dari",esc(p.name))}${p.address?R("Alamat",esc(p.address)):""}${R("Untuk pembayaran",b?"Tagihan air "+esc(b.period)+" · "+esc(x.sale_number):esc(x.sale_number))}${b?R("No. meter",esc(b.meter||wConn(b.conn_id).meter_no||"-")):""}${R("Pembayaran tagihan",rp(y.amount))}${y.fine>0?R("Denda keterlambatan",rp(y.fine)):""}<tr><th>Total diterima</th><th class="n">${rp(tot)}</th></tr>${R("Dibayar ke",esc(ci?ci.name:"-"))}${R("Total tagihan",rp(x.total))}${R(sisa>0.005?"<b>Sisa tagihan</b>":"Status",sisa>0.005?"<b>"+rp(sisa)+"</b>":"Lunas")}</table><div class="tb">Terbilang: ${cap(terbilang(tot))}</div>${sig([["Pembayar",p.name],["Bendahara",tres()]],0,y.date)}</div>`}

// ===== v1.1.169 — Master > Tarif Air: golongan tarif, denda keterlambatan, biaya pasang baru, diskon =====
// Semua disimpan di db.settings (air_class, air_late, air_inst, air_disc) sehingga tanpa koleksi/tabel baru; bawaan nonaktif.
function ensureAirAcc(d){if(!Array.isArray(d.accounts))return;const add=(c,n)=>{if(!d.accounts.some(a=>a.code===c))d.accounts.push({_id:"ACC"+c,code:c,name:n,type:"revenue",parent_id:"ACC4000",status:"aktif"})};add("4210","Pendapatan Denda Air");add("4220","Pendapatan Pasang Baru Air")}
const aClasses=()=>Array.isArray(db.settings.air_class)?db.settings.air_class:[],
 aLate=()=>Object.assign({on:false,type:"tetap",val:0,grace:0,max:0},db.settings.air_late||{}),
 aInst=()=>Object.assign({on:false,name:"Biaya pasang baru",amt:0},db.settings.air_inst||{}),
 aDiscs=()=>Array.isArray(db.settings.air_disc)?db.settings.air_disc:[],
 discByCode=c=>aDiscs().find(x=>x.code===c),
 clsName=c=>(aClasses().find(x=>x.code===c)||{name:c}).name;
// konfigurasi tarif untuk satu sambungan: golongan menimpa model, beban tetap, minimum, dan blok; jatuh tempo/unit tetap dari tarif standar
function airCfgFor(c){const g=c&&c.cls?aClasses().find(x=>x.code===c.cls):null;return g?{...airCfg(),mode:g.mode,abon:g.abon,min_m3:g.min_m3,tiers:g.tiers}:airCfg()}
// diskon: {code,name,type,val,amt}; null bila tidak ada/nonaktif/lingkup tidak cocok
function discFor(code,scope,base){if(!code)return null;const d=discByCode(code);if(!d||d.active===false||(d.scope!=="semua"&&d.scope!==scope))return null;
 const amt=Math.min(Math.round(base),d.type==="persen"?Math.round(base*d.val/100):Math.round(d.val));return amt>0?{code:d.code,name:d.name,type:d.type,val:d.val,amt}:null}
const discOpts=scope=>{const L=aDiscs().filter(d=>d.active!==false&&(d.scope==="semua"||d.scope===scope));return L.length?'<option value="">Tanpa diskon</option>'+opt(L,d=>[d.code,d.name+" ("+(d.type==="persen"?String(d.val).replace(".",",")+"%":"Rp "+fm(d.val))+")"]):""};
// denda keterlambatan: sekali per tagihan, pada pembayaran pertama sesudah jatuh tempo + tenggang; null bila tidak berlaku
function lateFine(x,d,o){const L=aLate();if(!L.on||!x||!x.bill||x.fine_done||!x.bill.due||!(o>0))return null;if(d<=addDays(x.bill.due,+L.grace||0))return null;
 let f=L.type==="persen"?Math.round(o*L.val/100):Math.round(+L.val);if(+L.max>0&&f>L.max)f=Math.round(L.max);return f>0?f:null}
// biaya pasang baru: penjualan kredit (piutang pelanggan) Dr 1400 / Cr 4220
function instSale(c,d){const I=aInst(),a=Math.round(+I.amt);if(!(a>0))throw Error("Biaya pasang baru belum diisi di Unit Air > Pengaturan > Tarif");
 const t=post({type:"sale_credit",date:d,unit:c.unit_id,desc:I.name+" – "+cust(c.party_id).name+" ("+c.meter_no+")",lines:[{acc:"ACC1400",d:a},{acc:"ACC4220",c:a}]}),
  x={_id:uid("SAL"),sale_number:numNext("sale",d),unit_id:c.unit_id,party_id:c.party_id,date:d,payment_type:"credit",total:a,cash_id:null,transaction_id:t._id,status:"posted",install:{conn_id:c._id}};
 db.sales.push(x);db.sale_items.push({_id:uid("SIT"),sale_id:x._id,product_id:null,label:I.name+" "+c.meter_no,unit:"",qty:1,price:a,subtotal:a});audit("sale","sale",x._id,I.name+" · "+c.meter_no);return x}
const tarifTxt=g=>g.mode==="tier"?"Bertingkat: "+g.tiers.map(t=>(t.upto==null?"selebihnya":"≤ "+qf(t.upto)+" m³")+" Rp "+fm(t.price)).join(" · "):"Rp "+fm(g.tiers[0].price)+" per m³",
 gTxt=g=>tarifTxt(g)+(g.abon?" · beban tetap Rp "+fm(g.abon):"")+(g.min_m3?" · minimum "+qf(g.min_m3)+" m³":"");
function gtMd(v){const e=$("#gt-tr");if(e)e.hidden=v!=="tier"}
function gtTog(c){const a=aClasses().slice(),g=a.find(x=>x.code===c);if(!g)return;g.active=g.active===false;db.settings.air_class=a;audit("update","settings","air_class",(g.active?"Aktifkan":"Nonaktifkan")+" golongan "+g.name);save();S.msg="Golongan "+g.name+(g.active?" diaktifkan":" dinonaktifkan; sambungan yang sudah memakainya tetap ditagih dengan tarif golongan ini")+"";render()}
function saveGol(){try{negAny();const n=i=>{const e=$("#"+i),x=e?pn(e.value.trim()):"";return x===""?NaN:+x},nm=$("#gt-n").value.trim(),md=$("#gt-md").value==="tier"?"tier":"flat",p1=n("gt-p1"),ab=n("gt-ab"),mn=n("gt-mn");let tiers;
 if(!nm)throw fe("gt-n","Nama golongan wajib");if(aClasses().some(x=>x.code!==S.egl&&x.name.toLowerCase()===nm.toLowerCase()))throw fe("gt-n","Nama golongan sudah dipakai");
 if(!(p1>=0))throw fe("gt-p1",md==="flat"?"Harga per m³ tidak valid":"Harga blok 1 tidak valid");
 if(md==="flat")tiers=[{upto:null,price:p1}];else{const u1=n("gt-u1"),u2=n("gt-u2"),p2=n("gt-p2"),p3=n("gt-p3");
  if(!(u1>0))throw fe("gt-u1","Batas blok 1 harus lebih dari 0");if(!(u2>u1))throw fe("gt-u2","Batas blok 2 harus lebih besar dari blok 1");
  [["gt-p2",p2],["gt-p3",p3]].forEach(([i,x])=>{if(!(x>=0))throw fe(i,"Harga per m³ tidak valid")});tiers=[{upto:u1,price:p1},{upto:u2,price:p2},{upto:null,price:p3}]}
 if(!(ab>=0))throw fe("gt-ab","Beban tetap tidak valid");if(!(mn>=0))throw fe("gt-mn","Pemakaian minimum tidak valid");
 if(tiers.every(t=>!t.price)&&!ab)throw fe("gt-ab","Semua tarif 0; isi tarif atau beban tetap");
 const arr=aClasses().slice(),e=arr.find(x=>x.code===S.egl);
 if(e)Object.assign(e,{name:nm,mode:md,abon:ab,min_m3:mn,tiers});else arr.push({code:seqCode("GOL",arr.map(x=>x.code)),name:nm,mode:md,abon:ab,min_m3:mn,tiers,active:true});
 db.settings.air_class=arr;audit("update","settings","air_class",(e?"Ubah":"Tambah")+" golongan tarif "+nm);save();okM();S.msg="Golongan "+nm+" disimpan; berlaku untuk tagihan berikutnya (tagihan lama tidak berubah)"}catch(e){ferr(e);return}render()}
function saveLate(){try{negAny();const n=i=>{const x=pn($("#"+i).value.trim());return x===""?0:+x},on=$("#al-on").value==="1",ty=$("#al-ty").value==="persen"?"persen":"tetap",v=n("al-v"),g=n("al-g"),m=n("al-m");
 if(!isFinite(v)||v<0)throw fe("al-v","Nilai denda tidak valid");if(ty==="persen"&&v>100)throw fe("al-v","Persentase maksimal 100");if(on&&!(v>0))throw fe("al-v","Isi nilai denda lebih dari 0");
 if(!(g>=0&&g<=90))throw fe("al-g","Tenggang 0–90 hari");if(!(m>=0))throw fe("al-m","Batas maksimum tidak valid");
 if(on&&(acc("ACC4210")||{}).status==="nonaktif")throw Error("Akun 4210 Pendapatan Denda Air nonaktif; aktifkan dulu di Master > Akun");
 db.settings.air_late={on,type:ty,val:v,grace:Math.round(g),max:m};audit("update","settings","air_late",on?"Denda air aktif: "+(ty==="persen"?v+"%":"Rp "+fm(v))+", tenggang "+Math.round(g)+" hari":"Denda air dinonaktifkan");save();okM();S.msg=on?"Denda keterlambatan aktif; berlaku pada pembayaran tagihan yang terlambat berikutnya":"Denda keterlambatan dinonaktifkan"}catch(e){ferr(e);return}render()}
function saveInst(){try{negAny();const on=$("#ai-on").value==="1",nm=$("#ai-n").value.trim(),a=Math.round(+pn($("#ai-a").value.trim()||"0"));
 if(!nm)throw fe("ai-n","Nama biaya wajib");if(!isFinite(a)||a<0)throw fe("ai-a","Nominal tidak valid");if(on&&!(a>0))throw fe("ai-a","Isi nominal lebih dari 0");
 if(on&&(acc("ACC4220")||{}).status==="nonaktif")throw Error("Akun 4220 Pendapatan Pasang Baru Air nonaktif; aktifkan dulu di Master > Akun");
 db.settings.air_inst={on,name:nm,amt:a};audit("update","settings","air_inst",on?nm+" aktif: Rp "+fm(a):"Biaya pasang baru dinonaktifkan");save();okM();S.msg=on?"Biaya pasang baru aktif; muncul saat menambah sambungan baru":"Biaya pasang baru dinonaktifkan"}catch(e){ferr(e);return}render()}
function dsTog(c){const a=aDiscs().slice(),d=a.find(x=>x.code===c);if(!d)return;d.active=d.active===false;db.settings.air_disc=a;audit("update","settings","air_disc",(d.active?"Aktifkan":"Nonaktifkan")+" diskon "+d.name);save();S.msg="Diskon "+d.name+(d.active?" diaktifkan":" dinonaktifkan; tidak diterapkan lagi, termasuk pada sambungan yang memakainya");render()}
function saveDisc(){try{negAny();const nm=$("#ad-n").value.trim(),ty=$("#ad-t").value==="nominal"?"nominal":"persen",v=+pn($("#ad-v").value.trim()||"0"),sc=["semua","tagihan","penjualan"].includes($("#ad-s").value)?$("#ad-s").value:"semua";
 if(!nm)throw fe("ad-n","Nama diskon wajib");if(aDiscs().some(x=>x.code!==S.eds&&x.name.toLowerCase()===nm.toLowerCase()))throw fe("ad-n","Nama diskon sudah dipakai");
 if(!isFinite(v)||!(v>0))throw fe("ad-v","Isi nilai diskon lebih dari 0");if(ty==="persen"&&v>100)throw fe("ad-v","Persentase maksimal 100");
 const arr=aDiscs().slice(),e=arr.find(x=>x.code===S.eds);if(e)Object.assign(e,{name:nm,type:ty,val:v,scope:sc});else arr.push({code:seqCode("DSK",arr.map(x=>x.code)),name:nm,type:ty,val:v,scope:sc,active:true});
 db.settings.air_disc=arr;audit("update","settings","air_disc",(e?"Ubah":"Tambah")+" diskon "+nm);save();okM();S.msg="Diskon "+nm+" disimpan"}catch(e){ferr(e);return}render()}
function vTarifAirX(){
 const c=airCfg(),GL=aClasses(),L=aLate(),IN=aInst(),DL=aDiscs(),use=code=>db.water_connections.filter(x=>x.cls===code).length,
  sm=(on,t)=>on?`<p class="k">${t}</p>`:'<p class="k">Nonaktif.</p>';
 return`<h2>Golongan, denda, pasang baru, dan diskon</h2><p class="k">Standar saat ini: ${esc(gTxt(c))}. Semua pengaturan di bawah bawaannya nonaktif dan hanya berlaku untuk transaksi berikutnya.</p>
${addB("Tambah golongan tarif","gl")}${dcard("Golongan tarif",GL.length?GL.length+" golongan":"Belum ada golongan",(GL.length?`<div class="upl">${GL.map((g,i)=>`<div class="upr alr${g.active===false?" vd":""}">${avA(g.name,i)}<span class="upm"><b>${esc(g.name)}</b><small>${esc(gTxt(g))}</small><small>${use(g.code)} sambungan</small></span><span class="upa">${g.active===false?'<span class="bdg">Nonaktif</span>':'<span class="bdg ok">Aktif</span>'}<span class="alb">${ib("edit","Edit","mdOpen('gl','"+g.code+"')","s")}${g.active===false?ib("check","Aktifkan","gtTog('"+g.code+"')","s"):ib("x","Nonaktifkan","gtTog('"+g.code+"')","s")}</span></span></div>`).join("")}</div>`:'<div class="empty"><p>Semua sambungan memakai tarif standar.</p></div>')+'<p class="k">Golongan dipilih per sambungan di Unit Air > Sambungan. Perubahan tarif hanya berlaku untuk tagihan berikutnya.</p>',"alf")}
${dcard("Denda keterlambatan",L.on?"Aktif":"Nonaktif",sm(L.on,"Denda "+(L.type==="persen"?String(L.val).replace(".",",")+"% dari sisa tagihan":"Rp "+fm(L.val)+" per tagihan")+", tenggang "+L.grace+" hari"+(L.max>0?", maksimum Rp "+fm(L.max):""))+`<p class="k">Dikenakan sekali per tagihan, pada pembayaran pertama sesudah jatuh tempo + tenggang, dan dicatat sebagai Pendapatan Denda Air (akun 4210). Saat Terima pembayaran, denda dapat diubah atau dibebaskan.</p><button class="b" onclick="mdOpen('dn','')">Ubah pengaturan denda</button>`,"alf")}
${dcard("Biaya pasang baru",IN.on?"Aktif · "+IN.name+" Rp "+fm(IN.amt):"Nonaktif",sm(IN.on,esc(IN.name)+" Rp "+fm(IN.amt)+" ditagihkan saat menambah sambungan baru")+`<p class="k">Ditagihkan sebagai piutang pelanggan (Dr 1400 / Cr 4220 Pendapatan Pasang Baru Air); pelanggan membayar lewat Unit Air > Piutang. Pilihan Tagihkan dapat dimatikan per sambungan.</p><button class="b" onclick="mdOpen('pb','')">Ubah biaya pasang baru</button>`,"alf")}
${addB("Tambah diskon","ds")}${dcard("Diskon",DL.length?DL.length+" diskon":"Belum ada diskon",(DL.length?`<div class="upl">${DL.map((d,i)=>`<div class="upr alr${d.active===false?" vd":""}">${avA(d.name,i)}<span class="upm"><b>${esc(d.name)}</b><small>${d.type==="persen"?String(d.val).replace(".",",")+"%":"Rp "+fm(d.val)} · ${d.scope==="semua"?"tagihan dan penjualan":d.scope==="tagihan"?"hanya tagihan air":"hanya penjualan lain"}</small></span><span class="upa">${d.active===false?'<span class="bdg">Nonaktif</span>':'<span class="bdg ok">Aktif</span>'}<span class="alb">${ib("edit","Edit","mdOpen('ds','"+d.code+"')","s")}${d.active===false?ib("check","Aktifkan","dsTog('"+d.code+"')","s"):ib("x","Nonaktifkan","dsTog('"+d.code+"')","s")}</span></span></div>`).join("")}</div>`:'<div class="empty"><p>Belum ada diskon.</p></div>')+'<p class="k">Tagihan air: diskon dipilih per sambungan (berlaku tiap bulan). Penjualan lain: dipilih saat mencatat penjualan. Total dicatat setelah diskon; rincian tampil di nota. Diskon nonaktif tidak diterapkan lagi.</p>',"alf")}`}
